'use client';

import { useState } from 'react';
import { vehicleSlug } from '@/lib/vehicle-slug';

interface Props {
  vehicle: { year: number; make: string; model: string; trim?: string | null };
  width?: number;
  className?: string;
}

/**
 * Vehicle hero image with graceful fallback.
 *
 * Tries to load /vehicles/{slug}.png (generated by
 * scripts/generate-hero-images.js using OpenAI gpt-image-1) and falls
 * back to a generic coupe silhouette if the file isn't present.
 *
 * Slug match (trimmed first, then untrimmed) so a "2019 Camaro ZL1 1LE"
 * with no trim-specific image can still pick up the "2019 Camaro" base
 * image as a fallback before falling all the way to the silhouette.
 *
 * Image generation budget: ~17 cars seeded today, covering owner's two
 * vehicles + the top 15 highest-traffic US YMMTs. More can be added
 * by running scripts/generate-hero-images.js with an extended list;
 * the file presence is the only signal this component checks.
 */
export function VehicleHero({ vehicle, width = 200, className = '' }: Props) {
  const { year, make, model, trim } = vehicle;

  // Try the most-specific slug first, then progressively wider matches.
  const candidates = [
    vehicleSlug(year, make, model, trim || null),
    vehicleSlug(year, make, model, null),
  ].filter((v, i, a) => a.indexOf(v) === i); // dedupe

  const [attempt, setAttempt] = useState(0);
  const [failed, setFailed] = useState(false);

  const onError = () => {
    if (attempt < candidates.length - 1) {
      setAttempt((a) => a + 1);
    } else {
      setFailed(true);
    }
  };

  if (failed) {
    // Inline silhouette fallback — minimal SVG so we don't need to
    // depend on the design-bundle ChallengerSilhouette which isn't
    // ported into the runtime tree.
    return (
      <svg
        viewBox="0 0 240 90"
        width={width}
        height={(width * 90) / 240}
        className={className}
        aria-label={`${year} ${make} ${model} silhouette`}
      >
        <path
          d="M20 65 Q22 50 35 45 Q55 36 80 36 L130 30 Q160 28 185 34 Q210 38 220 50 Q224 56 222 65 L210 66 Q205 76 195 76 Q185 76 180 66 L70 66 Q65 76 55 76 Q45 76 40 66 Z"
          fill="#1a1a1a"
        />
        <circle cx="55" cy="68" r="9" fill="#1a1a1a" />
        <circle cx="55" cy="68" r="5" fill="#888" />
        <circle cx="195" cy="68" r="9" fill="#1a1a1a" />
        <circle cx="195" cy="68" r="5" fill="#888" />
      </svg>
    );
  }

  const src = `/vehicles/${candidates[attempt]}.png`;
  return (
    // Using a plain <img> rather than next/image because:
    //  1. We deliberately want client-side onError to drive the
    //     silhouette fallback when the file is absent.
    //  2. Hero images are ~1.3MB but vehicle pages are content-heavy
    //     anyway; this isn't a perf bottleneck and skipping Image
    //     optimization avoids the 404→500 cascade in Next's image
    //     proxy when the source file is missing.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      key={src}
      src={src}
      alt={`${year} ${make} ${model}${trim ? ' ' + trim : ''}`}
      width={width}
      onError={onError}
      className={className}
      style={{ display: 'block', maxWidth: '100%', height: 'auto', objectFit: 'contain' }}
    />
  );
}
