'use client';

import { useState } from 'react';
import { vehicleHeroCandidates } from '@/lib/vehicle-hero';

interface Props {
  vehicle: { year: number; make: string; model: string; trim?: string | null };
  width?: number;
  className?: string;
}

/**
 * Vehicle hero image with graceful fallback.
 *
 * Candidates come from the build-time manifest (src/data/vehicle-heroes.json
 * via vehicleHeroCandidates): exact year+trim → base model → same model,
 * nearest year within a generation window. So a 2022 Camry LE owner gets
 * the 2022 Camry XSE shot instead of a silhouette, and a 2020 Camry owner
 * still matches the 2022 image — but a 1998 Camry doesn't (wrong body
 * style reads as "that's not my car").
 *
 * onError still walks the candidate list so a stale manifest entry
 * (file deleted without rebuilding) degrades to the silhouette instead
 * of a broken image.
 *
 * Library: /public/vehicles, generated by scripts/generate-hero-images.js
 * (gpt-image-1, ~$0.04/image). After adding images run
 * scripts/build-hero-manifest.js (the generator does it automatically).
 */
export function VehicleHero({ vehicle, width = 200, className = '' }: Props) {
  const { year, make, model, trim } = vehicle;

  const candidates = vehicleHeroCandidates(year, make, model, trim);

  const [attempt, setAttempt] = useState(0);
  const [failed, setFailed] = useState(false);

  const onError = () => {
    if (attempt < candidates.length - 1) {
      setAttempt((a) => a + 1);
    } else {
      setFailed(true);
    }
  };

  if (failed || candidates.length === 0) {
    // Inline silhouette fallback — minimal SVG so we don't need to
    // depend on the design-bundle ChallengerSilhouette which isn't
    // ported into the runtime tree.
    return (
      <svg
        viewBox="0 0 240 90"
        width={width}
        height={(width * 90) / 240}
        className={className}
        aria-label={`${year} ${make} ${model} silhouette`}
      >
        <path
          d="M20 65 Q22 50 35 45 Q55 36 80 36 L130 30 Q160 28 185 34 Q210 38 220 50 Q224 56 222 65 L210 66 Q205 76 195 76 Q185 76 180 66 L70 66 Q65 76 55 76 Q45 76 40 66 Z"
          fill="#1a1a1a"
        />
        <circle cx="55" cy="68" r="9" fill="#1a1a1a" />
        <circle cx="55" cy="68" r="5" fill="#888" />
        <circle cx="195" cy="68" r="9" fill="#1a1a1a" />
        <circle cx="195" cy="68" r="5" fill="#888" />
      </svg>
    );
  }

  const src = candidates[attempt];
  return (
    // Using a plain <img> rather than next/image because:
    //  1. We deliberately want client-side onError to drive the
    //     silhouette fallback when the file is absent.
    //  2. Hero images are small webps; this isn't a perf bottleneck and
    //     skipping Image optimization avoids the 404→500 cascade in
    //     Next's image proxy when the source file is missing.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      key={src}
      src={src}
      alt={`${year} ${make} ${model}${trim ? ' ' + trim : ''}`}
      width={width}
      onError={onError}
      className={className}
      style={{ display: 'block', maxWidth: '100%', height: 'auto', objectFit: 'contain' }}
    />
  );
}
