// GENERATED by reviewed known-issue batches. Do not edit by hand.
// Batch modules are additive so a new make review cannot remove prior approvals.

import { productUrlFingerprints as productUrls0, vendorUrlFingerprints as vendorUrls0, retailerHostFingerprints as retailerHosts0 } from './known-issue-reviewed-retailer-links/alfa-romeo';
import { productUrlFingerprints as productUrls1, vendorUrlFingerprints as vendorUrls1, retailerHostFingerprints as retailerHosts1 } from './known-issue-reviewed-retailer-links/audi';
import { productUrlFingerprints as productUrls2, vendorUrlFingerprints as vendorUrls2, retailerHostFingerprints as retailerHosts2 } from './known-issue-reviewed-retailer-links/bmw';
import { productUrlFingerprints as productUrls3, vendorUrlFingerprints as vendorUrls3, retailerHostFingerprints as retailerHosts3 } from './known-issue-reviewed-retailer-links/buick';
import { productUrlFingerprints as productUrls4, vendorUrlFingerprints as vendorUrls4, retailerHostFingerprints as retailerHosts4 } from './known-issue-reviewed-retailer-links/cadillac';
import { productUrlFingerprints as productUrls5, vendorUrlFingerprints as vendorUrls5, retailerHostFingerprints as retailerHosts5 } from './known-issue-reviewed-retailer-links/chrysler';
import { productUrlFingerprints as productUrls6, vendorUrlFingerprints as vendorUrls6, retailerHostFingerprints as retailerHosts6 } from './known-issue-reviewed-retailer-links/citroen';
import { productUrlFingerprints as productUrls7, vendorUrlFingerprints as vendorUrls7, retailerHostFingerprints as retailerHosts7 } from './known-issue-reviewed-retailer-links/cupra';
import { productUrlFingerprints as productUrls8, vendorUrlFingerprints as vendorUrls8, retailerHostFingerprints as retailerHosts8 } from './known-issue-reviewed-retailer-links/dacia';
import { productUrlFingerprints as productUrls9, vendorUrlFingerprints as vendorUrls9, retailerHostFingerprints as retailerHosts9 } from './known-issue-reviewed-retailer-links/datsun';
import { productUrlFingerprints as productUrls10, vendorUrlFingerprints as vendorUrls10, retailerHostFingerprints as retailerHosts10 } from './known-issue-reviewed-retailer-links/ford';
import { productUrlFingerprints as productUrls11, vendorUrlFingerprints as vendorUrls11, retailerHostFingerprints as retailerHosts11 } from './known-issue-reviewed-retailer-links/genesis';
import { productUrlFingerprints as productUrls12, vendorUrlFingerprints as vendorUrls12, retailerHostFingerprints as retailerHosts12 } from './known-issue-reviewed-retailer-links/gmc';
import { productUrlFingerprints as productUrls13, vendorUrlFingerprints as vendorUrls13, retailerHostFingerprints as retailerHosts13 } from './known-issue-reviewed-retailer-links/honda';
import { productUrlFingerprints as productUrls14, vendorUrlFingerprints as vendorUrls14, retailerHostFingerprints as retailerHosts14 } from './known-issue-reviewed-retailer-links/hyundai';
import { productUrlFingerprints as productUrls15, vendorUrlFingerprints as vendorUrls15, retailerHostFingerprints as retailerHosts15 } from './known-issue-reviewed-retailer-links/infiniti';
import { productUrlFingerprints as productUrls16, vendorUrlFingerprints as vendorUrls16, retailerHostFingerprints as retailerHosts16 } from './known-issue-reviewed-retailer-links/international';
import { productUrlFingerprints as productUrls17, vendorUrlFingerprints as vendorUrls17, retailerHostFingerprints as retailerHosts17 } from './known-issue-reviewed-retailer-links/jaguar';
import { productUrlFingerprints as productUrls18, vendorUrlFingerprints as vendorUrls18, retailerHostFingerprints as retailerHosts18 } from './known-issue-reviewed-retailer-links/jeep';
import { productUrlFingerprints as productUrls19, vendorUrlFingerprints as vendorUrls19, retailerHostFingerprints as retailerHosts19 } from './known-issue-reviewed-retailer-links/kia';
import { productUrlFingerprints as productUrls20, vendorUrlFingerprints as vendorUrls20, retailerHostFingerprints as retailerHosts20 } from './known-issue-reviewed-retailer-links/land-rover';
import { productUrlFingerprints as productUrls21, vendorUrlFingerprints as vendorUrls21, retailerHostFingerprints as retailerHosts21 } from './known-issue-reviewed-retailer-links/lexus';
import { productUrlFingerprints as productUrls22, vendorUrlFingerprints as vendorUrls22, retailerHostFingerprints as retailerHosts22 } from './known-issue-reviewed-retailer-links/lincoln';
import { productUrlFingerprints as productUrls23, vendorUrlFingerprints as vendorUrls23, retailerHostFingerprints as retailerHosts23 } from './known-issue-reviewed-retailer-links/lucid';
import { productUrlFingerprints as productUrls24, vendorUrlFingerprints as vendorUrls24, retailerHostFingerprints as retailerHosts24 } from './known-issue-reviewed-retailer-links/mazda';
import { productUrlFingerprints as productUrls25, vendorUrlFingerprints as vendorUrls25, retailerHostFingerprints as retailerHosts25 } from './known-issue-reviewed-retailer-links/mercedes-benz';
import { productUrlFingerprints as productUrls26, vendorUrlFingerprints as vendorUrls26, retailerHostFingerprints as retailerHosts26 } from './known-issue-reviewed-retailer-links/mercury';
import { productUrlFingerprints as productUrls27, vendorUrlFingerprints as vendorUrls27, retailerHostFingerprints as retailerHosts27 } from './known-issue-reviewed-retailer-links/mg';
import { productUrlFingerprints as productUrls28, vendorUrlFingerprints as vendorUrls28, retailerHostFingerprints as retailerHosts28 } from './known-issue-reviewed-retailer-links/mini';
import { productUrlFingerprints as productUrls29, vendorUrlFingerprints as vendorUrls29, retailerHostFingerprints as retailerHosts29 } from './known-issue-reviewed-retailer-links/mitsubishi';
import { productUrlFingerprints as productUrls30, vendorUrlFingerprints as vendorUrls30, retailerHostFingerprints as retailerHosts30 } from './known-issue-reviewed-retailer-links/nissan';
import { productUrlFingerprints as productUrls31, vendorUrlFingerprints as vendorUrls31, retailerHostFingerprints as retailerHosts31 } from './known-issue-reviewed-retailer-links/opel';
import { productUrlFingerprints as productUrls32, vendorUrlFingerprints as vendorUrls32, retailerHostFingerprints as retailerHosts32 } from './known-issue-reviewed-retailer-links/peugeot';
import { productUrlFingerprints as productUrls33, vendorUrlFingerprints as vendorUrls33, retailerHostFingerprints as retailerHosts33 } from './known-issue-reviewed-retailer-links/polestar';
import { productUrlFingerprints as productUrls34, vendorUrlFingerprints as vendorUrls34, retailerHostFingerprints as retailerHosts34 } from './known-issue-reviewed-retailer-links/pontiac';
import { productUrlFingerprints as productUrls35, vendorUrlFingerprints as vendorUrls35, retailerHostFingerprints as retailerHosts35 } from './known-issue-reviewed-retailer-links/porsche';
import { productUrlFingerprints as productUrls36, vendorUrlFingerprints as vendorUrls36, retailerHostFingerprints as retailerHosts36 } from './known-issue-reviewed-retailer-links/ram';
import { productUrlFingerprints as productUrls37, vendorUrlFingerprints as vendorUrls37, retailerHostFingerprints as retailerHosts37 } from './known-issue-reviewed-retailer-links/renault';
import { productUrlFingerprints as productUrls38, vendorUrlFingerprints as vendorUrls38, retailerHostFingerprints as retailerHosts38 } from './known-issue-reviewed-retailer-links/rivian';
import { productUrlFingerprints as productUrls39, vendorUrlFingerprints as vendorUrls39, retailerHostFingerprints as retailerHosts39 } from './known-issue-reviewed-retailer-links/saab';
import { productUrlFingerprints as productUrls40, vendorUrlFingerprints as vendorUrls40, retailerHostFingerprints as retailerHosts40 } from './known-issue-reviewed-retailer-links/saturn';
import { productUrlFingerprints as productUrls41, vendorUrlFingerprints as vendorUrls41, retailerHostFingerprints as retailerHosts41 } from './known-issue-reviewed-retailer-links/seat';
import { productUrlFingerprints as productUrls42, vendorUrlFingerprints as vendorUrls42, retailerHostFingerprints as retailerHosts42 } from './known-issue-reviewed-retailer-links/skoda';
import { productUrlFingerprints as productUrls43, vendorUrlFingerprints as vendorUrls43, retailerHostFingerprints as retailerHosts43 } from './known-issue-reviewed-retailer-links/subaru';
import { productUrlFingerprints as productUrls44, vendorUrlFingerprints as vendorUrls44, retailerHostFingerprints as retailerHosts44 } from './known-issue-reviewed-retailer-links/suzuki';
import { productUrlFingerprints as productUrls45, vendorUrlFingerprints as vendorUrls45, retailerHostFingerprints as retailerHosts45 } from './known-issue-reviewed-retailer-links/tesla';
import { productUrlFingerprints as productUrls46, vendorUrlFingerprints as vendorUrls46, retailerHostFingerprints as retailerHosts46 } from './known-issue-reviewed-retailer-links/toyota';
import { productUrlFingerprints as productUrls47, vendorUrlFingerprints as vendorUrls47, retailerHostFingerprints as retailerHosts47 } from './known-issue-reviewed-retailer-links/triumph';
import { productUrlFingerprints as productUrls48, vendorUrlFingerprints as vendorUrls48, retailerHostFingerprints as retailerHosts48 } from './known-issue-reviewed-retailer-links/volkswagen';
import { productUrlFingerprints as productUrls49, vendorUrlFingerprints as vendorUrls49, retailerHostFingerprints as retailerHosts49 } from './known-issue-reviewed-retailer-links/volvo';

const REVIEWED_PRODUCT_URLS = new Set<string>([...productUrls0, ...productUrls1, ...productUrls2, ...productUrls3, ...productUrls4, ...productUrls5, ...productUrls6, ...productUrls7, ...productUrls8, ...productUrls9, ...productUrls10, ...productUrls11, ...productUrls12, ...productUrls13, ...productUrls14, ...productUrls15, ...productUrls16, ...productUrls17, ...productUrls18, ...productUrls19, ...productUrls20, ...productUrls21, ...productUrls22, ...productUrls23, ...productUrls24, ...productUrls25, ...productUrls26, ...productUrls27, ...productUrls28, ...productUrls29, ...productUrls30, ...productUrls31, ...productUrls32, ...productUrls33, ...productUrls34, ...productUrls35, ...productUrls36, ...productUrls37, ...productUrls38, ...productUrls39, ...productUrls40, ...productUrls41, ...productUrls42, ...productUrls43, ...productUrls44, ...productUrls45, ...productUrls46, ...productUrls47, ...productUrls48, ...productUrls49]);
const REVIEWED_VENDOR_URLS = new Set<string>([...vendorUrls0, ...vendorUrls1, ...vendorUrls2, ...vendorUrls3, ...vendorUrls4, ...vendorUrls5, ...vendorUrls6, ...vendorUrls7, ...vendorUrls8, ...vendorUrls9, ...vendorUrls10, ...vendorUrls11, ...vendorUrls12, ...vendorUrls13, ...vendorUrls14, ...vendorUrls15, ...vendorUrls16, ...vendorUrls17, ...vendorUrls18, ...vendorUrls19, ...vendorUrls20, ...vendorUrls21, ...vendorUrls22, ...vendorUrls23, ...vendorUrls24, ...vendorUrls25, ...vendorUrls26, ...vendorUrls27, ...vendorUrls28, ...vendorUrls29, ...vendorUrls30, ...vendorUrls31, ...vendorUrls32, ...vendorUrls33, ...vendorUrls34, ...vendorUrls35, ...vendorUrls36, ...vendorUrls37, ...vendorUrls38, ...vendorUrls39, ...vendorUrls40, ...vendorUrls41, ...vendorUrls42, ...vendorUrls43, ...vendorUrls44, ...vendorUrls45, ...vendorUrls46, ...vendorUrls47, ...vendorUrls48, ...vendorUrls49]);
const REVIEWED_RETAILER_HOSTS = new Set<string>([...retailerHosts0, ...retailerHosts1, ...retailerHosts2, ...retailerHosts3, ...retailerHosts4, ...retailerHosts5, ...retailerHosts6, ...retailerHosts7, ...retailerHosts8, ...retailerHosts9, ...retailerHosts10, ...retailerHosts11, ...retailerHosts12, ...retailerHosts13, ...retailerHosts14, ...retailerHosts15, ...retailerHosts16, ...retailerHosts17, ...retailerHosts18, ...retailerHosts19, ...retailerHosts20, ...retailerHosts21, ...retailerHosts22, ...retailerHosts23, ...retailerHosts24, ...retailerHosts25, ...retailerHosts26, ...retailerHosts27, ...retailerHosts28, ...retailerHosts29, ...retailerHosts30, ...retailerHosts31, ...retailerHosts32, ...retailerHosts33, ...retailerHosts34, ...retailerHosts35, ...retailerHosts36, ...retailerHosts37, ...retailerHosts38, ...retailerHosts39, ...retailerHosts40, ...retailerHosts41, ...retailerHosts42, ...retailerHosts43, ...retailerHosts44, ...retailerHosts45, ...retailerHosts46, ...retailerHosts47, ...retailerHosts48, ...retailerHosts49]);

function canonicalUrl(value: string): string | null {
  try {
    const url = new URL(value);
    url.hash = '';
    return url.toString();
  } catch {
    return null;
  }
}

function fingerprint(value: string): string {
  const hash = (seed: number): string => {
    let result = (0x811c9dc5 ^ seed) >>> 0;
    for (let index = 0; index < value.length; index += 1) {
      result = Math.imul(result ^ value.charCodeAt(index), 0x01000193) >>> 0;
    }
    result = (result ^ (result >>> 16)) >>> 0;
    result = Math.imul(result, 0x85ebca6b) >>> 0;
    result = (result ^ (result >>> 13)) >>> 0;
    result = Math.imul(result, 0xc2b2ae35) >>> 0;
    result = (result ^ (result >>> 16)) >>> 0;
    return result.toString(16).padStart(8, '0');
  };
  return `${hash(0x9e3779b9)}${hash(0x243f6a88)}${hash(0xb7e15162)}`;
}

export function isReviewedKnownIssueProductUrl(value: string): boolean {
  const canonical = canonicalUrl(value);
  return canonical !== null && REVIEWED_PRODUCT_URLS.has(fingerprint(canonical));
}

export function isReviewedKnownIssueVendorUrl(vendor: string, value: string): boolean {
  const canonical = canonicalUrl(value);
  return canonical !== null && REVIEWED_VENDOR_URLS.has(fingerprint(`${vendor.trim().toLowerCase()}\n${canonical}`));
}

export function isReviewedKnownIssueRetailerHost(host: string): boolean {
  return REVIEWED_RETAILER_HOSTS.has(fingerprint(host.trim().toLowerCase().replace(/^www\./, '')));
}
