// GENERATED by scripts/build-repair-first-verified-batch.mjs. Do not edit by hand.
// Batch modules are additive so a new make review cannot remove prior approvals.

import { productUrlFingerprints as productUrls0, vendorUrlFingerprints as vendorUrls0, retailerHostFingerprints as retailerHosts0 } from './known-issue-reviewed-retailer-links/honda';
import { productUrlFingerprints as productUrls1, vendorUrlFingerprints as vendorUrls1, retailerHostFingerprints as retailerHosts1 } from './known-issue-reviewed-retailer-links/hyundai';
import { productUrlFingerprints as productUrls2, vendorUrlFingerprints as vendorUrls2, retailerHostFingerprints as retailerHosts2 } from './known-issue-reviewed-retailer-links/infiniti';
import { productUrlFingerprints as productUrls3, vendorUrlFingerprints as vendorUrls3, retailerHostFingerprints as retailerHosts3 } from './known-issue-reviewed-retailer-links/jaguar';
import { productUrlFingerprints as productUrls4, vendorUrlFingerprints as vendorUrls4, retailerHostFingerprints as retailerHosts4 } from './known-issue-reviewed-retailer-links/jeep';
import { productUrlFingerprints as productUrls5, vendorUrlFingerprints as vendorUrls5, retailerHostFingerprints as retailerHosts5 } from './known-issue-reviewed-retailer-links/kia';

const REVIEWED_PRODUCT_URLS = new Set<string>([...productUrls0, ...productUrls1, ...productUrls2, ...productUrls3, ...productUrls4, ...productUrls5]);
const REVIEWED_VENDOR_URLS = new Set<string>([...vendorUrls0, ...vendorUrls1, ...vendorUrls2, ...vendorUrls3, ...vendorUrls4, ...vendorUrls5]);
const REVIEWED_RETAILER_HOSTS = new Set<string>([...retailerHosts0, ...retailerHosts1, ...retailerHosts2, ...retailerHosts3, ...retailerHosts4, ...retailerHosts5]);

function canonicalUrl(value: string): string | null {
  try {
    const url = new URL(value);
    url.hash = '';
    return url.toString();
  } catch {
    return null;
  }
}

function fingerprint(value: string): string {
  const hash = (seed: number): string => {
    let result = (0x811c9dc5 ^ seed) >>> 0;
    for (let index = 0; index < value.length; index += 1) {
      result = Math.imul(result ^ value.charCodeAt(index), 0x01000193) >>> 0;
    }
    result = (result ^ (result >>> 16)) >>> 0;
    result = Math.imul(result, 0x85ebca6b) >>> 0;
    result = (result ^ (result >>> 13)) >>> 0;
    result = Math.imul(result, 0xc2b2ae35) >>> 0;
    result = (result ^ (result >>> 16)) >>> 0;
    return result.toString(16).padStart(8, '0');
  };
  return `${hash(0x9e3779b9)}${hash(0x243f6a88)}${hash(0xb7e15162)}`;
}

export function isReviewedKnownIssueProductUrl(value: string): boolean {
  const canonical = canonicalUrl(value);
  return canonical !== null && REVIEWED_PRODUCT_URLS.has(fingerprint(canonical));
}

export function isReviewedKnownIssueVendorUrl(vendor: string, value: string): boolean {
  const canonical = canonicalUrl(value);
  return canonical !== null && REVIEWED_VENDOR_URLS.has(fingerprint(`${vendor.trim().toLowerCase()}\n${canonical}`));
}

export function isReviewedKnownIssueRetailerHost(host: string): boolean {
  return REVIEWED_RETAILER_HOSTS.has(fingerprint(host.trim().toLowerCase().replace(/^www\./, '')));
}
