// GENERATED by scripts/build-repair-first-verified-batch.mjs for Citroen.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://automotopart.co.uk/products/valeo-828342-clutch-kit
  '63c28844eef4f485fd0f780f',
  // https://citroendirectparts.co.uk/product/citroen-c3-2002-2005-petrol-cabin-pollen-filter/
  'cb385c61c90ab815be0111e4',
  // https://eurofrance24.fr/pompe-a-eau-original-citroen-peugeot-c4-c5-308-508-16thp-1201j8.html
  '7527c3d1d1b1f8742da9c9ee',
  // https://onlineautomotive.co.uk/citroen/c1/2016/1.0/transmission/clutch-kits-and-parts/luk/620335700?id=930589
  'deb0b33038060b46fc555d21',
  // https://shop.advanceautoparts.com/p/303-products-automotive-protectant-24-oz-30232/12567548-P
  '46e75bb935a31d8746bb22a9',
  // https://tpuk.net/turbo-fitting-kit-1-6-hdi-tdci-dv6-110-ford-peugeot-citroen-oil-pump-filter-kit.html
  '6758a2b6642301d1e48403e3',
  // https://www.ebay.co.uk/itm/278291477342?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'c76123213d0b1372614ed98e',
  // https://www.lymmengineparts.co.uk/citroen-EB2DT-timing-belt-kit
  'c09535611750da5b848bfebe',
  // https://www.lymmengineparts.co.uk/timing-chain-kit-for-citroen-c4-c5-ds3-ds4-ds5-1-6-thp-vti-ep6
  '33b3835a6660a02f3302b74b',
  // https://www.partservice.co.uk/citroen-c3-1.4-diesel-2003/product/filt-fi-filters-air-cabin-fuel-oil/cabin-filter/FRAAHC319
  'fd1241202b8f057eb1d29f48',
  // https://www.sphere-discount.com/gb/hydractive-3/306098-7-spheres-for-citroen-c5-hydractive-3.html
  'cb8908d907375bfec087e99d',
  // https://www.vidarrautomotive.co.uk/product-page/turbocharger-oil-feed-pipe-for-citroen-ds3-ds4-ds5-1-6-thp-2010-2015-ecd-ct-002a
  '191e6956129b28e9d8ad2c46',
  // https://www.winparts.co.uk/engine-parts-accessories/ignition/ignition-coil/c612/ignition-coil-dic-0100-denso/p658658.html
  '321ef4327e95c505d13153a0',
] as const;

export const vendorUrlFingerprints = [
  // advance auto parts | https://shop.advanceautoparts.com/p/303-products-automotive-protectant-24-oz-30232/12567548-P
  '56ba7bd72ece8feddd4c0d74',
  // automotopart | https://automotopart.co.uk/products/valeo-828342-clutch-kit
  '40023dccd00c7ef19362dba4',
  // citroen direct parts | https://citroendirectparts.co.uk/product/citroen-c3-2002-2005-petrol-cabin-pollen-filter/
  '002bea3fef36b29c2046ae7a',
  // ebay uk / nn4-online | https://www.ebay.co.uk/itm/278291477342?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'c16f55f3d6a039c69566e2b8',
  // eurofrance24 | https://eurofrance24.fr/pompe-a-eau-original-citroen-peugeot-c4-c5-308-508-16thp-1201j8.html
  '5030a15655c88bbdb52127e6',
  // lymm engine parts | https://www.lymmengineparts.co.uk/citroen-EB2DT-timing-belt-kit
  '6e4ec8aad90832a8a75e7e70',
  // lymm engine parts | https://www.lymmengineparts.co.uk/timing-chain-kit-for-citroen-c4-c5-ds3-ds4-ds5-1-6-thp-vti-ep6
  'b415b2a2a34cab9188cbc3b4',
  // online automotive uk | https://onlineautomotive.co.uk/citroen/c1/2016/1.0/transmission/clutch-kits-and-parts/luk/620335700?id=930589
  'f0c91ccb894f6f5061939863',
  // partservice ltd | https://www.partservice.co.uk/citroen-c3-1.4-diesel-2003/product/filt-fi-filters-air-cabin-fuel-oil/cabin-filter/FRAAHC319
  'c4cea6a70754feae925219e9',
  // sphere discount / fournitures auto ouest | https://www.sphere-discount.com/gb/hydractive-3/306098-7-spheres-for-citroen-c5-hydractive-3.html
  'ab5199b5a12d2979b68fa7b4',
  // transit parts uk | https://tpuk.net/turbo-fitting-kit-1-6-hdi-tdci-dv6-110-ford-peugeot-citroen-oil-pump-filter-kit.html
  '44f7d21e01d2b14b58c2390c',
  // vidarr automotive | https://www.vidarrautomotive.co.uk/product-page/turbocharger-oil-feed-pipe-for-citroen-ds3-ds4-ds5-1-6-thp-2010-2015-ecd-ct-002a
  '18a5f6277e1daabc77c81be7',
  // winparts uk | https://www.winparts.co.uk/engine-parts-accessories/ignition/ignition-coil/c612/ignition-coil-dic-0100-denso/p658658.html
  '71f6946bc08ce66827128d23',
] as const;

export const retailerHostFingerprints = [
  // automotopart.co.uk
  '72e928ec7051bff20702a64f',
  // citroendirectparts.co.uk
  'cab69a5bc95ae6f715a4bb3b',
  // ebay.co.uk
  'b8ce2a1a552a116904d8b01a',
  // eurofrance24.fr
  '243ca48c7e7c0886745ef3f8',
  // lymmengineparts.co.uk
  '2a1cb09f39b5709c9c960421',
  // onlineautomotive.co.uk
  '51bde1f3e17bb17bfdec512a',
  // partservice.co.uk
  'b617762bc3de5c8abc788843',
  // shop.advanceautoparts.com
  '3d7f5ea36b6847e33e997fca',
  // sphere-discount.com
  '65c2361c0cc12a686ced8dc9',
  // tpuk.net
  '1b1752f61d791457cbc5b7a2',
  // vidarrautomotive.co.uk
  '260b291f75e176a5ac225ff4',
  // winparts.co.uk
  'a93bc9ddb8951d55000a7066',
] as const;
