// GENERATED by scripts/build-repair-first-verified-batch.mjs for Hyundai.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://a-premium.com/product/aisin-ac-compressor-accaz-00631
  '62848d0395a76f0235c3a9ae',
  // https://a-premium.com/product/aisin-ac-compressor-accaz-00633
  '8ff76d748b55489f61d575c1',
  // https://a-premium.com/product/denso-ac-compressor-471-6063
  '43bf2402a32041a833e39efc',
  // https://newparts.com/product/monroe/171405
  'c97a577743a45962bb031cc3',
  // https://otoparcasan.com/oto-yedek-parca/hyundai_i20_i20-gb-09-2014/triger-zincir-seti?o=o
  'b35dd7fa926462cfc2f24b7e',
  // https://partsouq.com/shop/product/976143X000-hyundai-kia-thermistor-assy-a-c-evap/14909777
  'bd5602ada2773a93789bdae2',
  // https://shop.advanceautoparts.com/p/driveworks-camber-bolt-kit-dw-k5330/11049756-P
  '004527ba021512761df72b60',
  // https://www.autodoc.co.uk/exedy/8346294
  'a4f4fa49ac87e822fdefbf9c',
  // https://www.autopartsprime.com/hyundai/sensor-crankshaft-position/oe-391802b000?pnType=2
  '1bfed20a252570a922621633',
  // https://www.autozone.com/p/cloyes-engine-timing-chain-kit-9-0976sx/1460002
  'b34e19d6b122d6a9e870f333',
  // https://www.autozone.com/p/duralast-platinum-battery-h6-agm/319460
  '28fcf208d9ec597fc0822166',
  // https://www.autozone.com/p/mobil-1-gear-oil-104361/1437
  '514e36de22c6d2b5ec1226ec',
  // https://www.autozone.com/p/mobil-1-motor-oil-120903/452341
  '55330db037ef3cea72c48060',
  // https://www.autozone.com/p/noco-battery-charger-genius1/606157
  '9f33b7ac8d165c441da7abb4',
  // https://www.autozone.com/p/optima-battery-dh5/1340240
  '3115bb5eb59a982d74c1d316',
  // https://www.autozone.com/p/pennzoil-motor-oil-550046126/426996
  'a252de1dcd29dc82b2514d2e',
  // https://www.autozone.com/p/permatex-silicone-grease-20352/1459493
  '40bfc2edc762fe034036cbc9',
  // https://www.batterymart.com/p-battery-tender-jr-12v-0_75a-battery-charger.html
  '647103cc4c8079f6fa154377',
  // https://www.bksmotors.com/4142132000.html
  'b5d4566a10bf1d66b38d4795',
  // https://www.bksmotors.com/843664.html
  '651d5e049acd2e38a76e9344',
  // https://www.bksmotors.com/844409.html
  '5be9bbd88a25cc11e79b1b9f',
  // https://www.cartoolshop.com/products/timing-chain-kit-exhaust-intake-cvvt-gear-24321-2e000-for-kia-soul-hyundai-elantra-2-0l-1-8l-l4
  'c5c9383b57fa4b45e2d9e23b',
  // https://www.genracer.com/oem-hyundai-concentric-slave-cylinder-for-hyundai-genesis-coupe-2010-16/
  '9fbf3319c227dd6bb7bac8af',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-atf-jws-3309-t4~00232-19023.html
  '751f6abec7ad64c49f8988f9',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-bearing-kit~56359-l1aaa-fff.html
  '8fa8095a90cfaa9ad8152664',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-boot-kit-fr-axle-whe~49509-24a01.html
  '2dbcdd504a04b0befab80096',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-bush-trail-arm~55160-1e000.html
  '02f3a55a9eb0f702cfdd0e21',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-bush-trail-arm~55160-1r000.html
  '5605fcb70b39ea0107e8d8b9',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake-lh~58310-d3a00.html
  'd97810ee13e0f7c1d89bf54d',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake-lh~58310-n9a10.html
  '516e161ba0d6f8ecb38a5d3d',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake-rh~58311-d3a00.html
  '6fcd1d1da95273668c47d88a',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake-rh~58311-n9a10.html
  'da6a99f6f74ce995a012611f',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake~58310-2ca31.html
  'bff1d46a9cd472bf281b71f7',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake~58311-2ca31.html
  '8250a14bbd873614940e106c',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-camera-assy-back-view~99240-k2000.html
  '86517576504681f293ed4831',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-camera-assy-back-view~99240-k2500.html
  '60d1db5d3ca2e8dec76b177b',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-cap-assy-fuel-filler~31010-2c700.html
  'c01acf986026fe8172609cae',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-cap-assy-fuel-filler~31010-3l600.html
  '6c17af294576e611ccda2297',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-checker-assy-rr-door~79490-2v000.html
  '9d0d114786afdc8a5ccf293e',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-2s500.html
  '99ce79e42726f7efda37a34f',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-2s602.html
  '76ed85dee4ab3caea244ef91',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-c2000.html
  'bc6c3c148792ec654a2f7e3d',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-c2100.html
  '5a6ad0583cbc2888b9fb83ea',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-c2500.html
  'bd14e422f9f7373596ed79e4',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-c2600.html
  '44967de4dba9770b932c249f',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-d3200.html
  '0e2e812f369573504895b6e6',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-d3300.html
  'd6627c38d44a40c554b3aa3d',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-d3750.html
  'a299b21033f736d1cf5bb98b',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-d3950.html
  'e83c7690fd65e3ed1972a73a',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-d9001.html
  'c08b2ff7864e6f3594ad4f78',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-j9000.html
  '44cbe6e1c5ee0d5fa6167e37',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-j9200.html
  '23f94b43bf7bacbfdb79e2a2',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-j9500.html
  'f82bb2c1f8491b50fa8cbb7c',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-coupling-assy-4wd~47800-24700.html
  'fd33677486efbe19bbe293b5',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-coupling-assy-4wd~47800-3b510.html
  'c2960e5524f8fffed9c50d1c',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-coupling-assy-4wd~47800-3b520.html
  '0f8a856b6c8a55e6a64d9e7e',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-cylinder-assy-clutch-release~41710-39100.html
  'b56371c6187db54ced03bfad',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-cylinder-assy-clutch~41710-28000.html
  'b1787f3aebc061a3936a0476',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-flexible-coupling~56315-2k000-fff.html
  'a07f16fe0c134042e7ff10ca',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-fuel-pump-sender-m~31110-2d501.html
  'ea970af0df511c998fbe60cc',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-gasket-surge-tank~29215-37100.html
  '895b503a669185d2dcb353d3',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-gasket-surge-tank~29215-3c100.html
  'e62bb40b9448d3bc36265fe1',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-gasket-surge-tank~29215-3c200.html
  '19756c7d6b04a1d1a8954085',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-hose-assy-p-s-oil-pr~57510-3l100.html
  '3d008fffc376dcdbf77efd17',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-hose-assy-p-s-oil-pr~57510-3l300.html
  'f06a821f6e9dbed9489a8f0f',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-joint-assy-strg~56400-2m000.html
  'fe88919c31666dddde405319',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-joint-assy-strg~56400-3n000.html
  'cae58c071480938c7f5da5f9',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-joint-assy-strg~56400-3n001.html
  '88b31ddc09775e34813ffb0d',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-joint-assy-strg~56400-3n100.html
  '247a699c3dfbe802730b4310',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-link-assy-front-stabilizer-lh~54830-gi000.html
  'a4fc8e7ed21aee70f8b21d49',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-link-assy-front-stabilizer-rh~54831-gi000.html
  '9745410bf6569a23f0e02424',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-oil-control-valve-as~24355-23800.html
  '73a6954a2a9055a5710a5b86',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-oil-control-valve-as~24355-2b700.html
  '5c740d7462d733794887b023',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-oil-flow-control-val~24355-2e100.html
  '6076f1e9bf8bcc160a1e6c06',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-oil-flow-control-val~24355-2g500.html
  '9848ee5d8269983e1174ad7a',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-oil-flow-control-val~24375-2g500.html
  'a9a9de19a11f99fc66f7f305',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-parking-brake-assy-e~59700-3m900.html
  '623b358e4b0959e529dea6f7',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-parking-brake-assy-electronic~59700-3n600.html
  '058d470d620069370f06fb4b',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-pump-high-pressure~35320-2g740.html
  '2e4ca0e6f38756ff23b76219',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-regulator-assy-fr-dr-p-wdo-lh~82403-39000.html
  'f726ba66e6ae5c95f90e64cd',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-regulator-assy-fr-dr-p-wdo-rh~82404-39000.html
  '7d1ae02a1f1931149f72e33d',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-regulator-assy-rr-dr~83404-39000.html
  '6879816fb5f3f7e7c5b53978',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-roller-tappet~35325-2g700.html
  '2aeda2260f4ebbbd0e83211d',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-seal-oil~47351-39010.html
  '2e5e1ad456f1f3ce26cd1a62',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-seal-oil~53050-3c000.html
  '4c87e42890799e441b8aeabb',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-seal-oil~53050-3c021.html
  '0214df8c5184aaac4c48ee9b',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-sensor-assy-input-sp~42620-39051.html
  '6c2954fcf9ea7660d460a95f',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-sensor-assy-knock~39250-2e000.html
  'bfdef246f544a6c8d0ea3bab',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-sensor-fuel-tank-pre~31435-1ea00.html
  '1bba43a60c05675e59fd0ba6',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-service-kit-oil-filter-2~26320-3ckb0.html
  '0886ffbf3b4b5a186b1cf5c6',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-service-kit-oil-filter~26350-2m000.html
  'edc05fb18c30201be4a057c0',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-set-double-clutch~41200-2d220.html
  '2de5962044737f3198286073',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-sp-cvt-1~00232-19081.html
  '7f398353f32a9ce91e99207e',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-spacer-pinion-bearin~53045-3c000.html
  'edd19e3c8db9f67fa4764437',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-starter-assy-kit~36100-3ca00.html
  '5312fe65903593d6e533eeb2',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-starter-assy~36100-3c150.html
  '4819a23d0e9186cb4d6c596a',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-starter-assy~36100-3c221.html
  'b1aa70c0c94abcd727f664be',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-switch-assy-stop-lamp-4p~93810-38110.html
  '13301acaa0cc1040a3da1e31',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-tensioner-assy-timing-chain~24410-3f401.html
  '6e6de0b1ea3dbfe7d79209fe',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-tensioner-assy-timing-chain~24410-3f411.html
  '1540250505b84aaf583ac5ec',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-tensioner-assy-vlv-t~24410-21010.html
  '3b00bb4dfd92177de33b16f5',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-thermostat-assy~25500-23010.html
  '6ac35584e447104828303f51',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-thermostat-assy~25500-2gga0.html
  '24a238789e7b7994011ab7a3',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-turbocharger~28231-2b700.html
  '072ac1f2403b40c30bafa4d6',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-turbocharger~28231-2b740.html
  'bc0c6dee37d40ae6da855b90',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-valve-pcv~26740-21314.html
  '640f38cd9fa8fb8f4bdc2d97',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-valve-purge-control~28910-22040.html
  'bb56f97074a446c6fcdc775c',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-valve-purge-control~28910-25100.html
  'd7f961c968a292009a0efe32',
  // https://www.hyundaipartsdeal.com/genuine/hyundai-valve-purge-control~28910-3c200.html
  '797a0a0d9f224f75595fc43d',
  // https://www.hyundaipartsdeal.com/oem-hyundai-entourage-crankshaft_position_sensor.html
  '88d419d1e70d6c094b3c5707',
  // https://www.hyundaipartsdeal.com/oem-hyundai-pcv_valve.html
  '62276947544053b1a8f02f16',
  // https://www.jegs.com/i/Melling/689/3-1045S/10002/-1
  'ed3c9405312f1980f9e227ca',
  // https://www.motoristas.com.br/embreagem/kits-de-embreagem/kit-embreagem-hb20-1-0-2012-2013-2014-2015-2016
  'dba265943f725d050dda1d34',
  // https://www.motrparts.com/shop/valeo-hyundai-creta-clutch-set-843663/
  'f2b23c2e608699e63d7cfac6',
  // https://www.partsgeek.com/cfw8bjp-hyundai-tiburon-timing-belt-kit.html
  '28a75b647a987e6e9463cddf',
  // https://www.partsgeek.com/dq241cj-hyundai-xg350-intake-manifold-gasket-set.html
  '70154f4fa15d79afe66c72b0',
  // https://www.partsgeek.com/grp7rg5-hyundai-elantra-timing-belt-kit.html
  '9dff74df329cefddc3061574',
  // https://www.partsgeek.com/j2qpgxn-hyundai-tiburon-timing-belt-kit.html
  '2d3b4efb623eb4091e4d7cb8',
  // https://www.partsgeek.com/mjk37wz-hyundai-elantra-wheel-bearing.html
  'd1d2858a5f449c5a5fb04497',
  // https://www.partsgeek.com/np5gz2s-hyundai-xg350-timing-belt-kit.html
  '12f52d5ca8ca3dda5ee29a04',
  // https://www.partsgeek.com/shmgq2h-hyundai-xg350-power-steering-pump.html
  '980d26ee84cee39f4536d5d3',
  // https://www.shockwarehouse.com/products/kyb-sm5618-mount-components
  'c9a35b5f6995aae31a2fc755',
  // https://www.sixityauto.com/gates-timing-belt-kit-w/-water-pump-for-2003-2008-hyundai-tiburon-2-7l-v6---engine-tckwp-oe-upgrade-2020031581.html
  'b4648005a5c70448274214b5',
  // https://www.suncoreindustries.com/product/23286/for-hyundai-equus-2009-2016-rear-pair-air-ride-suspension-spring-bags
  'bc1a426bd93ef0083cab839c',
  // https://www.suspension.com/beck-arnley/monroe-171404
  '2d895fd9c61b2ba97e32fec2',
  // https://www.tirerack.com/tires/tires.jsp?partnum=44YR0EPRXL&tireMake=Michelin&tireModel=e.PRIMACY
  '3661ed90e288b076e9e9fd77',
  // https://yoshiparts.com/parts/hyundai-4262139052
  '3aedef5e12f2e733f58ab759',
] as const;

export const vendorUrlFingerprints = [
  // a-premium | https://a-premium.com/product/aisin-ac-compressor-accaz-00631
  'a3c1e1549c4804cbfcbe4779',
  // a-premium | https://a-premium.com/product/aisin-ac-compressor-accaz-00633
  'b3d4f890645cdd6db51bb3db',
  // a-premium | https://a-premium.com/product/denso-ac-compressor-471-6063
  'd6700242f494846907efc015',
  // advance auto parts | https://shop.advanceautoparts.com/p/driveworks-camber-bolt-kit-dw-k5330/11049756-P
  '18948f8a9e24ec9824ce1a4f',
  // amazon | https://www.amazon.com/dp/B01MZ1TS1U?tag=au7o-20
  'd2a4cbb882023b8db6d45c6b',
  // amazon | https://www.amazon.com/dp/B01N9S55AN?tag=au7o-20
  '74ca02197cacd85d4ce13c33',
  // amazon | https://www.amazon.com/MAHLE-Original-VS50409-Engine-Gasket/dp/B005ETOQ52?tag=au7o-20
  'bc83196b775f4dab5b9805b1',
  // amazon | https://www.amazon.com/Walker-Products-235-1456-engineered-components/dp/B079YJZKWW?tag=au7o-20
  'afd0c7113afb95183e02fb38',
  // auto peças motoristas | https://www.motoristas.com.br/embreagem/kits-de-embreagem/kit-embreagem-hb20-1-0-2012-2013-2014-2015-2016
  '8327c6bc663c3da128c5fc5f',
  // autodoc uk | https://www.autodoc.co.uk/exedy/8346294
  'bf954c49f2ba4678985cb861',
  // autopartsprime | https://www.autopartsprime.com/hyundai/sensor-crankshaft-position/oe-391802b000?pnType=2
  '8c2a82696c7a7781561e753b',
  // autozone | https://www.autozone.com/p/cloyes-engine-timing-chain-kit-9-0976sx/1460002
  'f7b257e1ddeb11c2abc2d22c',
  // autozone | https://www.autozone.com/p/duralast-platinum-battery-h6-agm/319460
  'a0017e2aa33ecfe75b3077a1',
  // autozone | https://www.autozone.com/p/mobil-1-gear-oil-104361/1437
  '68e760eb58541749e3f0d6c2',
  // autozone | https://www.autozone.com/p/mobil-1-motor-oil-120903/452341
  '1947b39d40391212a80967a2',
  // autozone | https://www.autozone.com/p/noco-battery-charger-genius1/606157
  '4f3ddf98f67f11fc7960b2f3',
  // autozone | https://www.autozone.com/p/optima-battery-dh5/1340240
  'ff5fcb19f52dcd6923e30b90',
  // autozone | https://www.autozone.com/p/pennzoil-motor-oil-550046126/426996
  'ede4865af8acf3fabe94b24e',
  // autozone | https://www.autozone.com/p/permatex-silicone-grease-20352/1459493
  'ea2c60ebc63af3bb5eef87b5',
  // battery mart | https://www.batterymart.com/p-battery-tender-jr-12v-0_75a-battery-charger.html
  '00c9fe02f4717f657f0d2650',
  // bks motors | https://www.bksmotors.com/4142132000.html
  'ac7e39eb829e8d8f1d344f39',
  // bks motors | https://www.bksmotors.com/843664.html
  '54a7f90f7c8a4061e98eef66',
  // bks motors | https://www.bksmotors.com/844409.html
  '4a84b96c0c7c840a4b4f6802',
  // cartoolshop | https://www.cartoolshop.com/products/timing-chain-kit-exhaust-intake-cvvt-gear-24321-2e000-for-kia-soul-hyundai-elantra-2-0l-1-8l-l4
  '97bcf0e41637ab1df5f2a1c3',
  // ebay | https://www.ebay.com/itm/111095838075?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&toolid=10049
  '1e00c2fd0b3d597a55e3f75d',
  // ebay | https://www.ebay.com/itm/117198415533?_skw=Walker+Products+235-1353+Engine+Crankshaft+Position+Sensor&hash=item1b4991e6ad%3Ag%3Ahg0AAeSwCQJqeLxj&mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=&toolid=10049
  '11368bc73a8960aa0e54244c',
  // ebay | https://www.ebay.com/itm/125825697081?_skw=Denso+221-3702+Radiator&hash=item1d4bcbc539%3Ag%3A0rkAAeSwjhBpolz9&mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=&toolid=10049
  '6d64efd9339a37a8aa3eda01',
  // ebay | https://www.ebay.com/itm/156883003708
  'f0907e8cccde5152df2c0186',
  // ebay | https://www.ebay.com/itm/277243903900?_skw=Walker+Products+235-1456+Engine+Crankshaft+Position+Sensor&hash=item408d063f9c%3Ag%3ANggAAeSwdy5oYvEC&mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=&toolid=10049
  '071a6d1697e817147b2d6437',
  // ebay | https://www.ebay.com/itm/335400623194?campid=5339164204
  '2b6cc92b1d4bcb6ec86a00e3',
  // ebay | https://www.ebay.com/itm/364192875830
  '7150be2c3c788d6f965ec995',
  // ebay | https://www.ebay.com/itm/389217855148?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&toolid=10049
  'c1f6380361ae9055b11f3ad7',
  // genracer | https://www.genracer.com/oem-hyundai-concentric-slave-cylinder-for-hyundai-genesis-coupe-2010-16/
  'f37f022c165eaeb848586acf',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-atf-jws-3309-t4~00232-19023.html
  '469aa7c858f1cee9a431fa21',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-bearing-kit~56359-l1aaa-fff.html
  '87e00d65ccf7cc9f94275c52',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-boot-kit-fr-axle-whe~49509-24a01.html
  'dfbe6968f2a53192cd2c3a38',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-bush-trail-arm~55160-1e000.html
  'a71735b1f910862ac9f57e3f',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-bush-trail-arm~55160-1r000.html
  '9bd962796f69669b02dfae46',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake-lh~58310-d3a00.html
  'c863c7d4e537c5a49285c320',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake-lh~58310-n9a10.html
  '48c30504414ead3ada22b73f',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake-rh~58311-d3a00.html
  '951c4d4d26c02df134cba2bd',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake-rh~58311-n9a10.html
  '7de514687e9ab970bf356bad',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake~58310-2ca31.html
  'a00dc9501cb9c563c0ae0c2c',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-caliper-kit-rr-brake~58311-2ca31.html
  'f5f7a3c5bc5d8f3c631f92e2',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-camera-assy-back-view~99240-k2000.html
  'db4e326e3b02179b20b8ab4e',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-camera-assy-back-view~99240-k2500.html
  'c58d6be299e31fc1e3bccfda',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-cap-assy-fuel-filler~31010-2c700.html
  'e778832e1ca7749ba834dfe7',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-cap-assy-fuel-filler~31010-3l600.html
  'b22112ff9bffb10f49a727d4',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-checker-assy-rr-door~79490-2v000.html
  '0aad2209551cae794dbcf04a',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-2s500.html
  'f79c8fa8b22472b0cc8b6a9f',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-2s602.html
  'dd0a8978b06610b4ed42710f',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-c2000.html
  '71f32a1eb9662cb6298934ec',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-c2100.html
  '237374b3519267c4fa541a12',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-c2500.html
  '7b1261803efe55181a69d46b',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-c2600.html
  'ce93c8877e26d981ece5d741',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-d3200.html
  '6922967aab38665ea62eb9a0',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-d3300.html
  'fb28e7d7c4e80a69f1791a42',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-d3750.html
  '02062fd7dde31ec2214b7984',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-d3950.html
  '79040f99a1060add6f78d8e8',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-d9001.html
  '74b8ae759ab39715f8d079f5',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-j9000.html
  'd09ff1e0aa14d00bba616399',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-j9200.html
  '9f603a30c2f3f27af3244cf9',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-compressor-assy~97701-j9500.html
  'e3fe903a23c4862d4d7bdbdc',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-coupling-assy-4wd~47800-24700.html
  '6b0a795974daf92aecdec154',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-coupling-assy-4wd~47800-3b510.html
  'af780a7c2888c1cc642e66d6',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-coupling-assy-4wd~47800-3b520.html
  'ef22669abefc49cff5b06272',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-cylinder-assy-clutch-release~41710-39100.html
  '3f38ae8ea3b81535a161b0da',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-cylinder-assy-clutch~41710-28000.html
  'ef0dedc787cdb08055112275',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-flexible-coupling~56315-2k000-fff.html
  'ba70de16f60da0bf893650cd',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-fuel-pump-sender-m~31110-2d501.html
  '1aaae92cb7c400f9c166ce79',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-gasket-surge-tank~29215-37100.html
  '3190aa746572d0a2ed1e92de',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-gasket-surge-tank~29215-3c100.html
  'c15b163cc15ec9e85664b7b4',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-gasket-surge-tank~29215-3c200.html
  '1d333723c9388ca2fbdb3a92',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-hose-assy-p-s-oil-pr~57510-3l100.html
  'a36591b27ee16cbc756525dd',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-hose-assy-p-s-oil-pr~57510-3l300.html
  '5419fcf8c1cb1ab4ba871c0d',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-joint-assy-strg~56400-2m000.html
  '256e8fb92b23a72a52881292',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-joint-assy-strg~56400-3n000.html
  '56a01659baeee58abfe71bc7',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-joint-assy-strg~56400-3n001.html
  'b8411b4d69e386a34049f24e',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-joint-assy-strg~56400-3n100.html
  'e3b3e110ad7f2bc0217fa757',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-link-assy-front-stabilizer-lh~54830-gi000.html
  '88ed756b57befa5e3b18e4d8',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-link-assy-front-stabilizer-rh~54831-gi000.html
  'b8647fc7d27b0be2ff086fcf',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-oil-control-valve-as~24355-23800.html
  'e1b3b0b15670a5cadc6c38d5',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-oil-control-valve-as~24355-2b700.html
  'df5ad36ccee5454b08031451',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-oil-flow-control-val~24355-2e100.html
  '57b7df6d31981e6452d5a2a4',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-oil-flow-control-val~24355-2g500.html
  '776706dfbcc9298c7f36885a',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-oil-flow-control-val~24375-2g500.html
  '0616b3a68959f92871da1e93',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-parking-brake-assy-e~59700-3m900.html
  '630f93c1ab3c079d4cda5f36',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-parking-brake-assy-electronic~59700-3n600.html
  '76d04478e5b682961c152027',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-pump-high-pressure~35320-2g740.html
  '48a9f2c94ce60874f709247a',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-regulator-assy-fr-dr-p-wdo-lh~82403-39000.html
  '18d3bdb033d2ef1c1bda6fc0',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-regulator-assy-fr-dr-p-wdo-rh~82404-39000.html
  '977950086cb9c52e2134f0fa',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-regulator-assy-rr-dr~83404-39000.html
  'cb46d1e915cf5693e8bde183',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-roller-tappet~35325-2g700.html
  '0265a7d2512140d9cf3c2318',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-seal-oil~47351-39010.html
  '94b83ebb365f33768b0b8c24',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-seal-oil~53050-3c000.html
  'db3dafa8eab07a941fd3e2e6',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-seal-oil~53050-3c021.html
  'f30e9f52800632da8dc2e48c',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-sensor-assy-input-sp~42620-39051.html
  '5daa85e3b9860f615f4bf725',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-sensor-assy-knock~39250-2e000.html
  'c2538f953fb9fbe3d65d4cbe',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-sensor-fuel-tank-pre~31435-1ea00.html
  '842b65fe13edc77b2d62e44b',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-service-kit-oil-filter-2~26320-3ckb0.html
  '8a08dc451b6a98bce628581a',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-service-kit-oil-filter~26350-2m000.html
  '1ecc1e93f0908ca93193266b',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-set-double-clutch~41200-2d220.html
  '894051bad72d3c2895f481fa',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-sp-cvt-1~00232-19081.html
  '8ca344872e2d2aa62f08adde',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-spacer-pinion-bearin~53045-3c000.html
  '3127f84d9fae019c15ba3ad3',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-starter-assy-kit~36100-3ca00.html
  'e67d36e20c05d5530c10ce80',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-starter-assy~36100-3c150.html
  '8a3d8313596e7961eea06656',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-starter-assy~36100-3c221.html
  'd28b8b5e2887ca5f4518a05d',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-switch-assy-stop-lamp-4p~93810-38110.html
  'c702b805f40b7f5c12add1c3',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-tensioner-assy-timing-chain~24410-3f401.html
  '8e8a9330a7ecac32b18a35c0',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-tensioner-assy-timing-chain~24410-3f411.html
  '68b952fe37595f7dfed0b0f0',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-tensioner-assy-vlv-t~24410-21010.html
  'c17124ac08c20a28eb2ab0bb',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-thermostat-assy~25500-23010.html
  '8ddbc3b1b3ae9fe0306dee08',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-thermostat-assy~25500-2gga0.html
  '3f98f713f1d4d696e49ae081',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-turbocharger~28231-2b700.html
  '4040727a7d9ca2bca54a962c',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-turbocharger~28231-2b740.html
  'ca69aafe894ffcd72819e5e4',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-valve-pcv~26740-21314.html
  '6a9125a6fd3aedd2d30f94e5',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-valve-purge-control~28910-22040.html
  'fad0b8e7407e0dd85a8e746d',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-valve-purge-control~28910-25100.html
  '45cd135988f5564781c5ea9a',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/genuine/hyundai-valve-purge-control~28910-3c200.html
  'ede4c96ca33bdbb2e2e4a430',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/oem-hyundai-entourage-crankshaft_position_sensor.html
  'dfc1f05e82f5e3cd82b4bc07',
  // hyundaipartsdeal | https://www.hyundaipartsdeal.com/oem-hyundai-pcv_valve.html
  '9371c9bf506a423c338ea0b6',
  // jegs | https://www.jegs.com/i/Melling/689/3-1045S/10002/-1
  'fbf477cbe621b45e7e40e386',
  // motrparts | https://www.motrparts.com/shop/valeo-hyundai-creta-clutch-set-843663/
  '7a24de9c71ac161b10b6ae3d',
  // newparts | https://newparts.com/product/monroe/171405
  '03f5b96f9ab72aad8f67dbab',
  // otoparcasan | https://otoparcasan.com/oto-yedek-parca/hyundai_i20_i20-gb-09-2014/triger-zincir-seti?o=o
  '9074e95997939f5d634b6088',
  // partsgeek | https://www.partsgeek.com/cfw8bjp-hyundai-tiburon-timing-belt-kit.html
  '5829aa59b37285a12bcbd95c',
  // partsgeek | https://www.partsgeek.com/dq241cj-hyundai-xg350-intake-manifold-gasket-set.html
  '523d6f5d4b2be649a24938fd',
  // partsgeek | https://www.partsgeek.com/grp7rg5-hyundai-elantra-timing-belt-kit.html
  'fad6b567afa756c6b161e092',
  // partsgeek | https://www.partsgeek.com/j2qpgxn-hyundai-tiburon-timing-belt-kit.html
  '0e0fc5443f27fcec0003d81b',
  // partsgeek | https://www.partsgeek.com/mjk37wz-hyundai-elantra-wheel-bearing.html
  '95c190d2cfc638347741ec5f',
  // partsgeek | https://www.partsgeek.com/np5gz2s-hyundai-xg350-timing-belt-kit.html
  '2aaf9d1764beba5dc80ebac5',
  // partsgeek | https://www.partsgeek.com/shmgq2h-hyundai-xg350-power-steering-pump.html
  'c138820bdb6115397a8e7227',
  // partsouq | https://partsouq.com/shop/product/976143X000-hyundai-kia-thermistor-assy-a-c-evap/14909777
  '5f4b5974474b87ccd8876f00',
  // shockwarehouse | https://www.shockwarehouse.com/products/kyb-sm5618-mount-components
  '1ef2bf30d723c073e40ce503',
  // sixity auto | https://www.sixityauto.com/gates-timing-belt-kit-w/-water-pump-for-2003-2008-hyundai-tiburon-2-7l-v6---engine-tckwp-oe-upgrade-2020031581.html
  '4fe04ae4e820adce0938de63',
  // suncore industries | https://www.suncoreindustries.com/product/23286/for-hyundai-equus-2009-2016-rear-pair-air-ride-suspension-spring-bags
  '5315438fb50ffbe7a0bc7d9d',
  // suspension.com | https://www.suspension.com/beck-arnley/monroe-171404
  'e22eac0242ab4ff77273dded',
  // tire rack | https://www.tirerack.com/tires/tires.jsp?partnum=44YR0EPRXL&tireMake=Michelin&tireModel=e.PRIMACY
  'f89fa299057ce0888872375e',
  // yoshiparts | https://yoshiparts.com/parts/hyundai-4262139052
  'e11ae61f676c6b1ef1f33783',
] as const;

export const retailerHostFingerprints = [
  // a-premium.com
  '2b22673ab54376412b813f20',
  // autodoc.co.uk
  '4cd20245762105f62f30d8d7',
  // autopartsprime.com
  'b6e04d2c3d46d1504d717b52',
  // autozone.com
  '12fa1f440ebfbfd1c0ab1b19',
  // batterymart.com
  '1edf6cfd91489b361250eb64',
  // bksmotors.com
  '3620002c78436edf9e17f5c5',
  // cartoolshop.com
  'a8833a5946653931b3a9af48',
  // genracer.com
  '3931a5dc56450183eeb68f18',
  // hyundaipartsdeal.com
  '59116f8f9064816c77a05a60',
  // jegs.com
  '67a987c8a9f95e49be29cfa2',
  // motoristas.com.br
  'f09285248a059e1d4d969b78',
  // motrparts.com
  '4c774024d06558a4bd197997',
  // newparts.com
  'ac2493a0ce372b5ddb7c0d50',
  // otoparcasan.com
  'cd9be09f95afce06e89ef1d5',
  // partsgeek.com
  'b6c9d443e05ef437cef78a38',
  // partsouq.com
  '683c1cbf6558a789c03708f9',
  // shockwarehouse.com
  '4df11fb7e470d011461ad5d2',
  // shop.advanceautoparts.com
  '3d7f5ea36b6847e33e997fca',
  // sixityauto.com
  'aa7a0d469cbff99842de4076',
  // suncoreindustries.com
  '1b8592eec41c8c3b8e88db52',
  // suspension.com
  '5eef982f34dff812d91f953a',
  // tirerack.com
  'bd55ec3718c71267850a50dd',
  // yoshiparts.com
  '4a4f3ac0c6f1b825cf462037',
] as const;
