// GENERATED by scripts/build-repair-first-verified-batch.mjs for Infiniti.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://parts.infinitiusa.com/parts/infiniti-engine-timing-chain-tensioner-130701mr0a
  'a5912f838f0c3a35bc6cb400',
  // https://parts.infinitiusa.com/parts/infiniti-sunroof-glass-912106sa2a
  '15ba4804d344bbc3c1d75e61',
  // https://stillen.com/products/2006-2010-infiniti-m35-more-dba-street-series-t2-standard-brake-rotor-front-dba2308
  '3cf8b92432ae3dbf71405208',
  // https://www.autopartsprime.com/infiniti/core-assy-front-heater/oe-271401ca0a
  'aa562a61d3fc82cfab3f1287',
  // https://www.autozone.com/p/cardone-reman-power-steering-pump-1h-72009/1191202
  '73e7aa6f0e3fbe9c6a7b3821',
  // https://www.autozone.com/p/duralast-platinum-battery-h6-agm/319460
  '28fcf208d9ec597fc0822166',
  // https://www.autozone.com/p/hitachi-automotive-engine-camshaft-position-sensor-cps0006/1112531
  'bb094912b243d5c4200bc770',
  // https://www.autozone.com/p/mobil-1-motor-oil-123843/785110
  '0218b331b3d51d05b01c0db9',
  // https://www.autozone.com/p/noco-battery-charger-genius2/606158
  '068850ef790695046c231920',
  // https://www.carcoverplanet.com/2006-infiniti-g35_polycarpet-dashboard-cover.html
  'cbad3fcbcd43753c833bfd31',
  // https://www.carcoverplanet.com/2007-infiniti-g35_polycarpet-dashboard-cover.html
  '3d2808ec2962a522251fba31',
  // https://www.carcoverplanet.com/2008-infiniti-g35-dashboard-covers.html
  'df60b7b1aafa6a972ceeaa64',
  // https://www.carcoverplanet.com/2008-infiniti-g37_polycarpet-dashboard-cover.html
  'bcafbbab01cfea4e693703e1',
  // https://www.carparts.com/details/Infiniti/M35/Beck_Arnley/Control_Arm/2006/BEC1027721.html?vehicle%5Bmake%5D=Infiniti&vehicle%5Bmodel%5D=M35&vehicle%5Byear%5D=2006
  '79ee8529307e7c104b985d9c',
  // https://www.finditparts.com/products/4660396/denso-221-3428
  'fff63018dcbfca905fe29902',
  // https://www.finditparts.com/products/5892658/denso-999-0601
  '28df02cafb719da5a4d6d699',
  // https://www.infinitipartsdeal.com/oem-2007-infiniti-g35-ignition_lock_cylinder.html
  '880628f36e5b028cebe8ca33',
  // https://www.infinitipartsdeal.com/oem-2011-infiniti-g37-engine_control_module.html
  '7e7981433516b7a761ea8aec',
  // https://www.infinitipartsdeal.com/oem-infiniti-fx50-brake_pad_set.html
  '4ade9237df5f6ec202e76d0c',
  // https://www.infinitipartsdeal.com/oem-infiniti-fx50-thermostat.html
  '8a6c23e2b9433e823c94f038',
  // https://www.infinitipartsdeal.com/oem-infiniti-g35-valve_stem_seal.html
  'bbd238213dc3c4d9edb6998b',
  // https://www.infinitipartsdeal.com/oem-infiniti-g37-spool_valve.html
  'b4ffc05f1cebfe04a6e2cd36',
  // https://www.infinitipartsdeal.com/oem-infiniti-m35-camshaft_position_sensor.html
  '4804307a3aff4b07673b1656',
  // https://www.infinitipartsdeal.com/oem-infiniti-m37-blower_motor_resistor.html
  '244e167365cfe49700be338e',
  // https://www.infinitipartsdeal.com/oem-infiniti-timing_chain_tensioner.html
  'acfb0920fa51404367c04b50',
  // https://www.infinitipartsdeal.com/parts/infiniti-absorber-kit~e6210-1la8a.html
  'e1b740478574816f66afae8f',
  // https://www.infinitipartsdeal.com/parts/infiniti-actr-asmy-mix-w~27732-1ma0a.html
  'f25a5f934feb053a0932553d',
  // https://www.infinitipartsdeal.com/parts/infiniti-actr-asmy-mix-w~27732-1ma1a.html
  '6975d0fb63b8f5174292ec46',
  // https://www.infinitipartsdeal.com/parts/infiniti-arm-compl-front~54500-1ca1a.html
  '5aea34117955b139e0e64494',
  // https://www.infinitipartsdeal.com/parts/infiniti-arm-compl-front~54501-1ca1a.html
  '5972b2a6c8212ce40032709b',
  // https://www.infinitipartsdeal.com/parts/infiniti-blower-asmy-fro~27220-1ma0a.html
  'c2bfe518ee4046231dec41fa',
  // https://www.infinitipartsdeal.com/parts/infiniti-camshaft-positi~23731-ey00b.html
  '36b3162d801fcc68fd632f9a',
  // https://www.infinitipartsdeal.com/parts/infiniti-camshaft-position-sensor~23731-4m50d.html
  '1992c698a70af157997cb451',
  // https://www.infinitipartsdeal.com/parts/infiniti-camshaft-position-sensor~23731-6j90d.html
  'a492b9ee5f47189bb02c25d2',
  // https://www.infinitipartsdeal.com/parts/infiniti-camshaft-position-sensor~23731-al61d.html
  '26ff829c69b360e133ecfda0',
  // https://www.infinitipartsdeal.com/parts/infiniti-cap-asmy-fill~17251-1nc0b.html
  '62d46c02d10d407e3255790a',
  // https://www.infinitipartsdeal.com/parts/infiniti-cap-assy-filler~17251-4ba0b.html
  'cb7ab8153e470e0e9e85b80e',
  // https://www.infinitipartsdeal.com/parts/infiniti-chain-camshaft~13028-6n200.html
  '32778ade308fbb7a3c989ea3',
  // https://www.infinitipartsdeal.com/parts/infiniti-chain-camshaft~13028-hg00f.html
  '26d0bb70735f1c52f71ee033',
  // https://www.infinitipartsdeal.com/parts/infiniti-chain-timing-ca~13028-jk20a.html
  '08eda7b39c1e79b0989c74e5',
  // https://www.infinitipartsdeal.com/parts/infiniti-compressor-asmy~53400-1la4c.html
  'f0f96721cd8f357d49c52653',
  // https://www.infinitipartsdeal.com/parts/infiniti-crankshaft-posi~23731-ja10c.html
  'aae76f3ea1e2d413a6758feb',
  // https://www.infinitipartsdeal.com/parts/infiniti-crankshaft-posi~23731-ja11b.html
  '9f90b6817c22e54d92e7ba2d',
  // https://www.infinitipartsdeal.com/parts/infiniti-fan-motor~21486-1bh0a.html
  'a39e2127fe187aa382ab4fa4',
  // https://www.infinitipartsdeal.com/parts/infiniti-filter-assy-oil-govenor~31726-28x0a.html
  '81cb71a14429af6cc0ccd0a8',
  // https://www.infinitipartsdeal.com/parts/infiniti-gear-asmy-pow~49200-1mt2b.html
  '148b71af736f32541c205308',
  // https://www.infinitipartsdeal.com/parts/infiniti-glass-assy-sunroof-rear~91604-6sa2a.html
  '68d66a11ebed79bc13a10363',
  // https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-sla~13091-ar000.html
  '7b459fcf6d040d7c3d7d211d',
  // https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-slack-side~13091-1ca2b.html
  '146776916db6daaeae638919',
  // https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-slack-side~13091-1la3a.html
  '9c3bdaf688bed77f9cfce7bc',
  // https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-slack-side~13091-hg00b.html
  'bde9c8124da6e61b89d89add',
  // https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-tension-side~13085-1ca2b.html
  '217398bb760e559a88ee5cbc',
  // https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-tension-side~13085-1la3a.html
  '6738e920e7212a44a5b70743',
  // https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-tension-side~13085-hg00b.html
  '66271178027eeb669045fbe1',
  // https://www.infinitipartsdeal.com/parts/infiniti-hose-drain~91389-1ca1a.html
  '9cd1e8c4c16736047becb375',
  // https://www.infinitipartsdeal.com/parts/infiniti-hose-drain~91389-1ca1b.html
  '06195bbc709093698b7cff1f',
  // https://www.infinitipartsdeal.com/parts/infiniti-hose-drain~91389-1ca2a.html
  'db39d30ec8702e0710904b5a',
  // https://www.infinitipartsdeal.com/parts/infiniti-hose-drain~91390-5ub1a.html
  'a5a2125d8a5a6478e56b8ce0',
  // https://www.infinitipartsdeal.com/parts/infiniti-hose-tube-asm~49720-1mc1a.html
  'c7ad55388106a2bf8d9bd83f',
  // https://www.infinitipartsdeal.com/parts/infiniti-hose-tube-asm~49720-1mc2a.html
  '2167524a0fe687c9a58cea86',
  // https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54500-1ba8a.html
  'e654f14c96805375851da1d4',
  // https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54500-1ma0b.html
  '35e90eaf4e4c0c485e9ef110',
  // https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54500-1md1a.html
  '716c22d6b34fae152ae746d8',
  // https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54500-ej72a.html
  '1ebfd841a65113784954404e',
  // https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54500-jl03b.html
  '68699ed8006389a4d9e9d1e8',
  // https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54501-1ba8a.html
  '8d940226afddf21d9bd0557e',
  // https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54501-1ma0b.html
  'f2e02626a9c893b87e4617d8',
  // https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54501-1md1a.html
  '373432d5380c8bf7c785c500',
  // https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54501-ej72a.html
  '419c4b4109666ba716844822',
  // https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54501-jl03b.html
  'fb5f0bc62e0c89096a9756f9',
  // https://www.infinitipartsdeal.com/parts/infiniti-lock-set-steeri~48700-1nc0a.html
  '235d1d9484b66f93c51b6668',
  // https://www.infinitipartsdeal.com/parts/infiniti-lock-set-steeri~d8700-jk000.html
  '6412d9ba8ed203deb47126c6',
  // https://www.infinitipartsdeal.com/parts/infiniti-module-asmy-vel~23751-jk00b.html
  '82ea54047bcd1eda763cfe3b',
  // https://www.infinitipartsdeal.com/parts/infiniti-motor-fan-asm~21481-1bh0b.html
  '0359a7f800452f47a4b5f2d2',
  // https://www.infinitipartsdeal.com/parts/infiniti-motor-fan-assy-w-shroud~21481-5na0a.html
  '84e4b306bcf32b7efb9f63e6',
  // https://www.infinitipartsdeal.com/parts/infiniti-motor-fan-assy-w-shroud~21481-5na1a.html
  'ef27056ec0277e039dfab195',
  // https://www.infinitipartsdeal.com/parts/infiniti-ns-3-cvt-fluid-1-qt-x-12~999mp-cv0ns3.html
  '1392725a6371e87869127e96',
  // https://www.infinitipartsdeal.com/parts/infiniti-oil_strainer-3172828x0a.html
  '2e55319d97226b6a5912f7a1',
  // https://www.infinitipartsdeal.com/parts/infiniti-oil-filter~15208-65f1e.html
  '310bc406d9c18d2b6e89ed41',
  // https://www.infinitipartsdeal.com/parts/infiniti-packing-rear-co~26553-4an0a.html
  '730bffdf57b8c38016b7e581',
  // https://www.infinitipartsdeal.com/parts/infiniti-pad-kit-disc-br~d1060-jl00k.html
  '1c28f89403abfd3ee2efa686',
  // https://www.infinitipartsdeal.com/parts/infiniti-pad-kit-disc-brake~d1060-ca093.html
  '8d450cf6113cbb5f8addb4f3',
  // https://www.infinitipartsdeal.com/parts/infiniti-pad-kit-disc~41060-eg090.html
  '2e605fb998130f54e13a5f12',
  // https://www.infinitipartsdeal.com/parts/infiniti-plug~74816-ju40b.html
  'f12297cb4f61dde53baf1090',
  // https://www.infinitipartsdeal.com/parts/infiniti-power-steering~999mp-ag000p.html
  '33c9698f4282ae74f14d2616',
  // https://www.infinitipartsdeal.com/parts/infiniti-pulley-assy-idler~11925-5ca0c.html
  'c93a4d068ac26524950abdc6',
  // https://www.infinitipartsdeal.com/parts/infiniti-pump-assy-water~b1010-jk20a.html
  'dfca6cdb9e79d7641b4d0b45',
  // https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~80720-cl70b.html
  'ad3ef21f4da6023461cfa0f1',
  // https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~80721-am811.html
  'd287dd6e97e7cc5d9dc3a017',
  // https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~80721-cl70b.html
  '1277a04ea27b09b21a97d85f',
  // https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~82720-jk000.html
  'f141174be0d46d4adfa3581b',
  // https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~82721-cm30a.html
  '126305c6301cf90825ad9834',
  // https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~82721-jk000.html
  '27736a824d977582ebe1df59',
  // https://www.infinitipartsdeal.com/parts/infiniti-rod-assy-connecting-stabilizer~54618-jk05b.html
  '4383989f94e0616b63188a6f',
  // https://www.infinitipartsdeal.com/parts/infiniti-rod-assy-connecting-stabilizer~54618-jk54a.html
  '490f8207c43338c6a97df137',
  // https://www.infinitipartsdeal.com/parts/infiniti-rod-assy-connecting-stabilizer~54668-jk05b.html
  '44a0b0dcd2f3e5c3fea27ad5',
  // https://www.infinitipartsdeal.com/parts/infiniti-rod-assy-connecting-stabilizer~54668-jk54a.html
  '8977ee1f8ee9ed30d3673f3a',
  // https://www.infinitipartsdeal.com/parts/infiniti-rod-compl-radiu~55110-eg000.html
  'ce9cd43a99cd6b0219692ea2',
  // https://www.infinitipartsdeal.com/parts/infiniti-rotor-disc-brak~40206-cg010.html
  'f2561b6ffd5c39e47a1f2543',
  // https://www.infinitipartsdeal.com/parts/infiniti-rotor-disc-brak~40206-cl70a.html
  '5527244a3c3fb3cb02541bfa',
  // https://www.infinitipartsdeal.com/parts/infiniti-rotor-disc-brak~40206-eg000.html
  '0e99318ea092b813b1d67ae6',
  // https://www.infinitipartsdeal.com/parts/infiniti-rotor-disc-brak~40206-jl00a.html
  'd892521baa15f174c0e1345e',
  // https://www.infinitipartsdeal.com/parts/infiniti-rotor-disc-brak~40206-za500.html
  '635e8fd1d2c47acf8436d470',
  // https://www.infinitipartsdeal.com/parts/infiniti-seal-oil-transf~33142-01j10.html
  '9852161a4623e1fa0a65641d',
  // https://www.infinitipartsdeal.com/parts/infiniti-seal-oil-transf~33216-cg01a.html
  'f0f174b4d83330a36e63920c',
  // https://www.infinitipartsdeal.com/parts/infiniti-sender-unit-fue~25060-1cb0c.html
  'aab24706b2f6ebe0a1a41122',
  // https://www.infinitipartsdeal.com/parts/infiniti-sender-unit-fue~25060-1cb1c.html
  '3579d08fde164155d5b39f43',
  // https://www.infinitipartsdeal.com/parts/infiniti-sender-unit-fue~25060-cg00e.html
  '9325c565475868d634e31d68',
  // https://www.infinitipartsdeal.com/parts/infiniti-sensor-asmy-hei~53820-1la2a.html
  'd8482647a510f1577838e476',
  // https://www.infinitipartsdeal.com/parts/infiniti-sensor-unit-tir~40700-1la0e.html
  'ad3aec101767f06c47f5f044',
  // https://www.infinitipartsdeal.com/parts/infiniti-separaor-assy-breather~11830-hg00c.html
  '85eed38acd3e41524ed2a47d',
  // https://www.infinitipartsdeal.com/parts/infiniti-tensioner-asmy~13070-ar000.html
  '5cdb1f869e9c8c3232704afa',
  // https://www.infinitipartsdeal.com/parts/infiniti-tensioner-assy-belt~13070-1la2b.html
  '45daa347bc2efade2d06b599',
  // https://www.infinitipartsdeal.com/parts/infiniti-tensioner-assy-chain~13070-1ca2c.html
  'c63522064a6e762db7d32e08',
  // https://www.infinitipartsdeal.com/parts/infiniti-tensioner-assy-chain~13070-hg00f.html
  '742672ebfbd178a2e9defa33',
  // https://www.infinitipartsdeal.com/parts/infiniti-timing-chain-camchaft~13028-1ca6a.html
  '562183f3698f636fb8e4fe42',
  // https://www.infinitipartsdeal.com/parts/infiniti-timing-chain-camchaft~13028-1la6a.html
  '2f75ec375254f28df024934f',
  // https://www.infinitipartsdeal.com/parts/infiniti-valve-asmy-co~14930-ja10d.html
  '670fd00ac363025d42414e48',
  // https://www.infinitipartsdeal.com/parts/infiniti-valve-assy-control~14935-jf02c.html
  '58816aa037796d3a3ac1b894',
  // https://www.infinitipartsdeal.com/parts/infiniti-weatherstrip-tr~84830-1ma0b.html
  'a21b65063ee0f59bef781961',
  // https://www.moog-suspension-parts.com/moog-k750273
  'bc80962993bbf52b09bc443a',
  // https://www.nisformance.com/OEM-VQ35DE-Timing-Kit-p/nis-detk.htm
  'ad448b16e0f69ef6a24222ce',
  // https://www.nissanpartsdeal.com/parts/nissan-mobil-super-synthetic-0w-20-qt~999pk-0w20msn.html
  'ff75b007c75cec490971bd35',
  // https://www.partsgeek.com/2v8qkmx-infiniti-fx50-stabilizer-bar-link.html
  '66dbc56ba2a78b6d137ecbe2',
  // https://www.partsgeek.com/7k5sj99-infiniti-fx50-radiator.html
  'c0b3dd1967c4807de9fdadb2',
  // https://www.partsgeek.com/8xf6myp-infiniti-m35-radiator.html
  'f3b32ffab85aaaaba8c54d38',
  // https://www.partsgeek.com/kpvx3k4-infiniti-fx45-radiator.html
  '996faaa1b0bad11ce5b85698',
  // https://www.partsgeek.com/kybrcx5-infiniti-m35-control-arm-and-ball-joint-assembly.html
  'cfc8d8a62ce1d9be01e05ecc',
  // https://www.partsgeek.com/yj15gx4-infiniti-g35-window-regulator.html
  '934b979ff7b1707632fcd401',
  // https://www.sixityauto.com/4-pc-denso-tpms-tire-pressure-sensors-for-infiniti-m56-2011-2013-monitoring-system-2056053890.html
  'bbded5e9bd076f7ece89f9b4',
  // https://www.suspension.com/beckarnley-102-6142
  '417331725feb652ec45aa240',
  // https://www.suspension.com/beckarnley-102-6143
  '38d7ef890b7a04beb97e97ba',
  // https://www.suspension.com/moog-rk622084
  'b113b20e2a64dc3f03b23969',
  // https://www.suspension.com/moog-rk622085
  'b9c7fdcf58a663db6bbf8a66',
  // https://www.suspension.com/moog-rk622196
  '0e981ac3a96442e775cbdbcd',
  // https://www.suspension.com/spc/moog-rk622198
  '15e0bff5819c8578e62d63ef',
  // https://www.walmart.com/ip/108587771
  'e7345f01892364d59f9b0a95',
  // https://www.walmart.com/ip/17128876
  'cb78266a63e15c6a88ec1a2d',
  // https://www.z1motorsports.com/cam-crank-sensor/infiniti/oem-09-10-infiniti-m35-camshaft-position-sensor-vq35hr-p-41605.html
  'd584aa99f77c2a8cbd09dcb0',
  // https://www.z1motorsports.com/cam-crank-sensor/infiniti/oem-infiniti-m35-m37q70-crankshaft-position-sensor-p-41608.html
  'f1ce8c31bfba34061bf25c44',
  // https://www.z1motorsports.com/camshaft-and-valve-mechanism/assembled-by-z1-motorsports/oem-11-19-infiniti-m56-q70-timing-kit-56l-p-45060.html
  'c8732fa9dc260371470f4b25',
  // https://www.z1motorsports.com/camshaft-and-valve-mechanism/nissan/oem-vq37vhr-timing-kit-p-12470.html
  'd66e9295466877a3e4405c0d',
  // https://www.z1motorsports.com/cylinder-head-and-valve-cover/assembled-by-z1-motorsports/oem-370z-g37-q50-q60-vq37vhr-valve-cover-and-gasket-kit-p-25174.html
  'bcf70c49a3897d955d501dae',
  // https://www.z1motorsports.com/cylinder-head-and-valve-cover/nissan/oem-370z-g37-q50-q60-valve-cover-gasket-vq37vhr-p-8879.html
  '7181e67a8f21db79ec6d6000',
  // https://www.z1motorsports.com/engine-gasket-kit/nissan/nissan-oem-fluid-gasket-rtv-p-7247.html
  'daf7f9d055477fefc18a8531',
  // https://www.z1motorsports.com/engine-maintenance/assembled-by-z1-motorsports/oem-infiniti-q50-q60-30t-oil-change-kit-p-36652.html
  '9243753baf19bf1ce20345c7',
  // https://www.z1motorsports.com/fan-ac-and-power-steering-belt/infiniti/oem-vr30ddtt-belt-tensioner-assembly-p-10185.html
  '03fee0c9a33ac6876e7e0c99',
  // https://www.z1motorsports.com/front-timing-cover/nissan/vq35hr-vq37vhr-timing-cover-ring-and-seal-kit-p-9484.html
  '053ff779feb3b0315bb60987',
  // https://www.z1motorsports.com/front-timing-cover/z1-motorsports/370z-g37-vq37vhr-rear-timing-cover-oil-gallery-gasket-kit-p-17916.html
  '458829cafc7aca1836029aa9',
  // https://www.z1motorsports.com/fuel-pump-and-control-unit/infiniti/oem-05-10-infiniti-m35m45-fuel-level-sending-unit-p-41172.html
  'c97d3b1c4dac36a690b2f979',
  // https://www.z1motorsports.com/piston-crankshaft-and-flywheel/assembled-by-z1-motorsports/q60-q50-vr30-anti-jump-belt-upgrade-kit-p-41625.html
  '4709ba36e4a6fd6638127b45',
  // https://www.z1motorsports.com/piston-crankshaft-and-flywheel/nissan/oem-2007-infiniti-g35-coupe-piston-ring-set-p-72788.html
  'ec0797be9eac3656f338d13d',
  // https://www.z1motorsports.com/transmission/z1-motorsports/z1-370z-g37-v2-csc-elimination-kit-p-54892.html
  '391eae0c168d338c1126e44d',
  // https://www.z1motorsports.com/turbo-charger/assembled-by-z1-motorsports/oem-infiniti-q50-q60-vr30-turbo-service-gasket-kit-p-39362.html
  'fc0cd0b902ecf4fa986ce177',
  // https://www.z1motorsports.com/turbo-charger/infiniti/oem-q50-q60-vr30-30t-stock-turbo-300hp-p-9961.html
  '32c331aa848f98882faf6d1c',
  // https://www.z1motorsports.com/turbo-charger/infiniti/oem-q50-q60-vr30-30t-stock-turbo-400hp-p-9962.html
  'd6d73f17fd1235980021f3d9',
  // https://www.z1offroad.com/auto-transmission/nissan/oem-nissan-matic-transmission-transfer-case-fluid-p-77811.html
  '3dca6308f20fc69173fbf48e',
  // https://zspeed.com/products/zspeed-billet-v4-cmak
  'c8d96f6051e69db8162c6d21',
] as const;

export const vendorUrlFingerprints = [
  // autopartsprime | https://www.autopartsprime.com/infiniti/core-assy-front-heater/oe-271401ca0a
  '31b55b07c8371be58bbf280b',
  // autozone | https://www.autozone.com/p/cardone-reman-power-steering-pump-1h-72009/1191202
  '98a7d3531c9ca7dddc124a0c',
  // autozone | https://www.autozone.com/p/duralast-platinum-battery-h6-agm/319460
  'a0017e2aa33ecfe75b3077a1',
  // autozone | https://www.autozone.com/p/hitachi-automotive-engine-camshaft-position-sensor-cps0006/1112531
  '454fedff66b76cdd723934d5',
  // autozone | https://www.autozone.com/p/mobil-1-motor-oil-123843/785110
  '03c2eff7055bfd44246aff32',
  // autozone | https://www.autozone.com/p/noco-battery-charger-genius2/606158
  '40846f155405c1e558d2b83e',
  // carcoverplanet | https://www.carcoverplanet.com/2006-infiniti-g35_polycarpet-dashboard-cover.html
  '36fe6f08128c99fd1401f6ce',
  // carcoverplanet | https://www.carcoverplanet.com/2007-infiniti-g35_polycarpet-dashboard-cover.html
  '482289fb017af02a4b10e253',
  // carcoverplanet | https://www.carcoverplanet.com/2008-infiniti-g35-dashboard-covers.html
  'db90043e7c14ad61d3fbcccb',
  // carcoverplanet | https://www.carcoverplanet.com/2008-infiniti-g37_polycarpet-dashboard-cover.html
  '3e7d65ddac0a66372477a72d',
  // carparts.com | https://www.carparts.com/details/Infiniti/M35/Beck_Arnley/Control_Arm/2006/BEC1027721.html?vehicle%5Bmake%5D=Infiniti&vehicle%5Bmodel%5D=M35&vehicle%5Byear%5D=2006
  '066119184cf6b3ce5a8161ee',
  // ebay | https://www.ebay.com/itm/198333300684?_skw=Walker+Products+235-1386+Engine+Crankshaft+Position+Sensor&mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=&toolid=10049
  '8bae6cd6e7f1812840c647f2',
  // ebay | https://www.ebay.com/itm/236347499775?_skw=Denso+221-9285+Radiator&mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=&toolid=10049
  'f66d5a938978f2f117c8af62',
  // ebay | https://www.ebay.com/itm/286737392841?_skw=Walker+Products+235-1150+Engine+Camshaft+Position+Sensor&hash=item42c2e164c9%3Ag%3Apn0AAeSwb5xoiSkj&mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=&toolid=10049
  '8e486365e4da32196ea5e281',
  // ebay | https://www.ebay.com/itm/317884556502?_skw=Denso+221-3422+Radiator&hash=item4a036564d6%3Ag%3ALHQAAeSwvdxqV1D2&mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=&toolid=10049
  '0e64747e6da1a09a80337b65',
  // finditparts | https://www.finditparts.com/products/4660396/denso-221-3428
  '41adbee228efa4a102af2f78',
  // finditparts | https://www.finditparts.com/products/5892658/denso-999-0601
  '51cd0a6d898401520db8ba51',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/oem-2007-infiniti-g35-ignition_lock_cylinder.html
  '8147a9ceb6272669f4d5fc09',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/oem-2011-infiniti-g37-engine_control_module.html
  'fa8fb5f655a77640cf86ed86',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/oem-infiniti-fx50-brake_pad_set.html
  'c30c3e5968f805002355c1ae',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/oem-infiniti-fx50-thermostat.html
  '64f3fcfe1ef11b7ab1ae8ee4',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/oem-infiniti-g35-valve_stem_seal.html
  'a898f147ea91f3cdad0376ae',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/oem-infiniti-g37-spool_valve.html
  '1208b4707e48ab2ca5bd2d50',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/oem-infiniti-m35-camshaft_position_sensor.html
  'ecf655c5d7fb885f827dadb6',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/oem-infiniti-m37-blower_motor_resistor.html
  '9a9fdf062be9583a31b129d2',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/oem-infiniti-timing_chain_tensioner.html
  'f2c201717666e4b1f35a8bb5',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-absorber-kit~e6210-1la8a.html
  '76ec7c8e7cdfdc260f48b5a7',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-actr-asmy-mix-w~27732-1ma0a.html
  '66092cc60f9d77a99b4b23ab',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-actr-asmy-mix-w~27732-1ma1a.html
  'ee46cb712f3c3fe29379a1a1',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-arm-compl-front~54500-1ca1a.html
  '32ff945bce94a8d2292e0ccc',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-arm-compl-front~54501-1ca1a.html
  'dd2af4276a25b033b7108257',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-blower-asmy-fro~27220-1ma0a.html
  '422531401fb03c7cde30cbbf',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-camshaft-positi~23731-ey00b.html
  '3e9374eabe392a1b3c690e6d',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-camshaft-position-sensor~23731-4m50d.html
  '78c0e8d831170f832449f036',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-camshaft-position-sensor~23731-6j90d.html
  '75eeb18720c7d9b671a1a441',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-camshaft-position-sensor~23731-al61d.html
  '4d37a43d39a89c43bc8d4b70',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-cap-asmy-fill~17251-1nc0b.html
  '91d28f976b34976f4aed3e10',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-cap-assy-filler~17251-4ba0b.html
  'f95b51a1b17723d212bbc28e',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-chain-camshaft~13028-6n200.html
  '5206cd30c1b8d355158e7a36',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-chain-camshaft~13028-hg00f.html
  '467187a7ca47b43e88c1673f',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-chain-timing-ca~13028-jk20a.html
  '4566d4010f2fd350548db36b',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-compressor-asmy~53400-1la4c.html
  '085473b81b9df606eeef42a7',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-crankshaft-posi~23731-ja10c.html
  '19c261dcc84e34cd10a60ec9',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-crankshaft-posi~23731-ja11b.html
  '10d0ea8b74b99e0d859044ea',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-fan-motor~21486-1bh0a.html
  '25aeba3bf243946354857306',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-filter-assy-oil-govenor~31726-28x0a.html
  'e28ccc8890f5d2a513e5ad6a',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-gear-asmy-pow~49200-1mt2b.html
  '6fdf64e0fcd2fc689c8665bc',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-glass-assy-sunroof-rear~91604-6sa2a.html
  '998c83b9d285ee5398b0f70f',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-sla~13091-ar000.html
  '870d5746a7bc30c2a3dfcdb0',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-slack-side~13091-1ca2b.html
  'cac4efbc4094013b4b5a49c7',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-slack-side~13091-1la3a.html
  '44cb1a6af993d59e878a8023',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-slack-side~13091-hg00b.html
  'f769c58c395d1894e57cc2f3',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-tension-side~13085-1ca2b.html
  'd8bd2bab9f1ee62146fa38d7',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-tension-side~13085-1la3a.html
  'df96a13c2c3c02d17199015a',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-guide-chain-tension-side~13085-hg00b.html
  '86241630cd4ee961c14748ce',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-hose-drain~91389-1ca1a.html
  '942d9605dc90c51a289ef4c7',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-hose-drain~91389-1ca1b.html
  '95ea9485700d838b76e4b5bb',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-hose-drain~91389-1ca2a.html
  'c9df2be3de5682057f9c95ad',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-hose-drain~91390-5ub1a.html
  'f10f5cdaad6bc699c500deb7',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-hose-tube-asm~49720-1mc1a.html
  '4ffc83f0047a6fb3cc0897ca',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-hose-tube-asm~49720-1mc2a.html
  '70ddbefa9e6beb1914a23cb0',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54500-1ba8a.html
  'a26ce13302102c91c13702e8',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54500-1ma0b.html
  '14e2b453891e51e42c3ecc47',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54500-1md1a.html
  'a87b15c0724a5b1741443470',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54500-ej72a.html
  '29b3e2251b72f98ced88591d',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54500-jl03b.html
  '6fa742540f348131cb63fd34',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54501-1ba8a.html
  'fe3f2bb10a4bb6d301c5de6b',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54501-1ma0b.html
  '0d9f9b3d7f8967359dfa8344',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54501-1md1a.html
  'e2703253bd6e241c2472b587',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54501-ej72a.html
  'b5b1d87b56f4385302780c81',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-link-compl-tran~54501-jl03b.html
  '6b7c822af1d792c523289c87',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-lock-set-steeri~48700-1nc0a.html
  '0e2b16a1c742925208a995d8',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-lock-set-steeri~d8700-jk000.html
  '234a45b15fd6d83015a7c41f',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-module-asmy-vel~23751-jk00b.html
  '08e6a1727698333bdb889b98',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-motor-fan-asm~21481-1bh0b.html
  'ed58818ea7402c166c755b17',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-motor-fan-assy-w-shroud~21481-5na0a.html
  'a30cdb942c492259997740a0',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-motor-fan-assy-w-shroud~21481-5na1a.html
  'f6a2bcb0aabec90e7e881425',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-ns-3-cvt-fluid-1-qt-x-12~999mp-cv0ns3.html
  '103c62a82025bd0270099f3b',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-oil_strainer-3172828x0a.html
  '37f5db7eea44489c920e2bca',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-oil-filter~15208-65f1e.html
  '9dd90aaccb14608ddf3608e3',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-packing-rear-co~26553-4an0a.html
  'cec7f66ee9821e5c1a9487cb',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-pad-kit-disc-br~d1060-jl00k.html
  'd7022b65bcb069b48c8fc858',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-pad-kit-disc-brake~d1060-ca093.html
  'f4c62b193ffc092c1ff4370c',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-pad-kit-disc~41060-eg090.html
  '898e9db43d5ff90ea91d8eb8',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-plug~74816-ju40b.html
  'e64c5625f2f547584162d649',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-power-steering~999mp-ag000p.html
  'cd67da3cb4da6d47f4159659',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-pulley-assy-idler~11925-5ca0c.html
  '621646174ba94793bc7e40ab',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-pump-assy-water~b1010-jk20a.html
  '4d19df947d221f6041c34a77',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~80720-cl70b.html
  'abe8295574e26d4634aeb1b0',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~80721-am811.html
  'bf4be60ed469743280a337e9',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~80721-cl70b.html
  'b979c4a11cc55bf27ebf24c1',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~82720-jk000.html
  '0ecbe6debbdb146f187bec00',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~82721-cm30a.html
  '27dffea7e3f4969b8642fb2a',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-regulator-asmy~82721-jk000.html
  'b1126192ac9277cd2fe6cdc3',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-rod-assy-connecting-stabilizer~54618-jk05b.html
  '8f278ee9eb8112108452aa7f',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-rod-assy-connecting-stabilizer~54618-jk54a.html
  'e53a6dcfb0c0b544363785af',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-rod-assy-connecting-stabilizer~54668-jk05b.html
  'b3d68f525ed30159bdc395da',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-rod-assy-connecting-stabilizer~54668-jk54a.html
  '111002c03ca8be23662b6f36',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-rod-compl-radiu~55110-eg000.html
  '56bf7925decd59c6ac6a620f',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-rotor-disc-brak~40206-cg010.html
  'ec622f591126821e6c225b7c',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-rotor-disc-brak~40206-cl70a.html
  '200603984d79be1e6c7f8a12',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-rotor-disc-brak~40206-eg000.html
  'b3b3c8bbd4c13a6d01fad4fa',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-rotor-disc-brak~40206-jl00a.html
  'de2e3e409a281388a0a8e67a',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-rotor-disc-brak~40206-za500.html
  '76b49ca11aa264470d19710f',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-seal-oil-transf~33142-01j10.html
  'b64809084a3bc043ac05c085',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-seal-oil-transf~33216-cg01a.html
  'ac9e8355b92eff0188b3cd85',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-sender-unit-fue~25060-1cb0c.html
  '7709bd983783f407f6f85f36',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-sender-unit-fue~25060-1cb1c.html
  'a35ca5fb3202909c9c38f324',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-sender-unit-fue~25060-cg00e.html
  '943073e4bee801f48e776e90',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-sensor-asmy-hei~53820-1la2a.html
  '6e51f3465261fe96695b80ff',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-sensor-unit-tir~40700-1la0e.html
  'c45dc9da17b6e41099e2e273',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-separaor-assy-breather~11830-hg00c.html
  '0d7bb661fbe35a5a6653930d',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-tensioner-asmy~13070-ar000.html
  'e3c2f739876e9d9d0b5ac88e',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-tensioner-assy-belt~13070-1la2b.html
  '7f460a83073399eec75b0599',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-tensioner-assy-chain~13070-1ca2c.html
  'bed26b15ded164e5c6949333',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-tensioner-assy-chain~13070-hg00f.html
  '7d6c5f0ab7e0dd2eaa7460a2',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-timing-chain-camchaft~13028-1ca6a.html
  'a562f9eabdc5e9f556054b69',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-timing-chain-camchaft~13028-1la6a.html
  '498fbef66511efc01c9b28f0',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-valve-asmy-co~14930-ja10d.html
  '8bb69e0bc36efeeeaac4268c',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-valve-assy-control~14935-jf02c.html
  '3c4964ce7f061fabd29f1e01',
  // infinitipartsdeal | https://www.infinitipartsdeal.com/parts/infiniti-weatherstrip-tr~84830-1ma0b.html
  '44e67881d10aa971ace88c7c',
  // nisformance | https://www.nisformance.com/OEM-VQ35DE-Timing-Kit-p/nis-detk.htm
  '85ee4018aa6c26f9b471e28f',
  // nissanpartsdeal | https://www.nissanpartsdeal.com/parts/nissan-mobil-super-synthetic-0w-20-qt~999pk-0w20msn.html
  '133e1aed69e8eb4b69b6403d',
  // official infiniti parts store | https://parts.infinitiusa.com/parts/infiniti-engine-timing-chain-tensioner-130701mr0a
  '3a5852e47d542fdd0973ee3d',
  // official infiniti parts store | https://parts.infinitiusa.com/parts/infiniti-sunroof-glass-912106sa2a
  'ed11cbb2df7fcfcb6504528f',
  // partsgeek | https://www.partsgeek.com/2v8qkmx-infiniti-fx50-stabilizer-bar-link.html
  'c4e78c28dda0fd9113c09d34',
  // partsgeek | https://www.partsgeek.com/7k5sj99-infiniti-fx50-radiator.html
  '92014bdd799910762dce2d7d',
  // partsgeek | https://www.partsgeek.com/8xf6myp-infiniti-m35-radiator.html
  'e8b570675f8829a3e7167e72',
  // partsgeek | https://www.partsgeek.com/kpvx3k4-infiniti-fx45-radiator.html
  '0778048e0a7832b3983c9569',
  // partsgeek | https://www.partsgeek.com/kybrcx5-infiniti-m35-control-arm-and-ball-joint-assembly.html
  '66a3c525d68b08b0d6f3da32',
  // partsgeek | https://www.partsgeek.com/yj15gx4-infiniti-g35-window-regulator.html
  '066263bb75f44b5b6644851a',
  // sixity auto | https://www.sixityauto.com/4-pc-denso-tpms-tire-pressure-sensors-for-infiniti-m56-2011-2013-monitoring-system-2056053890.html
  '02fd2dfbbcfebdca4723f690',
  // stillen | https://stillen.com/products/2006-2010-infiniti-m35-more-dba-street-series-t2-standard-brake-rotor-front-dba2308
  'a046fbeb26f6e7d875d438b7',
  // suspension.com | https://www.moog-suspension-parts.com/moog-k750273
  'acffe80815114ab2d2357738',
  // suspension.com | https://www.suspension.com/beckarnley-102-6142
  'd8bd55c8492e1e7f70413132',
  // suspension.com | https://www.suspension.com/beckarnley-102-6143
  'be57983ff7a6567ebb29eab3',
  // suspension.com | https://www.suspension.com/moog-rk622084
  'cb551cf581c29e6429fd6be6',
  // suspension.com | https://www.suspension.com/moog-rk622085
  'f0bfcc57803217082485f413',
  // suspension.com | https://www.suspension.com/moog-rk622196
  'c0ba225cf804fb9d90c2f694',
  // suspension.com | https://www.suspension.com/spc/moog-rk622198
  '21766d0846f48d347af021dc',
  // walmart | https://www.walmart.com/ip/108587771
  '6cba2dc641745924b229c79e',
  // walmart | https://www.walmart.com/ip/17128876
  'd33e35373bd5335c75b4de91',
  // z1 motorsports | https://www.z1motorsports.com/cam-crank-sensor/infiniti/oem-09-10-infiniti-m35-camshaft-position-sensor-vq35hr-p-41605.html
  '5efb34548e3f0024ae86a56d',
  // z1 motorsports | https://www.z1motorsports.com/cam-crank-sensor/infiniti/oem-infiniti-m35-m37q70-crankshaft-position-sensor-p-41608.html
  'e2edc4d826ae85849f1462bd',
  // z1 motorsports | https://www.z1motorsports.com/camshaft-and-valve-mechanism/assembled-by-z1-motorsports/oem-11-19-infiniti-m56-q70-timing-kit-56l-p-45060.html
  'f73fda08b3e4e7bbc9ca2d94',
  // z1 motorsports | https://www.z1motorsports.com/camshaft-and-valve-mechanism/nissan/oem-vq37vhr-timing-kit-p-12470.html
  'c228b36207481aa054d73b20',
  // z1 motorsports | https://www.z1motorsports.com/cylinder-head-and-valve-cover/assembled-by-z1-motorsports/oem-370z-g37-q50-q60-vq37vhr-valve-cover-and-gasket-kit-p-25174.html
  '2a9d6dae03855c5abac541ef',
  // z1 motorsports | https://www.z1motorsports.com/cylinder-head-and-valve-cover/nissan/oem-370z-g37-q50-q60-valve-cover-gasket-vq37vhr-p-8879.html
  'c9d89b63ced9da7f93b2b1b0',
  // z1 motorsports | https://www.z1motorsports.com/engine-gasket-kit/nissan/nissan-oem-fluid-gasket-rtv-p-7247.html
  'c4d9064bd682b7e02c6ac4ff',
  // z1 motorsports | https://www.z1motorsports.com/engine-maintenance/assembled-by-z1-motorsports/oem-infiniti-q50-q60-30t-oil-change-kit-p-36652.html
  'd57f3f5687847a9dc3f30c47',
  // z1 motorsports | https://www.z1motorsports.com/fan-ac-and-power-steering-belt/infiniti/oem-vr30ddtt-belt-tensioner-assembly-p-10185.html
  'aa0a03aabbd2e011e8916855',
  // z1 motorsports | https://www.z1motorsports.com/front-timing-cover/nissan/vq35hr-vq37vhr-timing-cover-ring-and-seal-kit-p-9484.html
  '99c4d3add21cd29cad8ae46e',
  // z1 motorsports | https://www.z1motorsports.com/front-timing-cover/z1-motorsports/370z-g37-vq37vhr-rear-timing-cover-oil-gallery-gasket-kit-p-17916.html
  '70f92b5902d579aa76dda4b2',
  // z1 motorsports | https://www.z1motorsports.com/fuel-pump-and-control-unit/infiniti/oem-05-10-infiniti-m35m45-fuel-level-sending-unit-p-41172.html
  '4c29841b680b5ffc3245a6d7',
  // z1 motorsports | https://www.z1motorsports.com/piston-crankshaft-and-flywheel/assembled-by-z1-motorsports/q60-q50-vr30-anti-jump-belt-upgrade-kit-p-41625.html
  '8966ef82990f23ed304e0c18',
  // z1 motorsports | https://www.z1motorsports.com/piston-crankshaft-and-flywheel/nissan/oem-2007-infiniti-g35-coupe-piston-ring-set-p-72788.html
  '7c88980d96c659af591ca5af',
  // z1 motorsports | https://www.z1motorsports.com/transmission/z1-motorsports/z1-370z-g37-v2-csc-elimination-kit-p-54892.html
  '0b2462514816dc7fccc07275',
  // z1 motorsports | https://www.z1motorsports.com/turbo-charger/assembled-by-z1-motorsports/oem-infiniti-q50-q60-vr30-turbo-service-gasket-kit-p-39362.html
  'b183493056b16620e42d657a',
  // z1 motorsports | https://www.z1motorsports.com/turbo-charger/infiniti/oem-q50-q60-vr30-30t-stock-turbo-300hp-p-9961.html
  '6fa1b251d40553507f5c8b33',
  // z1 motorsports | https://www.z1motorsports.com/turbo-charger/infiniti/oem-q50-q60-vr30-30t-stock-turbo-400hp-p-9962.html
  'adba58b901e6cf9099a15cf1',
  // z1 off-road | https://www.z1offroad.com/auto-transmission/nissan/oem-nissan-matic-transmission-transfer-case-fluid-p-77811.html
  '6dc5779ff12a4fbe5fb11854',
  // zspeed performance | https://zspeed.com/products/zspeed-billet-v4-cmak
  'f332eb386808fffae33877e6',
] as const;

export const retailerHostFingerprints = [
  // autopartsprime.com
  'b6e04d2c3d46d1504d717b52',
  // autozone.com
  '12fa1f440ebfbfd1c0ab1b19',
  // carcoverplanet.com
  '8ca5fb21a8d0b3b388ec6f3d',
  // carparts.com
  'cb39b9c3d06e48b637584a8e',
  // finditparts.com
  '7e08600bd0825315e1f077e2',
  // infinitipartsdeal.com
  'f43a759e3d9288f8a27efc22',
  // moog-suspension-parts.com
  '7719c724255ce9cd16b11c65',
  // nisformance.com
  'f29756171117c06b6ff8bf17',
  // nissanpartsdeal.com
  'e30adbb167ada21c2629b83a',
  // parts.infinitiusa.com
  'c3651f11751e938f68d1a9e7',
  // partsgeek.com
  'b6c9d443e05ef437cef78a38',
  // sixityauto.com
  'aa7a0d469cbff99842de4076',
  // stillen.com
  '2138b6bee7725cb0ed746423',
  // suspension.com
  '5eef982f34dff812d91f953a',
  // walmart.com
  'ce624b6b31766d560320dd93',
  // z1motorsports.com
  'ae7bb61c4196afe7a5d54ab7',
  // z1offroad.com
  '636fd8157b51ef402c4d6dbc',
  // zspeed.com
  'e420e73ff399019719618deb',
] as const;
