// GENERATED by scripts/build-repair-first-verified-batch.mjs for International.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://scoutparts.com/Exhaust_Shield_For_Starter_71_80_IH_Scout_895570R11_Scout_II/p16533
  '61e9a75a6fda2942ccb8bc5f',
  // https://scoutparts.com/Ground_battery_wire_Battery_to_ground_New_Reproduction_like_original_878015R91_878018R91_437110R91_878019R91_878017R91_878015R91_878018R91_437110R91_878019R91_878017R91_Scout_II_Scout_80_Scout_800_Scout_II_Diesel_Scout_Terra_Scout_Traveler/p20969
  'ec9fe18cc1e59f7685d056c5',
  // https://scoutparts.com/Starter_Relay_Kit_With_12V_Harness_Send_More_Power_To_Your_Solenoid__Scout_II_Scout_80_Scout_800/p16071
  'dddf8a031dfbfdb663d3a035',
  // https://scoutparts.com/Valve_exhaust_IH_V8_Heat_Riser_Valve_NEW_heat_Regulator_1700538C91_324888C93_Scout_II_Scout_800_Travelall_Travelette_Pickup_Metro_Scout_Terra_Scout_Traveler/p13783
  'a3d83333d5fb95b5f3cfdad9',
  // https://www.gastankdepot.com/3019l-plastic-fuel-gas-tank-international-scout-ii-19-gallon.html
  '476ea97d1a1f087a08ac603d',
  // https://www.gastankdepot.com/scgts2-gas-tank-straps-international-scout-ii-19-gallon.html
  '37c298d33493b4dfb7996066',
  // https://www.gastankdepot.com/scsu2-gas-tank-sending-unit-international-scout-ii-19-gallon.html
  'ecc714354fa9a38c9f91c711',
  // https://www.ihpartsamerica.com/store/cc-7180.html
  'a7ada183ca40f2689bf10b6e',
  // https://www.ihpartsamerica.com/store/cs-sii-bod-mtl-pkg.html
  'b9e4509c40bdcab70a8b5317',
  // https://www.ihpartsamerica.com/store/iheng-alt-new.html
  '26a7a9f4a917518005da96ec',
  // https://www.ihpartsamerica.com/store/IHENG-TSTAT.html
  'e513c031ef6a20da063def47',
  // https://www.ihpartsamerica.com/store/pertronix.html
  '1904aafb731422740a8d74e3',
  // https://www.ihpartsamerica.com/store/SII-STRSTEER.html
  '1b5cbbcd50ff35466bb5f421',
  // https://www.ihpartsamerica.com/store/sl415824c1.html
  '6b97e50c16acd6a7157ca12e',
] as const;

export const vendorUrlFingerprints = [
  // gas tank depot | https://www.gastankdepot.com/3019l-plastic-fuel-gas-tank-international-scout-ii-19-gallon.html
  '715dd7583cc4671e583d060f',
  // gas tank depot | https://www.gastankdepot.com/scgts2-gas-tank-straps-international-scout-ii-19-gallon.html
  'fffce370a330ef06205ca50c',
  // gas tank depot | https://www.gastankdepot.com/scsu2-gas-tank-sending-unit-international-scout-ii-19-gallon.html
  '729f344cdc3b18d8bc83d53a',
  // ih parts america | https://www.ihpartsamerica.com/store/cc-7180.html
  '3442466b4987109198970078',
  // ih parts america | https://www.ihpartsamerica.com/store/cs-sii-bod-mtl-pkg.html
  'bdf1ff71ff7e61f5d3575916',
  // ih parts america | https://www.ihpartsamerica.com/store/iheng-alt-new.html
  'fcfaa28fc02e5d402bad216e',
  // ih parts america | https://www.ihpartsamerica.com/store/IHENG-TSTAT.html
  '15e146abaeaae2f60b8cf4a3',
  // ih parts america | https://www.ihpartsamerica.com/store/pertronix.html
  'f24477236b30fdebcffdeea7',
  // ih parts america | https://www.ihpartsamerica.com/store/SII-STRSTEER.html
  'a859a9214585abada3d5c3b8',
  // ih parts america | https://www.ihpartsamerica.com/store/sl415824c1.html
  '874bc0b462f14c1872496951',
  // scoutparts | https://scoutparts.com/Exhaust_Shield_For_Starter_71_80_IH_Scout_895570R11_Scout_II/p16533
  '811ed1b0194fa8e6b08ea343',
  // scoutparts | https://scoutparts.com/Ground_battery_wire_Battery_to_ground_New_Reproduction_like_original_878015R91_878018R91_437110R91_878019R91_878017R91_878015R91_878018R91_437110R91_878019R91_878017R91_Scout_II_Scout_80_Scout_800_Scout_II_Diesel_Scout_Terra_Scout_Traveler/p20969
  '15b305622ee6773ddda36058',
  // scoutparts | https://scoutparts.com/Starter_Relay_Kit_With_12V_Harness_Send_More_Power_To_Your_Solenoid__Scout_II_Scout_80_Scout_800/p16071
  'bfee8fdcf0b88788241526a0',
  // scoutparts | https://scoutparts.com/Valve_exhaust_IH_V8_Heat_Riser_Valve_NEW_heat_Regulator_1700538C91_324888C93_Scout_II_Scout_800_Travelall_Travelette_Pickup_Metro_Scout_Terra_Scout_Traveler/p13783
  '20c33c609648e7064c9602dd',
] as const;

export const retailerHostFingerprints = [
  // gastankdepot.com
  'cf78189ac291109da0bb64f0',
  // ihpartsamerica.com
  'ca9a7c3885c8db729d13b2a8',
  // scoutparts.com
  '7764c283cdfe23cea61e081a',
] as const;
