// GENERATED by scripts/build-repair-first-verified-batch.mjs for Kia.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://goturbo.net/gattck185-gates-timing-belt-component-kit-tck185
  '29bacda25058da3dcb619a47',
  // https://happymotorshop.com/en-eu/products/478103b520-oem-rear-differential-actuator-motor-for-hyundai-kia
  '971203688c46a9d83a90570a',
  // https://kia.oempartsonline.com/oem-parts/kia-blower-motor-881p0l1100
  'b48f8015897e5fa61c8050f5',
  // https://kia.oempartsonline.com/oem-parts/kia-condenser-97606g2000
  'e7f20e511c79e9c163ddbf81',
  // https://kia.oempartsonline.com/oem-parts/kia-headlamp-assembly-921013t520
  '5a4dacf8d627e50edf4ead9f',
  // https://kia.oempartsonline.com/oem-parts/kia-headlamp-assembly-921023t520
  'a37be1a5fdf4b65efea98493',
  // https://kia.oempartsonline.com/oem-parts/kia-hub-assembly-52730l1000
  '698b81826b9749a4ca3f915c',
  // https://kia.oempartsonline.com/oem-parts/kia-hub-assembly-52730n9000
  'c4da0af52d77c54c44917e32',
  // https://kia.oempartsonline.com/oem-parts/kia-latch-assembly-81230l0000
  'eeaae6b9fd91cd41714fdc3d',
  // https://kia.oempartsonline.com/oem-parts/kia-latch-assembly-81230l8000
  'd490edc151babb446e948812',
  // https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81310l3000
  '180e2728b01603e64e7c7f69',
  // https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81310l3010
  'b3357e4f5d59df171b19519a',
  // https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81320l3000
  '8ae8ab69fae0e0cd4d4fc1f3',
  // https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81320l3010
  'dbdd670889bf855e2311aa6f',
  // https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81410l3000
  'b1b96aab22e92cbf9f8263a9',
  // https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81410l3010
  'e0b7e90bd5760c3ddafb86a6',
  // https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81420l3000
  '02e418a8a576259e8c0bd258',
  // https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81420l3010
  '12451abaca72d23b62e93dd3',
  // https://kia.oempartsonline.com/oem-parts/kia-lower-shaft-56400l0000
  '04737556c85f15aada1d1a6b',
  // https://kia.oempartsonline.com/oem-parts/kia-oil-feed-tube-282402m810
  'a2899b49ca1581b122753bc2',
  // https://kia.oempartsonline.com/oem-parts/kia-oil-feed-tube-gasket-282412b710
  '3950c6246237c2423859303e',
  // https://kia.oempartsonline.com/oem-parts/kia-oil-return-tube-282482m800
  '16df640004c05164f6425ba9',
  // https://kia.oempartsonline.com/oem-parts/kia-oil-return-tube-gasket-282462b710
  'e2c41b35838a1af1386f0e3a',
  // https://kia.oempartsonline.com/oem-parts/kia-oil-return-tube-gasket-282472b700
  '1d329c5212e1b0aeb251a6d0',
  // https://kia.oempartsonline.com/oem-parts/kia-seat-back-heater-88370l3000
  '2699e656e3896de4ae1c1120',
  // https://kia.oempartsonline.com/oem-parts/kia-seat-back-heater-88370l3010
  '335124c9da4d9da1dce5b7d2',
  // https://kia.oempartsonline.com/oem-parts/kia-seat-cushion-heater-88170l3000
  'bf3d628756d119c3a9af6232',
  // https://kia.oempartsonline.com/oem-parts/kia-seat-cushion-heater-88170l3010
  'db05421e0c80b7a00334af24',
  // https://kia.oempartsonline.com/oem-parts/kia-strut-mount-54610l0000
  '3937bbc8df248ddf7ce8af20',
  // https://kia.oempartsonline.com/oem-parts/kia-strut-mount-54610l0100
  'c3d42d625d581235db34f649',
  // https://partlimit.com/products/ac-compressor-clutch-repair-kit-coil-pulley-bearing-for-hyundai-santa-fe-xg350-kia-amanti-3-5l/ac
  '684b185e510f84c4abef8568',
  // https://shop.advanceautoparts.com/p/3m-headliner-fabric-adhesive-38808-18.1-oz-38808/10506029-p
  '72a9286f49c15c120689984b',
  // https://shop.advanceautoparts.com/p/crc-gdi-ivd-intake-valve-and-turbo-cleaner-05319/11019388-P
  'b58cfd715d376bd14398f8eb',
  // https://shop.advanceautoparts.com/p/diehard-platinum-agm-battery-group-size-h6-760-cca-h6-agm/10210829-P
  'a6ec888583d3b55e546db76f',
  // https://shop.app/products/7589374263503/sunroof-drain-cleaning-tool-10ft
  '834005c50541884330100545',
  // https://www.am-autoparts.com/models-categories/Kia/Amanti/timing-belts.html
  'afcc7a10c332bc8e6eccd73c',
  // https://www.anker.com/products/a82g2
  '35358fbc0b1e14c1ea0cdf9f',
  // https://www.apple.com/shop/product/muqw3am/a/lightning-to-usb-cable-1-m
  '5d86ce2b5da0fe392ad73fe7',
  // https://www.autopartsprime.com/anchor/front-passenger-side-engine-mount/mp-9325
  '0c1725a9f7a904de5fd695d4',
  // https://www.autopartsprime.com/gates/powergrip-timing-belt-component-kit/mp-tck179
  '2deea0d1edf790247be6e981',
  // https://www.autopartsprime.com/kia/flange-nut-self-lock/oe-54559d1000
  '8c5f66e0a344a605b6c68055',
  // https://www.autozone.com/p/beck-arnley-direct-ignition-coil-178-8273/873480
  'c78f0d10e3cf80caf7240807',
  // https://www.autozone.com/p/duralast-platinum-battery-h5-agm/338292
  '195f92e6f3aeab19a2ca5e3b',
  // https://www.buyautoparts.com/buynow/2018/kia/rio/a-c-compressor-and-components-kit/61-98140-r6
  '4115c0b313227adc71a5753e',
  // https://www.carid.com/gates/powergrip-timing-belt-component-kit-mpn-tck318.html
  '916dacb51eba53827164083c',
  // https://www.carparts.com/details/cylinder-head-gasket/felpro/fp9717pt
  '2e75f20273bff5438ad17ce5',
  // https://www.carparts.com/details/Kia/Borrego/Cloyes/Timing_Chain_Kit/2009/CLO90771SX.html
  '47ce7c06cd0435d96f4f5e9e',
  // https://www.esrtech.com/products/qi2-wireless-car-charger-with-cryoboost-halolock?attribute_color=Black
  '0d0503518b1865992c0bac1f',
  // https://www.finditparts.com/products/5382862/fel-pro-9696b
  '2c7061f2393c28f83d49f745',
  // https://www.homedepot.com/p/308154451
  '2dc49ef44b6cf5f610f53d65',
  // https://www.homedepot.com/p/311360785
  'ade35b58079d350fb642c07a',
  // https://www.kia.parts/oem-parts/kia-a-c-condenser-976062s500
  '0e81754e8ef55f3c662b4700',
  // https://www.kia.parts/oem-parts/kia-air-filter-97133r0000
  '28b2ba44487c4e2cafb82782',
  // https://www.kia.parts/oem-parts/kia-air-filter-97133r0500
  'f82579b812d84e0cf1205a1a',
  // https://www.kia.parts/oem-parts/kia-bearing-54612l1000
  '3ba47081102da4bddae06323',
  // https://www.kia.parts/oem-parts/kia-blower-motor-97113l1100
  '2d0bed505c324b7ba0b6a516',
  // https://www.kia.parts/oem-parts/kia-brake-pads-58101r0a00
  '137c59da6e2122135eda2dcd',
  // https://www.kia.parts/oem-parts/kia-condenser-97606d3550
  '89de212268816faa432588be',
  // https://www.kia.parts/oem-parts/kia-condenser-97606d9900
  'fbbd4607264b93216a49647a',
  // https://www.kia.parts/oem-parts/kia-control-module-81870cv100
  'd0f39827cbd620941250aaa1',
  // https://www.kia.parts/oem-parts/kia-cover-assembly-clutch-412002b001fff
  '3b4663009f5c613f60061e1c',
  // https://www.kia.parts/oem-parts/kia-disc-brake-rotor-51712gi000
  'a76ad889d083f8303ad40cbf',
  // https://www.kia.parts/oem-parts/kia-evaporator-core-979271u000
  '363b024d4864cb9447914f4b',
  // https://www.kia.parts/oem-parts/kia-flexible-coupling-563152k000fff
  '852dd1af6e85f63ef84ec733',
  // https://www.kia.parts/oem-parts/kia-gs-atf-sp-iv-rear-12-um014ch065
  '3eed2fd1c40ab048c103d880',
  // https://www.kia.parts/oem-parts/kia-intermediate-shaft-56400c5500
  '3eb57bd63f3f68e43a16b163',
  // https://www.kia.parts/oem-parts/kia-lock-actuator-81800cv100
  'a6e888d788ae85dba9506605',
  // https://www.kia.parts/oem-parts/kia-oil-filter-263203n000
  'b3fcaf5d8fe9049345169c34',
  // https://www.kia.parts/oem-parts/kia-oil-pan-sealer-2145133t00
  '0991023d775917fbbfb3e140',
  // https://www.kia.parts/oem-parts/kia-power-cylinder-81831cv100
  '8c098302b2fbe58bf2bdf132',
  // https://www.kia.parts/oem-parts/kia-power-cylinder-81841cv100
  '8d7e99f195f46b60ad272d04',
  // https://www.kia.parts/oem-parts/kia-power-steering-cooler-tube-575502j210
  'd6631250ab26929db9dbd91f',
  // https://www.kia.parts/oem-parts/kia-power-steering-cooler-tube-575502j400
  '0a9f5e547fa5e42968f069d0',
  // https://www.kia.parts/oem-parts/kia-rotor-51712cv200
  '22ac67306454e4edc36f4da6',
  // https://www.kia.parts/oem-parts/kia-rotor-51712r0050
  '7b2958c89f9316811bcfebfe',
  // https://www.kia.parts/oem-parts/kia-rotor-58411cv200
  '90570d3f04b554c379a8cd92',
  // https://www.kia.parts/oem-parts/kia-rotor-58411gi000
  '671cd7330e4f13a52b776cac',
  // https://www.kia.parts/oem-parts/kia-strut-assembly-54650cv500
  '9d7992e33e662fcbe89ac476',
  // https://www.kia.parts/oem-parts/kia-strut-mount-54610gi000
  '1b0472aac13ddaf8aa7b1589',
  // https://www.kia.parts/oem-parts/kia-suspension-stabilizer-bar-link-kit-54830cv000
  '3d04860689ace907e0bda931',
  // https://www.kia.parts/oem-parts/kia-suspension-stabilizer-bar-link-kit-54831cv000
  'b64665804c92d2544bcac523',
  // https://www.kia.parts/oem-parts/kia-suspension-strut-54650cv400
  '2b243b64512ce886461f9779',
  // https://www.kia.parts/oem-parts/kia-suspension-strut-54651cv400
  'fe6adb31f04f16b16b1bc490',
  // https://www.kia.parts/oem-parts/kia-suspension-strut-54651cv500
  '91b7108a3f0a6f2dfc4ec2c4',
  // https://www.kia.parts/oem-parts/kia-touch-up-paint-pen-snow-white-pearl-swp-swa-ua011tu5014swpa
  'fa8ab0b24779375d2f7f2e63',
  // https://www.kia.parts/oem-parts/kia-windshield-86111cv110
  'ffa215fb325fde9e894969a1',
  // https://www.kiaautoparts.com/oem-parts/kia-atf-type-4-m-12-um013ch059
  '64680e82790472ac8b28a9fd',
  // https://www.kiacheapparts.com/oem-parts/kia-brake-pads-58101r0a10
  'd1caba28b2a4368584857510',
  // https://www.kiacheapparts.com/oem-parts/kia-drain-plug-gasket-2151323001
  '726479118836f90e5a06b81b',
  // https://www.kiaparts.com/oem-parts/kia-sp-cvt1-fluid-um018ch130
  '534d043310529c14c1535a96',
  // https://www.kiapartsnow.com/genuine/kia-0~373003c210sj.html
  '5cf556863d31e4904e7bce2d',
  // https://www.kiapartsnow.com/genuine/kia-0~391802m612.html
  '78e6487fd54b1fb5dead1a9c',
  // https://www.kiapartsnow.com/genuine/kia-0~82530r0300.html
  '532e8acc1f64c9faa21fc693',
  // https://www.kiapartsnow.com/genuine/kia-0~82540r0010.html
  'b60cf4b220554da2b479094d',
  // https://www.kiapartsnow.com/genuine/kia-0~82540r0300.html
  '14a08ff499f38b62f248f796',
  // https://www.kiapartsnow.com/genuine/kia-0~92170a7000fff.html
  '07dcbaa78da029c3c0501ca0',
  // https://www.kiapartsnow.com/genuine/kia-0~97701c6950ru.html
  '702f8f6232d74060da4c788f',
  // https://www.kiapartsnow.com/genuine/kia-actuator-fr-dr~957303c000.html
  'afa45ef2daa18cabd2ec6321',
  // https://www.kiapartsnow.com/genuine/kia-actuator-fr-dr~957503c000.html
  '6e1e817509462219db073441',
  // https://www.kiapartsnow.com/genuine/kia-actuator-rr-dr~957703c000.html
  '2563269ba2790a63f259a21d',
  // https://www.kiapartsnow.com/genuine/kia-actuator-rr-dr~957803c000.html
  '3af5b7966dee77ac249ddec9',
  // https://www.kiapartsnow.com/genuine/kia-bearing-strut~54612c1000.html
  '2c9162971d841147517f34ff',
  // https://www.kiapartsnow.com/genuine/kia-camera-assy-back-vie~99240h8000.html
  '46509e4f0b65ad2ed8195e50',
  // https://www.kiapartsnow.com/genuine/kia-canister-close~3143029200.html
  'a9cc50f06de7be6c7acbcce4',
  // https://www.kiapartsnow.com/genuine/kia-cap-assy-fuel-f~310103l500u.html
  '462714b2fd9eb14379e37ede',
  // https://www.kiapartsnow.com/genuine/kia-cap-assy-fuel-f~310103l600u.html
  '8379f902cdf64338f1d06914',
  // https://www.kiapartsnow.com/genuine/kia-coil-assy-ignit~273002gga0.html
  'ce596cf9e6cb958ddf92a1e4',
  // https://www.kiapartsnow.com/genuine/kia-coil-assy-ignit~273003f100.html
  'd8fa19a6e291d2ccb3c1f7af',
  // https://www.kiapartsnow.com/genuine/kia-coil-assy-ignit~2730126640.html
  '737d27cc6585bec94dfb55f3',
  // https://www.kiapartsnow.com/genuine/kia-compressor-assy~977011r100.html
  '52a635f01a11dea017a69670',
  // https://www.kiapartsnow.com/genuine/kia-compressor-assy~977011w600.html
  'd24dee72730c53176b59577c',
  // https://www.kiapartsnow.com/genuine/kia-compressor-assy~97701h9200.html
  '6b3ce828027235cd372c3978',
  // https://www.kiapartsnow.com/genuine/kia-coupling-assy-4~478003b520.html
  'eec9bc54e7036827f4dc57c2',
  // https://www.kiapartsnow.com/genuine/kia-cyl-clutch-mas~0k2a341400b.html
  '1bdcbbc559807028eec690b9',
  // https://www.kiapartsnow.com/genuine/kia-disc-front-wheel-bra~51712j5500.html
  '875e32b306f517858289d2c5',
  // https://www.kiapartsnow.com/genuine/kia-drive-unit-assy~834754d101.html
  'fda871c917bf4e06a0bb435c',
  // https://www.kiapartsnow.com/genuine/kia-drive-unit-assy~834754d102.html
  'ce81872a0194ce5e829864fd',
  // https://www.kiapartsnow.com/genuine/kia-drive-unit-assy~834854d102.html
  '58512fdd5efd2c2a697ae779',
  // https://www.kiapartsnow.com/genuine/kia-filter-assy-air~97133l1000.html
  '04a69bcdaaa3da4551ead32d',
  // https://www.kiapartsnow.com/genuine/kia-flexible-coupli~563152k000fff.html
  '0cdd31ae04c479ef9ba11d23',
  // https://www.kiapartsnow.com/genuine/kia-free-wheel-hub~0k08133210.html
  'e1334dd9e00d50c9f60d27f7',
  // https://www.kiapartsnow.com/genuine/kia-generator-assy~373003c170.html
  '93b0e2899ff0ac019ca9a644',
  // https://www.kiapartsnow.com/genuine/kia-generator-assy~373003c510sj.html
  '166fb035ee910c2a5deda1fa',
  // https://www.kiapartsnow.com/genuine/kia-injector-assy-f~353102b130.html
  '0050becada010bfe2480a581',
  // https://www.kiapartsnow.com/genuine/kia-injector-o-ring-kit~353122g750.html
  '1c32a57a121c01bd72adef9f',
  // https://www.kiapartsnow.com/genuine/kia-insulator-assy-strut~54611h6000.html
  'bec06f0a5c9aab29a684ae28',
  // https://www.kiapartsnow.com/genuine/kia-insulator-assy~546111w000.html
  'ea431e6f162c163af98ec6e3',
  // https://www.kiapartsnow.com/genuine/kia-insulator-strut~55311h5000.html
  'ecd86beda1fa55e6732ffed1',
  // https://www.kiapartsnow.com/genuine/kia-joint-assy-strg~56400c5000.html
  '32d212e3714d851a533b7145',
  // https://www.kiapartsnow.com/genuine/kia-latch-assy-fr-d~813203c001.html
  'b290cb048ecf390c4073cb10',
  // https://www.kiapartsnow.com/genuine/kia-latch-assy-rr-d~814104d010.html
  '90f572d9a5f60bf33534a4f5',
  // https://www.kiapartsnow.com/genuine/kia-latch-assy-rr-d~814204d010.html
  '94371d6a2658edc99c54c959',
  // https://www.kiapartsnow.com/genuine/kia-lever-assy-panoramar~81651c5000.html
  'bd5f8d94308c3abf632c7d0f',
  // https://www.kiapartsnow.com/genuine/kia-lever-assy-panoramar~81652c5000.html
  '295f40b51cf623c015e0b1f5',
  // https://www.kiapartsnow.com/genuine/kia-manifold-cataly~285102g445.html
  'd28f7b8b7e1c24d0bf3cc219',
  // https://www.kiapartsnow.com/genuine/kia-manifold-cataly~285102gbb0.html
  'c534305dc0774857685d9294',
  // https://www.kiapartsnow.com/genuine/kia-oil-flow-contro~243552g000.html
  '19c284f9687d349261374a8d',
  // https://www.kiapartsnow.com/genuine/kia-pad-front-spring-upr~54623f1000fff.html
  'eb5ed24875e64b3be078401c',
  // https://www.kiapartsnow.com/genuine/kia-plug-assy-spark~1882311101.html
  'ef21e117a778edfea9956515',
  // https://www.kiapartsnow.com/genuine/kia-plug-assy-spark~1884611070.html
  'a5cd7356d6146c35d09106cf',
  // https://www.kiapartsnow.com/genuine/kia-plug-assy-spark~1884711160.html
  'c8eb7143a2f5d04ef271a4a2',
  // https://www.kiapartsnow.com/genuine/kia-plug-assy-spark~1884909085.html
  '9f527db1d59d03b3a2bc7d5d',
  // https://www.kiapartsnow.com/genuine/kia-plug-assy-spark~1884911070.html
  '772805b714b586f8940ecc30',
  // https://www.kiapartsnow.com/genuine/kia-pump-assy-vacuum~288102m810.html
  'a425cc100c276e130463a0cc',
  // https://www.kiapartsnow.com/genuine/kia-pump-compt-wat~251002x401.html
  '46252f144e270c3d728fa365',
  // https://www.kiapartsnow.com/genuine/kia-reman-alternato~3730022650ru.html
  'eeebb0146556e522792b1025',
  // https://www.kiapartsnow.com/genuine/kia-reman-alternato~3730023650ru.html
  '7f676dc88d6004ab6d89589e',
  // https://www.kiapartsnow.com/genuine/kia-reman-alternato~3730037405ru.html
  'd4401442bfc9a34ae90e3e5e',
  // https://www.kiapartsnow.com/genuine/kia-reman-alternato~3730038310.html
  '2983a03312679083f915bec2',
  // https://www.kiapartsnow.com/genuine/kia-reman-alternato~3730039435ru.html
  'c2b630a9eed02b18caf644d9',
  // https://www.kiapartsnow.com/genuine/kia-reman-alternato~rk2aa18300u.html
  '6fcd025cc38a24c63b1ed69a',
  // https://www.kiapartsnow.com/genuine/kia-roller-arm-assy~839304d000.html
  '7a84be8f7d25b71066e3fe15',
  // https://www.kiapartsnow.com/genuine/kia-roller-arm-assy~839304d100.html
  '2ea758fb9570b3447810763f',
  // https://www.kiapartsnow.com/genuine/kia-roller-arm-assy~839404d000.html
  'bf1312c17dd7d61f9a479439',
  // https://www.kiapartsnow.com/genuine/kia-roller-arm-assy~839404d100.html
  '99d7367a6920bfe3aa3b4379',
  // https://www.kiapartsnow.com/genuine/kia-roller-assy-ctr~0k55273230g.html
  '887a3a9078fb14a6cc6949b0',
  // https://www.kiapartsnow.com/genuine/kia-run-assy-fr-dr-wdo-g~82530r0010.html
  'b8088424f001dbef5d25f0a5',
  // https://www.kiapartsnow.com/genuine/kia-sensor-a-t-inp~4262039051.html
  '9b1104359babfa42924fc1ae',
  // https://www.kiapartsnow.com/genuine/kia-sensor-a-t-out~4262139052.html
  'eab63ed22115dd505a788fc2',
  // https://www.kiapartsnow.com/genuine/kia-set-double-clutch~412002d220fff.html
  'f48fe541782427a022cf7136',
  // https://www.kiapartsnow.com/genuine/kia-switch-assy-mul~934003c520.html
  '9bf44511943581e713d2d945',
  // https://www.kiapartsnow.com/genuine/kia-switch-assy-sto~938102e000.html
  '3d8159fc169871e4d4abe674',
  // https://www.kiapartsnow.com/genuine/kia-switch-assy-sto~938103k000.html
  '9671591caf9253cb38dd5404',
  // https://www.kiapartsnow.com/genuine/kia-valve-assy-p-so~0k30e18740.html
  'b771886cf50fd34e1b6da00d',
  // https://www.kiapartsnow.com/genuine/kia-valve-assy-purge-control~289002gga2.html
  '0fc2794d3362b397d4a4f982',
  // https://www.kiapartsnow.com/genuine/kia-valve-canister-close~314300w000.html
  '01e6a72397379456d109a56f',
  // https://www.kiapartsnow.com/genuine/kia-valve-expansion~979162b010.html
  '6620014931893f7b4a13f24d',
  // https://www.kiapartsnow.com/genuine/kia-valve-purge-con~2891022040.html
  'a85ebbefd165548630074504',
  // https://www.kiapartsnow.com/genuine/kia-valve-purge-con~2891025100.html
  '5a1bf42b1fe6dbb55f40a2cb',
  // https://www.kiapartsnow.com/genuine/kia-valve-purge-con~2891026900.html
  'ccf4544edfb3324d9250bab6',
  // https://www.kiapartsnow.com/genuine/kia-valve-purge-con~289103c200.html
  '898580f03aa6bceab5b8a2f6',
  // https://www.kiapartsnow.com/genuine/kia-valve-purge-con~289103l135.html
  '56904dac4a5099c81908de49',
  // https://www.kiapartsnow.com/genuine/kia-valve-solenoid~463134e602.html
  '1b9e219e8083ca311bb56fa9',
  // https://www.kiapartsnow.com/genuine/kia-valve-solenoid~463134e702.html
  '49bac0cf0f1b87949241214e',
  // https://www.kiapartsnow.com/oem-2008-kia-rio-fuel_filler_neck.html
  '3044b51118f7e118c1cf32ef',
  // https://www.kiapartsnow.com/oem-kia-clutch_slave_cylinder.html
  '54a3ce48b46ae08838f5a513',
  // https://www.kiapartsonline.com/oem-parts/kia-windshield-86111cv130
  'd6dfea6eb8e367bd694d9023',
  // https://www.mishimoto.com/kia-stinger-gt-catch-can-2018.html
  'a5ddf5731b84d53fbddf9eaa',
  // https://www.partsgeek.com/2l3hnk3-kia-spectra-timing-belt-kit.html
  'e796c7adcc2d10ebfffd8993',
  // https://www.partsgeek.com/f4mc179-kia-amanti-alternator.html
  '20da9bd2eab457e0830af081',
  // https://www.partsgeek.com/fnlp3hj-kia-spectra-timing-belt-kit.html
  'e5f93106ed7aa750a1d7a6b4',
  // https://www.partsgeek.com/hqr114y-kia-sephia-head-bolt-set.html
  'fa6c46754f351657ed3f72cc',
  // https://www.partsgeek.com/lbzdqy4-kia-sephia-timing-belt-kit.html
  '91feb0a2fbb6bb27c3e55025',
  // https://www.partsgeek.com/lvq7lmf-kia-amanti-alternator.html
  '9c2ba266ec31d8ef547cd6d5',
  // https://www.partsgeek.com/t7dqkyk-kia-rio-ac-compressor-kit.html
  '40ddb25ba25d3f7f3e4de947',
  // https://www.partsgeek.com/vllpkt5-kia-rio-strut-and-coil-spring-assembly-set.html
  'e41b0f09d46f35d5d293fb98',
  // https://www.partsgeek.com/w6k7cr2-kia-sephia-head-gasket.html
  'a6dc1321d636b95c7b984f92',
  // https://www.partsgeek.com/y1nwcyp-kia-spectra-timing-belt-kit-and-water-pump.html
  '929892c2f69ae098bf25376d',
  // https://www.partsgeek.com/ykn5xd8-kia-rio-ignition-coil-spark-plug-and-wire-set.html
  '3e6adecabf7e3c9467b5f70b',
  // https://www.partssource.com/parts/krytox/GPL20535RU37
  '9c067a7d230cab299f8c033d',
  // https://www.quirkparts.com/oem-parts/hyundai-snap-ring-410682d000fff
  '64a86a0b0ff6c0907c528503',
  // https://www.rycompressors.com/shop/2009-kia-amanti-fh313-282181.html
  'a22db0ace4f81b918bc2d9f6',
  // https://www.steeda.com/bg-products-709-frigi-clean-kit
  '8f4b1528876871905646c399',
  // https://www.tascaparts.com/oem-parts/kia-oil-pressure-sending-unit-947513c000
  '4c1cd84758244a281f3f9ea6',
  // https://www.theruststore.com/products/fluid-film-11-75-oz-aerosol
  'fb1163e2879a3844f245e250',
  // https://www.tunersports.com/brembo-oe-p30113n-ceramic-pads-p503423.html
  '5b712421e630f8c7ca14d52b',
  // https://www.walmart.com/ip/36019107
  '72d049d725ab370a0a54248f',
] as const;

export const vendorUrlFingerprints = [
  // advance auto parts | https://shop.advanceautoparts.com/p/3m-headliner-fabric-adhesive-38808-18.1-oz-38808/10506029-p
  '9a0c4e7a3e08e5d317cd48d0',
  // advance auto parts | https://shop.advanceautoparts.com/p/crc-gdi-ivd-intake-valve-and-turbo-cleaner-05319/11019388-P
  'db5480b449a91f21fedd32aa',
  // advance auto parts | https://shop.advanceautoparts.com/p/diehard-platinum-agm-battery-group-size-h6-760-cca-h6-agm/10210829-P
  'ba7fe15e858117f91b6dadb7',
  // am autoparts | https://www.am-autoparts.com/models-categories/Kia/Amanti/timing-belts.html
  '2a500c5b3c3e804e99040013',
  // amazon | https://www.amazon.com/Moog-81234-Coil-Spring-Set/dp/B006DYL59W?tag=au7o-20
  '92272fa6d3b0f9f4a49d2cba',
  // anker | https://www.anker.com/products/a82g2
  '1340e3a2710b2d8676b8e6bb',
  // apple | https://www.apple.com/shop/product/muqw3am/a/lightning-to-usb-cable-1-m
  '752c57a3be06aa28f4e00351',
  // autopartsprime | https://www.autopartsprime.com/anchor/front-passenger-side-engine-mount/mp-9325
  'b1290953cc0f43b1904719d3',
  // autopartsprime | https://www.autopartsprime.com/gates/powergrip-timing-belt-component-kit/mp-tck179
  '84b62cf69be5a8746a4417dd',
  // autopartsprime | https://www.autopartsprime.com/kia/flange-nut-self-lock/oe-54559d1000
  'c300e964d67f6df7d28e8a45',
  // autozone | https://www.autozone.com/p/beck-arnley-direct-ignition-coil-178-8273/873480
  '4fbc19b0f0ef18c45100f8e1',
  // autozone | https://www.autozone.com/p/duralast-platinum-battery-h5-agm/338292
  '68266d5e02b2b8bbfc0a436f',
  // buyautoparts | https://www.buyautoparts.com/buynow/2018/kia/rio/a-c-compressor-and-components-kit/61-98140-r6
  'ce13a279f43fd03ab477c3e4',
  // carid | https://www.carid.com/gates/powergrip-timing-belt-component-kit-mpn-tck318.html
  'b3a9804d67a3bbb9878680b2',
  // carparts.com | https://www.carparts.com/details/cylinder-head-gasket/felpro/fp9717pt
  '5c10d92e7abb87d63e8223bb',
  // carparts.com | https://www.carparts.com/details/Kia/Borrego/Cloyes/Timing_Chain_Kit/2009/CLO90771SX.html
  'cd650e8d0e27bf2e9a36ba62',
  // ebay | https://www.ebay.com/itm/406487135127
  'a05d2bfce30cfb6d6d8fea05',
  // esr | https://www.esrtech.com/products/qi2-wireless-car-charger-with-cryoboost-halolock?attribute_color=Black
  'c9ae0c6c1257605f8b019038',
  // finditparts | https://www.finditparts.com/products/5382862/fel-pro-9696b
  '491c8b79e022e07fca626dc9',
  // form&function design via shop | https://shop.app/products/7589374263503/sunroof-drain-cleaning-tool-10ft
  'b07a65d7fa626a8e6980bfc2',
  // goturbo | https://goturbo.net/gattck185-gates-timing-belt-component-kit-tck185
  'f0549df29d204c68e118b7d7',
  // happy motor shop | https://happymotorshop.com/en-eu/products/478103b520-oem-rear-differential-actuator-motor-for-hyundai-kia
  '892f4d83c1f38f246dd652df',
  // home depot | https://www.homedepot.com/p/308154451
  '689cec925ce158e0adf69724',
  // home depot | https://www.homedepot.com/p/311360785
  '0f71f2b1bd00dae9f104fba1',
  // kia auto parts | https://www.kiaautoparts.com/oem-parts/kia-atf-type-4-m-12-um013ch059
  '465391eb51312253ea9e119f',
  // kia cheap parts | https://www.kiacheapparts.com/oem-parts/kia-brake-pads-58101r0a10
  '506a7bad8f4f6578e49634e2',
  // kia cheap parts | https://www.kiacheapparts.com/oem-parts/kia-drain-plug-gasket-2151323001
  'efbf9d97b6a55e38de7df96d',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-blower-motor-881p0l1100
  '9e095a1403859ab57badc70c',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-condenser-97606g2000
  'bb231c2698c5a7f4a75a5119',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-headlamp-assembly-921013t520
  '5fce917d701d9a70e6de0d13',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-headlamp-assembly-921023t520
  'f02c01298d1b7b12719b506a',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-hub-assembly-52730l1000
  '787958cb7e486546469db514',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-hub-assembly-52730n9000
  'ff515e13a52e26a496cade69',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-latch-assembly-81230l0000
  '796dc11aa0020a30e4255436',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-latch-assembly-81230l8000
  '9cc350ddf05085bc67342308',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81310l3000
  '191d0e9c1f5c751a7bb6273b',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81310l3010
  'a23bd8c4ac900c0e5adfcfd0',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81320l3000
  '9f6c9a375cea686b9e8c4329',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81320l3010
  '308aa58efe157259b099d15a',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81410l3000
  'a78acafc4767a1b83dcf1464',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81410l3010
  '096c9c72d0e97fbc2886b400',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81420l3000
  '4871f423cd7bb1a2c4b826ee',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-lock-actuator-81420l3010
  '3bec81a5f75dbda3d2e9fffb',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-lower-shaft-56400l0000
  '24ba802ec499b82fcd748c30',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-oil-feed-tube-282402m810
  '295a59cee2b13305fa073496',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-oil-feed-tube-gasket-282412b710
  'c8d03be6617797e09f476d00',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-oil-return-tube-282482m800
  '81c6454445eb5e36bc848667',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-oil-return-tube-gasket-282462b710
  '8df8987d361361a2cb41a343',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-oil-return-tube-gasket-282472b700
  '4809502eb843b06d083a8b5b',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-seat-back-heater-88370l3000
  '247f496cc84d13ad53c9696a',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-seat-back-heater-88370l3010
  'ecb5696f1a634ff2e02ae56e',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-seat-cushion-heater-88170l3000
  '585deb7f73c0e55d3644d82b',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-seat-cushion-heater-88170l3010
  'ce513bcb77afad210ab7b965',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-strut-mount-54610l0000
  '042822f758c84212c8a0ca16',
  // kia oem parts online | https://kia.oempartsonline.com/oem-parts/kia-strut-mount-54610l0100
  '2b9d8e3286df1915e5040aef',
  // kia parts | https://www.kia.parts/oem-parts/kia-flexible-coupling-563152k000fff
  'f1f8f3ac1db5ffbd1d8fadfa',
  // kia parts online | https://www.kiapartsonline.com/oem-parts/kia-windshield-86111cv130
  'b478dc0c469429662a1cdace',
  // kia.parts | https://www.kia.parts/oem-parts/kia-a-c-condenser-976062s500
  'c050f884da77d1d4da4dc68c',
  // kia.parts | https://www.kia.parts/oem-parts/kia-air-filter-97133r0000
  '578ef2fc7fb1517529503ab5',
  // kia.parts | https://www.kia.parts/oem-parts/kia-air-filter-97133r0500
  '48dd57fd3608250cc37a8b30',
  // kia.parts | https://www.kia.parts/oem-parts/kia-bearing-54612l1000
  '683be6fd4f7771f80059ab2d',
  // kia.parts | https://www.kia.parts/oem-parts/kia-blower-motor-97113l1100
  'e22d4b350dd726fc8059ada2',
  // kia.parts | https://www.kia.parts/oem-parts/kia-brake-pads-58101r0a00
  'b6c030af402d93e94bb0c766',
  // kia.parts | https://www.kia.parts/oem-parts/kia-condenser-97606d3550
  '2fee73f3a6160362e63ed6f0',
  // kia.parts | https://www.kia.parts/oem-parts/kia-condenser-97606d9900
  '330e66131401e67042073547',
  // kia.parts | https://www.kia.parts/oem-parts/kia-control-module-81870cv100
  'c57d0ebe49a7029b5eacb90b',
  // kia.parts | https://www.kia.parts/oem-parts/kia-cover-assembly-clutch-412002b001fff
  'bc6c0ac2e0468c1d18134f7c',
  // kia.parts | https://www.kia.parts/oem-parts/kia-disc-brake-rotor-51712gi000
  '10c551ede81261604271e8cc',
  // kia.parts | https://www.kia.parts/oem-parts/kia-evaporator-core-979271u000
  'e4cf91a801ef0cbdf0e3a814',
  // kia.parts | https://www.kia.parts/oem-parts/kia-gs-atf-sp-iv-rear-12-um014ch065
  '5a4112975daf5d3214d3e68a',
  // kia.parts | https://www.kia.parts/oem-parts/kia-intermediate-shaft-56400c5500
  'c0b934d880c063bc092b29d3',
  // kia.parts | https://www.kia.parts/oem-parts/kia-lock-actuator-81800cv100
  '935e480fa05a1587a1ce3a73',
  // kia.parts | https://www.kia.parts/oem-parts/kia-oil-filter-263203n000
  'd177895c460bb48a0f415bd5',
  // kia.parts | https://www.kia.parts/oem-parts/kia-oil-pan-sealer-2145133t00
  'd9b335f9f2c8e039c2377923',
  // kia.parts | https://www.kia.parts/oem-parts/kia-power-cylinder-81831cv100
  '4b1268cf4aa4ac1ceb587cda',
  // kia.parts | https://www.kia.parts/oem-parts/kia-power-cylinder-81841cv100
  '48c80d9c2ff150011820bcb8',
  // kia.parts | https://www.kia.parts/oem-parts/kia-power-steering-cooler-tube-575502j210
  'e21bc81ece58dc4e8e56f6fb',
  // kia.parts | https://www.kia.parts/oem-parts/kia-power-steering-cooler-tube-575502j400
  '50c2b7fc8d65e8eff82b148a',
  // kia.parts | https://www.kia.parts/oem-parts/kia-rotor-51712cv200
  '520879e782e43d17571221d8',
  // kia.parts | https://www.kia.parts/oem-parts/kia-rotor-51712r0050
  '9078db6fe98ad03baee79efe',
  // kia.parts | https://www.kia.parts/oem-parts/kia-rotor-58411cv200
  '9c94f694b9d117f7249037ab',
  // kia.parts | https://www.kia.parts/oem-parts/kia-rotor-58411gi000
  '698f5d3a6a04030abc0b3ac1',
  // kia.parts | https://www.kia.parts/oem-parts/kia-strut-assembly-54650cv500
  'b3522e9ee540a00630913e55',
  // kia.parts | https://www.kia.parts/oem-parts/kia-strut-mount-54610gi000
  'ce1aeb13dd5af7a13db550cb',
  // kia.parts | https://www.kia.parts/oem-parts/kia-suspension-stabilizer-bar-link-kit-54830cv000
  'bc5d595a0598408a5d30d6c7',
  // kia.parts | https://www.kia.parts/oem-parts/kia-suspension-stabilizer-bar-link-kit-54831cv000
  '3f0853d3982af5e094987873',
  // kia.parts | https://www.kia.parts/oem-parts/kia-suspension-strut-54650cv400
  '4da262f4220389104a56273a',
  // kia.parts | https://www.kia.parts/oem-parts/kia-suspension-strut-54651cv400
  'eb578108bb5f6e7812857f0f',
  // kia.parts | https://www.kia.parts/oem-parts/kia-suspension-strut-54651cv500
  'c44031f40259317b7daa4fc8',
  // kia.parts | https://www.kia.parts/oem-parts/kia-touch-up-paint-pen-snow-white-pearl-swp-swa-ua011tu5014swpa
  '3338d844f1e17897a1e6200b',
  // kia.parts | https://www.kia.parts/oem-parts/kia-windshield-86111cv110
  '72fa529570e3a5c695455b0b',
  // kiaautoparts.com | https://www.kiaautoparts.com/oem-parts/kia-atf-type-4-m-12-um013ch059
  'fcdbf02dc71648430a5eb2c6',
  // kiaparts.com | https://www.kiaparts.com/oem-parts/kia-sp-cvt1-fluid-um018ch130
  '81c960c8c0912c1beb8c3c8c',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-0~373003c210sj.html
  '9ed11dbe38854ffbd0cafdaf',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-0~391802m612.html
  'a7c3c10c52bde821bfd63f26',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-0~82530r0300.html
  '37f684355de0b70315333338',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-0~82540r0010.html
  '9f02854f8b7583dca4ca3c33',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-0~82540r0300.html
  'ff7bf427af1b1d5f797be4f5',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-0~92170a7000fff.html
  '36b19ce1dda81b154e859e13',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-0~97701c6950ru.html
  '356ffd1e98d2e39d8f6e2267',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-actuator-fr-dr~957303c000.html
  '31d68494fadd9508d2d889ac',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-actuator-fr-dr~957503c000.html
  '3f53816dfc0d6a2c6042f743',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-actuator-rr-dr~957703c000.html
  '44e3abb04843efda3732ab74',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-actuator-rr-dr~957803c000.html
  'f961f781a6bf470e2c6ccc38',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-bearing-strut~54612c1000.html
  'd0b0230f3859af1bd787a7cf',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-camera-assy-back-vie~99240h8000.html
  'b5bebded845c9c57d59080aa',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-canister-close~3143029200.html
  '31f3ed74954cdf6cc952dfd9',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-cap-assy-fuel-f~310103l500u.html
  'eec948b10134f401d885d59e',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-cap-assy-fuel-f~310103l600u.html
  '81b7ce59c8cb3fb2d55b87a2',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-coil-assy-ignit~273002gga0.html
  '06c5ac286ddb2ea0a49766e9',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-coil-assy-ignit~273003f100.html
  '4f7c6384c0f38d231fa2c8d2',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-coil-assy-ignit~2730126640.html
  'bbcef542b1e7ab24645a121b',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-compressor-assy~977011r100.html
  'bd4061ff4e3fc62ffa0f2fbe',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-compressor-assy~977011w600.html
  '72092dcbf8046fb543622bcf',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-compressor-assy~97701h9200.html
  'ff04a0159a708a2bb16d11a2',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-coupling-assy-4~478003b520.html
  'b6ee3048e24df8ddf41535af',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-cyl-clutch-mas~0k2a341400b.html
  '8721918d8806356f643c9038',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-disc-front-wheel-bra~51712j5500.html
  '51d8edebc5549c3e1f8dc73d',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-drive-unit-assy~834754d101.html
  '107240f4d278d8fc2f4bd696',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-drive-unit-assy~834754d102.html
  '3a206b4ea0d44e2bbd3d066f',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-drive-unit-assy~834854d102.html
  'f82d152f4126f9b21ccc2160',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-filter-assy-air~97133l1000.html
  '0ba81a90a8384a1770aded72',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-flexible-coupli~563152k000fff.html
  'ddf95eff39fdcbe8cea5ac8e',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-free-wheel-hub~0k08133210.html
  'a9b0465b921a5c8e69cdeb4f',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-generator-assy~373003c170.html
  'f2a04dfd2cdb3a26fca7aea3',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-generator-assy~373003c510sj.html
  'd3a2a5242f2de9e628bdb9c6',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-injector-assy-f~353102b130.html
  '734ca94002f04d85ab2de4df',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-injector-o-ring-kit~353122g750.html
  'b5972bd76f5e6dc7f4ec5adb',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-insulator-assy-strut~54611h6000.html
  '572a91fa9af6b19b2a22d231',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-insulator-assy~546111w000.html
  'eeeb7942d999fa94a1d4394f',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-insulator-strut~55311h5000.html
  '0749079b1e0d55aaf2198d77',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-joint-assy-strg~56400c5000.html
  '7fb91c36d172760107e6120c',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-latch-assy-fr-d~813203c001.html
  'f3a031bc87f4138ab84cc274',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-latch-assy-rr-d~814104d010.html
  '7d67929ed05788e0f8648ceb',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-latch-assy-rr-d~814204d010.html
  '5ddbb6b03f481a9b5d0049ba',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-lever-assy-panoramar~81651c5000.html
  'b7db60a6acd514af3e50fc78',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-lever-assy-panoramar~81652c5000.html
  '09ec67250b50b625f16548eb',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-manifold-cataly~285102g445.html
  'bdf5daf5ebe599cad8cf5906',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-manifold-cataly~285102gbb0.html
  '000965bf54d89f895d798696',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-oil-flow-contro~243552g000.html
  '66d1586e7ddeb68299778955',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-pad-front-spring-upr~54623f1000fff.html
  '13c52b51a4f131eedbb19d18',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-plug-assy-spark~1882311101.html
  '71078395f5038284f90185bf',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-plug-assy-spark~1884611070.html
  '0bc7258ca74988db8d147268',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-plug-assy-spark~1884711160.html
  'a3025e98856ffe3fd23d42da',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-plug-assy-spark~1884909085.html
  'db0d75fe93771d55aeca9d99',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-plug-assy-spark~1884911070.html
  '91b18e96fa9ba20b7db6ddc6',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-pump-assy-vacuum~288102m810.html
  'f9a0569b99f537aab0bbfeb5',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-pump-compt-wat~251002x401.html
  '9be055b594fb088ccf119768',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-reman-alternato~3730022650ru.html
  'c21414d29d8adf35a1c4ab92',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-reman-alternato~3730023650ru.html
  'ad35da61a06d77b8599ec062',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-reman-alternato~3730037405ru.html
  'a937c8015a0bf03d51cd57c8',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-reman-alternato~3730038310.html
  'd21aae0c86899d80fafab979',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-reman-alternato~3730039435ru.html
  '184f286fba068261c75696e8',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-reman-alternato~rk2aa18300u.html
  '99e5ea010fbf34e0b90a920d',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-roller-arm-assy~839304d000.html
  '6789d3ff833d816bab8d3a1a',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-roller-arm-assy~839304d100.html
  '009b85bcb749895578d86d7c',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-roller-arm-assy~839404d000.html
  'd2a45f88f15c050e24f87309',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-roller-arm-assy~839404d100.html
  '3b85e0f5d6124e36dee39f52',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-roller-assy-ctr~0k55273230g.html
  '43650719551881dbaf003519',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-run-assy-fr-dr-wdo-g~82530r0010.html
  'df8445d84206171b4b511ea7',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-sensor-a-t-inp~4262039051.html
  '9c32beb824968899cfc453b5',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-sensor-a-t-out~4262139052.html
  '10fb957c87346c56816deafc',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-set-double-clutch~412002d220fff.html
  '2853f433c39995702a11f258',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-switch-assy-mul~934003c520.html
  'c01c77536ec9cd0ae1d80bd5',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-switch-assy-sto~938102e000.html
  'eebc49c6609179263a406276',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-switch-assy-sto~938103k000.html
  '2ced2e19aef3eba0663f46bb',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-assy-p-so~0k30e18740.html
  'be9c02d7cc67a987e26aa6e3',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-assy-purge-control~289002gga2.html
  '51f79e939e6f6941e3c6f5ac',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-canister-close~314300w000.html
  'd9669d87d2567ddcdba4e53d',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-expansion~979162b010.html
  '8f5eb6db2491ba1b2ade037a',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-purge-con~2891022040.html
  'e33e48c8494da477cd4ab9f3',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-purge-con~2891025100.html
  'bc2f5580bb84705750c7f43f',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-purge-con~2891026900.html
  'cf793a18ace71577e637a258',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-purge-con~289103c200.html
  '8da4f22aef8bf948269591da',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-purge-con~289103l135.html
  'cbe80de9962303dc3053b815',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-solenoid~463134e602.html
  '453f09f157b8bf2ce65511af',
  // kiapartsnow | https://www.kiapartsnow.com/genuine/kia-valve-solenoid~463134e702.html
  'a388e86f0f426fddbc3f4ac6',
  // kiapartsnow | https://www.kiapartsnow.com/oem-2008-kia-rio-fuel_filler_neck.html
  '0c5c33cd21413396644c0847',
  // kiapartsnow | https://www.kiapartsnow.com/oem-kia-clutch_slave_cylinder.html
  'e943d2650d7874439983e1cf',
  // mishimoto | https://www.mishimoto.com/kia-stinger-gt-catch-can-2018.html
  '477ddf18f39ff72f54334812',
  // partlimit | https://partlimit.com/products/ac-compressor-clutch-repair-kit-coil-pulley-bearing-for-hyundai-santa-fe-xg350-kia-amanti-3-5l/ac
  '5b7f196d19dbd29dfeb4e00d',
  // partsgeek | https://www.partsgeek.com/2l3hnk3-kia-spectra-timing-belt-kit.html
  '88d5787f8e0c9d6cabdce3cc',
  // partsgeek | https://www.partsgeek.com/f4mc179-kia-amanti-alternator.html
  'f3eedce71273b55565338a97',
  // partsgeek | https://www.partsgeek.com/fnlp3hj-kia-spectra-timing-belt-kit.html
  '14e390307fd61c12e8b7987a',
  // partsgeek | https://www.partsgeek.com/hqr114y-kia-sephia-head-bolt-set.html
  '8d5e2774ed23e05b9d7246b6',
  // partsgeek | https://www.partsgeek.com/lbzdqy4-kia-sephia-timing-belt-kit.html
  '86153bb725e9bd377726ebd6',
  // partsgeek | https://www.partsgeek.com/lvq7lmf-kia-amanti-alternator.html
  '9022e0b28e6779428a8b55cc',
  // partsgeek | https://www.partsgeek.com/t7dqkyk-kia-rio-ac-compressor-kit.html
  '68feedd2d3a53209146564c4',
  // partsgeek | https://www.partsgeek.com/vllpkt5-kia-rio-strut-and-coil-spring-assembly-set.html
  '01556bf8d4a38b1f25953f61',
  // partsgeek | https://www.partsgeek.com/w6k7cr2-kia-sephia-head-gasket.html
  'cce96fffb5ce338d919e2503',
  // partsgeek | https://www.partsgeek.com/y1nwcyp-kia-spectra-timing-belt-kit-and-water-pump.html
  '4ef89ba3ff8c0a522e5bb072',
  // partsgeek | https://www.partsgeek.com/ykn5xd8-kia-rio-ignition-coil-spark-plug-and-wire-set.html
  'e22e2827005d26fca2ef2aa9',
  // partssource | https://www.partssource.com/parts/krytox/GPL20535RU37
  '21eb1762119bfe08d7a7aaec',
  // quirkparts | https://www.quirkparts.com/oem-parts/hyundai-snap-ring-410682d000fff
  '011c394fe17ffd8ab8d95d37',
  // r&y a/c compressors | https://www.rycompressors.com/shop/2009-kia-amanti-fh313-282181.html
  '350dac2b65a5e02165ba28f3',
  // steeda | https://www.steeda.com/bg-products-709-frigi-clean-kit
  '3fb5fd75caa32fee5d9d4138',
  // tasca parts | https://www.tascaparts.com/oem-parts/kia-oil-pressure-sending-unit-947513c000
  'd1d6dbacdfe10c8887cb4204',
  // the rust store | https://www.theruststore.com/products/fluid-film-11-75-oz-aerosol
  '644d3819fcb1ae2ec104cb1e',
  // tunersports | https://www.tunersports.com/brembo-oe-p30113n-ceramic-pads-p503423.html
  '930cd4d352d7a3ba953b7255',
  // walmart | https://www.walmart.com/ip/36019107
  '96485697292687d583b45621',
] as const;

export const retailerHostFingerprints = [
  // am-autoparts.com
  '1fd199dde0d1cf3ed07c1cc3',
  // anker.com
  'd4f0a3850a5f3bf23e2b65f1',
  // apple.com
  '95843ba3c02af90c2166f2a4',
  // autopartsprime.com
  'b6e04d2c3d46d1504d717b52',
  // autozone.com
  '12fa1f440ebfbfd1c0ab1b19',
  // buyautoparts.com
  '09a4b19765e53ad3defeea3e',
  // carid.com
  '94c5b484782a92c151da35b7',
  // carparts.com
  'cb39b9c3d06e48b637584a8e',
  // esrtech.com
  '82cf81ffbc06a6f50fe13877',
  // finditparts.com
  '7e08600bd0825315e1f077e2',
  // goturbo.net
  '82775127399373f691001c7b',
  // happymotorshop.com
  'edea1595e6612cce4b047471',
  // homedepot.com
  'a03f561e5a26554b4a3e07bf',
  // kia.oempartsonline.com
  '21a86e6fa54b3de2219958a6',
  // kia.parts
  'b404ecf3878828b938988749',
  // kiaautoparts.com
  '5d38a84e9d9c6cd5b3a5a0d0',
  // kiacheapparts.com
  'b18af241e344d068bfa0a817',
  // kiaparts.com
  'a90bad26e1479cc2423ef1d6',
  // kiapartsnow.com
  'c3f7fdeff37d1fce90f0d3d1',
  // kiapartsonline.com
  '4fb9ef4902a728e77d529d93',
  // mishimoto.com
  'f7496592c50882509b95b52a',
  // partlimit.com
  '79415640bcd0d25efbaea8f1',
  // partsgeek.com
  'b6c9d443e05ef437cef78a38',
  // partssource.com
  'ecda5fc9304235dfd005e71b',
  // quirkparts.com
  'c72749d3ca75db4654e28bfe',
  // rycompressors.com
  '75f738aee4076e1d32825648',
  // shop.advanceautoparts.com
  '3d7f5ea36b6847e33e997fca',
  // shop.app
  '8264f44637fa533f2f79a4e4',
  // steeda.com
  'ffbe5f4faa41c80b759b01f1',
  // tascaparts.com
  'dc7dcf27ad7e3a67eca2e5f6',
  // theruststore.com
  'a3eab909b47445e6a5f2e6f1',
  // tunersports.com
  '1a668c63b3cfa3fb3c508a73',
  // walmart.com
  'ce624b6b31766d560320dd93',
] as const;
