// GENERATED by scripts/build-repair-first-verified-batch.mjs for Land Rover.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://3brothersclassicrovers.com/collections/series-1-steering/products/standard-swivel-ball-oil-seal-rebuilders-kit-series-1954-84
  '2b9305d0ddd0a694f678f212',
  // https://3brothersclassicrovers.com/products/oil-seal-for-rear-hub-series-1-semi-float-axle-1948-58
  'd18d6e76e38e075135c34fbc',
  // https://antipodeanparts.com.au/products/spring-hanger-narrow-springs-front-and-rear-series-1-80
  '7afe8d445885620840c71aba',
  // https://ashcroft-transmissions.co.uk/product/mt82-output-shaft-kit/?add-to-cart=77991
  'eb7e847a0194a3b2f15e4e64',
  // https://ashcroft-transmissions.co.uk/product/r380/
  '68616350c684134295cb3858',
  // https://bmiparts.com.au/product/gasket-fuel-tank-sender-unit-series-lr
  '193ab27a09a5b52905576679',
  // https://britcar.com/product.php/95563/316/fuel_sender___unit_under_seat___land_rover_series_11_and_111
  '8fe51f77b3686e9f2bfdaf1c',
  // https://ckdshop.co.uk/product/master-cylinder-kit-107-109/
  '5510a7ff5397b9390c70b48b',
  // https://ckdshop.co.uk/product/master-cylinder-kit-80/
  '4ed9fd0c70ec3e81f2e26cda',
  // https://ddsmetal.co.uk/shop/90-110-td5-gearbox-cross-member-1998-2006-bolt-on-kvb500060/
  '44a4757d362281aa2257ce36',
  // https://embertonimperial.com/en-us/products/land-rover-series-2a-3-defender-bulkhead-ventilation-flap-seal-set-jae00003-x2
  '9c6777d936fab38a1b8cf823',
  // https://embertonimperial.com/en-us/products/land-rover-smiths-round-heater-motor-blower-fan-oem-series-1-2-2a-2b-swb-89
  '2ba0a74f32a7d23dbd9a9151',
  // https://embertonimperial.com/en-us/products/land-rover-steering-box-rebuild-kit-series-1-2-2a-reconditioning-set-bearings
  'd07e85df8e3812e652f7e928',
  // https://embertonimperial.com/products/land-rover-headlight-ignition-switch-key-genuine-lucas-oem-217589-series-1-80
  'ee585f97c57f131d13786de5',
  // https://embertonimperial.com/products/land-rover-series-1-80-12v-lucas-cw-cw1-cwx-windscreen-wiper-motor-unit-231554
  '3583d7d96db6ce41f6585596',
  // https://landrovertreasureshop.com/product/243141-genuine-front-rh-half-shaft-land-rover-series-i/
  '1f8070435404575ddf88e32e',
  // https://landrovertreasureshop.com/product/528703-layshaft-gearbox-land-rover-series/
  'bb3ccda555aca6a3b8912034',
  // https://landrovertreasureshop.com/product/land-rover-ignition-headlight-switch-complete-series-1-2-239570/
  'a67c7c699f220903f6cb0fc4',
  // https://lofclutches.com/shop/clutches/land-rover-clutches/defender/roadspec-tdci-puma-inc-flywheel/
  '91840b7ca80cf9f5674c42d9',
  // https://lucky8llc.com/collections/lr2/products/thermostat-housing-gasket
  'a6ebafcc88991231dbe1c337',
  // https://lucky8llc.com/collections/lr3-air-compressors/products/air-suspension-compressor-4
  '31d76572209a2a242dba68d5',
  // https://lucky8llc.com/collections/lr4-air-compressors/products/air-suspension-compressor-kit
  'a2fc75e51e1253dd11375f30',
  // https://lucky8llc.com/products/floor-mounted-dip-switch
  '8432530edb59d79afaf56e55',
  // https://lucky8llc.com/products/fuel-lift-pump-2-25-diesel
  'c9e88520f1e33c329922abcf',
  // https://lucky8llc.com/products/heavy-duty-steering-arm-drag-links-tie-rods
  '17fae39b21887d206ab03dba',
  // https://lucky8llc.com/products/stepper-motor-idle-air-valve
  'bb75e41701bd83bdeb459cb1',
  // https://msport-direct.co.uk/product/classic-valvemaster-lead-replacement-fuel-petrol-additive-250ml-treats-250l/
  '9ac8d128a4d43bf52c9d3e43',
  // https://qualitysuperchargers.com/products/genuine-eaton-oem-supercharger-rebuild-kit-snout-case-bearings-5-0-3-0-jaguar-land-rover-range-rover
  '20639ec18f9decadc0acfb55',
  // https://qualitysuperchargers.com/products/genuine-oem-supercharger-rebuild-repair-jaguar-land-range-rover-5-0-peek-47mm-2010-2014
  '0eb453d9d890d25ea6e1df2b',
  // https://rimmerbros.com/Item--i-CVH101150P
  'e995a441e2808fd946237692',
  // https://rimmerbros.com/Item--i-CVH101202P
  '67bd07e8d0758462d5952df4',
  // https://rimmerbros.com/Item--i-CVH101212P
  'ed67563bcdb45716be04be50',
  // https://rimmerbros.com/Item--i-LCN000140L
  'ca576a800c19d9fbc7f8735d',
  // https://rimmerbros.com/Item--i-LDN10027P1SET
  'b5bb06f1f4b96fe20977b940',
  // https://rimmerbros.com/Item--i-LR004405
  'd7ef65c107c2509ef641906f',
  // https://rimmerbros.com/Item--i-LR006371P
  '81c01b110247807fb6738774',
  // https://rimmerbros.com/Item--i-LR006372P
  '9feba20dd961b449ded9e66d',
  // https://rimmerbros.com/Item--i-LR033256
  '439a8562ffe2ffbee00d9706',
  // https://rimmerbros.com/Item--i-LR033257
  '9bf62bfe9690b91472538711',
  // https://rimmerbros.com/Item--i-LR098914
  'd35527e8f897cd0383c20a55',
  // https://rimmerbros.com/Item--i-LVB500190A
  'f29253b571ccb5b7de4a2959',
  // https://rimmerbros.com/Item--i-NRC1269P
  'dad5b45e20bd10976212a58b',
  // https://rimmerbros.com/Item--i-PEM000030PK
  'bcb6f4a6bbf798b799130335',
  // https://rimmerbros.com/Item--i-WAM2293KIT
  '7982f3e315074996893abe91',
  // https://rimmerbros.com/Item--i-ZUA001480
  '751cb305ea42942bb024b714',
  // https://safari-engineering.co.uk/new-land-rover-parts/repair-service-parts/transmission-parts/gearboxes/output-shaft-oil-seal-front-rear-series-1-series-2-series-3-frc1780
  '6d5984bfb1d0c3f6a36b2c92',
  // https://seriesparts.co.uk/PartDetail?stockid=2127
  '3b80f7e1f954fae8d92ef098',
  // https://shielderchassis.com/products/defender-110-200tdi-2-5td-2-5na-galvanised-bulkhead
  'ebcd50c10577719b340ac753',
  // https://shielderchassis.com/products/defender-110-300tdi-galvanised-bulkhead
  '753da880f2eb594b936663f2',
  // https://shielderchassis.com/products/defender-110-v8-galvanised-bulkhead
  '45d6046a953208159a12b7cc',
  // https://shielderchassis.com/products/defender-130-200tdi-2-5td-2-5na-galvanised-bulkhead
  'd1563709a0ce35a6f98daa97',
  // https://shielderchassis.com/products/defender-130-300tdi-galvanised-bulkhead
  '2579a5b3356214479d894be0',
  // https://shielderchassis.com/products/defender-90-200tdi-2-5td-2-5na-galvanised-bulkhead
  '1bbd0ab0f1e55979b3b8a031',
  // https://shielderchassis.com/products/defender-90-300tdi-galvanised-bulkhead
  '4ace28e055e6087921c99b77',
  // https://shielderchassis.com/products/defender-90-v8-galvanised-bulkhead
  'ed77a475230f5f8696e1bab9',
  // https://shielderchassis.com/products/land-rover-series-2a-88-109-inch-galvanised-bulkhead
  '1521892c390d8a9dbd57c536',
  // https://toni-einspritzpumpenservices.de/produkt/einspritzpumpe-land-rover-225l-dpa-3249f751-3249f750/
  '7e54a7fca36abc378d86e692',
  // https://twinwoods4x4.com/product/defender-swivel-housing-kit-non-abs-ga3179g-da3179g/
  'f0831363c2875a96886da767',
  // https://twinwoods4x4.com/product/lqx100130-td5-oil-pump-chain-sprocket/
  '0977871d74cae2218223565e',
  // https://twinwoods4x4.com/product/td5-oil-pump-bolt-discovery-defender-lyp101400-lyg101210/
  'a34f36b799b967798293b3e4',
  // https://vitesse-ltd.co.uk/product/shock-absorber-series-88-front/
  'e8e00305ff19efc91340e552',
  // https://vitesse-ltd.co.uk/product/timing-chain-kit-2-25-pet/
  '54ba0bc7577e401e8d928d22',
  // https://www.airsuspension.com/products/arnott-new-front-left-air-spring-03-12-land-rover-range-rover-l322
  'a7e99d4341ff27ec0b245fdd',
  // https://www.airsuspension.com/products/arnott-new-front-right-air-spring-03-12-land-rover-range-rover-l322
  'ccf01d32699ccdd73c030091',
  // https://www.airsuspension.com/products/arnott-new-rear-air-spring-03-12-land-rover-range-rover-l322-left-or-right
  '345f8269ac03fc052483f44b',
  // https://www.airsuspension.com/products/rear-air-spring-13-22-land-rover-range-rover-l405-lt-rt
  '69d563a80e7e56e1eeb0c2d1',
  // https://www.angclassiccarparts.co.uk/products/landrover/defender-series-8890110-discovery/engine/fuel-pump-repair-kit-ac-delco-land-rover-series-ii-iii-225-petrol
  'e27784578676b3ffa5db43fe',
  // https://www.autoelectricsupplies.co.uk/p/landrover-1948-54
  'e3fbcb7b22f7f45fa91438a5',
  // https://www.autoelectricsupplies.co.uk/p/lucas-c40
  'a209cf576d4203ddff94c06a',
  // https://www.automec.co.uk/products/brake-pipe-set-land-rover-series-1-80-rhd-1948-1958-gb5600
  '29ac2600141d477928b17819',
  // https://www.autosparks.co.uk/land-rover-series-1-wiring-harness-set-10
  '1b03aa084032a61e0f803c7c',
  // https://www.autosparks.co.uk/land-rover-series-2-wiring-harness-set-10
  'caf93a32e36c0a1073faf9ba',
  // https://www.bearmach.es/en/productos/3/land-rover-parts/producto/13853/270225/
  'b42fa9c80864a04a52b25ae6',
  // https://www.bellengineering.co.uk/product-page/haldex-5-pump
  '43282a0c771d7c81daf3816d',
  // https://www.bellengineering.co.uk/product-page/haldex-5-unit
  '8ab89cff8f61dc99ac42f539',
  // https://www.bellengineering.co.uk/product-page/haldex-module
  'fceacb82a15d5c2658be732c',
  // https://www.bellengineering.co.uk/product-page/land-rover-freelander-1-reconditioned-ird-4wd
  'a2182fc461a67b3feca86947',
  // https://www.bellengineering.co.uk/product-page/land-rover-freelander-1-reconditioned-vcu
  '0512950f4aabe5510b36ea77',
  // https://www.britishautoparts.com.au/inc/sdetail/23951
  '0304471d36b59ae7f8062896',
  // https://www.britishparts.co.uk/land-rover/discovery-5-l462/steering-suspension/height-sensor-rear-lr098915-land-rover
  '15d2638cd41865956c6c29ce',
  // https://www.britishparts.co.uk/land-rover/series-1-2-2a-3/engine-petrol/camshaft-247709
  '7bf8e08f72ab9ccd1cbd0cf9',
  // https://www.britishwiring.com/Land-Rover-Series-2A-Main-Wiring-Harness-p/lr202pb.htmCartID%3D1?CartID=1
  'a30b2031c3a38ed671695e9a',
  // https://www.britishwiring.com/Land-Rover-Series-2A-Main-Wiring-Harness-p/lr203pp.htm
  '7dcef7f0686145dfc0204601',
  // https://www.britishwiring.com/Land-Rover-Series-2A-Main-Wiring-Harness-p/lr212pb.htmCartID%3D1?CartID=1
  '85b7032bbb809c2c48823e6c',
  // https://www.britishwiring.com/Land-Rover-Series-2A-Main-Wiring-Harness-p/lr213pb.htm
  '82ae6c127f50077f212759ed',
  // https://www.brookwell.co.uk/product/aftermarket-mainshaft-oil-seal-236305
  '9af4eb0418d2af685afe609b',
  // https://www.brookwell.co.uk/product/aftermarket-rear-crankshaft-seal-set-542494
  'ebb47b683674e056f6d772c2',
  // https://www.brookwell.co.uk/product/aftermarket-seal-swivel-bearing-housing-rtc3528
  '293e5d7f88d0bf4498db4d76',
  // https://www.brookwell.co.uk/product/britpart-earth-lead-gearbox-chassis-575184
  'f6b7c296c8312b4ae879d69a',
  // https://www.brookwell.co.uk/product/girling-wheel-cylinder-seal-kit-275744
  'b7ad090340ff161b77ff269f',
  // https://www.brookwell.co.uk/product/gkn-universal-joint-rtc3346
  'ca823ae4feff6f27be92bd79',
  // https://www.copperbraid.co.uk/product/copper-braid-earth-strap-50-mm2-250-amps/
  '2b7855f9fa14bf31065f88b2',
  // https://www.designdevelopmenteng.co.uk/shop/Land-Rover-Series-One-80-LHD-Steering-Box-Kit-p488889168
  '108c3ca6e17dbdd006f669b7',
  // https://www.designdevelopmenteng.co.uk/shop/Land-Rover-Series-Relay-Mounting-Plate-CNC-Machined-p389433979
  '747196400c9419ae62760445',
  // https://www.dingocroft.co.uk/acatalog/Brake-Master-Cylinder-268982.html
  '14851c379686010b3b275956',
  // https://www.dtc-uk.com/product/duralac-anti-corrosive-jointing-compound/
  'c5e504cbd1b1d4deb70ac88c',
  // https://www.ebay.co.uk/itm/355363261499?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'f40e5e2865d67aa60d376d83',
  // https://www.empiretuning.co.uk/product/oem-td5-injector-harness-rocker-gasket-amr6103g/
  '758c871d35a1bbd87e2460bd',
  // https://www.engelimports.com/en/water-pump/363939/
  'ebd1bd7cc5d12a1c5baa04ae',
  // https://www.famousfour.co.uk/new_parts/ff_part?part=16686
  'de8204a9a29b23a63b1ce5b6',
  // https://www.jgs4x4.co.uk/defender-swivel-housing-repair-kit-with-swivel-housing-da3167/
  '76570ebec0fdd67b4fce2f44',
  // https://www.jgs4x4.co.uk/gearbox-bearing-kit-for-series-ii-and-series-iia-suffix-a-da3361/
  '86bf10ed76196951e9cf3d09',
  // https://www.jgs4x4.co.uk/land-rover-series-rear-mainshaft-oil-seal/
  '39ca2dafddf79199f06de3c8',
  // https://www.jgs4x4.co.uk/series-2-2a-gearbox-bearing-kit/
  '8d466bc1a9951f44d12731b1',
  // https://www.johncraddockltd.co.uk/213340-oil-seal-for-steering-relay-landrover-1948-84.html
  'db3fae12b1045570c97ef99b',
  // https://www.johncraddockltd.co.uk/217290-genuine-driveshaft-front-tractajoint-1948-53.html
  '3aa4a0fd0251f748cd731174',
  // https://www.johncraddockltd.co.uk/218020-fuel-tank-80-inch-1948-53.html
  'cd654de893ff23f3609fd076',
  // https://www.johncraddockltd.co.uk/219007-brake-linings-and-rivets-for-handbrake-shoes-1948-64.html
  '92d8f33fadaff56e27e32426',
  // https://www.johncraddockltd.co.uk/219824girling-girling-brake-hose-front-and-rear-1948-53.html
  'f8d6746e6b3d5b5ec563dc82',
  // https://www.johncraddockltd.co.uk/235006-master-cylinder-80-inch-1948-53-non-genuine.html
  'd4d66d43a8025a83ac3a6ffc',
  // https://www.johncraddockltd.co.uk/236630-genuine-flange-rear-output-shaft.html
  '1b4d6ec92a00b5b9d4b6c03f',
  // https://www.johncraddockltd.co.uk/241687-r-master-cylinder-s-w-b-1954-58-non-genuine.html
  '892ab5a4feb3d29aba8555b4',
  // https://www.johncraddockltd.co.uk/244711-pinion-assy-starter-motor-1955-84-all-4-and-6-cylinders.html
  '4211420480c5963b1c4cc10b',
  // https://www.johncraddockltd.co.uk/260055-brush-set-starter-motor-1948-72-2-brushes-2-pair-are-fitted-to-starter-motor.html
  '722bc448bf55b456c9492b42',
  // https://www.johncraddockltd.co.uk/260550-genuine-land-rover-diaphragm-fuel-pump-1948-58-48-58.html
  '61900cbe0331bec87e50c6e9',
  // https://www.johncraddockltd.co.uk/261256-lucas-dynamo-brush-set-type-c45-2-litre-diesel.html
  '5113e6deb6ebfa190a00fa8f',
  // https://www.johncraddockltd.co.uk/261483-brush-set-for-dynamo-c39-type.html
  'bd409c88262d2b90a365a632',
  // https://www.johncraddockltd.co.uk/262102-head-gasket-set-1951-55-2-litre-petrol.html
  '114b1c444b01b34a63f644bb',
  // https://www.johncraddockltd.co.uk/268038-bottom-hose-1948-58-also-use-as-top-hose-and-cut-to-suit.html
  'a5e2a6344af503118814ee61',
  // https://www.johncraddockltd.co.uk/270604-wheel-bearing-rear-1948-58.html
  '4679dfb9413a45d71197404b',
  // https://www.johncraddockltd.co.uk/274423-handbrake-drum-all-models-up-to-1984.html
  '659b14b5a4026983eb9047cb',
  // https://www.johncraddockltd.co.uk/307421-rubber-bulkhead-to-screen-1954-58-lentgh-is-60-5-inches.html
  '8fb72946fd57fd134ebd8854',
  // https://www.johncraddockltd.co.uk/320902-track-rod-end-lh-thread-1948-to-july-1974.html
  '66ed63b63d6ba8c220cdddd8',
  // https://www.johncraddockltd.co.uk/503754-brake-master-cylinder-overhaul-kit-109-inch-1958-66-cb-type.html
  'c014c70977981b526108d5a9',
  // https://www.johncraddockltd.co.uk/507687b-carburettor-rebuild-kit-solex-1958-67-includes-butterfly-and-spindle.html
  'e4483e7ebb869267e6005a4d',
  // https://www.johncraddockltd.co.uk/535649-head-gasket-2-litre-diesel-1956-61.html
  'a025e452a5bf82397da58c2f',
  // https://www.johncraddockltd.co.uk/591704-clutch-plate-9-inch-for-land-rover-1950-69.html
  '195211700a4ae99128ca33ce',
  // https://www.johncraddockltd.co.uk/602687-thermostat-series-1-and-v8-2-5d-and-2-5td-and-90110-petrol-4-cylinder-82-degrees.html
  '800dd2aa59bc21476345fbd0',
  // https://www.johncraddockltd.co.uk/7297l-jc3-collar-retaining-halfshaft-bearing-series-1-rear-1948-58.html
  'cb061d681cc031868d8591f5',
  // https://www.johncraddockltd.co.uk/grc115-radiator-cap-series-1-petrol-1948-58.html
  '63a780dc1c27e22889ab68cc',
  // https://www.johncraddockltd.co.uk/jc10086-r-jc3-series-1-dumb-iron-front-chassis-rh-1952-to-1955.html
  '6d3e37e9ceda4eb4366bd4a8',
  // https://www.johncraddockltd.co.uk/jc10086l-jc3-series-1-dumb-iron-front-chassis-lh-1952-to-1955.html
  '148fe71dd8aa885647b2fa87',
  // https://www.johncraddockltd.co.uk/jc159-jc3-rear-crossmember-for-series-1-1948-53-exact-replica-of-the-original-in-2mm-steel-and-bsf-fixings-comes-with-body-tags-both-types-and-chassi.html
  '7bfd4578e84cefb7baae165a',
  // https://www.johncraddockltd.co.uk/jc695-r-door-pillar-repair-panel-rh-1954-58.html
  '8b8f89797fd281f2deb1190d',
  // https://www.johncraddockltd.co.uk/jc695l-door-pillar-repair-panel-lh-1954-58.html
  '9f79f80e024ec292ccde1df2',
  // https://www.johncraddockltd.co.uk/jc7039-jc3-rear-crossmember-for-series-1-1954-58-this-item-is-an-exact-replica-of-the-original-in-2mm-steel-and-bsf-fixings-comes-with-body-tags-and.html
  'af7815e3c09a8620c25078f7',
  // https://www.johncraddockltd.co.uk/jc86-top-section-bulkhead-series-1-1954-58.html
  '6778a5bfaac559810e5d2123',
  // https://www.johncraddockltd.co.uk/jc93-footwell-repair-panels-series-1954-58-1-pair.html
  '7d8792adec7b54dc33fdc13b',
  // https://www.johncraddockltd.co.uk/rtc2990-crown-wheel-and-pinion-1950-84-see-ftc3586-for-bolts.html
  '21498f4ff7f5f588d4e59c4c',
  // https://www.limora.com/nl/adapter/364292/
  '18af51aa3e515c27f81911f6',
  // https://www.limora.com/nl/weber-carburateur/312818/
  '767267d98c513cb9717f48da',
  // https://www.lrdirect.com/549761-fuel-pump?sort_direction=1
  '54390780e30538803047ace7',
  // https://www.lrdirect.com/564706-brake-master-cyl-lwb-cb
  '66bc09ad8fed90834fc3bae5',
  // https://www.lrdirect.com/571235-drive-flange-hub-10-spline
  'ae0770de5ed7294aa266ef08',
  // https://www.lrdirect.com/591378-halfshaft-ser2a3-r-h-10-spline
  '390c957a1ca78c63f31b422d',
  // https://www.lrdirect.com/90517429-tappet-roller-2-25-2-5pddt
  '1dda146aa5a685c6c535dbee',
  // https://www.lrdirect.com/frc1644-halfshaft-swb-late-ser3-rh-24-sp
  'a932fb1ad7b31fde0dcc225e',
  // https://www.lrdirect.com/frc1645-halfshaft-swb-late-ser3-lh-24-sp
  'ecd6e6fdd446990dce8ecf58',
  // https://www.lrdirect.com/FRC1758-Synchro-3Rd-And-4Th-S2-3-Suff-A-B/
  'c3691a7872070ea215713858',
  // https://www.lrdirect.com/FRC1780-Oil-Seal-Output-Shaft-and-Transfer/
  '27cbcc9f27f0181a6d055fff',
  // https://www.lrdirect.com/lr027158-thermostat-and-hsg
  '8b07c65628d1706b49607fd8',
  // https://www.lrdirect.com/lr091586-pump-fuel
  '61c257364fcefdeb33f55020',
  // https://www.lrdirect.com/nsc500160-sensor-crankshaft-position
  '4ae6fdc2bad162f69143ccc9',
  // https://www.lrdirect.com/stc121-propshaft-front-swb
  'e1abc350cc397a5e7cb6611a',
  // https://www.lroe.co.uk/235553
  '4e9d60ae162ea5c0076a84ef',
  // https://www.lroe.co.uk/520849
  'f124bba600913da3d81286d0',
  // https://www.lroe.co.uk/products/RTC7136-Service
  '763a5f5b90135bb8ed63b79e',
  // https://www.lrparts.net/274423-handbrake-transmission-brake-drum-for-land-rover-series-2-2a-3.html
  'f1aa426dc7cdc98518dde791',
  // https://www.lrparts.net/3649-selector-shaft-detent-spring-for-land-rover-series-2a-3-priced-individually.html
  '0be4ab902f5c48704971475d',
  // https://www.lrparts.net/521328-thrust-washer-for-intermediate-shaft-on-land-rover-series-2a-3.html
  'a3b3901bc93d09f82e9cac6f',
  // https://www.lrparts.net/542492-rear-main-oil-seal-kit-for-land-rover-series-2-25-3-crank-bearing.html
  'bb4c84c719b0c1333637ae96',
  // https://www.lrparts.net/591379-rear-half-shaft-left-hand-for-short-wheel-base-land-rover-series-up-to-1980-10-spline.html
  '89833c41d6b597b659b21fac',
  // https://www.lrparts.net/595123-steering-drop-arm-for-land-rover-series-2a-3.html
  'af4ef69d8115616ac495583b',
  // https://www.lrparts.net/90217512-bearing-for-rear-output-shaft-on-land-rover-series-2a-3-transfer-box.html
  'b102e04d1cb9773337d148f9',
  // https://www.lrparts.net/as144-uprated-alloy-radiator-for-land-rover-series-2-3-with-2-25-petrol-by-allisport.html
  'a9105b650d0be75d86e58ab7',
  // https://www.lrparts.net/da1236-steering-box-repair-kit-for-land-rover-series-2-2a-and-3.html
  '2438edc1e3d91e1870d1bbd9',
  // https://www.lrparts.net/da2112-1-defender-and-discovery-td5-cylinder-head-set-complete-with-everything-needed-including-one-hole-head-gasket.html
  '28ada5214ca9a3810b10e551',
  // https://www.lrparts.net/da2112-2-defender-and-discovery-td5-cylinder-head-set-complete-with-everything-needed-including-two-hole-head-gasket.html
  '50ad41b46a61b26bccf7729e',
  // https://www.lrparts.net/da3178-swivel-housing-kit-for-defender-1994-1998-swivel-housing-ball-bearings-seals-pins-and-gaskets.html
  'e0963df59d993d76c59c815e',
  // https://www.lrparts.net/da3416-fai-timing-chain-kit-for-5-0l-aj133-3-0l-aj126-engines-range-rover-range-rover-sport-discovery-4-discovery-5-range-rover-velar-land-rover-defender-2020.html
  'bf1803d156389397b80a61a8',
  // https://www.lrparts.net/da5164-gen-5-haldex-service-kit-discovery-sport-range-rover-evoque-2016-onwards.html
  '7470aed784461fd06ead2dbf',
  // https://www.lrparts.net/da7215-transfer-box-repair-kit-fits-dd295-transfer-boxes-range-rover-sport-2005-2013-discovery-3-4.html
  'ef8463aab44457dfff3be41c',
  // https://www.lrparts.net/err2803-thermostat-for-200tdi-discovery-and-defender.html
  'b707d23c6855e5c07012b9c7',
  // https://www.lrparts.net/err5384-cylinder-head-bolt-for-defender-and-discovery-td5-essential-for-head-gasket-job-12-needed-to-complete-job.html
  '5d8a5569da05819f9fb8f795',
  // https://www.lrparts.net/etc7238-viscous-unit-for-coolant-fan-water-pump-on-200tdi-defender-and-discovery.html
  'bc33687d5b43c5aa45725049',
  // https://www.lrparts.net/frc1780-seal-for-front-rear-output-shaft-on-land-rover-series-2a-3.html
  '3a30bd2339242d73a77c093f',
  // https://www.lrparts.net/front-crankshaft-oil-seal-for-300tdi-defender-discovery.html
  'f1a4eec0190ed2bd07adca87',
  // https://www.lrparts.net/iab500280-chain-for-transfer-box-on-range-rover-l322-range-rover-sport-2005-2013-and-discovery-3-4.html
  'bd12d5be9ecfa57df07f7a6f',
  // https://www.lrparts.net/igh500040-transfer-box-motor-assembly-fits-range-rover-l322-l405-range-rover-sport-and-discovery-3-4.html
  'e70f317361f93a9127ab135c',
  // https://www.lrparts.net/iyk500010-trasnsfer-box-fluid-for-land-rover-discovery-3-4-and-range-rover-sport-from-2002-onwards-1-litre-tf-0870.html
  '99847334861219770378035d',
  // https://www.lrparts.net/lr004381-gasket-for-vacuum-pump-on-defender-2-4-puma-duratorq-engine.html
  '82fdc6b6ec040b7c4ada9ca6',
  // https://www.lrparts.net/lr018752-egr-valve-and-cooler-assembly-left-hand-for-3-0-tdv6-fits-3-0-diesel-discovery-4-5-range-rover-sport-2009-2019-and-range-rover-l405-genuine-land-rover.html
  '0231a9f727c599ff1c0ad4a9',
  // https://www.lrparts.net/lr023440.html
  '180553aad456fc132d9064f0',
  // https://www.lrparts.net/lr023442-rear-diff-pinion-oil-seal-for-freelander-2-discovery-sport-and-range-rover-evoque.html
  'b8eefabc32df31c7b58335db',
  // https://www.lrparts.net/lr038601.html
  '87ea89a7d6191eb103b871ef',
  // https://www.lrparts.net/lr038602-freelander-2-in-tank-fuel-pump-and-sender-right-hand-for-2-2-diesel.html
  '7a1557dbf291948367fa2a75',
  // https://www.lrparts.net/lr044088-defender-vacuum-pump-seal-for-puma-2-2-engines.html
  '968208acf13a5e6333879a2d',
  // https://www.lrparts.net/lr105975-thermostat-and-housing-for-2-0-diesel-ingenium-range-rover-evoque-mk1-and-discovery-sport.html
  '29def33e15b4759400859d32',
  // https://www.lrparts.net/lr108660-pump-vacuum.html
  '9355acab51ded29389755060',
  // https://www.lrparts.net/lr174475-rear-diff-pinion-seal-for-range-rover-l322-sport-l405-velar-and-discovery-3-4-5.html
  '2c8f6a3b6615af21be7ab904',
  // https://www.lrparts.net/lrc1021-front-and-rear-shock-absorber-kit-for-land-rover-series-for-swb-88-series-2-2a-3-by-boulder-ridge.html
  'db56fd9863fcc3c2c8473630',
  // https://www.lrparts.net/lrc10491-front-and-rear-shock-absorber-kit-for-land-rover-series-for-lwb-109-series-2-2a-3-by-boulder-ridge.html
  'fa5a792a56423201117468c7',
  // https://www.lrparts.net/lrc1393-defender-300tdi-full-clutch-kit-by-borg-beck-including-clutch-plate-cover-release-bearing-hd-fork-rear-crank-seal-and-fitting-clips.html
  '40635bd7552635b7fb07cba3',
  // https://www.lrparts.net/lrc2319-land-rover-series-track-rod-end-kit-six-piece-ball-joint-kit-for-series-2-2a-3-please-note-these-don-t-have-greaseable-nipples.html
  'f21f576c609363afa55ee072',
  // https://www.lrparts.net/lrc3459-land-rover-series-handbrake-adjuster-kit-with-brake-shoes-and-springs-also-includes-expander-seals-shim-and-pins.html
  '1c50c69d16de2c63d463318e',
  // https://www.lrparts.net/lrc9885-shielder-galvanised-bulkhead-for-land-rover-series-3-88-109-heavy-duty-single-skin-1-5mm-bulkhead.html
  'c0e14153db984c91db1eb07a',
  // https://www.lrparts.net/lvb000260-td5-cylinder-head-gasket-for-defender-and-discovery-3-holes-1-35mm.html
  '8809837ca2584ea42d98e3a5',
  // https://www.lrparts.net/nrc1269-steering-relay-for-land-rover-series-1-2-2a-3.html
  '63c251fc4c0322372012427c',
  // https://www.lrparts.net/pcc001020-pdk000100-radiator-for-land-rover-defender-fits-puma-2-4-2-2-and-td5-engines-fits-from-1998-onward.html
  'a858948d92bc389a41021cf2',
  // https://www.lrparts.net/pcd100160-defender-expansion-tank-cap-for-td5-and-puma-engines-also-fits-freelander-up-to-2003.html
  '657810e68c7e9da0155d188e',
  // https://www.lrparts.net/pel500110-thermostat-for-defender-td5-puma-and-discovery-td5-in-plastic-casing-82-degree-also-fits-freelander-1-k-series-1-8-petrol.html
  '687cdb6cb13318fc1e785dad',
  // https://www.lrparts.net/pet100790-water-pump-p-gasket-for-300tdi-fits-defender-discovery-1-and-range-rover-classic.html
  '9930582e5a16771b80bc1d3d',
  // https://www.lrparts.net/pgg500340-viscous-coupling-and-fan-for-defender-td5-and-puma-up-to-ca000001-chassis-and-discovery-td5.html
  'cbd6cec14b36df80e315176a',
  // https://www.lrparts.net/stc1116.html
  'c326b66ade7f1cf994eda8ec',
  // https://www.lrparts.net/stc1190-fuel-lift-pump-for-defender-naturally-aspirated-turbo-diesel-and-all-200tdi-defender-discovery.html
  '80627eef8af7fa00a8910561',
  // https://www.lrparts.net/stc639-engine-coolant-water-pump-for-defender-200tdi.html
  '3fad220db9686643f6089383',
  // https://www.lrparts.net/steering-relay-split-bush-2a-3.html
  '4bb7f4fa98dd7c2de3967137',
  // https://www.lrsoc.com/web/product/lr302300/
  'b12a96ee8078d3210576ee3e',
  // https://www.oldtimerbedarf.de/Spannungsregler-10V-elektronisch-Retrogehaeuse-negative-Masse-MGB
  '18284700cb0777ed62597b17',
  // https://www.onlinegearboxparts.com/product/lt76-overhaul-kit-main-box/
  'de22ee2c278e4a03b693b2bb',
  // https://www.onlinegearboxparts.com/product/series-3-lt76-overhaul-kit-transfer-box-minus-2-x-thrust-washers/
  '9249cac95c2b9f3ccd3fe859',
  // https://www.paddockspares.com/539741-swivel-chrome-ball.html
  'b61c3bc1672cea3426914dc5',
  // https://www.paddockspares.com/569339-brake-master-cylinder-single-line-servo-round-reservoir.html
  'ad4668ed936d9b38bb7a8b73',
  // https://www.paddockspares.com/591378-rear-halfshaft-rh-all-s2-2a-swb-to-80-81-10spline.html
  'eb0e3423491cfd9df7dc2ed3',
  // https://www.paddockspares.com/608464-ball-joint-rh.html
  'daec1d6b2adbdaca6395a351',
  // https://www.paddockspares.com/para01-front-parabolic-springs-pair-2-leaf.html
  'fdd4a54117192f6c40a04d57',
  // https://www.paddockspares.com/para02-88in-rear-parabolic-springs-pair-3-leaf.html
  '98df0e0b4908653d90cb34c9',
  // https://www.paddockspares.com/para03-109in-rear-parabolic-springs-pair-4-leaf.html
  'b9f58a5a08793405c45ef2dd',
  // https://www.paddockspares.com/rtc3417-brake-shoes-axle-set-lwb-front-4cyl-swb-fr80-81.html
  'cade1f2e9a7e8f7fd9123495',
  // https://www.paddockspares.com/yrm356-aluminium-seat-box-frame-series-2-3.html
  '6417d046ce458f15b74c2f35',
  // https://www.paintmanpanels.co.uk/shop/330426-landrover-series-3-rhd-front-wing-outer-skin-rh/
  'c7dcf7de83332afdf1869a12',
  // https://www.paintmanpanels.co.uk/shop/330427-landrover-series-3-lhd-front-wing-outer-skin-lh/
  '7a4a7a5d967140f54e026457',
  // https://www.paintmanpanels.co.uk/shop/347474-landrover-series-3-lhd-front-wing-outer-skin-rh/
  'bd37bb73d12c55acc3887365',
  // https://www.paintmanpanels.co.uk/shop/347475-landrover-series-3-rhd-front-wing-outer-skin-lh/
  '8d616c35dc09458031b4d686',
  // https://www.paintmanpanels.co.uk/shop/land-rover-series-bottom-door-repair-section/
  '7b010360eb0a986c49c166e5',
  // https://www.paintmanpanels.co.uk/shop/mrc2595top-land-rover-series-2-3-front-wing-top-lh/
  'e5ab1306e7139af1a3e1ee7e',
  // https://www.pedders.com.au/product/pedders-urethane-bush-leaf-spring-eye-shackle-kit-ep8072
  '765dfbcfd506e0de940ca88d',
  // https://www.polybush.co.uk/product/1-series-kit-14/
  '292f5a3895adcff8a0332787',
  // https://www.roverparts.eu/nl/products/591379-half-shaft-rear-lh-88-up-to-1980
  '6a10aff83ce14454cebae531',
  // https://www.roverparts.eu/products/ga3180-swivel-kit-defender-xa-onwards-with-abs
  '6ee7f00301d36f6165bdcbc4',
  // https://www.roverparts.eu/products/rtc3346-joint-universal-propshaft
  'ae3be7edafe0d6b8349999d8',
  // https://www.roverparts.eu/products/stc1119-valve-exhaust-6cyl
  '6913106db6dbe188819516e0',
  // https://www.roverparts.eu/products/stc574-propshaft-front
  '4fef0240e1f0bf961bd4a6ee',
  // https://www.roversnorth.com/parts/200tdicyl_rebuilt_cylinder_head_200tdi%26type%3D4
  '467b2ba09131304ad10ff566',
  // https://www.roversnorth.com/parts/300tdicyl_cylinder_head_complete_assembly_300tdi
  'c89cba4218efc579be75de1f',
  // https://www.roversnorth.com/parts/35595k_blower_motor_kit_w_fan_smith_s_heater_series_iia_iii%26type%3D4
  '00dd3c5d8794e02e6d469fbb',
  // https://www.roversnorth.com/parts/bls112l_ball_bearing_steering_gearbox_detent_series_ii_iia_iii
  '25d18b0b5150d4313a800199',
  // https://www.roversnorth.com/parts/err2640_oil_seal_rear_crank_v8_3_5_3_9_4_0_4_6
  '7ea27c87e2655bde8a68db20',
  // https://www.roversnorth.com/parts/err4762_hose_flame_trap_to_tee_3_5_and_3_9l_v8
  '12acfceec3b4abf20ab509a7',
  // https://www.roversnorth.com/parts/kvd001330gb_chassis_only_defender_110_td5_galvanized
  '4a752119a995ff456347f1c5',
  // https://www.roversnorth.com/parts/nrc236-18_rear_crossmember_with_18_inch_extensions_series_ii_iii_88
  '57a1f63b44b5172a1cc013a3',
  // https://www.roversnorth.com/parts/nrc236-6_rear_crossmember_6_extension_109_black
  '56942b2cbc8cd86b114701a5',
  // https://www.roversnorth.com/parts/plb472_front_radiator_panel_early_iia_euro
  '73e704c839d866077ea75559',
  // https://www.roversnorth.com/parts/plb535_wheel_cylinder_right_hand_88_front_or_109_rear
  '61f653294e86b849bbe40c18',
  // https://www.roversnorth.com/parts/plb536_wheel_cylinder_left_hand_88_front_or_109_rear
  '03a4ba2dedc90c1166f1d86b',
  // https://www.roversnorth.com/parts/plb537_wheel_cylinder_right_hand_rear_series_88
  '20b12a6cab01711e1746ebc7',
  // https://www.roversnorth.com/parts/plb538_wheel_cylinder_left_hand_rear_series_88
  'a53dfe18f3df64ff0732924c',
  // https://www.roversnorth.com/parts/plb541_wheel_cylinder_11_inch_brakes_left_hand_front_series_4_cylinder
  '4e5f05c8f3893e652196a1c6',
  // https://www.roversnorth.com/parts/plb542_wheel_cylinder_11_inch_brakes_right_hand_front_series_4_cylinder
  '2df9f7ca42688ae614a24c81',
  // https://www.roversnorth.com/parts/plc069_seatbox_assembly_flat_pack_series_iia_iii
  '3bf57406bdd238b8c078a148',
  // https://www.roversnorth.com/parts/plc314_swivel_ball_88_109_series_ii_iia_iii
  '369409e654ce9ada8960c27c',
  // https://www.roversnorth.com/parts/plc538_synchro_ring_1st_2nd_series_iii
  'd748cafc038d89be701115d6',
  // https://www.roversnorth.com/parts/plc599_wheel_cylinder_front_left_hand_6_cylinder_and_v8
  'de7110e99bc6ee333e765d42',
  // https://www.roversnorth.com/parts/plc600_wheel_cylinder_front_right_hand_6_cylinder_and_v8
  'c6028bacfb355372ed9b2a8b',
  // https://www.roversnorth.com/parts/plc752_master_cylinder_early_cv
  'd0895293510f282fc9a2934c',
  // https://www.roversnorth.com/parts/pld496hd_radiator_assembly_200tdi_defender_heavy_duty
  '302a48143305f791ef363f25',
  // https://www.roversnorth.com/parts/ple145_valve_seat_2_25l_petrol_exhaust
  '4c74fe398cc79faac13ef8f7',
  // https://www.roversnorth.com/parts/ple588s_stainless_steel_brake_shoe_adjuster_kit_series_ii_iia_iii_and_defender_with_rear_drum_brakes
  'f0ecef9332e4e76988147ebe',
  // https://www.roversnorth.com/parts/plf334a_water_pump_oem_4_cylinder_series_iia_iii_civilian
  'e89a949109df800986495c85',
  // https://www.roversnorth.com/parts/plk200hb_head_bolt_kit_200tdi
  'bffb3280092fbc40ce64cdf9',
  // https://www.roversnorth.com/parts/plm066_t_seal_rear_main_bearing_t_seal_v8
  '769faa25609a1a3aecdc7a1f',
  // https://www.roversnorth.com/parts/plm098_hose_pcv_to_manifold_v8
  'f0c4b79471594c730b1521b9',
  // https://www.roversnorth.com/parts/plm134_sensor_coolant_efi_defender_disco_i_p38a
  '6592cc323e316d6e0feb6043',
  // https://www.roversnorth.com/parts/ply666_spring_synchro_assy_series_iia_iii
  '1482aaf53661bb2f395b8de3',
  // https://www.roversnorth.com/parts/rna3181p_swivel_ball_rebuild_kit_series_iia_iii
  'dd926e65fa5f52a93f121c16',
  // https://www.roversnorth.com/parts/rnk1124_parabolic_spring_set_of_4_2_4leaf_88_109%26type%3D3
  'ba04a436810aa793af90cd61',
  // https://www.roversnorth.com/parts/rnk951_alternator_conversion_series_iia%26type%3D3
  'c0b848a9c455de5a98053844',
  // https://www.roversnorth.com/parts/shp0001_smiths_round_heater_core_matrix
  'dded052dff787aef60376b0e',
  // https://www.roversnorth.com/ProductInfo.aspx?code=268847&eq=&type=0
  '28a5d7915361c64921be19f8',
  // https://www.roversnorth.com/ProductInfo.aspx?code=CHAS34&eq=&type=0
  '6c02c56c785ab9a7e5ca2f4b',
  // https://www.roversnorth.com/ProductInfo.aspx?code=PLE588S&type=0
  'cb646900680f25f839232be1',
  // https://www.roversnorth.com/ProductInfo.aspx?code=PLF193&type=0
  '6d4e1da374ad2a9d29717d0a',
  // https://www.roversnorth.com/ProductInfo.aspx?code=PLF360K
  '92ddb8facf6a96885ca218ca',
  // https://www.roversnorth.com/ProductInfo.aspx?code=PLX862-3R&eq=&type=0
  'c01ba66da4760a51005c8d4d',
  // https://www.roversnorth.com/ProductInfo.aspx?code=PLX864-5R&eq=&type=0
  '0e13f10f38c07a835f5acf4b',
  // https://www.roversnorth.com/ProductInfo.aspx?code=RNA3168K&eq=&type=3
  'd0f5e66d4733adef38348db5',
  // https://www.roversnorth.com/ProductInfo.aspx?code=RNA3169&eq=&type=0
  'b31e020319c7227281328fd4',
  // https://www.roversnorth.com/ProductInfo.aspx?code=RNA3169P&eq=&type=0
  '705b881e7be3975ff0623acb',
  // https://www.roversnorth.com/ProductInfo.aspx?code=RNA3178&type=0
  '036afabe05656b64f00de88e',
  // https://www.roversnorth.com/ProductInfo.aspx?code=RNA3181&eq=&type=0
  '8e0903815ab64d79623df1e6',
  // https://www.rst-landrovers.co.uk/shop/axle-suspension/prop-shafts-bearings-joints/land-rover-75mm-prop-shaft-universal-joint-uj-rtc3458g/
  '141660e19f5612c016907141',
  // https://www.rst-landrovers.co.uk/shop/fuel-amp-emissions/sender-units-fuel-amp-emissions/oem-land-rover-series-2-2a-3-fuel-tank-sender-unit-90560612/
  'c75860c61168b6d18277c172',
  // https://www.rst-landrovers.co.uk/shop/uncategorized/land-rover-series-2-2a-3-swb-88-petrol-diesel-fuel-tank-552174/
  '790df4436880fa0263901861',
  // https://www.scparts.co.uk/en/brake-shoes/212334/
  '991053e4237bdc7ce650ce91',
  // https://www.scparts.co.uk/en/chassis-frame/365594/
  '7d7aac0c12f2e95b217179e3',
  // https://www.scparts.co.uk/en/chassis-frame/365621/
  '30615088082c5972516cf7da',
  // https://www.scparts.co.uk/en/chassis-frame/371781/
  '26b83051bfd5dcabeba2e875',
  // https://www.scparts.co.uk/en/chassis-frame/485271/
  'b8c47533124badce94fca009',
  // https://www.scparts.co.uk/en/chassis-frame/520404/
  '32eb5d7dd64a204fe3151f91',
  // https://www.scparts.co.uk/en/chassis-outrigger/365603/
  'e36d6633d89e921cf467f8ca',
  // https://www.scparts.co.uk/en/crossmember/481391/
  'c71505d63bc5ea2e7ce24d94',
  // https://www.scparts.co.uk/en/cylinder-head-gasket/363609/
  '33659509813877f3e203bb38',
  // https://www.scparts.co.uk/en/leaf-spring-bracket/365592/
  '82904140cb7871e95030b1f8',
  // https://www.scparts.co.uk/en/leaf-spring-bracket/365593/
  '76154931475b9a040b8ae8f3',
  // https://www.scparts.co.uk/en/leaf-spring-bracket/366015/
  '87c6ec43f7748b16293f34d3',
  // https://www.scparts.co.uk/en/leaf-spring-bracket/487107/
  '70a6957e27be3ed25cb83795',
  // https://www.scparts.co.uk/en/oil-sealing-ring/363722/
  'bad02f3f64e608847e28d1aa',
  // https://www.scparts.co.uk/en/propshaft/373593/
  '1779355d7b80db570b9a3ec7',
  // https://www.scparts.co.uk/en/radiator/506643/
  '7db5d412ec61f10999dbdd86',
  // https://www.scparts.co.uk/en/timing-chain-tensioner/367524/
  'c507f3a58baeddd038c928bf',
  // https://www.scparts.co.uk/en/timing-chain-tensioner/369007/
  '192f14309807320e64592612',
  // https://www.seriesmagic.com.au/shop/p/frc4076-and-frc4077-high-quality-mainshaft-bronze-split-bush-set-series-1-2-2a-3-1953-plus
  '5965b57ba02b53b6f68d7f3c',
  // https://www.seriesparts.co.uk/PartDetail?stockid=214
  '9b5c26e186e15d4405bfdbc4',
  // https://www.sp-4x4.com/Bulkhead_Outrigger_LH_STC8355_p/lr513gn-s.htm
  'cb9e57d5f9071e6c3bfa052d',
  // https://www.sp-4x4.com/Bulkhead_Outrigger_RH_STC8354_p/lr513go-s.htm
  'dd792884591fc87b32b900bd',
  // https://www.sp-4x4.com/DA2008N_Chassis_Leg_Front_Left_Hand_For_Land_p/da2008n.htm
  'ec48748da1080e8d67a5c39b',
  // https://www.sp-4x4.com/DA2008O_Chassis_Leg_Front_Right_Hand_For_Lan_p/da2008o.htm
  '502184261e0584abfdc94829',
  // https://www.sp-4x4.com/GALVANISED_PAIR_SERIES_3_DOOR_TOPS_p/jwp5380.htm
  'c433fc145c64b85d323bc909',
  // https://www.sp-4x4.com/JWP5060_Galvanised_Def_Fully_Built_up_Complete_R_p/jwp5060.htm
  '47136d3714fa1c7163abdffe',
  // https://www.sp-4x4.com/JWP5061_Galvanised_Def_Fully_Built_up_Complete_L_p/jwp5061.htm
  'e52d3f9a1471bebe38d5daf4',
  // https://www.sp-4x4.com/LR250_88_Rear_Crossmember_with_extensions_with_p/lr250.htm
  '4b94d0ba67267ac379ed2063',
  // https://www.sp-4x4.com/LR252_109_Rear_1_4_Chassis_With_Ext_Inc_S_p/lr252.htm
  'fefa3993cce7c2e111e05e9a',
  // https://www.sp-4x4.com/LR721HDG_Heavy_Duty_Galvanised_Rear_Crossmember_p/lr721hdg.htm
  'e884fe2cafe96d9b788dc1a2',
  // https://www.sp-4x4.com/LR722G_Galvanised_Rear_Crossmember_for_Defender_p/lr722.htm
  'f26cdaa26a902fe2726d7112',
  // https://www.sp-4x4.com/product_p/lrc1021.htm
  'e9b668206643404be37f2b3c',
  // https://www.sp-4x4.com/TD5_Rear_Cross_member_Basic_KVB000290_p/lr610g.htm
  '2655bfb93b23a92ebd2db6b2',
  // https://www.sp-4x4.com/Timing_Belt_Kit_300_Tdi_Modified_STC4096L_p/stc4096r.htm
  'd37f41ca46b8f58fe3860a13',
  // https://www.turnerengineering.co.uk/products/542492-rear-oil-seal-kit-3mb-c2x20634935
  'cbc5518b13d73c88edba8684',
  // https://www.turnerengineering.co.uk/products/err-5057-fuel-pump-copy
  '7e49367374a029f105e8ffc8',
  // https://www.turnerengineering.co.uk/products/lr058095-oil-pump
  'e67ea3aca442f7fc4cf9afd2',
  // https://www.turnerengineering.co.uk/products/series-2-petrol-2-25-3mb-crankshaft-010-mains-big-ends
  '8b397aed205f0c8df284ae5b',
  // https://www.turnerengineering.co.uk/products/stc-1567-gasket-set-top-inc-elring-head-gasket
  '072628a2b159a767f64ddb98',
  // https://www.turnerengineering.co.uk/products/yll500040-head-locating-dowel
  'ec9a10592c1d75f469f28b8a',
  // https://www.v-rigger.com/Duralac-Pas-115ml-Tube
  '4b6395d5c4d21baf72883cfa',
  // https://yrmit.co.uk/product/bottom-of-vent-bulkhead-repair-panel-lr-defender-series-2-3/
  'c2b7476ef88ead0b291211ea',
  // https://yrmit.co.uk/product/bulkhead-upper-with-vents-repair-panel-lr-defender-lr-series-2-2a-3/
  '6db6caf945b5bfa4505268dd',
  // https://yrmit.co.uk/product/door-repair-section-lr-series-2-2a-3/
  '73c020e1015082d0afd8faed',
  // https://yrmit.co.uk/product/extended-bulkhead-repair-panels-lr-defender-lr-series-2-2a-3/
  'edab2d415199ff9092f822db',
  // https://yrmit.co.uk/product/hdg-tailgate-capping-lr-defender-lr-series-2-2a-3/
  '7c84e14224ab6c001801c32c',
  // https://yrmit.co.uk/product/lhs-footwell-repair-panel-lr-defender/
  'c38985a644769e4fcc9c4bb9',
  // https://yrmit.co.uk/product/lhs-lhd-footwell-repair-panel-ribbed-lr-series-2-2a-3/
  '22c206cdb185f42adb6ad492',
  // https://yrmit.co.uk/product/lhs-lhd-rhd-above-footwell-bulkhead-repair-panel-lr-defender/
  '11cb5563ca9cc8bb1a40ecb9',
  // https://yrmit.co.uk/product/lhs-lower-door-pillar-repair-section-lr-defender-lr-series-2-2a-3/
  '607689ccc25d5fbc00213c56',
  // https://yrmit.co.uk/product/lhs-rhd-footwell-repair-panel-ribbed-lr-series-2-2a-3/
  'aa9902b21f51820ee55385a8',
  // https://yrmit.co.uk/product/rhs-footwell-repair-panel-lr-defender/
  '5f3dd11f188d706496b4c0ef',
  // https://yrmit.co.uk/product/rhs-lhd-footwell-repair-panel-ribbed-lr-series-2-2a-3/
  '07314febe2e0167d7492af79',
  // https://yrmit.co.uk/product/rhs-lhd-rhd-above-footwell-bulkhead-repair-panel-lr-defender/
  'bda5bec1db6703afcdd93498',
  // https://yrmit.co.uk/product/rhs-lower-door-pillar-repair-section-lr-defender-lr-series-2-2a-3/
  '2134fde9243a28ee64a7f1b1',
  // https://yrmit.co.uk/product/rhs-rhd-footwell-repair-panel-ribbed-lr-series-2-2a-3/
  '903aa13270ebf898167e318b',
  // https://yrmit.co.uk/product/top-of-vent-bulkhead-repair-panel-lr-defender-series-2-3/
  'e955236c8094a1d956cfcba1',
] as const;

export const vendorUrlFingerprints = [
  // 3 brothers classic rovers | https://3brothersclassicrovers.com/collections/series-1-steering/products/standard-swivel-ball-oil-seal-rebuilders-kit-series-1954-84
  '5d0436f7cc3d5188ddc02c58',
  // 3 brothers classic rovers | https://3brothersclassicrovers.com/products/oil-seal-for-rear-hub-series-1-semi-float-axle-1948-58
  '1e1470aadfb3d47a1fb45c3f',
  // airsuspension.com | https://www.airsuspension.com/products/arnott-new-front-left-air-spring-03-12-land-rover-range-rover-l322
  '069f58b13426774be3ae37f6',
  // airsuspension.com | https://www.airsuspension.com/products/arnott-new-front-right-air-spring-03-12-land-rover-range-rover-l322
  '965fd6e1404aabfd1d3078ef',
  // airsuspension.com | https://www.airsuspension.com/products/arnott-new-rear-air-spring-03-12-land-rover-range-rover-l322-left-or-right
  '9376f4a00fb2846100445e65',
  // airsuspension.com | https://www.airsuspension.com/products/rear-air-spring-13-22-land-rover-range-rover-l405-lt-rt
  'bf1c2ff771c97065126aa4ea',
  // ang classic car parts | https://www.angclassiccarparts.co.uk/products/landrover/defender-series-8890110-discovery/engine/fuel-pump-repair-kit-ac-delco-land-rover-series-ii-iii-225-petrol
  'aa7a7428da5618b9a98f3e44',
  // antipodean parts | https://antipodeanparts.com.au/products/spring-hanger-narrow-springs-front-and-rear-series-1-80
  '75d4aa207d6ea16f3957b18a',
  // ashcroft transmissions | https://ashcroft-transmissions.co.uk/product/mt82-output-shaft-kit/?add-to-cart=77991
  'e00a1ea0fc8bdf4a5fd07aa8',
  // ashcroft transmissions | https://ashcroft-transmissions.co.uk/product/r380/
  '107d70dee3e09ebbcf340e2e',
  // auto electric supplies | https://www.autoelectricsupplies.co.uk/p/landrover-1948-54
  '31497d3d6dc546dbc8fdc56a',
  // auto electric supplies | https://www.autoelectricsupplies.co.uk/p/lucas-c40
  'e99c2cbc7ddb26412dd8ef42',
  // automec | https://www.automec.co.uk/products/brake-pipe-set-land-rover-series-1-80-rhd-1948-1958-gb5600
  '5eae6e80b19b38a862239536',
  // autosparks | https://www.autosparks.co.uk/land-rover-series-1-wiring-harness-set-10
  'ed31182ba4183705b099259a',
  // autosparks | https://www.autosparks.co.uk/land-rover-series-2-wiring-harness-set-10
  '9b9a6c0b5c5b06720a2fee05',
  // bearmach spain | https://www.bearmach.es/en/productos/3/land-rover-parts/producto/13853/270225/
  '2890d6b1a3d44632d3440274',
  // bell engineering | https://www.bellengineering.co.uk/product-page/haldex-5-pump
  '3de37921b573121a9d2e3684',
  // bell engineering | https://www.bellengineering.co.uk/product-page/haldex-5-unit
  'fe28d447dd114adb11c54844',
  // bell engineering | https://www.bellengineering.co.uk/product-page/haldex-module
  '85192125a50c6dfcf4701f9e',
  // bell engineering | https://www.bellengineering.co.uk/product-page/land-rover-freelander-1-reconditioned-ird-4wd
  '686172ec7e13088e1664582a',
  // bell engineering | https://www.bellengineering.co.uk/product-page/land-rover-freelander-1-reconditioned-vcu
  'a584a2f73e290be10b30a077',
  // britcar | https://britcar.com/product.php/95563/316/fuel_sender___unit_under_seat___land_rover_series_11_and_111
  'baaa44a4f335d1d9fe4d05a3',
  // british auto parts australia | https://www.britishautoparts.com.au/inc/sdetail/23951
  '1f8191c15647e42041408bcf',
  // british motor imports | https://bmiparts.com.au/product/gasket-fuel-tank-sender-unit-series-lr
  '3bae6e0f36e14fb77bbd256d',
  // british parts uk | https://www.britishparts.co.uk/land-rover/discovery-5-l462/steering-suspension/height-sensor-rear-lr098915-land-rover
  '39f14edaf233ddcca945d580',
  // british parts uk | https://www.britishparts.co.uk/land-rover/series-1-2-2a-3/engine-petrol/camshaft-247709
  'c1ab2425cc7d239478598c1a',
  // british wiring | https://www.britishwiring.com/Land-Rover-Series-2A-Main-Wiring-Harness-p/lr202pb.htmCartID%3D1?CartID=1
  'b429b68f3fea50348a3eddc0',
  // british wiring | https://www.britishwiring.com/Land-Rover-Series-2A-Main-Wiring-Harness-p/lr203pp.htm
  '36f32a761877d3221d660bd9',
  // british wiring | https://www.britishwiring.com/Land-Rover-Series-2A-Main-Wiring-Harness-p/lr212pb.htmCartID%3D1?CartID=1
  'bf5d3645ff9ff48c06d4d4e6',
  // british wiring | https://www.britishwiring.com/Land-Rover-Series-2A-Main-Wiring-Harness-p/lr213pb.htm
  'e7ce9f9be97e0db76fae9837',
  // brookwell supplies | https://www.brookwell.co.uk/product/aftermarket-mainshaft-oil-seal-236305
  'b68558f1e58cdf9b428fc4de',
  // brookwell supplies | https://www.brookwell.co.uk/product/aftermarket-rear-crankshaft-seal-set-542494
  'c24384ae0833828c0938722c',
  // brookwell supplies | https://www.brookwell.co.uk/product/aftermarket-seal-swivel-bearing-housing-rtc3528
  'c0cd303f8886c340186d4080',
  // brookwell supplies | https://www.brookwell.co.uk/product/britpart-earth-lead-gearbox-chassis-575184
  '4ec3ddb95e330e660ade9ccf',
  // brookwell supplies | https://www.brookwell.co.uk/product/girling-wheel-cylinder-seal-kit-275744
  'f9c7e91aa3df4e3b4cc9f50d',
  // brookwell supplies | https://www.brookwell.co.uk/product/gkn-universal-joint-rtc3346
  '1dbff03c2a4c390c2ded1293',
  // budget parts | https://www.roverparts.eu/nl/products/591379-half-shaft-rear-lh-88-up-to-1980
  'ecb0435ba68a7f4c938027b2',
  // budget parts | https://www.roverparts.eu/products/ga3180-swivel-kit-defender-xa-onwards-with-abs
  '2632446aeddba6de140851e9',
  // budget parts | https://www.roverparts.eu/products/rtc3346-joint-universal-propshaft
  '1304869b2ffec7d43f9bb124',
  // budget parts | https://www.roverparts.eu/products/stc1119-valve-exhaust-6cyl
  '45c89aa859c0c29b9d1760db',
  // budget parts | https://www.roverparts.eu/products/stc574-propshaft-front
  '549a1ae248297995b85d7c9c',
  // ckd shop | https://ckdshop.co.uk/product/master-cylinder-kit-107-109/
  '41e728ec40a84c1b21fab8b5',
  // ckd shop | https://ckdshop.co.uk/product/master-cylinder-kit-80/
  '83abfa0fa1abfa7d064153be',
  // copperbraid | https://www.copperbraid.co.uk/product/copper-braid-earth-strap-50-mm2-250-amps/
  '12120970737825de1787497b',
  // dds metal services | https://ddsmetal.co.uk/shop/90-110-td5-gearbox-cross-member-1998-2006-bolt-on-kvb500060/
  '37a58927d26434c6214fa4cc',
  // design and development engineering | https://www.designdevelopmenteng.co.uk/shop/Land-Rover-Series-One-80-LHD-Steering-Box-Kit-p488889168
  'c205cffd3eac198805196a6b',
  // design and development engineering | https://www.designdevelopmenteng.co.uk/shop/Land-Rover-Series-Relay-Mounting-Plate-CNC-Machined-p389433979
  '45b8bda3edfdc3e4c16256b9',
  // dingocroft | https://www.dingocroft.co.uk/acatalog/Brake-Master-Cylinder-268982.html
  '44e56d47a7ed48ed3055bbda',
  // dtc uk | https://www.dtc-uk.com/product/duralac-anti-corrosive-jointing-compound/
  '81fa42f10bf2284f3e4f2636',
  // ebay uk / seller listing | https://www.ebay.co.uk/itm/355363261499?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'b4b7b5a8998341a5377068b9',
  // emberton imperial | https://embertonimperial.com/en-us/products/land-rover-series-2a-3-defender-bulkhead-ventilation-flap-seal-set-jae00003-x2
  '3c5a6f86a351719052d960f0',
  // emberton imperial | https://embertonimperial.com/en-us/products/land-rover-smiths-round-heater-motor-blower-fan-oem-series-1-2-2a-2b-swb-89
  '4dfeb49fa61ac5302c98b9e0',
  // emberton imperial | https://embertonimperial.com/en-us/products/land-rover-steering-box-rebuild-kit-series-1-2-2a-reconditioning-set-bearings
  '117a0335965c6bc3f66fd983',
  // emberton imperial | https://embertonimperial.com/products/land-rover-headlight-ignition-switch-key-genuine-lucas-oem-217589-series-1-80
  '237aa38439f6fcb49ad15446',
  // emberton imperial | https://embertonimperial.com/products/land-rover-series-1-80-12v-lucas-cw-cw1-cwx-windscreen-wiper-motor-unit-231554
  '22e8842a28ffb1d94e43a622',
  // empire tuning | https://www.empiretuning.co.uk/product/oem-td5-injector-harness-rocker-gasket-amr6103g/
  '66eb927f877f3376d58eba88',
  // engel imports | https://www.engelimports.com/en/water-pump/363939/
  'f460d8bcd8c427664cd27656',
  // famous four | https://www.famousfour.co.uk/new_parts/ff_part?part=16686
  '91ffbb0bbd400a7266600a7f',
  // gaskets for classics via ebay | https://www.ebay.com/itm/195923538094?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '888192728a2faa733cb33a1c',
  // jgs4x4 | https://www.jgs4x4.co.uk/defender-swivel-housing-repair-kit-with-swivel-housing-da3167/
  '33f6c6a85852cdf08f754169',
  // jgs4x4 | https://www.jgs4x4.co.uk/gearbox-bearing-kit-for-series-ii-and-series-iia-suffix-a-da3361/
  'cafd70633769041929f8b470',
  // jgs4x4 | https://www.jgs4x4.co.uk/land-rover-series-rear-mainshaft-oil-seal/
  '374af6af92f7f143fa643893',
  // jgs4x4 | https://www.jgs4x4.co.uk/series-2-2a-gearbox-bearing-kit/
  '6ac33b9dc3c125b36162126e',
  // john craddock | https://www.johncraddockltd.co.uk/213340-oil-seal-for-steering-relay-landrover-1948-84.html
  'fba93a67545ec8e01fa7f48a',
  // john craddock | https://www.johncraddockltd.co.uk/217290-genuine-driveshaft-front-tractajoint-1948-53.html
  '0a441120f6adaa8e01ff15db',
  // john craddock | https://www.johncraddockltd.co.uk/218020-fuel-tank-80-inch-1948-53.html
  '76b001c31712b5bfdb906629',
  // john craddock | https://www.johncraddockltd.co.uk/219007-brake-linings-and-rivets-for-handbrake-shoes-1948-64.html
  '90919234bce6dbdb3e2c64b4',
  // john craddock | https://www.johncraddockltd.co.uk/219824girling-girling-brake-hose-front-and-rear-1948-53.html
  '5e1e8d97fca3599074923edc',
  // john craddock | https://www.johncraddockltd.co.uk/235006-master-cylinder-80-inch-1948-53-non-genuine.html
  'adb552fe512d782aab5bca89',
  // john craddock | https://www.johncraddockltd.co.uk/241687-r-master-cylinder-s-w-b-1954-58-non-genuine.html
  '618e0caf6ebbc9f270ff3cf7',
  // john craddock | https://www.johncraddockltd.co.uk/244711-pinion-assy-starter-motor-1955-84-all-4-and-6-cylinders.html
  '1ce7afa557a17927baee9adc',
  // john craddock | https://www.johncraddockltd.co.uk/260055-brush-set-starter-motor-1948-72-2-brushes-2-pair-are-fitted-to-starter-motor.html
  '7c0e4a3cfca5b4068bda86f5',
  // john craddock | https://www.johncraddockltd.co.uk/260550-genuine-land-rover-diaphragm-fuel-pump-1948-58-48-58.html
  '69c8447dbef683b3ff02e6ad',
  // john craddock | https://www.johncraddockltd.co.uk/261256-lucas-dynamo-brush-set-type-c45-2-litre-diesel.html
  '56c3f0f775ae4c807d08459c',
  // john craddock | https://www.johncraddockltd.co.uk/261483-brush-set-for-dynamo-c39-type.html
  'bc5ffeead4052da83e624f11',
  // john craddock | https://www.johncraddockltd.co.uk/262102-head-gasket-set-1951-55-2-litre-petrol.html
  '3abcfeb2e68585b65bdc1a48',
  // john craddock | https://www.johncraddockltd.co.uk/268038-bottom-hose-1948-58-also-use-as-top-hose-and-cut-to-suit.html
  '1227d78998a0a132539b9dae',
  // john craddock | https://www.johncraddockltd.co.uk/270604-wheel-bearing-rear-1948-58.html
  '35596d24799b706aa8a53be7',
  // john craddock | https://www.johncraddockltd.co.uk/274423-handbrake-drum-all-models-up-to-1984.html
  'c75cef21a85f7a05a1eeaecc',
  // john craddock | https://www.johncraddockltd.co.uk/307421-rubber-bulkhead-to-screen-1954-58-lentgh-is-60-5-inches.html
  '320241c282d7388e10d4896e',
  // john craddock | https://www.johncraddockltd.co.uk/320902-track-rod-end-lh-thread-1948-to-july-1974.html
  'efd186130cfc5ec9c0d2ddae',
  // john craddock | https://www.johncraddockltd.co.uk/503754-brake-master-cylinder-overhaul-kit-109-inch-1958-66-cb-type.html
  '1ecf06b599e7844c55647d3b',
  // john craddock | https://www.johncraddockltd.co.uk/507687b-carburettor-rebuild-kit-solex-1958-67-includes-butterfly-and-spindle.html
  '535fd84203bce39b4815f0ee',
  // john craddock | https://www.johncraddockltd.co.uk/535649-head-gasket-2-litre-diesel-1956-61.html
  '37bffdab2d2a61d41d2c1871',
  // john craddock | https://www.johncraddockltd.co.uk/591704-clutch-plate-9-inch-for-land-rover-1950-69.html
  'b73011b1c10a0d07b732915a',
  // john craddock | https://www.johncraddockltd.co.uk/602687-thermostat-series-1-and-v8-2-5d-and-2-5td-and-90110-petrol-4-cylinder-82-degrees.html
  '382a109457d8d8c8f0c912ac',
  // john craddock | https://www.johncraddockltd.co.uk/7297l-jc3-collar-retaining-halfshaft-bearing-series-1-rear-1948-58.html
  'f77e02ccec20b069aa5d75f4',
  // john craddock | https://www.johncraddockltd.co.uk/grc115-radiator-cap-series-1-petrol-1948-58.html
  '2eef5c04186aa393016a3d0e',
  // john craddock | https://www.johncraddockltd.co.uk/jc10086-r-jc3-series-1-dumb-iron-front-chassis-rh-1952-to-1955.html
  '6ca1dbc2a31c719e36912ab1',
  // john craddock | https://www.johncraddockltd.co.uk/jc10086l-jc3-series-1-dumb-iron-front-chassis-lh-1952-to-1955.html
  '384d4bd7e13ca4d70e2e76b7',
  // john craddock | https://www.johncraddockltd.co.uk/jc159-jc3-rear-crossmember-for-series-1-1948-53-exact-replica-of-the-original-in-2mm-steel-and-bsf-fixings-comes-with-body-tags-both-types-and-chassi.html
  '4827eca9e5605369c2e16536',
  // john craddock | https://www.johncraddockltd.co.uk/jc695-r-door-pillar-repair-panel-rh-1954-58.html
  '0654385e4666f4a2e566ce03',
  // john craddock | https://www.johncraddockltd.co.uk/jc695l-door-pillar-repair-panel-lh-1954-58.html
  'fae5aefab7805cfd6c1e05eb',
  // john craddock | https://www.johncraddockltd.co.uk/jc7039-jc3-rear-crossmember-for-series-1-1954-58-this-item-is-an-exact-replica-of-the-original-in-2mm-steel-and-bsf-fixings-comes-with-body-tags-and.html
  '4262ff655baa93aa2823efc1',
  // john craddock | https://www.johncraddockltd.co.uk/jc86-top-section-bulkhead-series-1-1954-58.html
  'a547232bda90a519b409ec0d',
  // john craddock | https://www.johncraddockltd.co.uk/jc93-footwell-repair-panels-series-1954-58-1-pair.html
  '86a9cfae1b5db4eb6e298669',
  // john craddock | https://www.johncraddockltd.co.uk/rtc2990-crown-wheel-and-pinion-1950-84-see-ftc3586-for-bolts.html
  '6d3fba557c732850955ee424',
  // john craddock ltd | https://www.johncraddockltd.co.uk/236630-genuine-flange-rear-output-shaft.html
  '221d2c120618a96c775d42f3',
  // land rover optional equipment | https://www.lroe.co.uk/products/RTC7136-Service
  'd4e73e18bd917d073bdd22e4',
  // land rover orphanage | https://www.lroe.co.uk/235553
  '8bba49100924cad8e6f87b02',
  // land rover orphanage | https://www.lroe.co.uk/520849
  '5f1e6a475715ad4ddea86072',
  // land rover series one club | https://www.lrsoc.com/web/product/lr302300/
  '1e4c93e309a8a612b9443d3e',
  // land rover treasure shop | https://landrovertreasureshop.com/product/243141-genuine-front-rh-half-shaft-land-rover-series-i/
  '38133313e06fce91d4c36d74',
  // land rover treasure shop | https://landrovertreasureshop.com/product/528703-layshaft-gearbox-land-rover-series/
  'e6e7d7817c998e77f10979ce',
  // land rover treasure shop | https://landrovertreasureshop.com/product/land-rover-ignition-headlight-switch-complete-series-1-2-239570/
  '29a0f82aa238562c5459f780',
  // limora | https://www.limora.com/nl/adapter/364292/
  'eaafbfe54bee93b7f86b8dc2',
  // limora | https://www.limora.com/nl/weber-carburateur/312818/
  '4a7aaa2d4d42c34584cd2882',
  // lof clutches | https://lofclutches.com/shop/clutches/land-rover-clutches/defender/roadspec-tdci-puma-inc-flywheel/
  'da41a1cb027ed9aaf645b602',
  // lr direct | https://www.lrdirect.com/549761-fuel-pump?sort_direction=1
  '8ece856a82b76941f6e1ab8d',
  // lr direct | https://www.lrdirect.com/564706-brake-master-cyl-lwb-cb
  'e51e8ba35949c83354dd5368',
  // lr direct | https://www.lrdirect.com/571235-drive-flange-hub-10-spline
  '15c3e8ffb595dabd8c39f7a0',
  // lr direct | https://www.lrdirect.com/591378-halfshaft-ser2a3-r-h-10-spline
  'edb61a044616d4974511e699',
  // lr direct | https://www.lrdirect.com/90517429-tappet-roller-2-25-2-5pddt
  'efbb7ef9863f1f2b4878603e',
  // lr direct | https://www.lrdirect.com/frc1644-halfshaft-swb-late-ser3-rh-24-sp
  '5d9d20b623f4a96dc7e4ff83',
  // lr direct | https://www.lrdirect.com/frc1645-halfshaft-swb-late-ser3-lh-24-sp
  '955e1fd843b3834c71b07243',
  // lr direct | https://www.lrdirect.com/FRC1780-Oil-Seal-Output-Shaft-and-Transfer/
  'd488da6c9d7c8d6c11973696',
  // lr direct | https://www.lrdirect.com/lr027158-thermostat-and-hsg
  '1081ab71b24ef55e575a04a9',
  // lr direct | https://www.lrdirect.com/lr091586-pump-fuel
  'ae7485e7ebf3deb5f8217d7d',
  // lr direct | https://www.lrdirect.com/nsc500160-sensor-crankshaft-position
  'd4cf9362c790db5ba048a235',
  // lr direct | https://www.lrdirect.com/stc121-propshaft-front-swb
  'b266481c7ce8934fb336c201',
  // lr parts | https://www.lrparts.net/274423-handbrake-transmission-brake-drum-for-land-rover-series-2-2a-3.html
  '0441ae43ba4acabac43c9f53',
  // lr parts | https://www.lrparts.net/3649-selector-shaft-detent-spring-for-land-rover-series-2a-3-priced-individually.html
  'b3a17d1ed1d00ffd2c1b6a20',
  // lr parts | https://www.lrparts.net/521328-thrust-washer-for-intermediate-shaft-on-land-rover-series-2a-3.html
  'f0c230000c847ab78fb33c48',
  // lr parts | https://www.lrparts.net/542492-rear-main-oil-seal-kit-for-land-rover-series-2-25-3-crank-bearing.html
  'eb0d267186e8eb1044ea6d58',
  // lr parts | https://www.lrparts.net/591379-rear-half-shaft-left-hand-for-short-wheel-base-land-rover-series-up-to-1980-10-spline.html
  '415e2ee3519b42ae6bf10a08',
  // lr parts | https://www.lrparts.net/595123-steering-drop-arm-for-land-rover-series-2a-3.html
  '83b541782f0498948252f553',
  // lr parts | https://www.lrparts.net/90217512-bearing-for-rear-output-shaft-on-land-rover-series-2a-3-transfer-box.html
  'd3ac0a732ff3a812ee6bdb16',
  // lr parts | https://www.lrparts.net/as144-uprated-alloy-radiator-for-land-rover-series-2-3-with-2-25-petrol-by-allisport.html
  '935c4377214891199b067f42',
  // lr parts | https://www.lrparts.net/da1236-steering-box-repair-kit-for-land-rover-series-2-2a-and-3.html
  '95672b340cd06d25973601b2',
  // lr parts | https://www.lrparts.net/da2112-1-defender-and-discovery-td5-cylinder-head-set-complete-with-everything-needed-including-one-hole-head-gasket.html
  'b0cb987b7b4e72add20538e3',
  // lr parts | https://www.lrparts.net/da2112-2-defender-and-discovery-td5-cylinder-head-set-complete-with-everything-needed-including-two-hole-head-gasket.html
  'f2e37ff1e303d05d226b838c',
  // lr parts | https://www.lrparts.net/da3178-swivel-housing-kit-for-defender-1994-1998-swivel-housing-ball-bearings-seals-pins-and-gaskets.html
  '77480d71cc45c8b777139026',
  // lr parts | https://www.lrparts.net/da3416-fai-timing-chain-kit-for-5-0l-aj133-3-0l-aj126-engines-range-rover-range-rover-sport-discovery-4-discovery-5-range-rover-velar-land-rover-defender-2020.html
  '5ea554e3ce3d862f8fa6d3a6',
  // lr parts | https://www.lrparts.net/da5164-gen-5-haldex-service-kit-discovery-sport-range-rover-evoque-2016-onwards.html
  'e62710a14e43b3955db0f70d',
  // lr parts | https://www.lrparts.net/da7215-transfer-box-repair-kit-fits-dd295-transfer-boxes-range-rover-sport-2005-2013-discovery-3-4.html
  'ea15e97b76248d884222a8e1',
  // lr parts | https://www.lrparts.net/err2803-thermostat-for-200tdi-discovery-and-defender.html
  'ff52cff496d538eb7563ea84',
  // lr parts | https://www.lrparts.net/err5384-cylinder-head-bolt-for-defender-and-discovery-td5-essential-for-head-gasket-job-12-needed-to-complete-job.html
  '97e9a828858355242aaf27ff',
  // lr parts | https://www.lrparts.net/etc7238-viscous-unit-for-coolant-fan-water-pump-on-200tdi-defender-and-discovery.html
  '906dafcabb99eb26ce1f0f16',
  // lr parts | https://www.lrparts.net/frc1780-seal-for-front-rear-output-shaft-on-land-rover-series-2a-3.html
  '741cb242d1e490e0ef8b33b6',
  // lr parts | https://www.lrparts.net/front-crankshaft-oil-seal-for-300tdi-defender-discovery.html
  'b28cf2588416bbe052fe883f',
  // lr parts | https://www.lrparts.net/iab500280-chain-for-transfer-box-on-range-rover-l322-range-rover-sport-2005-2013-and-discovery-3-4.html
  'b88d574f046a906a021709d9',
  // lr parts | https://www.lrparts.net/igh500040-transfer-box-motor-assembly-fits-range-rover-l322-l405-range-rover-sport-and-discovery-3-4.html
  '6528c5e87512e1d0b2fdc623',
  // lr parts | https://www.lrparts.net/iyk500010-trasnsfer-box-fluid-for-land-rover-discovery-3-4-and-range-rover-sport-from-2002-onwards-1-litre-tf-0870.html
  'a43f605540b116483ad436b0',
  // lr parts | https://www.lrparts.net/lr004381-gasket-for-vacuum-pump-on-defender-2-4-puma-duratorq-engine.html
  'c7c73d4a06364876c7a09f2f',
  // lr parts | https://www.lrparts.net/lr018752-egr-valve-and-cooler-assembly-left-hand-for-3-0-tdv6-fits-3-0-diesel-discovery-4-5-range-rover-sport-2009-2019-and-range-rover-l405-genuine-land-rover.html
  '3ad7ac1b4696cf7f3c5fb908',
  // lr parts | https://www.lrparts.net/lr023440.html
  'aceae77030e7ef286e14bfcb',
  // lr parts | https://www.lrparts.net/lr023442-rear-diff-pinion-oil-seal-for-freelander-2-discovery-sport-and-range-rover-evoque.html
  '39ff05e05e5eb1bbe32638bc',
  // lr parts | https://www.lrparts.net/lr038601.html
  '16f7188d0905d675e05be55a',
  // lr parts | https://www.lrparts.net/lr038602-freelander-2-in-tank-fuel-pump-and-sender-right-hand-for-2-2-diesel.html
  '5da8705afb0a3e5e8be0f93b',
  // lr parts | https://www.lrparts.net/lr044088-defender-vacuum-pump-seal-for-puma-2-2-engines.html
  'db3dad6a0efe8dc58f1eeca8',
  // lr parts | https://www.lrparts.net/lr105975-thermostat-and-housing-for-2-0-diesel-ingenium-range-rover-evoque-mk1-and-discovery-sport.html
  '9fd4a2109290c4b33a59acbd',
  // lr parts | https://www.lrparts.net/lr108660-pump-vacuum.html
  '0ebf97c4e10cecf511038867',
  // lr parts | https://www.lrparts.net/lr174475-rear-diff-pinion-seal-for-range-rover-l322-sport-l405-velar-and-discovery-3-4-5.html
  'c2dc4eb4b7ed3a0bf266091a',
  // lr parts | https://www.lrparts.net/lrc1021-front-and-rear-shock-absorber-kit-for-land-rover-series-for-swb-88-series-2-2a-3-by-boulder-ridge.html
  '522ecd7057068ed6f28f780a',
  // lr parts | https://www.lrparts.net/lrc10491-front-and-rear-shock-absorber-kit-for-land-rover-series-for-lwb-109-series-2-2a-3-by-boulder-ridge.html
  'f65f332564f796b30ff6a480',
  // lr parts | https://www.lrparts.net/lrc1393-defender-300tdi-full-clutch-kit-by-borg-beck-including-clutch-plate-cover-release-bearing-hd-fork-rear-crank-seal-and-fitting-clips.html
  '1a3fe1155bae539b73837a1c',
  // lr parts | https://www.lrparts.net/lrc2319-land-rover-series-track-rod-end-kit-six-piece-ball-joint-kit-for-series-2-2a-3-please-note-these-don-t-have-greaseable-nipples.html
  '6855a58e36af271e67a17bfa',
  // lr parts | https://www.lrparts.net/lrc3459-land-rover-series-handbrake-adjuster-kit-with-brake-shoes-and-springs-also-includes-expander-seals-shim-and-pins.html
  'a36e11715b1b1a92d2a10358',
  // lr parts | https://www.lrparts.net/lrc9885-shielder-galvanised-bulkhead-for-land-rover-series-3-88-109-heavy-duty-single-skin-1-5mm-bulkhead.html
  'b21880fa3cc9b37f685e1cda',
  // lr parts | https://www.lrparts.net/lvb000260-td5-cylinder-head-gasket-for-defender-and-discovery-3-holes-1-35mm.html
  '95f49d4e20e745eaa42a2ef7',
  // lr parts | https://www.lrparts.net/nrc1269-steering-relay-for-land-rover-series-1-2-2a-3.html
  '42c09be27a3f43974419baa6',
  // lr parts | https://www.lrparts.net/pcc001020-pdk000100-radiator-for-land-rover-defender-fits-puma-2-4-2-2-and-td5-engines-fits-from-1998-onward.html
  '51e5685e1b638e069128b812',
  // lr parts | https://www.lrparts.net/pcd100160-defender-expansion-tank-cap-for-td5-and-puma-engines-also-fits-freelander-up-to-2003.html
  'd5d15643d3f5da7296b9930e',
  // lr parts | https://www.lrparts.net/pel500110-thermostat-for-defender-td5-puma-and-discovery-td5-in-plastic-casing-82-degree-also-fits-freelander-1-k-series-1-8-petrol.html
  '0cc870f642ad1e6afc694fb8',
  // lr parts | https://www.lrparts.net/pet100790-water-pump-p-gasket-for-300tdi-fits-defender-discovery-1-and-range-rover-classic.html
  '58fcd47ff2b9430923f3edb7',
  // lr parts | https://www.lrparts.net/pgg500340-viscous-coupling-and-fan-for-defender-td5-and-puma-up-to-ca000001-chassis-and-discovery-td5.html
  '71c3a07405729dd9dce08bcf',
  // lr parts | https://www.lrparts.net/stc1116.html
  '6a912b1b4a5c7e9a36fe2096',
  // lr parts | https://www.lrparts.net/stc1190-fuel-lift-pump-for-defender-naturally-aspirated-turbo-diesel-and-all-200tdi-defender-discovery.html
  'e48ac892b3e154584bc37c40',
  // lr parts | https://www.lrparts.net/stc639-engine-coolant-water-pump-for-defender-200tdi.html
  'a46d07c82680823d6196cbfd',
  // lr parts | https://www.lrparts.net/steering-relay-split-bush-2a-3.html
  'cf7868a613eaca8cc1b07392',
  // lrdirect | https://www.lrdirect.com/FRC1758-Synchro-3Rd-And-4Th-S2-3-Suff-A-B/
  '188d69a33bdcdd692f21f17b',
  // lucky8 off road | https://lucky8llc.com/collections/lr2/products/thermostat-housing-gasket
  '35d89ba9a77be98b67ccd800',
  // lucky8 off road | https://lucky8llc.com/collections/lr3-air-compressors/products/air-suspension-compressor-4
  '5233ea6a16b3a76a1b058b4e',
  // lucky8 off road | https://lucky8llc.com/collections/lr4-air-compressors/products/air-suspension-compressor-kit
  '7f7ece5cb1b6e154a9842141',
  // lucky8 off road | https://lucky8llc.com/products/floor-mounted-dip-switch
  'f2074c5e923502b1f4d1e699',
  // lucky8 off road | https://lucky8llc.com/products/fuel-lift-pump-2-25-diesel
  '2824e3e80f5888dbb00fa397',
  // lucky8 off road | https://lucky8llc.com/products/heavy-duty-steering-arm-drag-links-tie-rods
  'eeb3e730849545a6d705f817',
  // lucky8 off road | https://lucky8llc.com/products/stepper-motor-idle-air-valve
  'e32e27cecbfe740d655ac9d0',
  // motorsport direct | https://msport-direct.co.uk/product/classic-valvemaster-lead-replacement-fuel-petrol-additive-250ml-treats-250l/
  '7277bf9a94be63e2b1ba6ed3',
  // oldtimerbedarf | https://www.oldtimerbedarf.de/Spannungsregler-10V-elektronisch-Retrogehaeuse-negative-Masse-MGB
  '532b80e42e99d7c011ebc7ea',
  // online gearbox parts | https://www.onlinegearboxparts.com/product/lt76-overhaul-kit-main-box/
  'bbd143109b552addba2bb04b',
  // online gearbox parts | https://www.onlinegearboxparts.com/product/series-3-lt76-overhaul-kit-transfer-box-minus-2-x-thrust-washers/
  'a2abc6b8724f8526ee7ff952',
  // paddock spares | https://www.paddockspares.com/539741-swivel-chrome-ball.html
  '1ba839637218f56b5b7a861d',
  // paddock spares | https://www.paddockspares.com/569339-brake-master-cylinder-single-line-servo-round-reservoir.html
  'abdd43d80490783bfc31aac6',
  // paddock spares | https://www.paddockspares.com/591378-rear-halfshaft-rh-all-s2-2a-swb-to-80-81-10spline.html
  'c5e077485f8862e16d5f87cd',
  // paddock spares | https://www.paddockspares.com/608464-ball-joint-rh.html
  '41213f6faf0d167fb61e12d1',
  // paddock spares | https://www.paddockspares.com/para01-front-parabolic-springs-pair-2-leaf.html
  '21cbf19189ea73fda664cbe7',
  // paddock spares | https://www.paddockspares.com/para02-88in-rear-parabolic-springs-pair-3-leaf.html
  '77bca6ecf59f3a114accf527',
  // paddock spares | https://www.paddockspares.com/para03-109in-rear-parabolic-springs-pair-4-leaf.html
  '4994bfd57b78a3f4430615c9',
  // paddock spares | https://www.paddockspares.com/rtc3417-brake-shoes-axle-set-lwb-front-4cyl-swb-fr80-81.html
  '583b6bcc5be60d8db8093b98',
  // paddock spares | https://www.paddockspares.com/yrm356-aluminium-seat-box-frame-series-2-3.html
  '5fe0600c1696bea782c7a3f8',
  // paintman panels | https://www.paintmanpanels.co.uk/shop/330426-landrover-series-3-rhd-front-wing-outer-skin-rh/
  '7f1e63ade3ede3183c8d0f73',
  // paintman panels | https://www.paintmanpanels.co.uk/shop/330427-landrover-series-3-lhd-front-wing-outer-skin-lh/
  '3c8c8dca1d3b94d470e3f29b',
  // paintman panels | https://www.paintmanpanels.co.uk/shop/347474-landrover-series-3-lhd-front-wing-outer-skin-rh/
  '9e20aef58f7a46254ed6fe4b',
  // paintman panels | https://www.paintmanpanels.co.uk/shop/347475-landrover-series-3-rhd-front-wing-outer-skin-lh/
  'b716eee587b0bfc4610506ab',
  // paintman panels | https://www.paintmanpanels.co.uk/shop/land-rover-series-bottom-door-repair-section/
  'b2fea223e43d8d2c00da25d6',
  // paintman panels | https://www.paintmanpanels.co.uk/shop/mrc2595top-land-rover-series-2-3-front-wing-top-lh/
  '75b463a3f59965639526c405',
  // pedders | https://www.pedders.com.au/product/pedders-urethane-bush-leaf-spring-eye-shackle-kit-ep8072
  '3bb5cf510b39e2f1b6f8e0f1',
  // polybush | https://www.polybush.co.uk/product/1-series-kit-14/
  '720783b3a9f92d1c7a91b435',
  // qualitysuperchargers | https://qualitysuperchargers.com/products/genuine-eaton-oem-supercharger-rebuild-kit-snout-case-bearings-5-0-3-0-jaguar-land-rover-range-rover
  '8eb55f32d855cdc6ba6175ff',
  // qualitysuperchargers | https://qualitysuperchargers.com/products/genuine-oem-supercharger-rebuild-repair-jaguar-land-range-rover-5-0-peek-47mm-2010-2014
  '8521f9c25414441b3d47ebe1',
  // rimmer bros | https://rimmerbros.com/Item--i-CVH101150P
  'b438cd1776dc7ece4813298c',
  // rimmer bros | https://rimmerbros.com/Item--i-CVH101202P
  '3d8eb853db0abd9980d7bed6',
  // rimmer bros | https://rimmerbros.com/Item--i-CVH101212P
  '3eaf7e5af0e315f0e554e5e9',
  // rimmer bros | https://rimmerbros.com/Item--i-LCN000140L
  'ca59a5c30e61758da28fac2b',
  // rimmer bros | https://rimmerbros.com/Item--i-LDN10027P1SET
  '96cc0cac0d9ca5a05a7a9293',
  // rimmer bros | https://rimmerbros.com/Item--i-LR004405
  '6ba426284f7c76ed1e755900',
  // rimmer bros | https://rimmerbros.com/Item--i-LR006371P
  '8e013163ea2b7a4df21dc59c',
  // rimmer bros | https://rimmerbros.com/Item--i-LR006372P
  '136b4c50c5130b7edcc5c05f',
  // rimmer bros | https://rimmerbros.com/Item--i-LR033256
  'b23749f8328fa7df3e93945c',
  // rimmer bros | https://rimmerbros.com/Item--i-LR033257
  '1a7c2b70dcdfb56cc2ffbb3b',
  // rimmer bros | https://rimmerbros.com/Item--i-LR098914
  '8c07b3cf8cffd12b3136ea50',
  // rimmer bros | https://rimmerbros.com/Item--i-LVB500190A
  'b3df570283f341066aed762d',
  // rimmer bros | https://rimmerbros.com/Item--i-NRC1269P
  '7416d02d67d1a35bbe943447',
  // rimmer bros | https://rimmerbros.com/Item--i-PEM000030PK
  'bf680cd1c25e59a3b682a747',
  // rimmer bros | https://rimmerbros.com/Item--i-WAM2293KIT
  '44abe43ddb965f310564c8c5',
  // rimmer bros | https://rimmerbros.com/Item--i-ZUA001480
  'be66468270295254eff3a50b',
  // rovers north | https://www.roversnorth.com/parts/200tdicyl_rebuilt_cylinder_head_200tdi%26type%3D4
  '61243000ec341ddd81b94c74',
  // rovers north | https://www.roversnorth.com/parts/300tdicyl_cylinder_head_complete_assembly_300tdi
  '41356d53f02354a030da8352',
  // rovers north | https://www.roversnorth.com/parts/35595k_blower_motor_kit_w_fan_smith_s_heater_series_iia_iii%26type%3D4
  'fa4c0ec4ead3be60685ffc6c',
  // rovers north | https://www.roversnorth.com/parts/bls112l_ball_bearing_steering_gearbox_detent_series_ii_iia_iii
  '3924858d0753d345e4a561f1',
  // rovers north | https://www.roversnorth.com/parts/err2640_oil_seal_rear_crank_v8_3_5_3_9_4_0_4_6
  'bda33e3001bd3f6d63f96616',
  // rovers north | https://www.roversnorth.com/parts/err4762_hose_flame_trap_to_tee_3_5_and_3_9l_v8
  '2d274343fa123635abe6466c',
  // rovers north | https://www.roversnorth.com/parts/kvd001330gb_chassis_only_defender_110_td5_galvanized
  '6b94186396d82e8f8a33c051',
  // rovers north | https://www.roversnorth.com/parts/nrc236-18_rear_crossmember_with_18_inch_extensions_series_ii_iii_88
  '72ac690e0e30a6f890c89f0a',
  // rovers north | https://www.roversnorth.com/parts/nrc236-6_rear_crossmember_6_extension_109_black
  '5aa97991817d5ea7d250d168',
  // rovers north | https://www.roversnorth.com/parts/plb472_front_radiator_panel_early_iia_euro
  '710bb933cc7c477676b8eac1',
  // rovers north | https://www.roversnorth.com/parts/plb535_wheel_cylinder_right_hand_88_front_or_109_rear
  '5f61489eed2fe173ae36aedd',
  // rovers north | https://www.roversnorth.com/parts/plb536_wheel_cylinder_left_hand_88_front_or_109_rear
  '80b15329dfd671192ae7b755',
  // rovers north | https://www.roversnorth.com/parts/plb537_wheel_cylinder_right_hand_rear_series_88
  '036f55540b9c03b53cc11d74',
  // rovers north | https://www.roversnorth.com/parts/plb538_wheel_cylinder_left_hand_rear_series_88
  'ee409588eb8639692e5e3eaf',
  // rovers north | https://www.roversnorth.com/parts/plb541_wheel_cylinder_11_inch_brakes_left_hand_front_series_4_cylinder
  '051cda8574434015944340b4',
  // rovers north | https://www.roversnorth.com/parts/plb542_wheel_cylinder_11_inch_brakes_right_hand_front_series_4_cylinder
  'c71796fbbb6cbaf5485bf648',
  // rovers north | https://www.roversnorth.com/parts/plc069_seatbox_assembly_flat_pack_series_iia_iii
  '015c6908cf7200ad5d31b507',
  // rovers north | https://www.roversnorth.com/parts/plc314_swivel_ball_88_109_series_ii_iia_iii
  'fcfde88d0c3d1da2fed8f604',
  // rovers north | https://www.roversnorth.com/parts/plc538_synchro_ring_1st_2nd_series_iii
  '52f98730766fa8a259b293eb',
  // rovers north | https://www.roversnorth.com/parts/plc599_wheel_cylinder_front_left_hand_6_cylinder_and_v8
  '76080a38c23d8323b6ef1ce6',
  // rovers north | https://www.roversnorth.com/parts/plc600_wheel_cylinder_front_right_hand_6_cylinder_and_v8
  '01d4e06a7bfc3998abf25eb9',
  // rovers north | https://www.roversnorth.com/parts/plc752_master_cylinder_early_cv
  'c5a93dd7a202d53554bb4437',
  // rovers north | https://www.roversnorth.com/parts/pld496hd_radiator_assembly_200tdi_defender_heavy_duty
  'd1e3ad43eddf206247625b4c',
  // rovers north | https://www.roversnorth.com/parts/ple145_valve_seat_2_25l_petrol_exhaust
  '012e8b259e32528116cdebfe',
  // rovers north | https://www.roversnorth.com/parts/ple588s_stainless_steel_brake_shoe_adjuster_kit_series_ii_iia_iii_and_defender_with_rear_drum_brakes
  '98faa2f3e157a0d4fa343401',
  // rovers north | https://www.roversnorth.com/parts/plf334a_water_pump_oem_4_cylinder_series_iia_iii_civilian
  '4e9448493bc2b8c9842e3172',
  // rovers north | https://www.roversnorth.com/parts/plk200hb_head_bolt_kit_200tdi
  '92cb7ee1fb556678d8df7156',
  // rovers north | https://www.roversnorth.com/parts/plm066_t_seal_rear_main_bearing_t_seal_v8
  'c800c38cffb45fae95cd48b0',
  // rovers north | https://www.roversnorth.com/parts/plm098_hose_pcv_to_manifold_v8
  '41dee1170b77543a75af45e2',
  // rovers north | https://www.roversnorth.com/parts/plm134_sensor_coolant_efi_defender_disco_i_p38a
  'ff5dc0479bc12a7f085bf4dc',
  // rovers north | https://www.roversnorth.com/parts/ply666_spring_synchro_assy_series_iia_iii
  '2b84783fcdac152dd26ad50b',
  // rovers north | https://www.roversnorth.com/parts/rna3181p_swivel_ball_rebuild_kit_series_iia_iii
  '273e849b0e3d431a5a7afc50',
  // rovers north | https://www.roversnorth.com/parts/rnk1124_parabolic_spring_set_of_4_2_4leaf_88_109%26type%3D3
  '661d2724b147c01c4227354a',
  // rovers north | https://www.roversnorth.com/parts/rnk951_alternator_conversion_series_iia%26type%3D3
  'ee308f7fdb7442ba1fa99470',
  // rovers north | https://www.roversnorth.com/parts/shp0001_smiths_round_heater_core_matrix
  '6cc91cda972cde72b9e2112c',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=268847&eq=&type=0
  '89f3866b32b5fdee83db89f9',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=CHAS34&eq=&type=0
  '4dd45fbed3fa52d44dcb7211',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=PLE588S&type=0
  '86efe01f8ef3bb5bfc74cada',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=PLF193&type=0
  '6eec31ccfa42d8bddb175872',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=PLF360K
  'fa49cae134f6b53be93a51bf',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=PLX862-3R&eq=&type=0
  'a81ac9ac89421754884682fb',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=PLX864-5R&eq=&type=0
  'f50282f69e827eee37115c76',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=RNA3168K&eq=&type=3
  '70978b2720ed8e0322a6bf5b',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=RNA3169&eq=&type=0
  '1cf17b72db45023ed4f9cfbd',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=RNA3169P&eq=&type=0
  '61b4dc42e75b18ed3174bf27',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=RNA3178&type=0
  '2317a58fa4ed81da16740771',
  // rovers north | https://www.roversnorth.com/ProductInfo.aspx?code=RNA3181&eq=&type=0
  'fdc191fd590d414cc5c20553',
  // rst landrovers | https://www.rst-landrovers.co.uk/shop/axle-suspension/prop-shafts-bearings-joints/land-rover-75mm-prop-shaft-universal-joint-uj-rtc3458g/
  'e906f281d8389cfccb1f32fc',
  // rst landrovers | https://www.rst-landrovers.co.uk/shop/fuel-amp-emissions/sender-units-fuel-amp-emissions/oem-land-rover-series-2-2a-3-fuel-tank-sender-unit-90560612/
  'c6d17f8b508719c51c7d7d6d',
  // rst landrovers | https://www.rst-landrovers.co.uk/shop/uncategorized/land-rover-series-2-2a-3-swb-88-petrol-diesel-fuel-tank-552174/
  '0d9f26a475702b7158361911',
  // safari engineering | https://safari-engineering.co.uk/new-land-rover-parts/repair-service-parts/transmission-parts/gearboxes/output-shaft-oil-seal-front-rear-series-1-series-2-series-3-frc1780
  'e792398bf83c3b3dc83660db',
  // sc parts group | https://www.scparts.co.uk/en/brake-shoes/212334/
  '888c7852652a355fb50fa79b',
  // sc parts group | https://www.scparts.co.uk/en/chassis-frame/365594/
  'd9b77ebb1dc78dfe72178c21',
  // sc parts group | https://www.scparts.co.uk/en/chassis-frame/365621/
  '127911b574629abe6d41e4de',
  // sc parts group | https://www.scparts.co.uk/en/chassis-frame/371781/
  '50885775adf925f9d656252d',
  // sc parts group | https://www.scparts.co.uk/en/chassis-frame/485271/
  '5128308a0d749bb7d601ecbe',
  // sc parts group | https://www.scparts.co.uk/en/chassis-frame/520404/
  'ba6a0febe38c11b0dbe3b0ba',
  // sc parts group | https://www.scparts.co.uk/en/chassis-outrigger/365603/
  '2511454cd4c91d3d2ef97711',
  // sc parts group | https://www.scparts.co.uk/en/crossmember/481391/
  'c49f17f35fbf21bccee11527',
  // sc parts group | https://www.scparts.co.uk/en/cylinder-head-gasket/363609/
  '352a551d4693628cdc1c097b',
  // sc parts group | https://www.scparts.co.uk/en/leaf-spring-bracket/365592/
  'c2f6930dee9cc904867d9bdd',
  // sc parts group | https://www.scparts.co.uk/en/leaf-spring-bracket/365593/
  '6aa7296d999aab572cd548a3',
  // sc parts group | https://www.scparts.co.uk/en/leaf-spring-bracket/366015/
  'a20bb7c4037c5d681cffcdc9',
  // sc parts group | https://www.scparts.co.uk/en/leaf-spring-bracket/487107/
  '89365f1b0d536c4060570ab2',
  // sc parts group | https://www.scparts.co.uk/en/oil-sealing-ring/363722/
  'c9c26d5d0975c53f4b4238f9',
  // sc parts group | https://www.scparts.co.uk/en/propshaft/373593/
  '6419ab548dd1d7b0f9115a30',
  // sc parts group | https://www.scparts.co.uk/en/radiator/506643/
  '7fc4655765826d92729ab819',
  // sc parts group | https://www.scparts.co.uk/en/timing-chain-tensioner/367524/
  '083ca9ce8219522be9b625d9',
  // sc parts group | https://www.scparts.co.uk/en/timing-chain-tensioner/369007/
  'e62388ec2a137d4791352feb',
  // series magic | https://www.seriesmagic.com.au/shop/p/frc4076-and-frc4077-high-quality-mainshaft-bronze-split-bush-set-series-1-2-2a-3-1953-plus
  'e65d5726ce6d0e0b96de76a4',
  // series parts | https://seriesparts.co.uk/PartDetail?stockid=2127
  '3e36ebcb1e152ab4d1e71006',
  // series parts | https://www.seriesparts.co.uk/PartDetail?stockid=214
  '69a60b60d73c1598cda49ef9',
  // shielder chassis | https://shielderchassis.com/products/defender-110-200tdi-2-5td-2-5na-galvanised-bulkhead
  'f3bd412f40140e39df3cdb93',
  // shielder chassis | https://shielderchassis.com/products/defender-110-300tdi-galvanised-bulkhead
  'b255a12d113ab43b09de87bb',
  // shielder chassis | https://shielderchassis.com/products/defender-110-v8-galvanised-bulkhead
  'f9c45b6059251a31e0c73d00',
  // shielder chassis | https://shielderchassis.com/products/defender-130-200tdi-2-5td-2-5na-galvanised-bulkhead
  '6dfb235a132a8c22de1f50c5',
  // shielder chassis | https://shielderchassis.com/products/defender-130-300tdi-galvanised-bulkhead
  'a3052de51528e168f2252f70',
  // shielder chassis | https://shielderchassis.com/products/defender-90-200tdi-2-5td-2-5na-galvanised-bulkhead
  '7ccbac11dcfc7b57b73058ff',
  // shielder chassis | https://shielderchassis.com/products/defender-90-300tdi-galvanised-bulkhead
  'c097da82d304239c3a222195',
  // shielder chassis | https://shielderchassis.com/products/defender-90-v8-galvanised-bulkhead
  '2b181cd726e8235f21b89d0e',
  // shielder chassis | https://shielderchassis.com/products/land-rover-series-2a-88-109-inch-galvanised-bulkhead
  '50aadf12e78bdbdda29c8cb8',
  // sp 4x4 | https://www.sp-4x4.com/Bulkhead_Outrigger_LH_STC8355_p/lr513gn-s.htm
  'ec64819fd21e6c40072f285f',
  // sp 4x4 | https://www.sp-4x4.com/Bulkhead_Outrigger_RH_STC8354_p/lr513go-s.htm
  'a91ec812dab18c1be8621f00',
  // sp 4x4 | https://www.sp-4x4.com/DA2008N_Chassis_Leg_Front_Left_Hand_For_Land_p/da2008n.htm
  'a54174b8f09ebf6adee65fae',
  // sp 4x4 | https://www.sp-4x4.com/DA2008O_Chassis_Leg_Front_Right_Hand_For_Lan_p/da2008o.htm
  '52b981089a9ba3ed957d9ed5',
  // sp 4x4 | https://www.sp-4x4.com/GALVANISED_PAIR_SERIES_3_DOOR_TOPS_p/jwp5380.htm
  'fe46d2daa028782566b75836',
  // sp 4x4 | https://www.sp-4x4.com/JWP5060_Galvanised_Def_Fully_Built_up_Complete_R_p/jwp5060.htm
  '0bd2c761349147c2ca71505b',
  // sp 4x4 | https://www.sp-4x4.com/JWP5061_Galvanised_Def_Fully_Built_up_Complete_L_p/jwp5061.htm
  '71c13979267c14dbdbe4fc93',
  // sp 4x4 | https://www.sp-4x4.com/LR250_88_Rear_Crossmember_with_extensions_with_p/lr250.htm
  '04030348d5d776877683f976',
  // sp 4x4 | https://www.sp-4x4.com/LR252_109_Rear_1_4_Chassis_With_Ext_Inc_S_p/lr252.htm
  'd04488f8e8320a5509c8d417',
  // sp 4x4 | https://www.sp-4x4.com/LR721HDG_Heavy_Duty_Galvanised_Rear_Crossmember_p/lr721hdg.htm
  '8234f960a1b69d05af9cd137',
  // sp 4x4 | https://www.sp-4x4.com/LR722G_Galvanised_Rear_Crossmember_for_Defender_p/lr722.htm
  'a536941ae648a0e29902bcf3',
  // sp 4x4 | https://www.sp-4x4.com/product_p/lrc1021.htm
  '46fcbe27605f887b0a4ad9cc',
  // sp 4x4 | https://www.sp-4x4.com/TD5_Rear_Cross_member_Basic_KVB000290_p/lr610g.htm
  'e28deb089ad5f30d5dca9179',
  // sp 4x4 | https://www.sp-4x4.com/Timing_Belt_Kit_300_Tdi_Modified_STC4096L_p/stc4096r.htm
  'f82f1fe45b67b9cb41bbadc1',
  // toni's einspritzpumpenservice | https://toni-einspritzpumpenservices.de/produkt/einspritzpumpe-land-rover-225l-dpa-3249f751-3249f750/
  'd8fbe2e2cc12c010bfb14312',
  // turner engineering | https://www.turnerengineering.co.uk/products/542492-rear-oil-seal-kit-3mb-c2x20634935
  'd733190655421154ee9ee7fd',
  // turner engineering | https://www.turnerengineering.co.uk/products/err-5057-fuel-pump-copy
  '992b10e72d95948a8590142c',
  // turner engineering | https://www.turnerengineering.co.uk/products/lr058095-oil-pump
  'fa062602b61cccd540ec956a',
  // turner engineering | https://www.turnerengineering.co.uk/products/series-2-petrol-2-25-3mb-crankshaft-010-mains-big-ends
  '5d69aebea53b439326812b8e',
  // turner engineering | https://www.turnerengineering.co.uk/products/stc-1567-gasket-set-top-inc-elring-head-gasket
  '2394b2366365d504100391be',
  // turner engineering | https://www.turnerengineering.co.uk/products/yll500040-head-locating-dowel
  '617846a88ca5ea3357d083ee',
  // twinwoods 4x4 | https://twinwoods4x4.com/product/defender-swivel-housing-kit-non-abs-ga3179g-da3179g/
  '186b8688cbe25c2bc5475463',
  // twinwoods 4x4 | https://twinwoods4x4.com/product/lqx100130-td5-oil-pump-chain-sprocket/
  'ac46e4ca6454da60dc213d3d',
  // twinwoods 4x4 | https://twinwoods4x4.com/product/td5-oil-pump-bolt-discovery-defender-lyp101400-lyg101210/
  '41a911bf4155b56bc4632644',
  // vitesse land rover | https://vitesse-ltd.co.uk/product/timing-chain-kit-2-25-pet/
  'd73893a34305fda3f15e3c40',
  // vitesse land rover parts | https://vitesse-ltd.co.uk/product/shock-absorber-series-88-front/
  '436254569b69c7a49a67c18a',
  // vr super store | https://www.v-rigger.com/Duralac-Pas-115ml-Tube
  '4e48be59a5213f9d54eecd6f',
  // yrm metal solutions | https://yrmit.co.uk/product/bottom-of-vent-bulkhead-repair-panel-lr-defender-series-2-3/
  '96c8ac4c2920dd45404e2d11',
  // yrm metal solutions | https://yrmit.co.uk/product/bulkhead-upper-with-vents-repair-panel-lr-defender-lr-series-2-2a-3/
  '381e66dcab3b3302f9d89a3a',
  // yrm metal solutions | https://yrmit.co.uk/product/door-repair-section-lr-series-2-2a-3/
  '69fc67f883548edad410916a',
  // yrm metal solutions | https://yrmit.co.uk/product/extended-bulkhead-repair-panels-lr-defender-lr-series-2-2a-3/
  'e70165a0bcaa4b61ff5007a4',
  // yrm metal solutions | https://yrmit.co.uk/product/hdg-tailgate-capping-lr-defender-lr-series-2-2a-3/
  'e9c7192a686474880fbb719c',
  // yrm metal solutions | https://yrmit.co.uk/product/lhs-footwell-repair-panel-lr-defender/
  '58e5dd6173f90c8a40294fa8',
  // yrm metal solutions | https://yrmit.co.uk/product/lhs-lhd-footwell-repair-panel-ribbed-lr-series-2-2a-3/
  '960fcafff61aa1fbf3a95cb9',
  // yrm metal solutions | https://yrmit.co.uk/product/lhs-lhd-rhd-above-footwell-bulkhead-repair-panel-lr-defender/
  'c261a36ae92fe0c68e2fa235',
  // yrm metal solutions | https://yrmit.co.uk/product/lhs-lower-door-pillar-repair-section-lr-defender-lr-series-2-2a-3/
  '9a780fb90b4f868d55e73a7f',
  // yrm metal solutions | https://yrmit.co.uk/product/lhs-rhd-footwell-repair-panel-ribbed-lr-series-2-2a-3/
  '5e0f9846fee89f8d46a149a1',
  // yrm metal solutions | https://yrmit.co.uk/product/rhs-footwell-repair-panel-lr-defender/
  'f90f7e1f1257fc49932542cc',
  // yrm metal solutions | https://yrmit.co.uk/product/rhs-lhd-footwell-repair-panel-ribbed-lr-series-2-2a-3/
  '0d95354973f5a34ac48b74ed',
  // yrm metal solutions | https://yrmit.co.uk/product/rhs-lhd-rhd-above-footwell-bulkhead-repair-panel-lr-defender/
  'dc4c17a95cfec2a022b49704',
  // yrm metal solutions | https://yrmit.co.uk/product/rhs-lower-door-pillar-repair-section-lr-defender-lr-series-2-2a-3/
  'd71cb510396f73c010ca6bf2',
  // yrm metal solutions | https://yrmit.co.uk/product/rhs-rhd-footwell-repair-panel-ribbed-lr-series-2-2a-3/
  '033d2676c22876bb817957de',
  // yrm metal solutions | https://yrmit.co.uk/product/top-of-vent-bulkhead-repair-panel-lr-defender-series-2-3/
  '0f2beb0229bbb6c9e97372b1',
] as const;

export const retailerHostFingerprints = [
  // 3brothersclassicrovers.com
  '4df3d6ff033ac4f1ade54669',
  // airsuspension.com
  '914f692e0c6f3c78418b3008',
  // angclassiccarparts.co.uk
  '9c7d3b477af8e5527e5bbc93',
  // antipodeanparts.com.au
  '4d382eaab4445f2cf25ef474',
  // ashcroft-transmissions.co.uk
  '622742281058a584af563001',
  // autoelectricsupplies.co.uk
  '4d90942ce3fdbcd57b8ccead',
  // automec.co.uk
  'b377711c5f1664018256f5e4',
  // autosparks.co.uk
  'fa95f5f2aca4c801a7ae28d4',
  // bearmach.es
  '941fb357a21e20920edc4ece',
  // bellengineering.co.uk
  '763999730d017e4fdd912380',
  // bmiparts.com.au
  'bb980cdfeeb62c78913533b3',
  // britcar.com
  '2bfc4e147253e7482a478aca',
  // britishautoparts.com.au
  '95c07177eb251e89553d9fdd',
  // britishparts.co.uk
  '85c7fa04ec5eada782bf610e',
  // britishwiring.com
  '37011398eae45703c1684e42',
  // brookwell.co.uk
  'e2ecec66c756bee520680306',
  // ckdshop.co.uk
  '83d0f792c8e90412dc246e8f',
  // copperbraid.co.uk
  '10c80c0199cf9994d01c9233',
  // ddsmetal.co.uk
  '2cb30467f2c964341e35d825',
  // designdevelopmenteng.co.uk
  'd7c497fe30210b63956abb81',
  // dingocroft.co.uk
  'ab06baf138b7cd9de8aafbf9',
  // dtc-uk.com
  '5d8367868e9119f34408f488',
  // ebay.co.uk
  'b8ce2a1a552a116904d8b01a',
  // embertonimperial.com
  'c3ca4d888acf820962a2c120',
  // empiretuning.co.uk
  '094a77f9455576c899b2a535',
  // engelimports.com
  'aa48aea98705c8d9eff6c684',
  // famousfour.co.uk
  '2d4701c314d9cc04e476e856',
  // jgs4x4.co.uk
  '68809bcd3fff5a93d320bd3c',
  // johncraddockltd.co.uk
  'b10281b7fa55db7f57a5b5ae',
  // landrovertreasureshop.com
  '837f7a493fa9aaf625653900',
  // limora.com
  '73e0bb9d6c00d64bd8b5c8a9',
  // lofclutches.com
  'be64e516a110689576b7c624',
  // lrdirect.com
  '2f21ef33a49631ee87defcb7',
  // lroe.co.uk
  '73a950365d1f5b155662ac2b',
  // lrparts.net
  'aa8ee79877fd4275750f9036',
  // lrsoc.com
  'a372056a415e0473ce4e336c',
  // lucky8llc.com
  '06394056d93a93fcaaff9e5c',
  // msport-direct.co.uk
  'c5d6095571e7a431f9ef6426',
  // oldtimerbedarf.de
  '2d8ea6aade2337d7beb4cedc',
  // onlinegearboxparts.com
  '537abef63294ead94a3ffdf1',
  // paddockspares.com
  '4d199f108bf953668d2dbc6c',
  // paintmanpanels.co.uk
  'dc83566bb409518636543e96',
  // pedders.com.au
  '727a5f52bb76b71036e41641',
  // polybush.co.uk
  '4542fe8e3784e181b16d20e8',
  // qualitysuperchargers.com
  'e37cf17f6c25b7610eab743b',
  // rimmerbros.com
  '681855952667ff09608579bb',
  // roverparts.eu
  '2fa4cd0f564ddc7d89d8d2a2',
  // roversnorth.com
  '2f9ee45ad85951ca6da104a3',
  // rst-landrovers.co.uk
  '1c96863c60ccba02118f3676',
  // safari-engineering.co.uk
  'bc89107cd9c2fde071d9f858',
  // scparts.co.uk
  '418aba5881e1a9f889f0c799',
  // seriesmagic.com.au
  '1a06e64caed923347f9de870',
  // seriesparts.co.uk
  '744a10b487b001a37d48c093',
  // shielderchassis.com
  'ef80d9472ad4f4b60c42c599',
  // sp-4x4.com
  '18d12d75ca1001435037c8f7',
  // toni-einspritzpumpenservices.de
  '33f0af5118fdef0d95af1843',
  // turnerengineering.co.uk
  '42dda4f99117989e6fb6d9d0',
  // twinwoods4x4.com
  'd3ddf170a75df625e7bd67f8',
  // v-rigger.com
  '566b9f63495edb2728dbdf8e',
  // vitesse-ltd.co.uk
  'e7c29f09e7a6788eec28b86a',
  // yrmit.co.uk
  '8e9a595c0c50d63b1b4ecc7b',
] as const;
