// GENERATED by scripts/build-repair-first-verified-batch.mjs for Lexus.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://frsport.com/products/aisin-tkt009-engine-timing-belt-kit-water-pump
  'c5329a62d39786c3e85b1a90',
  // https://modulemechanics.com/product/06370-07470-climate-control-module-with-warranty-lexus-is300-oem-control-module/
  'f7deec4c7f60f2dd3ae536dd',
  // https://modulemechanics.com/product/1997-lexus-ls400-engine-computer-ecu-repair-service/
  '0286faa400ab8ab84b8f2329',
  // https://parts.frontiertoyota.com/oem-parts/toyota-super-long-life-coolant-272sllc2
  '664703fcc2dee5c9f912799f',
  // https://parts.frontiertoyota.com/oem-parts/toyota-super-long-life-coolant-50-50-prediluted-272sllc2
  '193129af6b3c6a63749cb700',
  // https://shopfigs.com/v5/SUSPENSION-CHASSIS/FIGS-ADJUSTABLE-LCAs/FIGS-FRONT-LOWER-OE-REPLACEMENT-ADJUSTABLE-MEGA-ARM-LCA-MKIV-SUPRA-SC300-SC400-G1070
  '2c8e026d7dfb689472293bae',
  // https://taninautoelectronix.com/product/1992-2000-lexus-sc300-sc400-climate-control-repair/
  '2fd6561cbf3d0a9f54ad82e0',
  // https://taninautoelectronix.com/product/tae-1992-2000-lexus-sc300-sc400-climate-control-lcd-screen/
  'd6dfcde0fa4f7b1f07e7e698',
  // https://tmengineering.net/webstore/index.php?main_page=product_info&products_id=21
  '8c291e259b4a074a2ddce59a',
  // https://www.autozone.com/p/valvoline-auto-transmission-fluid-773636/1180479
  '8bb6a23e1e27366d0b597bfc',
  // https://www.buyautoparts.com/buynow/75-23697-ai
  'a5dae639f8009dbfb9b72fd5',
  // https://www.finditparts.com/products/16749558/arnott-industries-c-3418
  '02c700d72397caec07dc7496',
  // https://www.finditparts.com/products/6034365/aisin-tkt-021
  '982e3feeb500f1a0cc09f035',
  // https://www.finditparts.com/products/6034370/aisin-tkt-030
  '8e31c1d9106ed5d159df04c0',
  // https://www.hybridrestoration.com/batteries/2011-2017-lexus-ct200h-hybrid-battery-replacement
  '147c8796b824e67f5511187b',
  // https://www.hybridrestoration.com/batteries/2013-2017-lexus-es300h-hybrid-battery-replacement
  '9ea378548883e92838574472',
  // https://www.lexuspartsnow.com/parts/lexus-accumulator-front-suspension-control~49141-60020.html
  '8f990c9db378b48d401b4673',
  // https://www.lexuspartsnow.com/parts/lexus-accumulator-rear-suspension-control~49151-60020.html
  '428cc5be63987fa9ccb441ab',
  // https://www.lexuspartsnow.com/parts/lexus-actuator-assy-trans~36410-60083.html
  'd4ab546938b1df53d5f50c6a',
  // https://www.lexuspartsnow.com/parts/lexus-actuator-assy-trans~36410-60112.html
  'e2d57281a5ce999ebef85e54',
  // https://www.lexuspartsnow.com/parts/lexus-actuator-assy-trans~36410-60113.html
  '8a6a2a071afa5bd4d87fe32a',
  // https://www.lexuspartsnow.com/parts/lexus-alternator-assy~27060-46300.html
  '133cc5f572da5e3e63681e86',
  // https://www.lexuspartsnow.com/parts/lexus-battery-assy-hv-sup~g9510-33112.html
  'fbf871c9e17237953bba4fea',
  // https://www.lexuspartsnow.com/parts/lexus-battery-assy-hv-sup~g9510-76014.html
  'e22c02a8168e84158dfb7db3',
  // https://www.lexuspartsnow.com/parts/lexus-cap-sub-assy-distributor~19101-70020.html
  '1eb114e767bfab4fddf8fff2',
  // https://www.lexuspartsnow.com/parts/lexus-compressor-assy~88320-3a231.html
  '4b79e7cdca2891fc289d9141',
  // https://www.lexuspartsnow.com/parts/lexus-condenser-assy~88460-24091.html
  '0ec9bfe25733da7986d7f5ed',
  // https://www.lexuspartsnow.com/parts/lexus-cylinder-assy-pneum~48080-60020.html
  '1c8ea0b731d4490482966e1f',
  // https://www.lexuspartsnow.com/parts/lexus-cylinder-assy-pneum~48090-60020.html
  '6389e5f79e276d38c84e37b9',
  // https://www.lexuspartsnow.com/parts/lexus-cylinder-rr-stabili~48886-60032.html
  '60c747d676b4938162141c40',
  // https://www.lexuspartsnow.com/parts/lexus-cylinder-sub-assy-f~48007-60023.html
  'ea520516af48aba97e48f938',
  // https://www.lexuspartsnow.com/parts/lexus-disc-fr~43512-0c040.html
  '7f2d4f05193c390e89fc700a',
  // https://www.lexuspartsnow.com/parts/lexus-distributor-assy~19100-46011.html
  'd353ec5cd0e55107aa9c4fff',
  // https://www.lexuspartsnow.com/parts/lexus-dryer-cooler~88474-08010.html
  'c3ff338786dab8aa6d7b79a1',
  // https://www.lexuspartsnow.com/parts/lexus-dryer-cooler~88474-12010.html
  'ec60dee979fb2f3c85aeddb1',
  // https://www.lexuspartsnow.com/parts/lexus-dryer-cooler~88474-17010.html
  '90ee6fdf7a0821b7766a1ac3',
  // https://www.lexuspartsnow.com/parts/lexus-dryer-cooler~88474-47010.html
  '28bcf6fe7f687d8434557a6e',
  // https://www.lexuspartsnow.com/parts/lexus-dryer-cooler~88474-47020.html
  '12764824b036e33c9143762a',
  // https://www.lexuspartsnow.com/parts/lexus-evaporator-sub-assy~88501-06113.html
  'ac22dfd63067be538d14e6d7',
  // https://www.lexuspartsnow.com/parts/lexus-evaporator-sub-assy~88501-0e120.html
  'f0edcff6cc280df5e4bdd2ea',
  // https://www.lexuspartsnow.com/parts/lexus-evaporator-sub-assy~88501-0e130.html
  '8075ff73730387513e2b54ae',
  // https://www.lexuspartsnow.com/parts/lexus-evaporator-sub-assy~88501-48301.html
  'aed22a129d9658280909dc79',
  // https://www.lexuspartsnow.com/parts/lexus-evaporator-sub-assy~88501-48311.html
  'fa5ed7b8256b4e90a2c867d7',
  // https://www.lexuspartsnow.com/parts/lexus-fitting-kit-disc-brake-front~04947-60140.html
  '9d173d17b79557f658666a8e',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover-no-2~11214-50011.html
  '4dbdfc81d9de6edd4e3567e8',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover~11213-46020.html
  '3ee4cb6858452296fe81990b',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover~11213-46030.html
  'e9704e6f10b4fe24bb47a722',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover~11213-50021.html
  '39c28887382d3bec565551d8',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover~11213-50031.html
  '24b7f6652c4df0885c81efc2',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover~11214-46011.html
  'fd8456d8d73ec4f2b686aec9',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-intake-manifold-to-head-no-1~17171-50011.html
  '6fe9aef1d455df3344baf630',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-intake-manifold-to-head-no-1~17171-50020.html
  'ac15bbcac5c69d1824e7e212',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-kit-power-steering-pump~04446-30172.html
  '9a414aa33d76aaff1d6a5a16',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-kit-power-steering-pump~04446-50011.html
  '1755043a455fa587d63b1c41',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-pressure-port~44327-30030.html
  '6207c0afcddb39139c885513',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-spark-plug-tube~11193-15010.html
  '556f6618bebf1794ce649857',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-spark-plug-tube~11193-70010.html
  '83743bee2fe6188560b5efdd',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-throttle-body~22271-50010.html
  '54b9264e2d4f0392ea95122e',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-throttle-body~22271-50042.html
  '12c4b19f09af956bcc317762',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-transmission-drain-plug~35178-30010.html
  'cf5a13ea55e73030649702f3',
  // https://www.lexuspartsnow.com/parts/lexus-gasket-water-pump~16271-36040.html
  '820dbe2ca37509f379fc3f2f',
  // https://www.lexuspartsnow.com/parts/lexus-housing-sub-assy-st~48006-60031.html
  'c4c776889872226739836ba3',
  // https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front-lh~43340-59066.html
  'b6812da6b1101b4c07c9825d',
  // https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front-rh~43330-59066.html
  '10152f2245f4ed9acd0fbfaa',
  // https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front~43330-59036.html
  '53efca0c79a1e212456cf537',
  // https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front~43330-59045.html
  'fd6790d2f72e749627e97734',
  // https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front~43340-59036.html
  '2c57ff3581c5f95615996cc2',
  // https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front~43340-59045.html
  'b06b8b6bc48e5fa894db7fe9',
  // https://www.lexuspartsnow.com/parts/lexus-link-assy-electric~44200-30471.html
  '975968dbb0d049703c11f1df',
  // https://www.lexuspartsnow.com/parts/lexus-link-assy-power-ste~44200-30611.html
  '9998f3acb90d4770f92a9f64',
  // https://www.lexuspartsnow.com/parts/lexus-link-assy-power-ste~44200-30641.html
  'ae4f0eeca8f623321d4fc7df',
  // https://www.lexuspartsnow.com/parts/lexus-link-assy-power-steering~44200-30620.html
  'c84a22c2c362c3a1929e360a',
  // https://www.lexuspartsnow.com/parts/lexus-pad-kit-disc-brake~04465-34040.html
  'd6c0e5da59b22f1b9f811685',
  // https://www.lexuspartsnow.com/parts/lexus-pulley-camshaft-timing~13050-46010.html
  '6b7342707d2a5595aaa8d039',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-air~17600-0f010.html
  '0a79d07a9f12d19e145f6627',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-vane~44320-14240.html
  '1ae3e7299b5855ced7a30626',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-vane~44320-50010.html
  '6082f2ff69389d87229d2e3f',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-vane~44320-50020.html
  '4af40f757db199a7081ab7a4',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-vane~44320-50030.html
  'e133663a826c0b0ba20a00a6',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-water-w-m~g9040-47090.html
  'eabd6b0d4dd47e890615b590',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-water-w-m~g9040-52010.html
  'e345df9ed357b36963be1fa1',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-water~16100-09442.html
  'ee0624fad33d6181bcd79f39',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-water~16100-09690.html
  'dcc9649b0d997468bdd9f947',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-water~16100-39436.html
  '1f6419e922a44abe1f0ec89b',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-water~16100-39595.html
  'c64e203dc743a79ed39bd705',
  // https://www.lexuspartsnow.com/parts/lexus-pump-assy-water~16100-39616.html
  'fdd503e56cbb0603c2dcf5ff',
  // https://www.lexuspartsnow.com/parts/lexus-pump-motor-assy-h~48910-60033.html
  '05a935a372fd4a7b04ff212d',
  // https://www.lexuspartsnow.com/parts/lexus-regulator-sub-assy-front-door-window-lh~69802-24041.html
  '6452ca47b50e63166dbb3890',
  // https://www.lexuspartsnow.com/parts/lexus-regulator-sub-assy-front-door-window-rh~69801-24041.html
  '3694b3dd98210b3863b2d82b',
  // https://www.lexuspartsnow.com/parts/lexus-regulator-sub-assy~69801-24033.html
  '3b2609ebd8f0e0546f523221',
  // https://www.lexuspartsnow.com/parts/lexus-regulator-sub-assy~69802-24033.html
  '6c813a59fb215c9a614cdbd0',
  // https://www.lexuspartsnow.com/parts/lexus-reman-compressor~88320-3a231-84.html
  'cdb1c518e988c502338ee1a4',
  // https://www.lexuspartsnow.com/parts/lexus-ring-o~90301-56009.html
  '2a68c4c55a9b9ae9470decfc',
  // https://www.lexuspartsnow.com/parts/lexus-rotor-sub-assy-distributor~19102-46011.html
  'a9a0f4108d498acb13100904',
  // https://www.lexuspartsnow.com/parts/lexus-seal-type-t-oil~90311-38036.html
  '124a25650e9f4948b00b64bc',
  // https://www.lexuspartsnow.com/parts/lexus-seal-type-t-oil~90311-40020.html
  '9a643b898e16c8a9ed2be9b3',
  // https://www.lexuspartsnow.com/parts/lexus-seal-type-t-oil~90311-a0001.html
  'b1f2f81556956831c5c3200e',
  // https://www.lexuspartsnow.com/parts/lexus-seal-type-t-oil~90311-a0004.html
  '04bf812685dee7eea6d2a17f',
  // https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-hei~89407-60040.html
  '688fca6667111b9926026a0e',
  // https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-hei~89408-60030.html
  'f5cf626386ad6e87e93721aa',
  // https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control-front-lh~89406-50130.html
  '1a6581487ca5f4d35a074bbb',
  // https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control-front-rh~89405-50070.html
  '447cbd3b26203a72dee69fd3',
  // https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control-front-rh~89405-50100.html
  '96b75d8bb5daa41631053818',
  // https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control-rear-lh~89408-50070.html
  '3e099c0dc6e4f2ec0e451041',
  // https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control-rear-rh~89407-50070.html
  'ece6bde58e1a86658d47f758',
  // https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control~89406-50100.html
  'a257899b68aa94ff4a7d1868',
  // https://www.lexuspartsnow.com/parts/lexus-shaft-sub-assy-steering-intermediate~45202-0e010.html
  '546d498dd73292dc2ccb250f',
  // https://www.lexuspartsnow.com/parts/lexus-shim-kit-anti-squea~04945-0c060.html
  '0c292b83baf38bf29e04114d',
  // https://www.lexuspartsnow.com/parts/lexus-spring-coil-fr~48131-60k20.html
  'd503f2a4fcf1a1cf717a6bb4',
  // https://www.lexuspartsnow.com/parts/lexus-spring-coil-fr~48131-60k30.html
  'e0ecbc34662101c25f3b2383',
  // https://www.lexuspartsnow.com/parts/lexus-spring-coil-rr~48231-60j11.html
  '50ef848d7491948d797c28d6',
  // https://www.lexuspartsnow.com/parts/lexus-starter-assy~28100-50020.html
  '49f79c987ae62556fa4233ed',
  // https://www.lexuspartsnow.com/parts/lexus-starter-assy~28100-50062.html
  'd264d1f13058c5ef5ec7e475',
  // https://www.lexuspartsnow.com/parts/lexus-strainer-assy-oil~35330-30011.html
  'f4944281cd5f1e92e8766f5c',
  // https://www.lexuspartsnow.com/parts/lexus-tensioner-assy-chain-no-1~13540-46030.html
  'cab36e468efdda50e3a52b43',
  // https://www.lexuspartsnow.com/parts/lexus-tube-assy-pressure-feed~44410-48030.html
  'b97e1a33f5632445191d19b9',
  // https://www.lexuspartsnow.com/parts/lexus-tube-assy-pressure-feed~44410-48121.html
  '787d4258cbf3b2c148154185',
  // https://www.lexuspartsnow.com/parts/lexus-tube-assy-pressure-feed~44410-50060.html
  '2b97779c0bfae8f4e65b6b4c',
  // https://www.lexuspartsnow.com/parts/lexus-valve-assy-air-swit~25710-50022.html
  '37e8b52c3cbae4452db205bc',
  // https://www.lexuspartsnow.com/parts/lexus-valve-assy-front-shock-absorber-control-lh~48020-60010.html
  '885bbc67e25d6fc52f7071ed',
  // https://www.lexuspartsnow.com/parts/lexus-valve-assy-front-shock-absorber-control-rh~48010-60010.html
  'c22b76d0cf14eb68c3e5b409',
  // https://www.lexuspartsnow.com/parts/lexus-valve-assy-height-control-no-1~48940-60020.html
  '689d12211276da2c359dea91',
  // https://www.lexuspartsnow.com/parts/lexus-valve-assy-rear-shock-absorber-control-lh~48040-60010.html
  '6b3dd5a23ee1d007a7daf3f3',
  // https://www.lexuspartsnow.com/parts/lexus-valve-assy-rear-shock-absorber-control-rh~48030-60010.html
  '1e0d1b28a1923f5b2ae900f7',
  // https://www.lexuspartsnow.com/parts/lexus-valve-assy-water~87240-50050.html
  '77846f8efd64587225991d5d',
  // https://www.lexuspartsnow.com/parts/lexus-valve-assy-water~87240-50090.html
  '9527818b708e63098fc5f961',
  // https://www.lexuspartsnow.com/parts/lexus-valve-cooler-expansion~88515-07030.html
  '5ac727771c8dcb6fd9e73259',
  // https://www.lexuspartsnow.com/parts/lexus-valve-cooler-expansion~88515-22260.html
  '606c5956b4b3cb3241dfd254',
  // https://www.lexuspartsnow.com/parts/lexus-valve-expansion-no~88515-0e130.html
  '8361f17327d2dfdd341adacb',
  // https://www.lexuspartsnow.com/parts/lexus-valve-sub-assy-ventilation~12204-46031.html
  '053b0c6d873d7fff1ea1a6e4',
  // https://www.moog-suspension-parts.com/beckarnley-101-4588
  '716346d82599cd11d3ec63e5',
  // https://www.moog-suspension-parts.com/beckarnley-101-4589
  '35c22c127efb8d147f8cfa11',
  // https://www.partsgeek.com/ybbkh9t-lexus-sc430-timing-belt-kit.html
  '74ed4945d36ec3abc572f357',
  // https://www.shockwarehouse.com/products/arnott-as-2855-front-air-strut-lexus-ls-460-wrwd-usf40-swbusf41-lwb
  '8e86205d59a272f45eb4f5b4',
  // https://www.shockwarehouse.com/products/arnott-p-3188-oes-air-suspension-compressor-lexus-ls460-ls-600hl?variant=43489884831976
  '734ffbcc7bad0b7d07facec9',
  // https://www.suspension.com/superpro/spf3163k
  '2caf7d8414b04e2ed0103555',
  // https://www.teqsport.com/automatic-transmission-fluid/toyota/oem-toyota-automatic-transmission-fluid-atf-ws-p-69443.html
  'ccea4f6aad6a573aba9597d4',
  // https://www.voltshybridbatteries.com/product/lexus-es-300h-2012-2015-reconditioned-hybrid-battery-pack/
  '6844e42ca2f20b6646622fd0',
] as const;

export const vendorUrlFingerprints = [
  // autozone | https://www.autozone.com/p/valvoline-auto-transmission-fluid-773636/1180479
  '71d17e56c4ecf5528169c7e8',
  // buyautoparts | https://www.buyautoparts.com/buynow/75-23697-ai
  '3e3597aaa6594cc448194bb0',
  // figs engineering | https://shopfigs.com/v5/SUSPENSION-CHASSIS/FIGS-ADJUSTABLE-LCAs/FIGS-FRONT-LOWER-OE-REPLACEMENT-ADJUSTABLE-MEGA-ARM-LCA-MKIV-SUPRA-SC300-SC400-G1070
  '2603c004f3611c307a9f5f15',
  // finditparts | https://www.finditparts.com/products/16749558/arnott-industries-c-3418
  '383d8a710da2a1aa0ffb6073',
  // finditparts | https://www.finditparts.com/products/6034365/aisin-tkt-021
  '15ef9973edab79a5d0a1b3e0',
  // finditparts | https://www.finditparts.com/products/6034370/aisin-tkt-030
  '4f3a71c5eacf8c3f21aa6d1c',
  // fr sport | https://frsport.com/products/aisin-tkt009-engine-timing-belt-kit-water-pump
  '13c1806bfeac37eff0c626c8',
  // frontier toyota | https://parts.frontiertoyota.com/oem-parts/toyota-super-long-life-coolant-272sllc2
  'd0da841097d5805171eb3bca',
  // frontier toyota | https://parts.frontiertoyota.com/oem-parts/toyota-super-long-life-coolant-50-50-prediluted-272sllc2
  'e6337d9147a1ab9cd45d4f64',
  // hybrid restoration | https://www.hybridrestoration.com/batteries/2011-2017-lexus-ct200h-hybrid-battery-replacement
  '9fd2d65f8e580f657102efa1',
  // hybrid restoration | https://www.hybridrestoration.com/batteries/2013-2017-lexus-es300h-hybrid-battery-replacement
  '87c5ae5ac4891b1b7ae11fd4',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-accumulator-front-suspension-control~49141-60020.html
  '36206a82e9965086853d20f9',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-accumulator-rear-suspension-control~49151-60020.html
  '48a6a4e49bbe40bfe9d15318',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-actuator-assy-trans~36410-60083.html
  '918a129e806597d487e44375',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-actuator-assy-trans~36410-60112.html
  '2b858e8bbda7b9fbba2ce2d6',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-actuator-assy-trans~36410-60113.html
  '96ec9954d4c8dbefa80c4c33',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-alternator-assy~27060-46300.html
  '183138b6f078f32463e0d03e',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-battery-assy-hv-sup~g9510-33112.html
  'd69092d45d39477a8bbcebf8',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-battery-assy-hv-sup~g9510-76014.html
  'af6b8a5c4414c1176cd435cb',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-cap-sub-assy-distributor~19101-70020.html
  '5b544e056ba1795b5acb70d0',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-compressor-assy~88320-3a231.html
  'eb5a0608fac7567991023844',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-condenser-assy~88460-24091.html
  'c7ed545385a5cf46bd3b340e',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-cylinder-assy-pneum~48080-60020.html
  '32f7a134cdf0985cb32972f3',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-cylinder-assy-pneum~48090-60020.html
  '5df74e8b305fb5a451664373',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-cylinder-rr-stabili~48886-60032.html
  '181a1e38398e0d79afcb26b9',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-cylinder-sub-assy-f~48007-60023.html
  'd6c6035b969de8782c9d3cb7',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-disc-fr~43512-0c040.html
  'bcf1478df07e1199f36390bd',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-distributor-assy~19100-46011.html
  'd81741e46454c2b8c20e8371',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-dryer-cooler~88474-08010.html
  'b41b931475703e48c1b9d8a9',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-dryer-cooler~88474-12010.html
  '43758ddb143c426edef0656d',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-dryer-cooler~88474-17010.html
  '7c8135797d761f64907bd648',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-dryer-cooler~88474-47010.html
  'eb1c3ac3ee28cbbadb26b5d3',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-dryer-cooler~88474-47020.html
  'c315734b5922f3bbae8cd6db',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-evaporator-sub-assy~88501-06113.html
  '08db713f3728ada30406977e',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-evaporator-sub-assy~88501-0e120.html
  'dbea8cd16d3606e3e6fc96ac',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-evaporator-sub-assy~88501-0e130.html
  'cdb4b11b3872491ff730d0ef',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-evaporator-sub-assy~88501-48301.html
  '99d3a7036dbdfcaabb7a4061',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-evaporator-sub-assy~88501-48311.html
  'c5e85f3b401a5a08939fb26b',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-fitting-kit-disc-brake-front~04947-60140.html
  'a6422a60bceab60e5859b305',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover-no-2~11214-50011.html
  'dffadb9ca6d97809b79629a8',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover~11213-46020.html
  '1896a27977d70a51e2b251bb',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover~11213-46030.html
  '824c9606d4328d514ce52c75',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover~11213-50021.html
  '18b42c9ad891ec41936951b0',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover~11213-50031.html
  'f3feb9c3889392127ddaac93',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-cylinder-head-cover~11214-46011.html
  '82f84eb9d7355686a28bcb07',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-intake-manifold-to-head-no-1~17171-50011.html
  '4431685a06ea7c498612a668',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-intake-manifold-to-head-no-1~17171-50020.html
  '4d1b3d253f3ec87b29e32342',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-kit-power-steering-pump~04446-30172.html
  '55b3c07df43a6fe3b0e61060',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-kit-power-steering-pump~04446-50011.html
  'e8eb111786a0f27c30f08b10',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-pressure-port~44327-30030.html
  'ea51ae82831b5237ef28e773',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-spark-plug-tube~11193-15010.html
  '6d62dca8742ac24adeb041e4',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-spark-plug-tube~11193-70010.html
  '198049fcc51f712b5e5ae5ba',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-throttle-body~22271-50010.html
  '93c1e5fc9f200063098381c9',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-throttle-body~22271-50042.html
  'deacba6c14f1080fcfbae361',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-transmission-drain-plug~35178-30010.html
  '2b0fd548f8521c873278c80d',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-gasket-water-pump~16271-36040.html
  '3675649184d283cba4075372',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-housing-sub-assy-st~48006-60031.html
  '636933e7d5219be084e6ee33',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front-lh~43340-59066.html
  'b292b1a3fbd47ef75fa19b01',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front-rh~43330-59066.html
  'be8eadc722997d2e67f0749c',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front~43330-59036.html
  'e7445cd1f5ef5ee51ab255f6',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front~43330-59045.html
  '33dc2e938af2bcb4004e9cfc',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front~43340-59036.html
  '2d7cb738105acb91d07235c6',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-joint-assy-lower-ball-front~43340-59045.html
  '6422dfb685ae9771ffc556bc',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-link-assy-electric~44200-30471.html
  '587142753927aff793b35de5',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-link-assy-power-ste~44200-30611.html
  '0a074a924b7ed44985e32540',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-link-assy-power-ste~44200-30641.html
  'b32fdde386f07555b1e532a6',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-link-assy-power-steering~44200-30620.html
  '3df3d7e7cb6185221c52044b',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pad-kit-disc-brake~04465-34040.html
  '7ebf4880ad6b675fae955d4d',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pulley-camshaft-timing~13050-46010.html
  '336a6aecac0b836aa8f66095',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-air~17600-0f010.html
  '839c05b65e70bed15f141c81',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-vane~44320-14240.html
  'd1d00ea87d0e9dde34e5f750',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-vane~44320-50010.html
  '69d1a1152c0aaf91a13031cc',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-vane~44320-50020.html
  'ad2dea37d63b3980b92b990a',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-vane~44320-50030.html
  'ab0b6106a75e3dbece2742dc',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-water-w-m~g9040-47090.html
  '0896fb767ed6c6062663069f',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-water-w-m~g9040-52010.html
  'f94d4514b8c2df539ffec0b0',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-water~16100-09442.html
  'b0fbca65368d43eac639eb14',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-water~16100-09690.html
  '461e180b2ac10c3cef6e22b2',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-water~16100-39436.html
  '574f51cfc274eeb588aa94d9',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-water~16100-39595.html
  '1158ea3988c0789d90beab10',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-assy-water~16100-39616.html
  '17aadb9bf32bb33333d7ab9d',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-pump-motor-assy-h~48910-60033.html
  '3cf3ac3441c66d3b65a3e55a',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-regulator-sub-assy-front-door-window-lh~69802-24041.html
  'b4017e63a75669b433f44a68',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-regulator-sub-assy-front-door-window-rh~69801-24041.html
  '0eafcd4f74430fca4c187ebe',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-regulator-sub-assy~69801-24033.html
  '5ffc04f38968e746f88c2c5a',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-regulator-sub-assy~69802-24033.html
  '9b290fef04390c1aa0bebb6a',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-reman-compressor~88320-3a231-84.html
  'fca536ef29c4cdae46165dcc',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-ring-o~90301-56009.html
  '92ae1b865c5c15ebb3253d85',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-rotor-sub-assy-distributor~19102-46011.html
  '5f069c71fc62f91677f9f2dc',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-seal-type-t-oil~90311-38036.html
  '387d37f8e71e4643f298edab',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-seal-type-t-oil~90311-40020.html
  '974f433d0727ae17fe56e38c',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-seal-type-t-oil~90311-a0001.html
  'ee94437b6b70574f5aa9a432',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-seal-type-t-oil~90311-a0004.html
  '6963da21de8c09de51c28b1a',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-hei~89407-60040.html
  '6a66a908bd2f6a8d4f3cfc30',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-hei~89408-60030.html
  'b518594a5fd06b192a3c04c6',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control-front-lh~89406-50130.html
  '69280f42cb4ddfdbdb039421',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control-front-rh~89405-50070.html
  'd3c5562808f3257748ce4393',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control-front-rh~89405-50100.html
  'bad4acf2edea9ffe29109617',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control-rear-lh~89408-50070.html
  'bb1cfc76a1cd177f49cb440d',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control-rear-rh~89407-50070.html
  '217041cc8c077673e45a024e',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-sensor-sub-assy-height-control~89406-50100.html
  '4b84390b14b2ff530f17d86e',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-shaft-sub-assy-steering-intermediate~45202-0e010.html
  '1dd112e65347f2180ab287a4',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-shim-kit-anti-squea~04945-0c060.html
  'f465a87673abfe675b44ebb5',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-spring-coil-fr~48131-60k20.html
  '8509c42ab1ff09e99ce026ca',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-spring-coil-fr~48131-60k30.html
  'ef467939a55fb7b6faff7424',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-spring-coil-rr~48231-60j11.html
  '76a51ea4e0102d34b77b25f2',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-starter-assy~28100-50020.html
  '714ea60a37f797468c7cc076',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-starter-assy~28100-50062.html
  '3a0894e9158397e24f9c4445',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-strainer-assy-oil~35330-30011.html
  'c7d8c9b0231c8866d2cdc0de',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-tensioner-assy-chain-no-1~13540-46030.html
  'e04ec11ab4e1d7956d414949',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-tube-assy-pressure-feed~44410-48030.html
  '6fd673930c9b0f2172ade92b',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-tube-assy-pressure-feed~44410-48121.html
  '203034b0969372ec736f5f5a',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-tube-assy-pressure-feed~44410-50060.html
  '36e82dc8d7b2ed49d01e6158',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-assy-air-swit~25710-50022.html
  '113f8eb7e4ebe41f4e1eec78',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-assy-front-shock-absorber-control-lh~48020-60010.html
  '7fcaf8da5a88cf46018bc113',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-assy-front-shock-absorber-control-rh~48010-60010.html
  '718362243b668acc70eb1f10',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-assy-height-control-no-1~48940-60020.html
  '0e865038e78bb308eef2259b',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-assy-rear-shock-absorber-control-lh~48040-60010.html
  '0dc963aea55c56567e8d7e04',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-assy-rear-shock-absorber-control-rh~48030-60010.html
  '8dea510000b8a4befc441391',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-assy-water~87240-50050.html
  '6552d51a19ca02d149e16e60',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-assy-water~87240-50090.html
  '5a1031c67cbc55fd7cfce232',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-cooler-expansion~88515-07030.html
  'a8a9d7068aede5ad9b8fd134',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-cooler-expansion~88515-22260.html
  'bc67db81d9f1bd4d0707ad9b',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-expansion-no~88515-0e130.html
  'f2353e9411d48b76e5eb8e6d',
  // lexuspartsnow | https://www.lexuspartsnow.com/parts/lexus-valve-sub-assy-ventilation~12204-46031.html
  '41998803aa845956d335dcac',
  // module mechanics | https://modulemechanics.com/product/06370-07470-climate-control-module-with-warranty-lexus-is300-oem-control-module/
  '547ddca44d354bc208e30633',
  // module mechanics | https://modulemechanics.com/product/1997-lexus-ls400-engine-computer-ecu-repair-service/
  'fbcd26bfeb1cfcdb0bf1c4b7',
  // moog-suspension-parts.com | https://www.moog-suspension-parts.com/beckarnley-101-4588
  'da51d476357b40b2448b8c6e',
  // moog-suspension-parts.com | https://www.moog-suspension-parts.com/beckarnley-101-4589
  'c985bc99e1a19609ff40e772',
  // partsgeek | https://www.partsgeek.com/ybbkh9t-lexus-sc430-timing-belt-kit.html
  '65855421136a329e44e27124',
  // shockwarehouse | https://www.shockwarehouse.com/products/arnott-as-2855-front-air-strut-lexus-ls-460-wrwd-usf40-swbusf41-lwb
  '858f537e9868029a70e5b9eb',
  // shockwarehouse | https://www.shockwarehouse.com/products/arnott-p-3188-oes-air-suspension-compressor-lexus-ls460-ls-600hl?variant=43489884831976
  '5dd6027cb2c667e029bfa56f',
  // suspension.com | https://www.suspension.com/superpro/spf3163k
  'c5478c3e67f7dda1c55a98da',
  // tanin auto electronix | https://taninautoelectronix.com/product/1992-2000-lexus-sc300-sc400-climate-control-repair/
  '0a7a7155cce1fb393af1e790',
  // tanin auto electronix | https://taninautoelectronix.com/product/tae-1992-2000-lexus-sc300-sc400-climate-control-lcd-screen/
  '65db6bd56d7becfd427ad140',
  // teqsport | https://www.teqsport.com/automatic-transmission-fluid/toyota/oem-toyota-automatic-transmission-fluid-atf-ws-p-69443.html
  '5d52c3a52bdb58e95e827684',
  // tm engineering | https://tmengineering.net/webstore/index.php?main_page=product_info&products_id=21
  'fb3c947ebf4374f6c806a863',
  // volts hybrid batteries | https://www.voltshybridbatteries.com/product/lexus-es-300h-2012-2015-reconditioned-hybrid-battery-pack/
  '82ee653aa336bec38d261f1c',
] as const;

export const retailerHostFingerprints = [
  // autozone.com
  '12fa1f440ebfbfd1c0ab1b19',
  // buyautoparts.com
  '09a4b19765e53ad3defeea3e',
  // finditparts.com
  '7e08600bd0825315e1f077e2',
  // frsport.com
  '5593d9b80f1780c4267bc603',
  // hybridrestoration.com
  '57704cd8849ac0f94d6142c3',
  // lexuspartsnow.com
  'fd0c92d3e8ed7bf80238ae62',
  // modulemechanics.com
  'e8f40574321d645464182e00',
  // moog-suspension-parts.com
  '7719c724255ce9cd16b11c65',
  // parts.frontiertoyota.com
  '7a0cd2e482a4cc0558b20ee9',
  // partsgeek.com
  'b6c9d443e05ef437cef78a38',
  // shockwarehouse.com
  '4df11fb7e470d011461ad5d2',
  // shopfigs.com
  '6fa3c857c60e41a45fffdcf6',
  // suspension.com
  '5eef982f34dff812d91f953a',
  // taninautoelectronix.com
  'f30c0a9caa85a2f2c342a84b',
  // teqsport.com
  '924bd584751ff3199ba54d2e',
  // tmengineering.net
  '1909875ef83c7f1cc209323b',
  // voltshybridbatteries.com
  'b6a2c2fb354bd4301a3854c3',
] as const;
