// GENERATED by scripts/build-repair-first-verified-batch.mjs for Lincoln.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://a-premium.com/product/a-premium-running-board-motor-aprbm047
  '06946c0a57959bfc8f8d21ea',
  // https://a-premium.com/product/a-premium-running-board-motor-aprbm049
  '5add4210e59e524374e0cc9a',
  // https://a-premium.com/product/ford-expedition-driver-&-passenger-power-running-board-motor3SicV8SMCR
  '9320fa6943147fba8a871169',
  // https://a-premium.com/product/ford-expedition-driver-running-board-motor-with-bracketioMjDTNO2Y
  'cee6878aaad093f93934df6f',
  // https://a-premium.com/product/ford-expedition-driver-running-board-motor-with-front-&-rear-bracket2kgtqu3ypz
  '2ffc9e81cd72be13d24512a0',
  // https://a-premium.com/product/ford-expedition-passenger-running-board-motor-with-bracketavTcLaPLlo
  '7bb1960f0181784e239a7504',
  // https://a-premium.com/product/lincoln-town-car-front-driver-window-regulator-with-motor-ATVM4nJNCS
  '48ed5da8ec5bf6c66b860de4',
  // https://a-premium.com/product/lincoln-town-car-rear-driver-window-regulator-with-motor-OkZOKHPOrB
  '89440bfe755ba1f888df263e',
  // https://a-premium.com/product/lincoln-town-rear-passenger-window-regulator-with-motor-nnfvi9McYI
  '412b98d700d531c4259b78cc',
  // https://a-premium.com/product/Passenger-Running-Board-Motor-with-Bracket-for-2007-2017-Lincoln-Navigator-M1qOYoNIFV
  'a0713825f8556fefc41a59a7',
  // https://a-premium.com/product/power-running-board-motor-aprbm046
  '6f78bb09ec42ae6b13b17481',
  // https://a-premium.com/product/power-running-board-motor-aprbm048
  'd876c2857791aa0e3fc10a06',
  // https://autobuffy.com/product/motorcraft-engine-coolant-antifreeze-vc-13dl-g
  '4f9d864b063555acad2e340e',
  // https://infotainment.com/products/replacement-service-ford-myford-touch-sync-2-apim-module
  '1894a7b3c6dd462f08a64a79',
  // https://parts.levittownfordparts.com/oem-parts/ford-automatic-transmission-torque-converter-jm5z7902ftc
  'f1939047d18d1c82a7bf59e5',
  // https://rotunda.service-solutions.com/en-US/Pages/ItemDetail.aspx?SKU=164-R4903
  '07aa485bd4383b9ca5486f43',
  // https://shop.valvolineglobal.com/products/full-synthetic-gear-oil-sae-75w-140?Size=1+GA
  '691f1465913f606d03b51be3',
  // https://shop.valvolineglobal.com/products/zerex-g05-50-50-prediluted-antifreeze?Size=1+GA&variant=44420073554197
  '4b5c70f09ca69b555802295b',
  // https://www.1aauto.com/ford-lincoln-mercury-ignition-coil-motorcraft-dg508/i/mceci00001
  '2947a802a258f7a86e064819',
  // https://www.am-autoparts.com/products/air-suspension-system-parts/AM-15284155.html
  '01f56c7ea8d230652985c4b2',
  // https://www.am-autoparts.com/products/air-suspension-system-parts/AM-1906992999.html
  'afc5e2884b51aeb0f8e3e2f7',
  // https://www.autozone.com/p/arnott-industries-air-suspension-spring-a-2148/922453
  '823204471388266f1313151f',
  // https://www.autozone.com/p/arnott-industries-air-suspension-spring-a-2153/922456
  'f16885e8cf0336e03fea60ac',
  // https://www.autozone.com/p/dorman-engine-intake-manifold-615-175/709039
  'f9add66a5e4b98c54a34b818',
  // https://www.autozone.com/p/duralast-platinum-battery-h7-agm/319458
  '6c7fddf5a778758644fc914d',
  // https://www.autozone.com/p/motorcraft-auto-transmission-fluid-xt-10-qlvc/703172
  'c3ab735d611b25725a473f70',
  // https://www.etoolcart.com/aa5z-8501-d-3-5l-3-7l-2007-2012-engine-water-pump-assembly.html
  'e7e9894cd3be96a719f128c9',
  // https://www.ford.com/product/suspension-levelling-compressor-p4000165652
  'fd5d9cae78b8b9cd0e599466',
  // https://www.fordpartsgiant.com/parts/ford-bolt_cp9z-6279-c.html
  '77f80e4d4e1729f46bea7319',
  // https://www.fordpartsgiant.com/parts/ford-bolt_hl3z-6279-a.html
  '1597100517560f8be97e0b5d',
  // https://www.fordpartsgiant.com/parts/ford-cam_l1mz-6c525-c.html
  'a54ca9207d6a7683a5ddfd53',
  // https://www.fordpartsgiant.com/parts/ford-cam_ml3z-6c525-a.html
  '57aafef292fb54d2a8ed59b6',
  // https://www.fordpartsgiant.com/parts/ford-cooler-egr_k2gz-9f464-b.html
  'd0039c78fd0663b2f1c86192',
  // https://www.fordpartsgiant.com/parts/ford-drive-motor_fa1z-14b351-a.html
  '1c210a95fe203be74d98194e',
  // https://www.fordpartsgiant.com/parts/ford-latch-asy-tailgate_fa1z-7443150-b.html
  'db11a950940d4b9e9a99dbc3',
  // https://www.fordpartsgiant.com/parts/ford-lift-asy-gas_fa1z-58406a10-b.html
  '8bae808f1c4a5354e5bf44a0',
  // https://www.fordpartsgiant.com/parts/ford-oil-automatic-transmission_xt-12-qulv.html
  'b5431e9702e510d7a6e39556',
  // https://www.fordpartsgiant.com/parts/ford-pump-asy-water_at4z-8501-a.html
  'fc5e92e4442dfb8187fba300',
  // https://www.fordpartsgiant.com/parts/ford-pump-asy-water_dg1z-8501-e.html
  'b31996c979a8127102235f18',
  // https://www.fordpartsgiant.com/parts/ford-rotor-asy-brake_pz1z-1125-b.html
  'e851e95e3c8b67cba0e285b5',
  // https://www.fordpartsgiant.com/parts/ford-seal-roof-panel-opening_fa1z-5851884-b.html
  '3c959d65621c2a9669e9bb0d',
  // https://www.fordpartsgiant.com/parts/ford-spring_lc5z-5a891-p.html
  'b31744022fd094d7e73a7e79',
  // https://www.fordpartsgiant.com/parts/ford-spring_lc5z-5a891-q.html
  '47ac8959ccb17f71a9d49b64',
  // https://www.fordpartsgiant.com/parts/ford-spring_lc5z-5a891-r.html
  '856fb9d3225c766a423e8798',
  // https://www.fordpartsgiant.com/parts/ford-sprocket-camshaft_l1mz-6256-e.html
  'db30348011a25ddc8c5dea1b',
  // https://www.fordpartsgiant.com/parts/ford-sprocket-camshaft_ml3z-6256-a.html
  '7bca81dda93e0d679d5a7465',
  // https://www.fordpartsgiant.com/parts/ford-tube-water-drain_fa1z-58502c52-a.html
  '0841deb1a426d616ff2ba309',
  // https://www.fordpartsgiant.com/parts/ford-tube-water-drain_fa1z-58502c52-b.html
  '019e8fbcf541e5f2b70fb666',
  // https://www.fordpartsgiant.com/parts/ford-tube-water-drain_fa1z-58502c53-a.html
  '3331da6c013b8dbc771f9cd2',
  // https://www.fordpartsgiant.com/parts/ford-tube-water-drain_fa1z-58502c53-b.html
  'cf451568f20f37741be99aeb',
  // https://www.fordpartsgiant.com/parts/ford-wire-asy_jl7z-13a409-k.html
  '04d4eb45f378191b3d26d363',
  // https://www.fordpartsgiant.com/parts/lincoln-spark-plug_cyfs-12y-pctx.html
  '5d3320e373a9d8adc473c68b',
  // https://www.fordpartsgiant.com/parts/lincoln-spring_lc5z-5a891-n.html
  'b452ee0b6ad684461721c95f',
  // https://www.fordpartsgiant.com/parts/lincoln-switch-asy-steering-wheel_gd9z-9c888-a.html
  'e5210c46bdaab4c02cfc8b65',
  // https://www.fortluft.com/champion-spark-plug-7989/
  'ddd2be208595cd700991e1c7',
  // https://www.napaonline.com/en/p/ARNP2937
  '8d7e75edfbfc7285b4125cb9',
  // https://www.oreillyauto.com/detail/c/arnott-air-suspension/arnott-air-suspension-air-compressor-new/arn0/p2932
  'd362e9e994234074dcaca922',
  // https://www.partcatalog.com/products/arnott-a-2647-air-suspension-spring
  'e9b1f8620a2080dd77093dc1',
  // https://www.partsgeek.com/4917nf8-lincoln-town-car-window-regulator.html
  '0a6b24f652ba21995c865cc9',
  // https://www.partsgeek.com/84h7zn4-lincoln-town-car-intake-manifold.html
  'b08b74d7ccf4e1c1e8ceb83c',
  // https://www.partsgeek.com/crdc67z-lincoln-ls-coolant-pipe.html
  'f8b8607ce98e58650fe30f16',
  // https://www.penntoolco.com/OT6918/
  'dedca8d2f19cf5c91facf361',
  // https://www.truckspring.com/products/arnott/replacement-air-spring-A-2143.aspx
  '58c6f2cc704a667d004fb234',
  // https://www.truckspring.com/products/arnott/replacement-air-spring-A-2735.aspx
  '3f1c16a1e9516b181cd5202f',
  // https://www.truckspring.com/products/Coil-Spring-Conversion-Kit-Arnott-Rear-With-Rear-Shocks-Lincoln-Ford-Mercury__C-2615.aspx
  'ae83dc3212b1c81fc34a5d8a',
] as const;

export const vendorUrlFingerprints = [
  // 1a auto | https://www.1aauto.com/ford-lincoln-mercury-ignition-coil-motorcraft-dg508/i/mceci00001
  '9a832d47e759a23688b14122',
  // a-premium | https://a-premium.com/product/a-premium-running-board-motor-aprbm047
  'b3f17115f2ac6e06d0939077',
  // a-premium | https://a-premium.com/product/a-premium-running-board-motor-aprbm049
  '47f0b80ee5cfdf16b89895de',
  // a-premium | https://a-premium.com/product/ford-expedition-driver-&-passenger-power-running-board-motor3SicV8SMCR
  '49d698b0a8e32ea3051f9973',
  // a-premium | https://a-premium.com/product/ford-expedition-driver-running-board-motor-with-bracketioMjDTNO2Y
  'df58d84595f557354040548d',
  // a-premium | https://a-premium.com/product/ford-expedition-driver-running-board-motor-with-front-&-rear-bracket2kgtqu3ypz
  'c270fef04171a7404b7262c6',
  // a-premium | https://a-premium.com/product/ford-expedition-passenger-running-board-motor-with-bracketavTcLaPLlo
  '4bdd77ebe38b6a58d43eec82',
  // a-premium | https://a-premium.com/product/lincoln-town-car-front-driver-window-regulator-with-motor-ATVM4nJNCS
  'de1d9b1be86c7832d0ace005',
  // a-premium | https://a-premium.com/product/lincoln-town-car-rear-driver-window-regulator-with-motor-OkZOKHPOrB
  '051e777c14f177521ac7120a',
  // a-premium | https://a-premium.com/product/lincoln-town-rear-passenger-window-regulator-with-motor-nnfvi9McYI
  'b5e43549f18256525c05af03',
  // a-premium | https://a-premium.com/product/Passenger-Running-Board-Motor-with-Bracket-for-2007-2017-Lincoln-Navigator-M1qOYoNIFV
  'd443d856538b0904c6c76295',
  // a-premium | https://a-premium.com/product/power-running-board-motor-aprbm046
  '49ea5d37c8d0f2bb299af1cd',
  // a-premium | https://a-premium.com/product/power-running-board-motor-aprbm048
  'da00d1fa0fcd755e217809f8',
  // am autoparts | https://www.am-autoparts.com/products/air-suspension-system-parts/AM-15284155.html
  '5fb16a8b9a29a2fd6ab8b6c3',
  // am autoparts | https://www.am-autoparts.com/products/air-suspension-system-parts/AM-1906992999.html
  'cd2b98a0b15bbae012e87555',
  // autobuffy | https://autobuffy.com/product/motorcraft-engine-coolant-antifreeze-vc-13dl-g
  'af1e4c021f5c78113d006131',
  // autozone | https://www.autozone.com/p/arnott-industries-air-suspension-spring-a-2148/922453
  '2408567cb5b84edb8a69143f',
  // autozone | https://www.autozone.com/p/arnott-industries-air-suspension-spring-a-2153/922456
  '0d454e65e5294e12f125056b',
  // autozone | https://www.autozone.com/p/dorman-engine-intake-manifold-615-175/709039
  '09d607891a2d7db40ec2224f',
  // autozone | https://www.autozone.com/p/duralast-platinum-battery-h7-agm/319458
  '118296d45ae653f81f8eb825',
  // autozone | https://www.autozone.com/p/motorcraft-auto-transmission-fluid-xt-10-qlvc/703172
  'c27ae78ecd94354827b8da70',
  // etoolcart | https://www.etoolcart.com/aa5z-8501-d-3-5l-3-7l-2007-2012-engine-water-pump-assembly.html
  '09d97dc3bdbf3e89c6afd462',
  // ford parts | https://www.ford.com/product/suspension-levelling-compressor-p4000165652
  '0a0541b9af9ab9dc91dc0fb3',
  // ford rotunda service solutions | https://rotunda.service-solutions.com/en-US/Pages/ItemDetail.aspx?SKU=164-R4903
  '9d127fcf4f77677a0b2171b5',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-bolt_cp9z-6279-c.html
  '65c20faf0895d406058104ab',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-bolt_hl3z-6279-a.html
  'ba2c12649adc45e862111704',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-cam_l1mz-6c525-c.html
  '4fcd1a026ecd97a0f9408169',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-cam_ml3z-6c525-a.html
  'ba7e3339d50bcde372aba7b5',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-cooler-egr_k2gz-9f464-b.html
  '788c6cf71d022e73fb10c08c',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-drive-motor_fa1z-14b351-a.html
  '31583a7bcbda634deef288e1',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-latch-asy-tailgate_fa1z-7443150-b.html
  'f73334d8c99904f50c8b22f0',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-lift-asy-gas_fa1z-58406a10-b.html
  '17125e468e9ddacbd42c20c4',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-oil-automatic-transmission_xt-12-qulv.html
  'f1bb961885bfe39b9200f4da',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-pump-asy-water_at4z-8501-a.html
  '156e2e39e6e55de0d49cd0d7',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-pump-asy-water_dg1z-8501-e.html
  '47f24856ff1f1d722842f032',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-rotor-asy-brake_pz1z-1125-b.html
  '471cb356b60b2eddb492c610',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-seal-roof-panel-opening_fa1z-5851884-b.html
  'aaa58761281e54c1949e9d10',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-spring_lc5z-5a891-p.html
  '0ef6067be7a6a2459e945ac9',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-spring_lc5z-5a891-q.html
  '867b6a2e5fddde859f82b6d8',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-spring_lc5z-5a891-r.html
  '10bd5ec491e48c7be0d5909e',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-sprocket-camshaft_l1mz-6256-e.html
  'b63a70574a04d1769ea9b2c3',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-sprocket-camshaft_ml3z-6256-a.html
  'b22af3cb912b144a353db39d',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-tube-water-drain_fa1z-58502c52-a.html
  '518ff2439465c7a6e3a8f9f5',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-tube-water-drain_fa1z-58502c52-b.html
  '7bf338a84e7264fb30f84ca2',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-tube-water-drain_fa1z-58502c53-a.html
  '562c81f8b214b85599d9aeea',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-tube-water-drain_fa1z-58502c53-b.html
  '94ce210f28ad938245f800a7',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/ford-wire-asy_jl7z-13a409-k.html
  'a7814f9bad28bdb72e0dae36',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/lincoln-spark-plug_cyfs-12y-pctx.html
  '84c082fa7321c8cfd8464cb2',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/lincoln-spring_lc5z-5a891-n.html
  '1b09d5e0f4c975c59943cc03',
  // fordpartsgiant | https://www.fordpartsgiant.com/parts/lincoln-switch-asy-steering-wheel_gd9z-9c888-a.html
  'ad943fadb11f23dfb13f2b82',
  // fortluft auto parts | https://www.fortluft.com/champion-spark-plug-7989/
  '14c0bbea53eb5ef4e1dd2882',
  // infotainment.com | https://infotainment.com/products/replacement-service-ford-myford-touch-sync-2-apim-module
  '662a699a05cd75a3e09dc480',
  // levittown ford parts | https://parts.levittownfordparts.com/oem-parts/ford-automatic-transmission-torque-converter-jm5z7902ftc
  'c93d26fa28cf6dee45104021',
  // napa | https://www.napaonline.com/en/p/ARNP2937
  'be4ba9f0671246103b05b9dd',
  // o'reilly auto parts | https://www.oreillyauto.com/detail/c/arnott-air-suspension/arnott-air-suspension-air-compressor-new/arn0/p2932
  '543dd65b1ac5d7b9715c957f',
  // partcatalog | https://www.partcatalog.com/products/arnott-a-2647-air-suspension-spring
  'c467fb797c5c52b56675d221',
  // partsgeek | https://www.partsgeek.com/4917nf8-lincoln-town-car-window-regulator.html
  '63e6da4338814d6472096890',
  // partsgeek | https://www.partsgeek.com/84h7zn4-lincoln-town-car-intake-manifold.html
  '742e1e93857fa3289c3ad0a6',
  // partsgeek | https://www.partsgeek.com/crdc67z-lincoln-ls-coolant-pipe.html
  '55adb9d22827d08a3707f7cc',
  // penn tool co. | https://www.penntoolco.com/OT6918/
  'dc70aeaf5db167a64d23c86e',
  // truckspring | https://www.truckspring.com/products/arnott/replacement-air-spring-A-2143.aspx
  'a87d23d6f324e57626d89792',
  // truckspring | https://www.truckspring.com/products/arnott/replacement-air-spring-A-2735.aspx
  '6d2724779d4dc1d3b342dc0b',
  // truckspring | https://www.truckspring.com/products/Coil-Spring-Conversion-Kit-Arnott-Rear-With-Rear-Shocks-Lincoln-Ford-Mercury__C-2615.aspx
  '6812e5565e1cd4614c62f96c',
  // valvoline | https://shop.valvolineglobal.com/products/full-synthetic-gear-oil-sae-75w-140?Size=1+GA
  'f0d6df7ba72761aa515c693c',
  // valvoline | https://shop.valvolineglobal.com/products/zerex-g05-50-50-prediluted-antifreeze?Size=1+GA&variant=44420073554197
  '3fc00bd2df2b3b91fcbbb71f',
] as const;

export const retailerHostFingerprints = [
  // 1aauto.com
  '3703d7177e3c08c25f297e88',
  // a-premium.com
  '2b22673ab54376412b813f20',
  // am-autoparts.com
  '1fd199dde0d1cf3ed07c1cc3',
  // autobuffy.com
  '7227399c6e43e2c7f0d1756a',
  // autozone.com
  '12fa1f440ebfbfd1c0ab1b19',
  // etoolcart.com
  'f9196586edd4245513e53aaf',
  // ford.com
  '46a9b64c1906f37e45594dd5',
  // fordpartsgiant.com
  '9c70a269d631dec0c292f0ce',
  // fortluft.com
  '4f300cb7a82305a06c7b4947',
  // infotainment.com
  '8be386f64cd708f7bf9cfa1c',
  // napaonline.com
  'f548aa17dadb360706774067',
  // oreillyauto.com
  'f896d798e92f000fdf6f2c6b',
  // partcatalog.com
  '85d0f7949323a49d56724bc5',
  // parts.levittownfordparts.com
  'bd71722f862ba75792f3d8c8',
  // partsgeek.com
  'b6c9d443e05ef437cef78a38',
  // penntoolco.com
  '2ea7396d420829414cce32d3',
  // rotunda.service-solutions.com
  'af300477844446a4b5888990',
  // shop.valvolineglobal.com
  'b409eb5204e7d7cf38a459e7',
  // truckspring.com
  '56ebe4f353d7464a442f7fc7',
] as const;
