// GENERATED by scripts/build-repair-first-verified-batch.mjs for Mazda.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://aipelectronics.com/products/complete-premium-electronic-ignition-distributor-for-1996-1998-kia-sephia-mazda-protege-1-5l-1-8l-t2t60371-mz14
  'a75ffc96f8e083cca6e00dbf',
  // https://conquestauto.com/products/new-oem-mazda-2006-2015-mazda5-sliding-door-latch-lock-mechanism-c235-72-9l0e
  'c145879b73e826a6e595124e',
  // https://corksport.com/mazdaspeed-6-2006-2007-rear-differential-mount.html
  'dbf9332b0540e8b8a45185c4',
  // https://corksport.com/mazdaspeed-high-flow-fuel-pump-internals.html
  '036268b1731c162da03d314a',
  // https://corksport.com/valve-cleaning-kit-for-mazdaspeed-3-mazdaspeed-6-and-mazda-cx-7.html
  '976d00d3ea306c8e57e5aaf7',
  // https://damondmotorsports.com/products/mazdaspeed3-rear-motor-mount-newly-revised
  'd6735ac521b9dc14a5cfefdf',
  // https://edgeautosport.com/mazda-oem-turbo-oil-feed-line-mazdaspeed-3-2007-2013-mazdaspeed-6-2006-2007/
  'ddbde0a94bc49d38d853c5cf',
  // https://edgeautosport.com/mazda-oem-turbocharger-mazdaspeed-3-2007-2013-mazdaspeed-6-2006-2007/
  '1f7ede072575932638cf9c2a',
  // https://edgeautosport.com/mazda-oem-vvt-replacement-kit-mazdaspeed-3-2007-2013-mazdaspeed-6-2006-2007/
  'aae827ce14710b8acaf90822',
  // https://injector-rehab.com/product/side-feed-fuel-injector-clean-and-flow-test/
  '5aae3d7ba676d563a05ee44d',
  // https://ipgparts.com/collections/exedy/products/exedy-replacement-clutch-slave-cylinder-fits-1990-2005-mazda-miata-na-nb
  '2ccf13ca7c7ff7d54d9231dc',
  // https://madnessautoworks.com/start-shopping/brakes-upgrade?product_id=300390317
  'ca3a11e7daf5677caca19be5',
  // https://madnessautoworks.com/start-shopping/suspension-upgrades-madness?order=DESC&product_id=300279916&sort=pd.name
  'a76c8d5bcd44fe96d804c6fa',
  // https://mazda.oempartsonline.com/oem-parts/mazda-evaporator-core-l20661j10a
  '06fa4187361e28ab3daf2422',
  // https://mazdashopusa.com/products/transmission-fluid-automatic-a7-mazda
  '8253f042da57090c9fe1fd73',
  // https://mazdashopusa.com/products/transmission-fluid-automatic-fz-mazda
  '193583a15af8e3fc22c3dcc5',
  // https://mazdatrix.com/product/gasket-water-pump-93-95/
  'd830687155cd2c3fe00c4567',
  // https://mazdatrix.com/product/ign-coil-04-on-rx8-each/
  'e19267f1ce40b6ab7202ca56',
  // https://mazdatrix.com/product/ign-coil-86-92-trail/
  'fad00a8083cb627fba2efae4',
  // https://mazdatrix.com/product/ign-coil-93-95-leading/
  'ccb7a7e798367c15f3b4b5e1',
  // https://mazdatrix.com/product/ign-coil-93-95-trail-1/
  'd3209fd0f6c5089055612975',
  // https://mazdatrix.com/product/ign-coil-93-95-trail-2/
  '475aea1cb6b72a5424ad2ed6',
  // https://mazdatrix.com/product/ign-plug-wires-04-on-rx8-ngk/
  '7e744ab0c6e05ee92da69aa8',
  // https://mazdatrix.com/product/ign-plug-wires-93-95-ngk/
  'ba8c9baae06f8f4aa684e1a5',
  // https://mazdatrix.com/product/pump-metering-04-on-rx8/
  '46e359898678ff7e7da06f13',
  // https://mazdatrix.com/product/pump-metering-o-ring-04-on-pump-to-engine/
  'a7b03f324de6a1ec5658228c',
  // https://mazdatrix.com/product/spark-plug-set-rx8-set-of-4-plugs/
  'cab1dda0c6ab4b2dc0dc54df',
  // https://mazdatrix.com/product/susp-toe-eliminator-86-92-all-pair/
  'f4f21a256935a0e1769d4395',
  // https://mazdatrix.com/product/water-pump-93-95/
  'cf518b10c33d70e137d6a423',
  // https://mazmartstore.mybigcommerce.com/mazda-oem-starter-for-rx-8-automatic-tranmission-only-n3z2-18-400/
  'c9b0bbcef3359149bb4d4a2d',
  // https://mazmartstore.mybigcommerce.com/mazda-oem-starter-for-rx-8-manual-tranmission-only-n3z1-18-400/
  'ba73845bf05d5152579e68d4',
  // https://mossmiata.com/1990-1997-mx-5-miata/239-570-cp-vinyl-zippered-standard-glass-window-factory-style-tops-by-robbins
  'd4410cf501a6f6fda3b24b02',
  // https://mossmiata.com/1990-1997-mx-5-miata/240-195-cp-vinyl-zippered-plastic-window-factory-style-convertible-tops-by-robbins
  'c3fbf57a663f2bdb6f479491',
  // https://mossmiata.com/1990-1997-mx-5-miata/971-031-valve-cover-gasket-by-mazda
  'ad501574196448c4badfc3c4',
  // https://mossmiata.com/2006-2015-mx-5-miata/903-465-rear-main-seal-by-mazda
  '6b016cd11ccd682259e8a9e1',
  // https://mossmiata.com/902-884-camshaft-position-sensor-o-ring-gasket-by-mazda
  '3af6a0cadd4ce9f6d04e12c9',
  // https://mossmiata.com/905-375-left-hand-replacement-door-sill
  '1981e5c19ff7f8a8bc8b0632',
  // https://mossmiata.com/905-376-right-hand-replacement-door-sill
  '5a201bef0e5791ef1cd78b4e',
  // https://mossmiata.com/971-035-valve-cover-gasket
  '10ec978e2d283d5e1a30880b',
  // https://mossmiata.com/971-036-valve-cover-gasket-by-mazda
  '7c3e06052b35571bac282376',
  // https://mossmiata.com/971-037-valve-cover-gasket-by-mazda
  'e8de59e45174f6dc2372e787',
  // https://no.co/genius1
  '3de309e7a074bd9f54c0fb9e',
  // https://painlessperformance.com/product/universal-body-engine-ground-strap-kit-part-no-40140/
  '6956e4f25628f5b2fdc3f83a',
  // https://parts.walser-mazda.com/p/Mazda__Tribute/Direct-Ignition-Coil/49185667/AJ0918100.html
  'b7c9840e2f1200eac5199573',
  // https://pbedirect.com/products/3m-cavity-wax-aerosol-08852
  'f6dc7d2dfab74ec7dc1ee215',
  // https://rotarytronics.com/product/rotary-compression-tester/
  '1a50ba41ff057fa6ab9986fe',
  // https://shop.advanceautoparts.com/p/permatex-dielectric-tune-up-grease-protects-electrical-connections-from-corrosion-3-oz.-22058/12027861-P
  '56bbce70cf242be4414532a2',
  // https://shop.advanceautoparts.com/p/permatex-ultra-grey-rtv-silicone-gasket-maker-3-oz-82194/7160017-P
  'd6072b6ed2c8fd249d41a815',
  // https://shop.advanceautoparts.com/p/valvoline-80w-90-high-performance-conventional-gear-oil-1-quart-vv831/7070003-P
  'c3dd237575771d907f6114f7',
  // https://shop.valvolineglobal.com/products/dex-merc-atf-automatic-transmission-fluid
  'f685474288ac0420b24db7c0',
  // https://shop.valvolineglobal.com/products/mercon-v-atf-automatic-transmission-fluid?Size=1+QT
  '7d9a15ee8ce340c74e9687a2',
  // https://sparktecmotorsports.com/i-30632869-magnaflow-converter-df-93-95-mazda-rx7-1-3l.html
  '2006e0ac4a52269bd78590b7',
  // https://store.awrracing.com/1993-2003-protege-1-8-and-2-0-protege-5-and-mazdaspeed-protege-rear-engine-mount/
  'bf7786a12a68ae0129e47ced',
  // https://treasurecoastmiata.com/i-14385851-1990-1993-premium-miata-timing-belt-water-pump-replacement-kit-gates-and-oem.html
  '9dc327ef2832d6280c74db5d',
  // https://treasurecoastmiata.com/i-18598700-new-94-00-mazda-miata-premium-gates-and-mazda-timing-belt-water-pump-replacement-kit.html
  '1bbdde3d2d0993ff5a3c5120',
  // https://tsurugi-online.com/products/mazda-genuine-n3h5-20-160f-oem-2004-11-rx-8-manifold-secondary-shutter-valve
  'b50764418c16fdfc1ee00a54',
  // https://www.1aauto.com/2010-13-mazda-3-main-recirculation-hvac-recirculation-door-actuator-trq-hca41844/i/1ahcx00441
  '0e1d92637b78af32c84306ad',
  // https://www.am-autoparts.com/products/brake-pads/AM-1064753972.html
  '1fa9d03ebc5c2eae15932f39',
  // https://www.am-autoparts.com/products/brake-pads/AM-2506058450.html
  '68fafc875e5bf536f7759069',
  // https://www.atkinsrotary.com/04-08-Rx8-Oil-Metering-Line-Kit-ARE109.html
  'b235956e40c7d343ae2b76ea',
  // https://www.atkinsrotary.com/84-88-13B-Rx7-Oil-Metering-Pump-O-Ring-N236-14-604.html
  '924eec127bb87022550ac8e6',
  // https://www.atkinsrotary.com/84-92-13b-rx7-atkins-designed-six-port-actuator-valve-kit-are113-.html
  '52a5bd1362cdb67ce852d25e',
  // https://www.atkinsrotary.com/86-88-N-A-Rx7-Oil-Metering-Line-Kit-ARE101.html
  '809926b018a64f9b99203305',
  // https://www.atkinsrotary.com/87-88-Turbo-Rx7-Oil-Metering-Line-Kit-ARE102.html
  '57ecd993f0bfec63e02ff683',
  // https://www.atkinsrotary.com/89-91-N-A-Rx7-Oil-Metering-Line-Kit-ARE106.html
  'ab0bb15b5b00c8be76ec16fd',
  // https://www.atkinsrotary.com/89-91-Turbo-Rx7-Oil-Metering-Line-Kit-ARE107.html
  '25b51efbe19f49e4c2e4627b',
  // https://www.atkinsrotary.com/89-95-Rx7-Oil-Metering-Pump-O-Ring-N350-14-604.html
  '03f700e7d6b12d630449a31d',
  // https://www.atkinsrotary.com/93-95-Rx7-Oil-Metering-Line-Kit-ARE108.html
  '922b25970b81efbf05a83049',
  // https://www.atkinsrotary.com/93-95-Rx7-Overhaul-Kit-B-ARE46.html
  '82f33c455d2ec2cb62a1821e',
  // https://www.atkinsrotary.com/93-95-Rx7-Pulsation-Damper-N3A2-20-180.html
  'b903fa920eb3b96750e776cb',
  // https://www.atkinsrotary.com/93-95-Rx7-Racing-Beat-Silicone-Radiator-Hose-Kit-11485.html
  '7c6518e7c5f245a2bc4b2a42',
  // https://www.atkinsrotary.com/93-95-rx7-vacuum-rat-nest-hose-n3a3-20-346a-
  '9ffcac69b9f990ebf3df6798',
  // https://www.atkinsrotary.com/Emission-Control/Shutter-Valves/04-11-Rx8-Shutter-Valve-Gasket-N3H4-20-155A.html
  'dbd2c5beea00c0b3697d360c',
  // https://www.atkinsrotary.com/Hoses/93-95-13B-Hoses/93-95-rx7-pre-control-turbo-hoses-n3a1-13-zly-
  '947bef5cd657abb260bb42d9',
  // https://www.atkinsrotary.com/Rotary-Engine-Rebuild-Kits/Rx8-Rebuild-Kits/04-11-Rx8-Rotor-Kit-ARE64.html
  '831edc90d9a55b0ce900e4e3',
  // https://www.autonationparts.com/parts/mazda-a-c-compressor-bfd161450a
  'bf4ea69fb6327beaae6611e3',
  // https://www.autopartsprime.com/centric/mp-14161555
  '37790240d4a9179a1560c890',
  // https://www.autopartsprime.com/centric/mp-14161556
  'b962fd5e02beab6a243b3429',
  // https://www.autopartsprime.com/mevotech/mp-cms761171
  '214d48459489a19e3dc489a6',
  // https://www.autopartsprime.com/mevotech/mp-cms761172
  '0c24d73d57430437eb6977c7',
  // https://www.autozone.com/batteries-starting-and-charging/battery/mazda/rx-8/b/group-size/35
  'f136b07d2f3591fc9c18b6dc',
  // https://www.autozone.com/p/crc-carburetor-throttle-body-cleaner-05078/55922
  '7138aa15820e7a78b6e09278',
  // https://www.autozone.com/p/crc-carburetor-throttle-body-cleaner-05379/55920
  '0bf5c8d202fff18a6c85e127',
  // https://www.autozone.com/p/crc-mass-air-flow-sensor-cleaner-05110/36011
  'd455d37a4bf9d13ccd7e665b',
  // https://www.autozone.com/p/duralast-gold-alternator-11005n/767423
  'ea8417166be870a2e7f4837b',
  // https://www.autozone.com/p/duralast-gold-alternator-13996n/763347
  '065321602763244521be4016',
  // https://www.autozone.com/p/duralast-gold-alternator-dlg11007/1142826
  '48cd7bd71c750bb94c698330',
  // https://www.autozone.com/p/duralast-gold-alternator-dlg15582/427630
  'c0e98aa1bdb1532b4a4c60e7',
  // https://www.autozone.com/p/duralast-platinum-battery-h6-efb/1070711
  '566c2a2ca664c8de17c3f992',
  // https://www.autozone.com/p/fel-pro-exhaust-gas-recirculation-egr-valve-gasket-70714/225604
  '703c7694fc3586d375cf8a4a',
  // https://www.autozone.com/p/fluid-film-multi-purpose-lubricant-as11/253803
  '75756529ebd01d31e4accc8e',
  // https://www.autozone.com/p/magnaflow-exhaust-products-catalytic-converter-49150/422142
  '8a8f94b6f0245cfbd7112129',
  // https://www.autozone.com/p/trugrade-a-c-condenser-7-3879/375626
  '1765a0768c283811c08df03d',
  // https://www.autozone.com/p/valvoline-flexfill-extended-protection-gear-oil-902150/1398579
  'c8acc2ac98851292f98e1710',
  // https://www.bestbuy.com/product/anker-usb-a-to-lightning-cable6ft-1pack-blue/JJ85864PL2
  'c22e1fd5e3cda633b7405857',
  // https://www.blauparts.com/mazda-cx-3-transmission-fluid-atf-change-kit-atf-type-fz-0000-fz-113e-01.html
  'c7cbaac76e4c3f9abbb7e0f6',
  // https://www.carid.com/cardone/electronic-ignition-distributor-mpn-84-35620.html
  '5c39e9499f0796edfcd657e4',
  // https://www.dbelectrical.com/products/new-alternator-for-1-6-1-8-2-0-mazda-protege-99-00-01-02-03-1999-2003-13719.html
  'edce88543ba2d5b3e1b86d06',
  // https://www.finditparts.com/products/10399717/
  '3dbaf6d36747b4504e33b42c',
  // https://www.finditparts.com/products/2455166/a-1-cardone-31-35602
  '86aefa1f615959e2bac2d745',
  // https://www.finditparts.com/products/8199600/fel-pro-es-72846
  '2322b867755d208d354fbd76',
  // https://www.floridamazdaparts.com/parts/mazda-window-regulator-gd4t58560c
  'c68bebc28915c1d23d551262',
  // https://www.floridamazdaparts.com/parts/mazda-window-regulator-gd4t59560c
  '9c14dea23b8b5b7fa977f97c',
  // https://www.invasionautoproducts.com/supercharger-mazda-sc-maz-9502.html
  '874aea044919db8a4189af24',
  // https://www.ipdusa.com/products/65848/Engine-mount-MTC-9082-Mazda-B25D39040-B25F39040A-B25F39040B-B25G39040-B25G39040C-B25G39040D
  '0a10113740912f5ba07c7eb7',
  // https://www.joetlc.com/products/clutch-slave-cylinder-for-ford-probe-or-mazda-626-mx6
  'beced1a520cd92405930bbdb',
  // https://www.koni-online.com/Mazda-CX-60-stossdaempfer-komplett-set-Special-Active-1x8245-1438L1x8245-1438R2x8245-1439
  '7c067a5c6550dc774f13b680',
  // https://www.maniacelectricmotors.com/13559.html
  'e80bb4b2cc2266aa5abf5b8b',
  // https://www.mazda-parts.com/oem-parts/mazda-crankshaft-position-sensor-bp4w18221b
  'ef7461027a97376a32a9780e',
  // https://www.mazda-parts.com/oem-parts/mazda-solenoid-pyfa12360a
  'cae67125c99b7f71ad372720',
  // https://www.mazda-parts.com/oem-parts/mazda-window-regulator-t00158590
  'ab361bbfeeefb8c03d136211',
  // https://www.mazda-parts.com/oem-parts/mazda-window-regulator-t00159590
  '637f771f6380414faa915528',
  // https://www.mazdaonlineparts.com/parts/mazda-pump-water-pe0115010d
  '925968da0f3a7254d30f0f58',
  // https://www.mazdaparts.us/parts/mazda-a-c-condenser-bdwk61480b
  'ba707d8deb696f40c59edf11',
  // https://www.mazdaparts.us/parts/mazda-expansion-valve-d09w61j14
  'f4217d129274d840fbd14879',
  // https://www.mazdaparts.us/parts/mazda-water-pump-pyfa15010d
  '6f2e54c5c54236cd62a20a39',
  // https://www.mazdapartsnow.com/genuine/mazda~actuator~l3k9124x0c
  'b5e5c5129b8f3b367dc99148',
  // https://www.mazdapartsnow.com/genuine/mazda~actuator~lf94124x0d
  'fa7621a2f62224e4d6877142',
  // https://www.mazdapartsnow.com/genuine/mazda~actuator~pe01124x0b
  '583e92e4bcd08703484a618a',
  // https://www.mazdapartsnow.com/genuine/mazda~egr-valve~bp3c20300a9u
  '0adc958196e825b26036925a',
  // https://www.mazdapartsnow.com/genuine/mazda~egr-valve~lfhj20300
  'd1f61b06a48d440e570a1896',
  // https://www.mazdapartsnow.com/genuine/mazda~egr-valve~zzda20300
  '3cea282f06ef8f4147b1099f',
  // https://www.mazdapartsnow.com/genuine/mazda~evaporator~cc4361j10
  '6fb975efcca304cbb8ffc958',
  // https://www.mazdapartsnow.com/genuine/mazda~expansion-valve~kf0361j14
  '6934995933f4ead69dad4a9d',
  // https://www.mazdapartsnow.com/genuine/mazda~gasket~lf0120305
  '80dc4ce180700598717f97ac',
  // https://www.mazdapartsnow.com/genuine/mazda~hub-bearing~kd312615xb
  'bf04e4bf61f3b3fb114be368',
  // https://www.mazdapartsnow.com/genuine/mazda~hub-rr-wheel~kd352615xd
  '02fd5c517c6d8e5028e304ff',
  // https://www.mazdapartsnow.com/genuine/mazda~hub-wheel~kd353304xj
  '681615b2624fd3024707a8f5',
  // https://www.mazdapartsnow.com/genuine/mazda~lock~tk4962310c
  '2b231ce64819927ca48b7226',
  // https://www.mazdapartsnow.com/genuine/mazda~manifold-gasket~pe1713460
  'a0db102933a19f4adb0cc731',
  // https://www.mazdapartsnow.com/genuine/mazda~manifold-gasket~py0113460
  'e15a7dbf6eaec7c35c0495f9',
  // https://www.mazdapartsnow.com/genuine/mazda~mass-air-flow-sensor~pe0113215
  '5c3ae3631716feaefddf86b7',
  // https://www.mazdapartsnow.com/genuine/mazda~motor-mount~d65239060h
  'a10e11e7e879612a0b459124',
  // https://www.mazdapartsnow.com/genuine/mazda~rear-main-seal~bp0511312
  '52ee0a85da677dd82f28e096',
  // https://www.mazdapartsnow.com/genuine/mazda~seal~fs0210602
  '47250011bd731d90315ca91b',
  // https://www.mazdapartsnow.com/genuine/mazda~solenoid-valve~lf8218740
  '4005798a707591d386331ea3',
  // https://www.mazdapartsnow.com/genuine/mazda~solenoid~l30118741
  '894aac5845ae36f1bb5e3aa6',
  // https://www.mazdapartsnow.com/genuine/mazda~solenoid~l51818741
  'b62cd43157c350d945d4d625',
  // https://www.mazdapartsnow.com/genuine/mazda~spring~lc7028011a
  '5805c105f4e97bba913192a0',
  // https://www.mazdapartsnow.com/genuine/mazda~strut~tk49626exl
  'e41ff94cad6d679402987587',
  // https://www.mazdapartsnow.com/genuine/mazda~strut~tk49636exl
  '8fda56599f925de977a8867c',
  // https://www.mazdapartsnow.com/genuine/mazda~temperature-sensor~g51861764a
  'e16f79f7b4df3404b47822e1',
  // https://www.mazdapartsnow.com/genuine/mazda~timing-chain~l3k912201a
  '07c944e8b726564c2f482aea',
  // https://www.mazdapartsnow.com/genuine/mazda~transmission-fluid~000077112e01
  'aa7d51cd9701aa348776441c',
  // https://www.mazdapartsnow.com/genuine/mazda~transmission-mount~bbm439070d
  '0316e26098885063932b83d4',
  // https://www.mazdapartsnow.com/genuine/mazda~transmission-mount~bbm539070c
  'bde70dc9f3ff2bb153f4d2fa',
  // https://www.mazdapartsnow.com/genuine/mazda~transmission-mount~cc2939070
  'a02932915e9895a6dd63ffdc',
  // https://www.mazdapartsnow.com/genuine/mazda~transmission-mount~dr6239070c
  '1c1969437ec66a089080e6da',
  // https://www.mazdapartsnow.com/genuine/mazda~turbocharger~l3yc1370za
  'c860f74f0bfc989977b2c667',
  // https://www.mazdastuff.com/Mazda-CX-5-Left-Motor-p/ka0g-26-8exa-55061.htm
  '599d0767ceb81aa94a5ecfca',
  // https://www.mazdastuff.com/Mazda-CX-5-Timing-cover-sealer-p/r2y1-10-431-45308.htm
  '72cd7a4550b9a32c3dfc0bcb',
  // https://www.mazdastuff.com/Mazda-Part-Number-Index-p/0000-77-80w9-qt.htm
  'e47b5f9bf53dd6cb163373f1',
  // https://www.mazdastuff.com/Mazda-Part-Number-Index-p/0000-77-sg1-qt.htm
  '1e4200065e302e559d8789d2',
  // https://www.mazdastuff.com/Mazda-Part-Number-Index-p/k001-w0-225.htm
  'f80eab7d135538b362517744',
  // https://www.mazdastuff.com/Mazda-Protege-EGR-valve-gasket-p/je27-20-305a-51025.htm
  '0e4d1f6891e9162b6c5f1d98',
  // https://www.mazdawholesaledirect.com/oem-parts/mazda-a-c-compressor-kd4561450a
  '27032190e279e684a3b9ad54',
  // https://www.mishimoto.com/mishimoto-mazda-miata-1999-2005-performance-aluminum-radiator.html
  '6045e813b667ff202bfc3497',
  // https://www.motorcityreman.com/mazda-mpv-02-03-04-05-06-v6-alternator.html
  '4c3d4dcb553dfdc8812dd6b5',
  // https://www.motorcityreman.com/mazda-mpv-2000-2001-25l-alternator.html
  '9911f6f56b34ea88c297af12',
  // https://www.motorcityreman.com/mazda-rx-8-06-07-08-starter.html
  '18548fd70d615cb19ff9af76',
  // https://www.napaonline.com/en/p/CRC05361
  '14306735b93297260999c4d2',
  // https://www.oregonperformancetransmission.com/product/TRG-SKGF4A-EL.html
  'f4960e4a7e361daa78603fe9',
  // https://www.originalmazdaparts.com/oem-parts/mazda-water-pump-py8w15010b
  'bb8de28b6e0c5fb32c08bdef',
  // https://www.partcatalog.com/kyb-sm5308-suspension-strut-mount-kit.html
  'c460b0bb8f1982cf88a15a31',
  // https://www.partcatalog.com/products/dorman-cs360018-clutch-slave-cylinder
  'c4a671eabbb1d209d72fb35b',
  // https://www.partcatalog.com/products/moog-k80869-suspension-stabilizer-bar-link-rear
  '07104600dca9dface24dbfa8',
  // https://www.partsgeek.com/3199v3c-mazda-cx9-water-pump.html
  '10d73cdbd4a2518739878ada',
  // https://www.partsgeek.com/4fvs2nv-mazda-protege-stabilizer-bar-link.html
  '7f6848209b5073cc260c0215',
  // https://www.partsgeek.com/7tfc3by-mazda-protege-head-gasket.html
  '11b5fb2e3ad4d41262aa4491',
  // https://www.partsgeek.com/94c1h2b-mazda-cx9-water-pump.html
  '61eafba4b3254b7329c4c7cb',
  // https://www.partsgeek.com/bwlswwm-mazda-rx7-fuel-injector-seal-kit.html
  'cc9597bc579adac642bed65d',
  // https://www.partsgeek.com/c9vymm4-mazda-cx5-ac-receiver-drier.html
  'cb55969081f855133cb04b3b',
  // https://www.partsgeek.com/dd755q7-mazda-b3000-head-bolt-set.html
  'fa94a7a2c3ecb80ce3a10d29',
  // https://www.partsgeek.com/fl93g2s-mazda-protege-thermostat-gasket.html
  '3f8509e63cd6931d6bb71bd3',
  // https://www.partsgeek.com/gbproducts/WC/17609-01001554.html
  'd8715ce54289af841217fd52',
  // https://www.partsgeek.com/hbkmhw9-mazda-mx6-transmission-mount.html
  '67edd2b866896396704c3390',
  // https://www.partsgeek.com/hywwsxm-mazda-3-door-latch-assembly.html
  'cc887afd541c49efbf8afc6c',
  // https://www.partsgeek.com/k9w1qwn-mazda-mx6-timing-belt-kit.html
  '7d9017550b98a8f55c41e6ff',
  // https://www.partsgeek.com/kcj3y2j-mazda-mx6-stabilizer-bar-link-kit.html
  'a4191eef07cdbc085a5e7a7e',
  // https://www.partsgeek.com/l286b7j-mazda-cx9-timing-set.html
  'd3f195c9cfc34de8a476f804',
  // https://www.partsgeek.com/n1w2pqs-mazda-3-shock-absorber.html
  'e2e77ce2dff7d5dcf1cb8385',
  // https://www.partsgeek.com/q9tkh9k-mazda-b3000-head-gasket-set.html
  '7cb266183359a246a571ceeb',
  // https://www.partsgeek.com/rvccwqg-mazda-cx9-timing-set.html
  '059dd6202e530f722d098acc',
  // https://www.partsgeek.com/ryv6xpr-mazda-cx-30-ac-condenser.html
  '2ed6778b61cc043d588d9c97',
  // https://www.partsgeek.com/w89t173-mazda-6-trailing-arm-bushing.html
  '109ad2bad4acbc45ea35bfcc',
  // https://www.partsgeek.com/y5lnd9y-mazda-cx-3-ac-condenser-and-receiver-drier-assembly.html
  '70ef3aa74936631ec5060f4e',
  // https://www.realmazdaparts.com/oem-parts/mazda-compressor-assembly-d09w61450
  '0753f0c75a7e921f00dd9968',
  // https://www.realmazdaparts.com/oem-parts/mazda-mount-ga2g39070c
  'b5f9957da1dff70330964ee4',
  // https://www.sixityauto.com/2-pc-national-engine-camshaft-seals-for-1993-1997-mazda-mx-6-3hrkgjm27e.html
  'a26d00e9d46f34ae8891072b',
  // https://www.tascaparts.com/oem-parts/mazda-windshield-pillar-trim-fastener-driver-s-side-lh-bcjl68162
  '91b3a35aaed31a86db0be224',
  // https://www.tascaparts.com/oem-parts/mazda-windshield-pillar-trim-fastener-passenger-side-rh-bcjh68162
  'eb370580dc2a0b8aa87979d8',
  // https://www.transmissionpartsdistributors.com/f4e-4eat-f-f4a-el-transmission-filter-kit-fits-90-shallow-pan-type/
  '998fde297cb161e987d6c685',
  // https://www.walmart.com/ip/14621612697
  '24d72a12cd7d5c5e12ba09d2',
  // https://www.xtremediesel.com/motorcraft-75w-140-gear-oil-xy-75w140-ql
  'b7f703aa7516da8ccd9e51a0',
] as const;

export const vendorUrlFingerprints = [
  // 1a auto | https://www.1aauto.com/2010-13-mazda-3-main-recirculation-hvac-recirculation-door-actuator-trq-hca41844/i/1ahcx00441
  '445705e3d9cc90c6030c7a38',
  // advance auto parts | https://shop.advanceautoparts.com/p/permatex-dielectric-tune-up-grease-protects-electrical-connections-from-corrosion-3-oz.-22058/12027861-P
  '3812bdd54b22909684ba586b',
  // advance auto parts | https://shop.advanceautoparts.com/p/permatex-ultra-grey-rtv-silicone-gasket-maker-3-oz-82194/7160017-P
  '962b4c9d428f983938658fa7',
  // advance auto parts | https://shop.advanceautoparts.com/p/valvoline-80w-90-high-performance-conventional-gear-oil-1-quart-vv831/7070003-P
  'f65a08a2e66f28e9d562797b',
  // aip electronics | https://aipelectronics.com/products/complete-premium-electronic-ignition-distributor-for-1996-1998-kia-sephia-mazda-protege-1-5l-1-8l-t2t60371-mz14
  '1d79d328926183d316e5cfef',
  // am autoparts | https://www.am-autoparts.com/products/brake-pads/AM-1064753972.html
  'cf2fd29c75b0a792755336d7',
  // am autoparts | https://www.am-autoparts.com/products/brake-pads/AM-2506058450.html
  'e92562428ff2d34c66542093',
  // atkins rotary | https://www.atkinsrotary.com/04-08-Rx8-Oil-Metering-Line-Kit-ARE109.html
  '0fa8d8cf105dee4e8a6f8242',
  // atkins rotary | https://www.atkinsrotary.com/84-88-13B-Rx7-Oil-Metering-Pump-O-Ring-N236-14-604.html
  '83993499f7369f12cc028694',
  // atkins rotary | https://www.atkinsrotary.com/84-92-13b-rx7-atkins-designed-six-port-actuator-valve-kit-are113-.html
  '48afab2f682ea17fe6de6b05',
  // atkins rotary | https://www.atkinsrotary.com/86-88-N-A-Rx7-Oil-Metering-Line-Kit-ARE101.html
  '3a56a2aee48b150c9ea3959f',
  // atkins rotary | https://www.atkinsrotary.com/87-88-Turbo-Rx7-Oil-Metering-Line-Kit-ARE102.html
  'a7943f0350e4d35f0d35d19f',
  // atkins rotary | https://www.atkinsrotary.com/89-91-N-A-Rx7-Oil-Metering-Line-Kit-ARE106.html
  'e5ff8f46c1bd681ffb4c9291',
  // atkins rotary | https://www.atkinsrotary.com/89-91-Turbo-Rx7-Oil-Metering-Line-Kit-ARE107.html
  'd22c6a1159bfaaf4cf1e7107',
  // atkins rotary | https://www.atkinsrotary.com/89-95-Rx7-Oil-Metering-Pump-O-Ring-N350-14-604.html
  'e0394e21429763ca1541b91e',
  // atkins rotary | https://www.atkinsrotary.com/93-95-Rx7-Oil-Metering-Line-Kit-ARE108.html
  '648694946cdf4fcc169a0d0d',
  // atkins rotary | https://www.atkinsrotary.com/93-95-Rx7-Overhaul-Kit-B-ARE46.html
  'd8eb2cd44c2ae819c173d20d',
  // atkins rotary | https://www.atkinsrotary.com/93-95-Rx7-Pulsation-Damper-N3A2-20-180.html
  'c6efab6df716a3935be3673b',
  // atkins rotary | https://www.atkinsrotary.com/93-95-Rx7-Racing-Beat-Silicone-Radiator-Hose-Kit-11485.html
  '44cbf16e2ef9a494add86183',
  // atkins rotary | https://www.atkinsrotary.com/93-95-rx7-vacuum-rat-nest-hose-n3a3-20-346a-
  '536eb96937c5aaf72409a6c0',
  // atkins rotary | https://www.atkinsrotary.com/Emission-Control/Shutter-Valves/04-11-Rx8-Shutter-Valve-Gasket-N3H4-20-155A.html
  '933f08f900122f5297870264',
  // atkins rotary | https://www.atkinsrotary.com/Hoses/93-95-13B-Hoses/93-95-rx7-pre-control-turbo-hoses-n3a1-13-zly-
  'b59a9145d36c9a2cfe304d39',
  // atkins rotary | https://www.atkinsrotary.com/Rotary-Engine-Rebuild-Kits/Rx8-Rebuild-Kits/04-11-Rx8-Rotor-Kit-ARE64.html
  '5d8899508977f3d76d6b87a1',
  // auto parts prime | https://www.autopartsprime.com/centric/mp-14161555
  '0533e4c6723240267cf19f91',
  // auto parts prime | https://www.autopartsprime.com/centric/mp-14161556
  'ef99bc7d33ff38f95a1e2db3',
  // auto parts prime | https://www.autopartsprime.com/mevotech/mp-cms761171
  'effd89a6f097050e07703200',
  // auto parts prime | https://www.autopartsprime.com/mevotech/mp-cms761172
  'f8e1066cd260564adefee71b',
  // autonation parts | https://www.autonationparts.com/parts/mazda-a-c-compressor-bfd161450a
  'cc1eebbd2bc43e7b7ae17800',
  // autozone | https://www.autozone.com/batteries-starting-and-charging/battery/mazda/rx-8/b/group-size/35
  '4c68f7b188f389e01dd166bd',
  // autozone | https://www.autozone.com/p/crc-carburetor-throttle-body-cleaner-05078/55922
  '4623f85756d838a06586b4ca',
  // autozone | https://www.autozone.com/p/crc-carburetor-throttle-body-cleaner-05379/55920
  '9720b5a06ad3eb097a45682b',
  // autozone | https://www.autozone.com/p/crc-mass-air-flow-sensor-cleaner-05110/36011
  'b993cf60258bf6cc38c260a9',
  // autozone | https://www.autozone.com/p/duralast-gold-alternator-11005n/767423
  '77d81fdbca5099d7f1ddff12',
  // autozone | https://www.autozone.com/p/duralast-gold-alternator-13996n/763347
  'a777da437f703a7ceb3d41f2',
  // autozone | https://www.autozone.com/p/duralast-gold-alternator-dlg11007/1142826
  'eae5467fc911bb6e3a92e87f',
  // autozone | https://www.autozone.com/p/duralast-gold-alternator-dlg15582/427630
  '18502ec4e9a4e917bfa6f495',
  // autozone | https://www.autozone.com/p/duralast-platinum-battery-h6-efb/1070711
  '22f5b1d4094f8e1cc71c39c2',
  // autozone | https://www.autozone.com/p/fel-pro-exhaust-gas-recirculation-egr-valve-gasket-70714/225604
  'aed67933869b1a83b4ef4bc8',
  // autozone | https://www.autozone.com/p/fluid-film-multi-purpose-lubricant-as11/253803
  '35655cc9f39d9691163c9719',
  // autozone | https://www.autozone.com/p/magnaflow-exhaust-products-catalytic-converter-49150/422142
  '54cb5542e1242d2a1033994b',
  // autozone | https://www.autozone.com/p/trugrade-a-c-condenser-7-3879/375626
  '15848d7888b597ee5f81df7a',
  // autozone | https://www.autozone.com/p/valvoline-flexfill-extended-protection-gear-oil-902150/1398579
  'd9c27010beff04983a0e5a54',
  // awr racing | https://store.awrracing.com/1993-2003-protege-1-8-and-2-0-protege-5-and-mazdaspeed-protege-rear-engine-mount/
  '6d65355b2e0751f594a61d51',
  // best buy | https://www.bestbuy.com/product/anker-usb-a-to-lightning-cable6ft-1pack-blue/JJ85864PL2
  '54418616738e6a071f21ca98',
  // blauparts | https://www.blauparts.com/mazda-cx-3-transmission-fluid-atf-change-kit-atf-type-fz-0000-fz-113e-01.html
  '80119bf2f1520f94169257cf',
  // carid | https://www.carid.com/cardone/electronic-ignition-distributor-mpn-84-35620.html
  '150612db72eea4bb6e57c198',
  // conquest auto parts | https://conquestauto.com/products/new-oem-mazda-2006-2015-mazda5-sliding-door-latch-lock-mechanism-c235-72-9l0e
  'f3d98f1c9eab1e77a0e72b36',
  // corksport | https://corksport.com/mazdaspeed-6-2006-2007-rear-differential-mount.html
  '1889b40893085ca6beaf5041',
  // corksport | https://corksport.com/mazdaspeed-high-flow-fuel-pump-internals.html
  '7f7082bd324722a916c5d39a',
  // corksport | https://corksport.com/valve-cleaning-kit-for-mazdaspeed-3-mazdaspeed-6-and-mazda-cx-7.html
  'a0d844e02c1a55db6a207247',
  // damond motorsports | https://damondmotorsports.com/products/mazdaspeed3-rear-motor-mount-newly-revised
  '457e6b3e2a46010db8d167ae',
  // db electrical | https://www.dbelectrical.com/products/new-alternator-for-1-6-1-8-2-0-mazda-protege-99-00-01-02-03-1999-2003-13719.html
  'a69d4e691589399f397f37dd',
  // ebay | https://www.ebay.com/itm/145159291916?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'e1bc5fda9fa0e34d93684d5a',
  // ebay | https://www.ebay.com/itm/177762286994?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '357f526fa03de64cc696529f',
  // ebay - florida parts distributors | https://www.ebay.com/itm/226595011775?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '5a4c0db886bee730c14d24b7',
  // ebay - rareelectrical | https://www.ebay.com/itm/375990664172?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '18accbb48f591277b0267d4d',
  // ebay — the parts department | https://www.ebay.com/itm/123808129373?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'b0707798a4f90dbd35591097',
  // edge autosport | https://edgeautosport.com/mazda-oem-turbo-oil-feed-line-mazdaspeed-3-2007-2013-mazdaspeed-6-2006-2007/
  'a5d6a7db9f5af09677d9e2db',
  // edge autosport | https://edgeautosport.com/mazda-oem-turbocharger-mazdaspeed-3-2007-2013-mazdaspeed-6-2006-2007/
  'a386ef6cd8ac739ae8a68d41',
  // edge autosport | https://edgeautosport.com/mazda-oem-vvt-replacement-kit-mazdaspeed-3-2007-2013-mazdaspeed-6-2006-2007/
  '013447458a351d35c7316f9b',
  // finditparts | https://www.finditparts.com/products/10399717/
  'e8819929b54e57ee8bb2993f',
  // finditparts | https://www.finditparts.com/products/2455166/a-1-cardone-31-35602
  'd26626137b94bc139ceed376',
  // finditparts | https://www.finditparts.com/products/8199600/fel-pro-es-72846
  '55bd0a6b2dbba53d0133b466',
  // florida mazda parts | https://www.floridamazdaparts.com/parts/mazda-window-regulator-gd4t58560c
  'dc797f7cb8b28c6c8aade669',
  // florida mazda parts | https://www.floridamazdaparts.com/parts/mazda-window-regulator-gd4t59560c
  '3fd71adb158a9c99d08b7caf',
  // injector-rehab | https://injector-rehab.com/product/side-feed-fuel-injector-clean-and-flow-test/
  '803218c41746c00287c3d1ac',
  // invasion auto products | https://www.invasionautoproducts.com/supercharger-mazda-sc-maz-9502.html
  '5e703861a9dd455a78e1aad1',
  // ipd usa | https://www.ipdusa.com/products/65848/Engine-mount-MTC-9082-Mazda-B25D39040-B25F39040A-B25F39040B-B25G39040-B25G39040C-B25G39040D
  '513d30077e08525de1860b10',
  // ipgparts | https://ipgparts.com/collections/exedy/products/exedy-replacement-clutch-slave-cylinder-fits-1990-2005-mazda-miata-na-nb
  'f468c0161034776d3f593072',
  // joetlc | https://www.joetlc.com/products/clutch-slave-cylinder-for-ford-probe-or-mazda-626-mx6
  '5eba517ef5ab2895f19ab07a',
  // koni online germany | https://www.koni-online.com/Mazda-CX-60-stossdaempfer-komplett-set-Special-Active-1x8245-1438L1x8245-1438R2x8245-1439
  'c8d2d90445e4dc85d195888f',
  // madness autoworks | https://madnessautoworks.com/start-shopping/brakes-upgrade?product_id=300390317
  '243358f4b2b5a55377135938',
  // madness autoworks | https://madnessautoworks.com/start-shopping/suspension-upgrades-madness?order=DESC&product_id=300279916&sort=pd.name
  '15f6ac1211f7078573a89f82',
  // maniac electric motors | https://www.maniacelectricmotors.com/13559.html
  'e7d0729a23704a2d0b059a6a',
  // mazda oem parts online | https://mazda.oempartsonline.com/oem-parts/mazda-evaporator-core-l20661j10a
  '7341b833f1b7eb6221fc856e',
  // mazda online parts | https://www.mazdaonlineparts.com/parts/mazda-pump-water-pe0115010d
  '0809a9e792a8a6f9801de814',
  // mazda stuff | https://www.mazdastuff.com/Mazda-Protege-EGR-valve-gasket-p/je27-20-305a-51025.htm
  '948d4939b89266a656d4bee6',
  // mazda wholesale direct | https://www.mazdawholesaledirect.com/oem-parts/mazda-a-c-compressor-kd4561450a
  'f05917b9b0947aba3d97f7d2',
  // mazda-parts | https://www.mazda-parts.com/oem-parts/mazda-crankshaft-position-sensor-bp4w18221b
  'ddea7493dd86ac053c628fa9',
  // mazda-parts | https://www.mazda-parts.com/oem-parts/mazda-window-regulator-t00158590
  'cf5bc552006173688cb4779e',
  // mazda-parts | https://www.mazda-parts.com/oem-parts/mazda-window-regulator-t00159590
  '42368d3445847f8b7b034690',
  // mazda-parts.com | https://www.mazda-parts.com/oem-parts/mazda-solenoid-pyfa12360a
  '11bf9c13cfc17a892ba4f3d4',
  // mazdaparts.us | https://www.mazdaparts.us/parts/mazda-a-c-condenser-bdwk61480b
  '459dbf66d038df57c6ea9ad8',
  // mazdaparts.us | https://www.mazdaparts.us/parts/mazda-expansion-valve-d09w61j14
  'f55e28ddfdba02a44d4438ed',
  // mazdaparts.us | https://www.mazdaparts.us/parts/mazda-water-pump-pyfa15010d
  'd665b5e36271731491bb8fbd',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~actuator~l3k9124x0c
  'f47d2ae6120acedfc09bcc29',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~actuator~lf94124x0d
  'bec50d661b11f7026a445a35',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~actuator~pe01124x0b
  '430453642e728434537766eb',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~egr-valve~bp3c20300a9u
  '5be07a7f0d3c819d0ad83157',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~egr-valve~lfhj20300
  '82236c5dca3615c096c806f9',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~egr-valve~zzda20300
  '9411e638abc0c985d4755706',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~evaporator~cc4361j10
  'bcdf30f5f69aef08960de1c1',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~expansion-valve~kf0361j14
  '2c0f8ac27c0fbff1fc35fcc9',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~gasket~lf0120305
  '4cd82a50beabe97966d5b09a',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~hub-bearing~kd312615xb
  'cddc5dd3544102d9999b0fb0',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~hub-rr-wheel~kd352615xd
  '12af4b02d98f22ba4a0ee8c5',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~hub-wheel~kd353304xj
  'fa73a4aded3447ba1215fd52',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~lock~tk4962310c
  'dcce4380a247fd9ac7db45eb',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~manifold-gasket~pe1713460
  '1e647e87fa1790a3d54feb87',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~manifold-gasket~py0113460
  '6b08dacc7e30ed9e2645cd7b',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~mass-air-flow-sensor~pe0113215
  'bb4cd0e05a46bfdea4475220',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~motor-mount~d65239060h
  '89aafe60e045ff62a9f4aa84',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~rear-main-seal~bp0511312
  '5864ece115b6396d1d02c741',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~seal~fs0210602
  '66dd788055b75a5b4199fe87',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~solenoid-valve~lf8218740
  '7a6ce19f3a3bdb95ab2018d7',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~solenoid~l30118741
  '91135731b6af43414ba5f0a4',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~solenoid~l51818741
  '869199b2abbcdd714bab5c2c',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~spring~lc7028011a
  '21c7fbe3e91d85f67bbdbdd9',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~strut~tk49626exl
  '51d5c1bbedb199cecf7053a3',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~strut~tk49636exl
  'fe1974f4d4b491f1f1f9360f',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~temperature-sensor~g51861764a
  '3ec5e649f1e8c8df17613af9',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~timing-chain~l3k912201a
  '9e0a5e30084a84d6ac486ea8',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~transmission-fluid~000077112e01
  'ac067a0b59a7ac447ebe6a57',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~transmission-mount~bbm439070d
  'a70dfeeb0be44ca78b17442a',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~transmission-mount~bbm539070c
  '88b21805cf87b5ffa9730d29',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~transmission-mount~cc2939070
  'e614f153b751e657fdccb0d5',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~transmission-mount~dr6239070c
  '638bfee5bdfe4c6de86851c0',
  // mazdapartsnow | https://www.mazdapartsnow.com/genuine/mazda~turbocharger~l3yc1370za
  '0f542ae72d4e84a8944d9451',
  // mazdashop usa | https://mazdashopusa.com/products/transmission-fluid-automatic-a7-mazda
  'a3ce5a0c88f5b133c21d1e82',
  // mazdashop usa | https://mazdashopusa.com/products/transmission-fluid-automatic-fz-mazda
  '19459466a7a7e8e85b3bfa3a',
  // mazdastuff | https://www.mazdastuff.com/Mazda-CX-5-Left-Motor-p/ka0g-26-8exa-55061.htm
  'ab8c2e3492c24621bf198f85',
  // mazdastuff | https://www.mazdastuff.com/Mazda-CX-5-Timing-cover-sealer-p/r2y1-10-431-45308.htm
  'd92b8719f702209cc68b8c4c',
  // mazdastuff | https://www.mazdastuff.com/Mazda-Part-Number-Index-p/0000-77-80w9-qt.htm
  'af0e914e865f1e505fb8bba8',
  // mazdastuff | https://www.mazdastuff.com/Mazda-Part-Number-Index-p/0000-77-sg1-qt.htm
  'cac365af571b9edfe7bf28c2',
  // mazdastuff | https://www.mazdastuff.com/Mazda-Part-Number-Index-p/k001-w0-225.htm
  'a24b51b5e2122c81c926ad58',
  // mazdatrix | https://mazdatrix.com/product/gasket-water-pump-93-95/
  'b67740d805365d1ff799c061',
  // mazdatrix | https://mazdatrix.com/product/ign-coil-04-on-rx8-each/
  '8a2c2257e1ceb42cce2366ca',
  // mazdatrix | https://mazdatrix.com/product/ign-coil-86-92-trail/
  'd59c91566b1a423f9e4dd5b0',
  // mazdatrix | https://mazdatrix.com/product/ign-coil-93-95-leading/
  '8bd653636e787cf6155cd497',
  // mazdatrix | https://mazdatrix.com/product/ign-coil-93-95-trail-1/
  '697eba34423147f5677655aa',
  // mazdatrix | https://mazdatrix.com/product/ign-coil-93-95-trail-2/
  '7659530b4fa48292c9663150',
  // mazdatrix | https://mazdatrix.com/product/ign-plug-wires-04-on-rx8-ngk/
  '0b73d04fdd3dcae13ed7c1cd',
  // mazdatrix | https://mazdatrix.com/product/ign-plug-wires-93-95-ngk/
  '13d15ef764e07ef344f4ff48',
  // mazdatrix | https://mazdatrix.com/product/pump-metering-04-on-rx8/
  'ae0e694d47689029bb720739',
  // mazdatrix | https://mazdatrix.com/product/pump-metering-o-ring-04-on-pump-to-engine/
  '6a0fe8d1ee4106e887438f54',
  // mazdatrix | https://mazdatrix.com/product/spark-plug-set-rx8-set-of-4-plugs/
  '09ecb7b9b00085d762146fcd',
  // mazdatrix | https://mazdatrix.com/product/susp-toe-eliminator-86-92-all-pair/
  'fc44d2c0d841b5c7ebf1c658',
  // mazdatrix | https://mazdatrix.com/product/water-pump-93-95/
  'bf32fc7935c58e6d02c780c6',
  // mazmart | https://mazmartstore.mybigcommerce.com/mazda-oem-starter-for-rx-8-automatic-tranmission-only-n3z2-18-400/
  'dbfa0aef8c34618f59095922',
  // mazmart | https://mazmartstore.mybigcommerce.com/mazda-oem-starter-for-rx-8-manual-tranmission-only-n3z1-18-400/
  '1c278b76fb8a679343016d4a',
  // mishimoto | https://www.mishimoto.com/mishimoto-mazda-miata-1999-2005-performance-aluminum-radiator.html
  'a4d369592939b71f1decdee1',
  // moss miata | https://mossmiata.com/1990-1997-mx-5-miata/239-570-cp-vinyl-zippered-standard-glass-window-factory-style-tops-by-robbins
  '9de14a82d0336c5231ebbba6',
  // moss miata | https://mossmiata.com/1990-1997-mx-5-miata/240-195-cp-vinyl-zippered-plastic-window-factory-style-convertible-tops-by-robbins
  '8c96f5d0b4d16d6c5d6c26aa',
  // moss miata | https://mossmiata.com/1990-1997-mx-5-miata/971-031-valve-cover-gasket-by-mazda
  'a355ab239161ca56c0810aa0',
  // moss miata | https://mossmiata.com/2006-2015-mx-5-miata/903-465-rear-main-seal-by-mazda
  'cc18b752d5a632c0f6af7674',
  // moss miata | https://mossmiata.com/902-884-camshaft-position-sensor-o-ring-gasket-by-mazda
  'e5a90d5b16a4538b8639786a',
  // moss miata | https://mossmiata.com/905-375-left-hand-replacement-door-sill
  '33ca39c34a93597b07aa85f9',
  // moss miata | https://mossmiata.com/905-376-right-hand-replacement-door-sill
  'c6e3aa6c2d4489d46263080a',
  // moss miata | https://mossmiata.com/971-035-valve-cover-gasket
  '55c88569e6b7191fbda49535',
  // moss miata | https://mossmiata.com/971-036-valve-cover-gasket-by-mazda
  '67df451da756781a019b3fce',
  // moss miata | https://mossmiata.com/971-037-valve-cover-gasket-by-mazda
  '998c1fdf48a2e9ffd28ae630',
  // motor city reman | https://www.motorcityreman.com/mazda-mpv-02-03-04-05-06-v6-alternator.html
  '2a82069d2510afc68a939894',
  // motor city reman | https://www.motorcityreman.com/mazda-mpv-2000-2001-25l-alternator.html
  '030e01c0e4b8eb91daf49ae5',
  // motor city reman | https://www.motorcityreman.com/mazda-rx-8-06-07-08-starter.html
  'ecce9a1d618715aeb1560d46',
  // napa | https://www.napaonline.com/en/p/CRC05361
  '00e3cacb85e16afc9fabf97f',
  // noco | https://no.co/genius1
  '0df108937fb7227cd18afe2e',
  // oregon performance transmission | https://www.oregonperformancetransmission.com/product/TRG-SKGF4A-EL.html
  '055528b4b18d1f55a2da6a91',
  // original mazda parts | https://www.originalmazdaparts.com/oem-parts/mazda-water-pump-py8w15010b
  '9fbe0f210a71012fd6c064c6',
  // painless performance | https://painlessperformance.com/product/universal-body-engine-ground-strap-kit-part-no-40140/
  '6eb73729372e4e95679f3860',
  // partcatalog | https://www.partcatalog.com/kyb-sm5308-suspension-strut-mount-kit.html
  '918d80813376326d9a1008d2',
  // partcatalog | https://www.partcatalog.com/products/dorman-cs360018-clutch-slave-cylinder
  '0e954525fce001d64466baed',
  // partcatalog | https://www.partcatalog.com/products/moog-k80869-suspension-stabilizer-bar-link-rear
  '6e46a6c22a0a99be2d7a32f4',
  // partsgeek | https://www.partsgeek.com/3199v3c-mazda-cx9-water-pump.html
  'a7cacf194adc43a5e505ee2d',
  // partsgeek | https://www.partsgeek.com/4fvs2nv-mazda-protege-stabilizer-bar-link.html
  'dbf7c748c47e3bcf8c95ab20',
  // partsgeek | https://www.partsgeek.com/7tfc3by-mazda-protege-head-gasket.html
  '0c25f1625c6915befc6df883',
  // partsgeek | https://www.partsgeek.com/94c1h2b-mazda-cx9-water-pump.html
  '2bc288aaece34392cd9100aa',
  // partsgeek | https://www.partsgeek.com/bwlswwm-mazda-rx7-fuel-injector-seal-kit.html
  'f231c2684936e2bb1d3eceaa',
  // partsgeek | https://www.partsgeek.com/c9vymm4-mazda-cx5-ac-receiver-drier.html
  '9acfe1dd30dffa499da657c8',
  // partsgeek | https://www.partsgeek.com/dd755q7-mazda-b3000-head-bolt-set.html
  '3d2969e446a315674378c80d',
  // partsgeek | https://www.partsgeek.com/fl93g2s-mazda-protege-thermostat-gasket.html
  'dc93bb8ca3d14e99c11b6228',
  // partsgeek | https://www.partsgeek.com/gbproducts/WC/17609-01001554.html
  '523e909a185e40fef03192ab',
  // partsgeek | https://www.partsgeek.com/hbkmhw9-mazda-mx6-transmission-mount.html
  '4ec9d3e9266c46849834d1ec',
  // partsgeek | https://www.partsgeek.com/hywwsxm-mazda-3-door-latch-assembly.html
  'f9530c1fa279e7d0b4d123db',
  // partsgeek | https://www.partsgeek.com/k9w1qwn-mazda-mx6-timing-belt-kit.html
  'f53157e847f01790067b5a43',
  // partsgeek | https://www.partsgeek.com/kcj3y2j-mazda-mx6-stabilizer-bar-link-kit.html
  'd0459c106d1d4d1534ea7a49',
  // partsgeek | https://www.partsgeek.com/l286b7j-mazda-cx9-timing-set.html
  'f5f049b18d0c0e3ee9564588',
  // partsgeek | https://www.partsgeek.com/n1w2pqs-mazda-3-shock-absorber.html
  'f6b404cd3fb2327b33b488d7',
  // partsgeek | https://www.partsgeek.com/q9tkh9k-mazda-b3000-head-gasket-set.html
  '2ac06391fe88186f45b6e2bb',
  // partsgeek | https://www.partsgeek.com/rvccwqg-mazda-cx9-timing-set.html
  '755aeb80456a12ab1e1f18fd',
  // partsgeek | https://www.partsgeek.com/ryv6xpr-mazda-cx-30-ac-condenser.html
  '3579a2bf1177e0000aa99416',
  // partsgeek | https://www.partsgeek.com/w89t173-mazda-6-trailing-arm-bushing.html
  '52fbf2e99305c4252e35b024',
  // partsgeek | https://www.partsgeek.com/y5lnd9y-mazda-cx-3-ac-condenser-and-receiver-drier-assembly.html
  'e88ac9acda5ea22038f3ddec',
  // pbe direct | https://pbedirect.com/products/3m-cavity-wax-aerosol-08852
  '83eac9b1cb940baa591bf181',
  // real mazda parts | https://www.realmazdaparts.com/oem-parts/mazda-mount-ga2g39070c
  '3a7740b18e25a49972a9780f',
  // realmazdaparts | https://www.realmazdaparts.com/oem-parts/mazda-compressor-assembly-d09w61450
  '4fe5edf9ea9b3f7a5a6663dd',
  // rotarytronics | https://rotarytronics.com/product/rotary-compression-tester/
  'bdbdd144e0dda5bafd989060',
  // sixity auto | https://www.sixityauto.com/2-pc-national-engine-camshaft-seals-for-1993-1997-mazda-mx-6-3hrkgjm27e.html
  'a882318f5cb3fe0367a07255',
  // sparktec motorsports | https://sparktecmotorsports.com/i-30632869-magnaflow-converter-df-93-95-mazda-rx7-1-3l.html
  'eb56d0bdecb3cf7111c3b2f2',
  // tasca parts | https://www.tascaparts.com/oem-parts/mazda-windshield-pillar-trim-fastener-driver-s-side-lh-bcjl68162
  '450408959f54cb66dad14e6b',
  // tasca parts | https://www.tascaparts.com/oem-parts/mazda-windshield-pillar-trim-fastener-passenger-side-rh-bcjh68162
  '86d40f99bd2b95496fbed944',
  // transmission parts distributors | https://www.transmissionpartsdistributors.com/f4e-4eat-f-f4a-el-transmission-filter-kit-fits-90-shallow-pan-type/
  '33242b5287789afe1c50d7a0',
  // treasure coast miata | https://treasurecoastmiata.com/i-14385851-1990-1993-premium-miata-timing-belt-water-pump-replacement-kit-gates-and-oem.html
  '4a1e12aed55b7bf5b78e17f0',
  // treasure coast miata | https://treasurecoastmiata.com/i-18598700-new-94-00-mazda-miata-premium-gates-and-mazda-timing-belt-water-pump-replacement-kit.html
  '1f5aa052c146fd8b4d18ac9b',
  // tsurugi motors | https://tsurugi-online.com/products/mazda-genuine-n3h5-20-160f-oem-2004-11-rx-8-manifold-secondary-shutter-valve
  '6cd96ea0295ad62abe72ab04',
  // valvoline | https://shop.valvolineglobal.com/products/dex-merc-atf-automatic-transmission-fluid
  'bad651f33e711edcee273737',
  // valvoline | https://shop.valvolineglobal.com/products/mercon-v-atf-automatic-transmission-fluid?Size=1+QT
  '2e7411c71aecd7fd685871c1',
  // walmart | https://www.walmart.com/ip/14621612697
  '4132cbfb9b2741556a70f6c1',
  // walser mazda parts | https://parts.walser-mazda.com/p/Mazda__Tribute/Direct-Ignition-Coil/49185667/AJ0918100.html
  '06dc9243500dff18b54472a3',
  // xdp | https://www.xtremediesel.com/motorcraft-75w-140-gear-oil-xy-75w140-ql
  '46d15be68d73038dbafd46e1',
] as const;

export const retailerHostFingerprints = [
  // 1aauto.com
  '3703d7177e3c08c25f297e88',
  // aipelectronics.com
  'cb621e25cbc75ad46684be36',
  // am-autoparts.com
  '1fd199dde0d1cf3ed07c1cc3',
  // atkinsrotary.com
  '6e011b8c6175ce0c6bcd83b8',
  // autonationparts.com
  'e9524fc443950c52556c1422',
  // autopartsprime.com
  'b6e04d2c3d46d1504d717b52',
  // autozone.com
  '12fa1f440ebfbfd1c0ab1b19',
  // bestbuy.com
  'b61ff117c9370f79544a9d0c',
  // blauparts.com
  'b4a4af48260536a22ae1567c',
  // carid.com
  '94c5b484782a92c151da35b7',
  // conquestauto.com
  '07de8cc6df7857142559edef',
  // corksport.com
  '7fd7d9a91975d7476745e8e0',
  // damondmotorsports.com
  'ea323d0fc7de29ec77ae9178',
  // dbelectrical.com
  'b81de7cae5d3707adb0a43ee',
  // edgeautosport.com
  'b4535ae39adbe7c261637e19',
  // finditparts.com
  '7e08600bd0825315e1f077e2',
  // floridamazdaparts.com
  'bf3b93c833c9e84e586b0ac4',
  // injector-rehab.com
  '1a1218160fb3996cbd1e841b',
  // invasionautoproducts.com
  '3562b2cc86d6939cc232cd4f',
  // ipdusa.com
  'a2612f6f7d8ce919cf720630',
  // ipgparts.com
  'b48443878aa65de12582166f',
  // joetlc.com
  '4d22147fe6524de1033a809c',
  // koni-online.com
  '5f19365d5fc410b70af20ba0',
  // madnessautoworks.com
  'a4dee0998485ee49698f590e',
  // maniacelectricmotors.com
  'bd9be17c62b4521b601ec4ed',
  // mazda-parts.com
  '36aa5a70a14feb2d2e6c166d',
  // mazda.oempartsonline.com
  '919c83b9969071a4674b481d',
  // mazdaonlineparts.com
  '193a691a8e17f7658615ab6a',
  // mazdaparts.us
  '6c9965a02209c88770960e23',
  // mazdapartsnow.com
  '1298b0ea5defd5b7e7a25433',
  // mazdashopusa.com
  '6653957776b132e6d2e4fbaa',
  // mazdastuff.com
  'c00221c96b7364bdaa946947',
  // mazdatrix.com
  '677374874166db080ed8ab74',
  // mazdawholesaledirect.com
  '4134cf793efc7fca9347dd52',
  // mazmartstore.mybigcommerce.com
  'c35f188788dca2078d75970b',
  // mishimoto.com
  'f7496592c50882509b95b52a',
  // mossmiata.com
  '609f2789c6f63fd74acad981',
  // motorcityreman.com
  '1a2f881a0f7bc24d53f9e1af',
  // napaonline.com
  'f548aa17dadb360706774067',
  // no.co
  'b7d605d2fccd56c3c240c385',
  // oregonperformancetransmission.com
  '7e79306f8a1fb78cf45349a3',
  // originalmazdaparts.com
  'd88908c8e19c842b3fba4c73',
  // painlessperformance.com
  'e6890c05a2464ce31ba01dd0',
  // partcatalog.com
  '85d0f7949323a49d56724bc5',
  // parts.walser-mazda.com
  '87ddb6abad50b92471db49c5',
  // partsgeek.com
  'b6c9d443e05ef437cef78a38',
  // pbedirect.com
  '1690a3cf19945fad6c56239a',
  // realmazdaparts.com
  '2cf50cc30df2c0a4f803ea78',
  // rotarytronics.com
  '942b114e25f6b79969d9a17f',
  // shop.advanceautoparts.com
  '3d7f5ea36b6847e33e997fca',
  // shop.valvolineglobal.com
  'b409eb5204e7d7cf38a459e7',
  // sixityauto.com
  'aa7a0d469cbff99842de4076',
  // sparktecmotorsports.com
  'bc77a30edd0aac4d2d7094f6',
  // store.awrracing.com
  '0acd47f40cde3e7a14111514',
  // tascaparts.com
  'dc7dcf27ad7e3a67eca2e5f6',
  // transmissionpartsdistributors.com
  '4ab231502874540915b5ddf6',
  // treasurecoastmiata.com
  '4e80f2c827c4e1735407de14',
  // tsurugi-online.com
  'a3c2b373c5a6ff644f26b8d3',
  // walmart.com
  'ce624b6b31766d560320dd93',
  // xtremediesel.com
  '4281112e10eb397d3ccf28fd',
] as const;
