// GENERATED by scripts/build-repair-first-verified-batch.mjs for Opel.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://a1allcars.co.uk/product/vauxhall-insignia-2009-2013-electric-handbrake-switch-13271123/
  '505f3471f901ae62b2d7581d',
  // https://acornautoparts.co.uk/shop/adblue-injection/3647595-new-adblue-injector-for-opel-vauxhall-grandland-grandland-x-1-5-turbo-d-2018-on/
  '403d04db7f00e71316a9b3ef',
  // https://auto724.co.uk/nox-sensor-bosch-9816276480
  'b13daa72c1cc82c6d76654ed',
  // https://business.walmart.com/ip/Electric-Parking-Brake-Switch-for-Vauxhall-for-Astra-J-for-ZAFIRA-C-20843230/7709074793
  '472755defdc0234ea38b4c47',
  // https://carparts247.co.uk/aisin-121947800.html
  '9b0de9ca35bb0d685efac44b',
  // https://carparts247.co.uk/lemforder-92381.html
  '9a8dce5abe2146ad2243fc5a',
  // https://carparts247.co.uk/schaeffler-luk-18011.html
  '525324e063f072b81e424c7f',
  // https://ctek.com/en-uk/products/cs-one-gen-1-uk
  'f340c81125cd336e362c1cad',
  // https://evotectuning.co.uk/products/genuine-gm-dexos-2-5-30-fully-synthetic-oil-5litre
  '8ca9d067d4d7008d41fe03d6',
  // https://gtautomotiveparts.co.uk/product/gtck207/
  '3d23004ab5240f19a38ef1f9',
  // https://haldexparts.co.uk/products/borgwarner-20986573-saab-opel-coupling-oil-filter-kit
  'b079b6788a2f8112a8455176',
  // https://haldexparts.co.uk/products/opel-saab-0404029-rear-differential-oil-pump-gm-lsd
  '90a5ab1a5aa36039c9d8aebc',
  // https://klifex.net/products/full-swirl-flap-repair-kit-opel-z19dth-z19dtj-55210201
  '13444aa09b8fe0fcdba689b3',
  // https://motostacja.com/p/TOTAL-INEO-FIRST-0W20-5L/
  '91b58b2fda8215f140d81983',
  // https://shop.midlandautocare.co.uk/collections/timing-chain-kits/products/vauxhall-corsa-d-1-2-1-4-timing-chain-kit-a12xer-a14xel-a14xer-engine
  'b08c51603f91cfae67ce3a14',
  // https://shop.midlandautocare.co.uk/products/opel-vauxhall-insignia-2-0-cdti-timing-cam-belt-kit-and-water-pump
  '4561d0f6fe932c3fcbd7b491',
  // https://shop.midlandautocare.co.uk/products/r9m-engine-timing-chain-kit
  'a944735b1cfc2439a0f705df',
  // https://spareto.com/products/metzger-cable-repair-set-interior-heating-fan-eng-preheat-sys-dot/2322008
  '76b58745e62db577e8b6597b',
  // https://vauxcentre.co.uk/collections/engine-parts-timing-belt-kit/products/genuine-vauxhall-corsa-d-early-z12xep-z14xep-timing-chain-kit-93191271-new
  'b80251d423c586fdc2bf6f0e',
  // https://vauxcentre.co.uk/products/oe-vauxhall-1-7-diesel-egr-valve-97376663-95523829
  '216ff08c59411a7da8926e59',
  // https://vauxcentre.co.uk/products/oem-vauxhall-corsa-d-handbrake-cable-assy-r-l-1305-1475-mm-long-new-13355087
  'ea15813fb158b3d030d8c783',
  // https://vauxcentre.co.uk/products/original-vauxhall-zafira-c-1-6-diesel-position-1-nox-sensor-55485493-new
  '753751ab90f410ed3e050473',
  // https://vauxcentre.co.uk/products/original-vauxhall-zafira-c-1-6-diesel-position-2-nox-sensor-55485442-new
  'fdb7acdd5699b209efe05495',
  // https://vauxcentre.co.uk/products/vauxhall-zafira-c-2-0-diesel-position-1-nox-sensor-55598161-new-oe-part
  'cbd9165286f6d55bf69e161b',
  // https://vauxhallpartsdirect.co.uk/product/vauxhall-insignia-2009-2017-electric-hand-brake-module/
  'f785f5af547d0c582dc7a2aa',
  // https://www.autodoc.co.uk/adriauto/15699042
  '0c4bf22b9631e11dc5d39267',
  // https://www.autodoc.co.uk/total/15229578
  '338fb3883eaf3885bfb1c7ff',
  // https://www.autodoc.parts/general-motors/26749524
  '19f12aac6a2f5f7f4469acf7',
  // https://www.cats2u.co.uk/vauxhall/42049-vauxhall-mokka-16-0115-1219-diesel-particulate-filter.html
  '55b60e24d20e19cce99685e8',
  // https://www.dpf-catalysts24.com/particle-filter-opel-mokka-a-1-7-cdti-j13-sku-dpf-g9096.html
  '08aaf0525c664687a3c705f3',
  // https://www.ebay.co.uk/itm/185194276592?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '71f459ca790ba425673b35f5',
  // https://www.ebay.co.uk/itm/203861524086?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'f8c0bbefcc26b737410e1437',
  // https://www.ebay.co.uk/itm/315390588296?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '4dea0cdb8b7f62602b3c77ab',
  // https://www.ebay.co.uk/itm/318089853717?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '207e9a83b2ed33af18258080',
  // https://www.ebay.co.uk/itm/376629131002?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '66b5c8d341f195e2535526fa',
  // https://www.generalopel.com/urun/opel-insignia-a-elektrikli-el-fren-teli-komple-gm-orjinal
  'c97dc929d06e28c02b76d22d',
  // https://www.halfords.com/motoring/engine-oils-and-fluids/adblue/halfords-10l-adblue-293283.html?includeFitting=false
  '9f560443dc676ddc37c854d9',
  // https://www.hawkparts.co.uk/product/subframes/front/front-subframe-crossmember-for-opel-corsa-d-s07-06-15-13427070/
  '61d58f12f9591f74f6d694f0',
  // https://www.ic24.uk/products/f6140f-air-conditioning-condenser-dcn15005
  'bfe4e0cd3044654056f35ba1',
  // https://www.iparts.pl/czesc/sprzeglo-komplet-sachs-2290601239%2C0-32-2290601239-4626799.html
  '9f3efd6080af53ea6805bfb0',
  // https://www.jendvandenbosch.nl/egr-koeler-1-6-cdti-b16dth-diesel-origineel-55509027-opel-astra-insignia-mokka-zafira/a16518
  '4100ee794ff3de24e4bbbea5',
  // https://www.jendvandenbosch.nl/egr-koeler-1.6-cdti-b16dth-diesel-origineel-55509027-opel-astra-insignia-mokka-zafira/a16518
  'e016924fb5af29fcc5cd147c',
  // https://www.leadercomponents.com/product/lsc-13248240-heater-blower-fan-resistor-new/
  '3bb1a05635537f4c1852c80d',
  // https://www.leadercomponents.com/product/lsc-55590953-55572962-genuine-egr-valve-cooler-and-valve-vacuum-tank-repair-kit-new/
  '66b4f01d838452268b7e8dfc',
  // https://www.leadercomponents.com/product/lsc-9829870080-genuine-egr-valve-12v-5-pin-connector-new/
  'acbb2bfc207457195452d35b',
  // https://www.mymotorworld.com/bga-tc1030fk-timing-chain-kit
  '19e9715897cecee5aa2602a0',
  // https://www.neobrothers.co.uk/car-parts/fuel-system/fuel-additive/nox-sensor/oe-nox-sensor-rear-position-2-vauxhall-zafira-c-2-0-b20dth-b20dtj-55598169
  '060a3b515a2910d2de27004f',
  // https://www.onlinecarparts.co.uk/car-brands/spare-parts-vauxhall/zafira-mk-ii-b-m75/19308/10553/water-pump-timing-belt-kit.html
  '52421392b19bf060fcffc516',
  // https://www.onlinecarparts.co.uk/ina-21498935.html
  'f9ededaa3a73be69a2a5f5ca',
  // https://www.opel-sklep.com/pl/p/Pompa-wody-oryginalna-1.6-1.8-benzyna-Z16XEP-Z18XER-1334142-25195119-OPEL-GM/942
  '0f1a32358eb65e59dba95b42',
  // https://www.sussexautos.com/products/aisin-oem-automatic-transmission-fluid-atf-aw2-1-litre
  '3767850a83da9646d3627ff4',
  // https://www.winparts.co.uk/engine-parts-accessories/timing-and-belts/timing-chain/c1175/timing-chain-kit-ina-engine-kit/p1435164.html
  'ba2d9d4a5e10311832b09fd1',
] as const;

export const vendorUrlFingerprints = [
  // a1 all cars | https://a1allcars.co.uk/product/vauxhall-insignia-2009-2013-electric-handbrake-switch-13271123/
  '1196a19e7379d1833cd5a4eb',
  // acorn auto parts | https://acornautoparts.co.uk/shop/adblue-injection/3647595-new-adblue-injector-for-opel-vauxhall-grandland-grandland-x-1-5-turbo-d-2018-on/
  '0be32e151ab5630b5b73ec33',
  // auto724 | https://auto724.co.uk/nox-sensor-bosch-9816276480
  '4b390a5844d7087b2d539f5e',
  // autodoc | https://www.autodoc.parts/general-motors/26749524
  'f9dc0a46f1b08bbeaeff55ff',
  // autodoc uk | https://www.autodoc.co.uk/adriauto/15699042
  'c7bd7cae9f1d5a357820ae8c',
  // autodoc uk | https://www.autodoc.co.uk/total/15229578
  'a7eb7d4ea0624d322e5cefd2',
  // carparts247 | https://carparts247.co.uk/aisin-121947800.html
  'f12f639493bfc2afd31aa097',
  // carparts247 | https://carparts247.co.uk/lemforder-92381.html
  'a0f392380530e1a692c667ea',
  // carparts247 | https://carparts247.co.uk/schaeffler-luk-18011.html
  '354168ef1b9a19cd69bf5c59',
  // cats2u | https://www.cats2u.co.uk/vauxhall/42049-vauxhall-mokka-16-0115-1219-diesel-particulate-filter.html
  'd41deb36df16a868e74c1c78',
  // ctek | https://ctek.com/en-uk/products/cs-one-gen-1-uk
  'c230e0973afb03e14700793d',
  // dpf-catalysts24 | https://www.dpf-catalysts24.com/particle-filter-opel-mokka-a-1-7-cdti-j13-sku-dpf-g9096.html
  '4d0911a6dbf64cec0e12861e',
  // ebay uk | https://www.ebay.co.uk/itm/185194276592?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'd9a7ab17fdcf73344d9c6c03',
  // ebay uk | https://www.ebay.co.uk/itm/203861524086?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'c3f8552698e9052d7d2fad1a',
  // ebay uk | https://www.ebay.co.uk/itm/315390588296?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '3bd663d473d78731807b89c7',
  // ebay uk | https://www.ebay.co.uk/itm/318089853717?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '605ce90da49143f3ecdbdd1f',
  // ebay uk | https://www.ebay.co.uk/itm/376629131002?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'ad1fb5dd161f56576db13c50',
  // evotec gm parts | https://evotectuning.co.uk/products/genuine-gm-dexos-2-5-30-fully-synthetic-oil-5litre
  '89487b35a91d56cfc870bf66',
  // general opel | https://www.generalopel.com/urun/opel-insignia-a-elektrikli-el-fren-teli-komple-gm-orjinal
  'ca84ac75c36d96262b9336a7',
  // gtautomotive parts | https://gtautomotiveparts.co.uk/product/gtck207/
  '0ae4e105b26a3b90d5ff672a',
  // haldex parts | https://haldexparts.co.uk/products/borgwarner-20986573-saab-opel-coupling-oil-filter-kit
  '44710c436b0903681d25b785',
  // haldex parts | https://haldexparts.co.uk/products/opel-saab-0404029-rear-differential-oil-pump-gm-lsd
  '180edfc90a5fafc01c8d881f',
  // halfords | https://www.halfords.com/motoring/engine-oils-and-fluids/adblue/halfords-10l-adblue-293283.html?includeFitting=false
  '56bcfb174393bc3b1fa97e3b',
  // hawk parts | https://www.hawkparts.co.uk/product/subframes/front/front-subframe-crossmember-for-opel-corsa-d-s07-06-15-13427070/
  'dac71c2b69168475d1af4522',
  // ic24 uk | https://www.ic24.uk/products/f6140f-air-conditioning-condenser-dcn15005
  '020034c9a276dd7728e6e790',
  // iparts | https://www.iparts.pl/czesc/sprzeglo-komplet-sachs-2290601239%2C0-32-2290601239-4626799.html
  '1c18612ebfc129c617f00d9e',
  // j&d van den bosch | https://www.jendvandenbosch.nl/egr-koeler-1-6-cdti-b16dth-diesel-origineel-55509027-opel-astra-insignia-mokka-zafira/a16518
  '207c48fe53391f939529ee39',
  // j&d van den bosch | https://www.jendvandenbosch.nl/egr-koeler-1.6-cdti-b16dth-diesel-origineel-55509027-opel-astra-insignia-mokka-zafira/a16518
  '58ec3d0ce70d1b9cceae3784',
  // klifex | https://klifex.net/products/full-swirl-flap-repair-kit-opel-z19dth-z19dtj-55210201
  '7783342b886f51f2bff484a3',
  // leader specialist components | https://www.leadercomponents.com/product/lsc-13248240-heater-blower-fan-resistor-new/
  'c1b9138642ad2661a9899eaf',
  // leader specialist components | https://www.leadercomponents.com/product/lsc-55590953-55572962-genuine-egr-valve-cooler-and-valve-vacuum-tank-repair-kit-new/
  '8085815fcb8ef5d7abafa373',
  // leader specialist components | https://www.leadercomponents.com/product/lsc-9829870080-genuine-egr-valve-12v-5-pin-connector-new/
  '7ca57ff2190ae9a8ea8d5487',
  // midland autocare | https://shop.midlandautocare.co.uk/collections/timing-chain-kits/products/vauxhall-corsa-d-1-2-1-4-timing-chain-kit-a12xer-a14xel-a14xer-engine
  'e609838992c87e0d4e6b2567',
  // midland autocare | https://shop.midlandautocare.co.uk/products/opel-vauxhall-insignia-2-0-cdti-timing-cam-belt-kit-and-water-pump
  '7ef61b5d251ec05c52e76b8c',
  // midland autocare | https://shop.midlandautocare.co.uk/products/r9m-engine-timing-chain-kit
  'e89d6a9eec69798a38440dc5',
  // motostacja | https://motostacja.com/p/TOTAL-INEO-FIRST-0W20-5L/
  '609aed0ef2129eeee67ffc1d',
  // my motor world | https://www.mymotorworld.com/bga-tc1030fk-timing-chain-kit
  'e7911ea394bc4eebbd3d6aac',
  // neo brothers | https://www.neobrothers.co.uk/car-parts/fuel-system/fuel-additive/nox-sensor/oe-nox-sensor-rear-position-2-vauxhall-zafira-c-2-0-b20dth-b20dtj-55598169
  '33663cc43cb973be0948117c',
  // onlinecarparts | https://www.onlinecarparts.co.uk/ina-21498935.html
  '145657b6daaf7a7284f8f29b',
  // onlinecarparts uk | https://www.onlinecarparts.co.uk/car-brands/spare-parts-vauxhall/zafira-mk-ii-b-m75/19308/10553/water-pump-timing-belt-kit.html
  '642f5f6db958c308dbc83442',
  // onlinecarparts uk | https://www.onlinecarparts.co.uk/ina-21498935.html
  '5e1d1ce2fe5351bd72563827',
  // opel-sklep | https://www.opel-sklep.com/pl/p/Pompa-wody-oryginalna-1.6-1.8-benzyna-Z16XEP-Z18XER-1334142-25195119-OPEL-GM/942
  'a2e7dc16d555843908f98ce9',
  // spareto | https://spareto.com/products/metzger-cable-repair-set-interior-heating-fan-eng-preheat-sys-dot/2322008
  '9a4e3c73fd99834f61b18fbb',
  // sussex autos | https://www.sussexautos.com/products/aisin-oem-automatic-transmission-fluid-atf-aw2-1-litre
  '9b3997c732a9612c1858060e',
  // vauxcentre | https://vauxcentre.co.uk/collections/engine-parts-timing-belt-kit/products/genuine-vauxhall-corsa-d-early-z12xep-z14xep-timing-chain-kit-93191271-new
  '5d33f3d97c509ca3221a3140',
  // vauxcentre | https://vauxcentre.co.uk/products/oe-vauxhall-1-7-diesel-egr-valve-97376663-95523829
  '13d428a67c9253b8fec1f118',
  // vauxcentre | https://vauxcentre.co.uk/products/oem-vauxhall-corsa-d-handbrake-cable-assy-r-l-1305-1475-mm-long-new-13355087
  'f14e68ee9f0cb0a965d0d72e',
  // vauxcentre | https://vauxcentre.co.uk/products/original-vauxhall-zafira-c-1-6-diesel-position-1-nox-sensor-55485493-new
  '998c66d7f17dda725f490f50',
  // vauxcentre | https://vauxcentre.co.uk/products/original-vauxhall-zafira-c-1-6-diesel-position-2-nox-sensor-55485442-new
  'feb3f49d81f3270fdfb8c796',
  // vauxcentre | https://vauxcentre.co.uk/products/vauxhall-zafira-c-2-0-diesel-position-1-nox-sensor-55598161-new-oe-part
  'f4eb27b1a627c7564bbb9bd1',
  // vauxhall parts direct | https://vauxhallpartsdirect.co.uk/product/vauxhall-insignia-2009-2017-electric-hand-brake-module/
  '22c8a677ede0864bc09f4434',
  // walmart business | https://business.walmart.com/ip/Electric-Parking-Brake-Switch-for-Vauxhall-for-Astra-J-for-ZAFIRA-C-20843230/7709074793
  'c0b4485d26ce53eec36c3b92',
  // winparts | https://www.winparts.co.uk/engine-parts-accessories/timing-and-belts/timing-chain/c1175/timing-chain-kit-ina-engine-kit/p1435164.html
  '553f0a22ba7f574320989ba1',
] as const;

export const retailerHostFingerprints = [
  // a1allcars.co.uk
  '4867b879240c7f829f9c0aaa',
  // acornautoparts.co.uk
  '85256b00229802faed3fecf3',
  // auto724.co.uk
  '93d52f96283d716be83e32c0',
  // autodoc.co.uk
  '4cd20245762105f62f30d8d7',
  // autodoc.parts
  'f282187b5c9596afa3326ac8',
  // business.walmart.com
  '54e0b7d99e709c8b24851cb9',
  // carparts247.co.uk
  'd93aeb63dd512fb3ad02a91e',
  // cats2u.co.uk
  '9adb9eebb3206123f014f2c7',
  // ctek.com
  '1ad46f76014642ad65be89e7',
  // dpf-catalysts24.com
  '3309c54515dc2aaafd01fd7e',
  // ebay.co.uk
  'b8ce2a1a552a116904d8b01a',
  // evotectuning.co.uk
  '84711eb324781a61be295742',
  // generalopel.com
  '6f6dfb2f14c09ce8571a5057',
  // gtautomotiveparts.co.uk
  'b6e3354e37513269a49defdb',
  // haldexparts.co.uk
  '7153e5c00b71a21abe60717c',
  // halfords.com
  'c36484e503828def606e6e1a',
  // hawkparts.co.uk
  '3ef5211b93a991291801d181',
  // ic24.uk
  '2ea3b5dc79707f17376a0287',
  // iparts.pl
  '39718df09e8923530ebfee42',
  // jendvandenbosch.nl
  '0845c3e1745d6cf3c2130dda',
  // klifex.net
  'dbf6c3db29814f03d2e37eed',
  // leadercomponents.com
  '5d323069996d8638d9eaa7ac',
  // motostacja.com
  '3f81a3de38c015bb365829cd',
  // mymotorworld.com
  'c589df42e67de1e9ea5c4a5a',
  // neobrothers.co.uk
  'bc623e01f9836945fcf319cd',
  // onlinecarparts.co.uk
  '9fbb8e4f410d28a8f8429149',
  // opel-sklep.com
  '3522f30782ddae7c01abe4b1',
  // shop.midlandautocare.co.uk
  '687a29158f19db51aa3fc2a7',
  // spareto.com
  '009c0f41db766dccb62537a0',
  // sussexautos.com
  '5fd74cae405c78ae6d796399',
  // vauxcentre.co.uk
  '161d825ed46ccd76e74f82e6',
  // vauxhallpartsdirect.co.uk
  '07ccc000dc2faa11c066f50a',
  // winparts.co.uk
  'a93bc9ddb8951d55000a7066',
] as const;
