// GENERATED by scripts/build-repair-first-verified-batch.mjs for Porsche.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://eurosporttuning.com/porsche-oil-separator-genuine-porsche-0pc115099b/
  '092b053d1f5c71081f928c8e',
  // https://flat6motorsports.com/collections/987-exterior/products/rennline-radiator-protection-grill-screens-987-cayman-boxster
  '19ca09497ff811f6001851c5',
  // https://lnengineering.com/ims-solution-for-dual-row-ims-my97-01/
  'fc9e971a07afec9fdd9e2f88',
  // https://lnengineering.com/ims-solution-for-single-row-ims-my00-05/
  '03e6ad522c0fdba878749eaa',
  // https://lnengineering.com/oem-porsche-911-chain-tensioner-update-kit-93010591199/
  '19305a5716ba249ab4c963f5',
  // https://lnengineering.com/rear-main-seal-rms-for-my97-08-m96-m97/
  '098eb2246fc0c6f58375ae44',
  // https://patrickmotorsports.com/products/tra91530230114
  '75cc76457ab2446a268d58b5',
  // https://radhausperformance.com/products/pre-order-for-radhaus-95b-1-coolant-vent-line-bypass-kit-2015-2018-macan-s-gts-turbo
  'e780197a1c441616f35ea79c',
  // https://shop.porsche.com/us/en-US/p/-95804490171-B/95804490171
  'e4bed0b5078ceafb9c8787b2',
  // https://sierramadrecollection.com/products/blower-motor-assembly-for-a-c-and-heater-911-boxster-cayman-spyder-718-boxster-718-cayman-718-spyder-2012-2023-3
  '6a9ab6c3bc219886d1fa38be',
  // https://sierramadrecollection.com/products/porsche-battery-box-right-911-912-65-73-901-501-504-00-grv
  '9189813cd53a23615a7f5897',
  // https://sierramadrecollection.com/products/porsche-engine-oil-separator-diaphragm-718-boxster-718-cayman-2017-2024-9a2-107-904-00
  '92cf7b121976ac779eeb6683',
  // https://sierramadrecollection.com/products/porsche-ignition-switch-05-12-997-618-159-07
  'f18c5cd2f9b54b8516c7bba9',
  // https://sierramadrecollection.com/products/porsche-oil-separator-boxster-97-02-996-107-023-04
  '12f9d13059d8af5ae02a9612',
  // https://sr1performance.com/products/porsche-981-2013-2016-gts-boxster-and-cayman-3-piece-radiator-grilles
  'b7340bb516a7be8e377de970',
  // https://teile.com/en/porsche-parts-shop/model-911-992/41/Transmission-clutch/302-Replacement-transmission/10/302-05-Gear-housing-snap-rings-washers/Vent-line/101603
  '99b2f41b9e5ea9524075a36c',
  // https://teile.com/en/porsche-parts-shop/model-cayman-981c/33/Engine-cooling/105-Water-cooling/1/105-20-Water-supply-tank/Coolant-filler-cap-lid/57502
  '7a660726a8c81c4dba91ec84',
  // https://www.demon-tweeks.com/us/dinitrol-ml-penetrating-rust-proofing-cavity-wax-1242392/
  '53a783158e0e54b2f05730a8',
  // https://www.ecstuning.com/b-genuine-porsche-parts/vacuum-power-change-over-valve-priced-each/7pp906270/
  'eaf205530ffa93103bb5c5e5',
  // https://www.ecstuning.com/b-genuine-porsche-parts/water-pump/9a210605003/
  '5e6476fa1b525613e9128378',
  // https://www.ecstuning.com/b-vaico-parts/air-oil-separator/99610702601~vai/
  'c58bf36f26fdee180c42fc4a',
  // https://www.europaparts.com/coolant-expansion-tank-98710604703.html
  'd30996bd876291a2b351a285',
  // https://www.europaparts.com/coolant-pipe-kit-cayenne-955-v8.html
  'c83b266e05fe1db59a7468fe',
  // https://www.fcpeuro.com/products/porsche-coolant-expansion-tank-genuine-porsche-98110604706
  'ab4e1e8ad21a43ef929f6c9c',
  // https://www.fcpeuro.com/products/porsche-engine-coolant-reservoir-genuine-porsche-982121407c
  'e8521eb2bbbb869d1a5509f1',
  // https://www.fcpeuro.com/products/porsche-engine-crankcase-vent-valve-911-14543005001
  '4feaf3227e2522346901490c',
  // https://www.fcpeuro.com/products/porsche-engine-oil-drain-plug-genuine-porsche-9gt115647b
  '37ceb54a613d2e22d6ccecaf',
  // https://www.fcpeuro.com/products/porsche-engine-oil-pan-seal-genuine-porsche-0pb115111b
  'c2ecff2ac16fb5a2c7b874d6',
  // https://www.fcpeuro.com/products/porsche-engine-oil-separator-911-14543004001
  'a6843846f08975379aad3658',
  // https://www.fcpeuro.com/products/porsche-engine-oil-separator-911-14543007001
  'c11ba85e76856a23d292a8fb',
  // https://www.fcpeuro.com/products/porsche-radiator-cap-911-boxster-cayman-por-99610644704
  '5335804e35d4398cc4aa9a63',
  // https://www.oemvwshop.com/9gt301280-vent-hose-p2803747/?cid=3063
  'c1e24dda6860cdba7c76a5cc',
  // https://www.paragon-products.com/product-p/pp911.110.abv.htm
  '683b59db7243d941ce21dc2c',
  // https://www.partsgeek.com/2wb34cd-porsche-911-oil-thermostat-o-ring.html
  '13066583089bffc864110cd4',
  // https://www.partsgeek.com/rwmcm78-porsche-718-cayman-oil-separator.html
  'c9c4abb394aa9668afee69cd',
  // https://www.pcarpartsguys.com/product/635540/swepco-gear-lube-201-8090-weight-1-gallon
  '4db0332ba483374e46bd25ff',
  // https://www.radiatorgrillstore.com/product-page/2013-2016-porsche-981-boxster-and-cayman-front-and-side-intake-grills
  'b69b39f06a25e19d644be180',
  // https://www.restoration-design.com/store/product/PP200
  '5a3b96d56be1dbefbe960f33',
  // https://www.restoration-design.com/store/product/PP218
  '84b9b914fb454c5558a695a0',
  // https://www.restoration-design.com/store/product/PP219SL
  '00f5a3b42b72fbe8b258e1e2',
  // https://www.restoration-design.com/store/product/PP219SR
  'ec2057a02dc19003999ecd77',
  // https://www.rmeuropean.com/Products/0PB905093F-MFG482-V6820.aspx
  '04dbafc87768d0d33ffe5ef8',
  // https://www.rmeuropean.com/Products/94610602660-MFG100.aspx
  '43fcfce16b387c1818b88839',
  // https://www.rmeuropean.com/Products/9A210747300-MFG100.aspx
  '826a258a6338a60aa0e6d601',
] as const;

export const vendorUrlFingerprints = [
  // demon tweeks | https://www.demon-tweeks.com/us/dinitrol-ml-penetrating-rust-proofing-cavity-wax-1242392/
  '103b12d9753fce20e9c18caa',
  // ebay / loeber motors | https://www.ebay.com/itm/376937450904?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  'e37ed03ab37ba62e4ba334e4',
  // ecs tuning | https://www.ecstuning.com/b-genuine-porsche-parts/vacuum-power-change-over-valve-priced-each/7pp906270/
  '28e7c9f8bd48b5e1e26b367b',
  // ecs tuning | https://www.ecstuning.com/b-genuine-porsche-parts/water-pump/9a210605003/
  '3adeec15e271375484f337b0',
  // ecs tuning | https://www.ecstuning.com/b-vaico-parts/air-oil-separator/99610702601~vai/
  'f2ff74fb3312474b78edb1f1',
  // europa parts | https://www.europaparts.com/coolant-expansion-tank-98710604703.html
  '7ad914f17bd9cc6c19edca2b',
  // europa parts | https://www.europaparts.com/coolant-pipe-kit-cayenne-955-v8.html
  '222c7898be3947c3c33f6203',
  // eurosport tuning | https://eurosporttuning.com/porsche-oil-separator-genuine-porsche-0pc115099b/
  '80293a2f55737c683074b3ba',
  // fcp euro | https://www.fcpeuro.com/products/porsche-coolant-expansion-tank-genuine-porsche-98110604706
  '596f02aac5d53f77aa73a405',
  // fcp euro | https://www.fcpeuro.com/products/porsche-engine-coolant-reservoir-genuine-porsche-982121407c
  '302c8baa2ce2d6d7671210cc',
  // fcp euro | https://www.fcpeuro.com/products/porsche-engine-crankcase-vent-valve-911-14543005001
  '1409b46704fb5e0639243edf',
  // fcp euro | https://www.fcpeuro.com/products/porsche-engine-oil-drain-plug-genuine-porsche-9gt115647b
  'bb7afd3ac42000a6d9786e56',
  // fcp euro | https://www.fcpeuro.com/products/porsche-engine-oil-pan-seal-genuine-porsche-0pb115111b
  'd7b559ae2254fffbcb14afa5',
  // fcp euro | https://www.fcpeuro.com/products/porsche-engine-oil-separator-911-14543004001
  '40f6de8bfbdc84c02b55c8e0',
  // fcp euro | https://www.fcpeuro.com/products/porsche-engine-oil-separator-911-14543007001
  '562687c2349e5fcc690af831',
  // fcp euro | https://www.fcpeuro.com/products/porsche-radiator-cap-911-boxster-cayman-por-99610644704
  '46cabac750501dc301684b27',
  // flat 6 motorsports | https://flat6motorsports.com/collections/987-exterior/products/rennline-radiator-protection-grill-screens-987-cayman-boxster
  '24e8b9fee9eefe8ee7f20d0f',
  // ln engineering | https://lnengineering.com/ims-solution-for-dual-row-ims-my97-01/
  '63b3c7d0a14f4a0cd34f81b9',
  // ln engineering | https://lnengineering.com/ims-solution-for-single-row-ims-my00-05/
  'e8e0d71e735e9c262c65aaaf',
  // ln engineering | https://lnengineering.com/oem-porsche-911-chain-tensioner-update-kit-93010591199/
  'e9f416bf50c6074cc1aada7e',
  // ln engineering | https://lnengineering.com/rear-main-seal-rms-for-my97-08-m96-m97/
  '8f41ecefb4722c18e0584a74',
  // oemvwshop | https://www.oemvwshop.com/9gt301280-vent-hose-p2803747/?cid=3063
  '0bdb057bcb481a0bcdf43907',
  // p car parts guys | https://www.pcarpartsguys.com/product/635540/swepco-gear-lube-201-8090-weight-1-gallon
  'fcebc69bfb7958dc73f6b788',
  // paragon products | https://www.paragon-products.com/product-p/pp911.110.abv.htm
  '936168417a52272a2c85bf2a',
  // partsgeek | https://www.partsgeek.com/2wb34cd-porsche-911-oil-thermostat-o-ring.html
  '2676823af50b909e8ca2a21d',
  // partsgeek | https://www.partsgeek.com/rwmcm78-porsche-718-cayman-oil-separator.html
  'dacb3eb23153c154c0591b5d',
  // patrick motorsports | https://patrickmotorsports.com/products/tra91530230114
  'f1854467882d3b386760ecf7',
  // porsche shop | https://shop.porsche.com/us/en-US/p/-95804490171-B/95804490171
  '91e2925940613925463d7d12',
  // porsche shop us | https://shop.porsche.com/us/en-US/p/-95804490171-B/95804490171
  '74e59c50129ae98ce1de5f4a',
  // radhaus performance | https://radhausperformance.com/products/pre-order-for-radhaus-95b-1-coolant-vent-line-bypass-kit-2015-2018-macan-s-gts-turbo
  '477a6c6fd4fdc819184d86cb',
  // radiator grille store | https://www.radiatorgrillstore.com/product-page/2013-2016-porsche-981-boxster-and-cayman-front-and-side-intake-grills
  '1fcd48419e219cba5b8dccb0',
  // restoration design | https://www.restoration-design.com/store/product/PP200
  '31ef0836032eec7f3d7d38c6',
  // restoration design | https://www.restoration-design.com/store/product/PP218
  'd62fc19209ff7a4b2c9a750e',
  // restoration design | https://www.restoration-design.com/store/product/PP219SL
  'edae62f2ad2c2936f227ce1e',
  // restoration design | https://www.restoration-design.com/store/product/PP219SR
  'a04670bc63b2f7f88108af7f',
  // rm european | https://www.rmeuropean.com/Products/0PB905093F-MFG482-V6820.aspx
  '3b599a0e72926d8228a91f0a',
  // rm european | https://www.rmeuropean.com/Products/94610602660-MFG100.aspx
  '9d15fdd013c7dd856589f2df',
  // rm european | https://www.rmeuropean.com/Products/9A210747300-MFG100.aspx
  '64d7fa8316a538bec9950bdd',
  // sierra madre collection | https://sierramadrecollection.com/products/blower-motor-assembly-for-a-c-and-heater-911-boxster-cayman-spyder-718-boxster-718-cayman-718-spyder-2012-2023-3
  '52e37f1f34744c5b501fd02a',
  // sierra madre collection | https://sierramadrecollection.com/products/porsche-battery-box-right-911-912-65-73-901-501-504-00-grv
  '9e84b2ed4510a7002f305de0',
  // sierra madre collection | https://sierramadrecollection.com/products/porsche-engine-oil-separator-diaphragm-718-boxster-718-cayman-2017-2024-9a2-107-904-00
  '22f108888dd50f11b15de3ce',
  // sierra madre collection | https://sierramadrecollection.com/products/porsche-ignition-switch-05-12-997-618-159-07
  'f5733d3ec69626357c8b330d',
  // sierra madre collection | https://sierramadrecollection.com/products/porsche-oil-separator-boxster-97-02-996-107-023-04
  'ef11e91ac977dcb57a19640c',
  // sr1 performance | https://sr1performance.com/products/porsche-981-2013-2016-gts-boxster-and-cayman-3-piece-radiator-grilles
  'e8ba299d77c350cef2f01f57',
  // teile.com | https://teile.com/en/porsche-parts-shop/model-911-992/41/Transmission-clutch/302-Replacement-transmission/10/302-05-Gear-housing-snap-rings-washers/Vent-line/101603
  '5099a703461e32ce3519731b',
  // teile.com | https://teile.com/en/porsche-parts-shop/model-cayman-981c/33/Engine-cooling/105-Water-cooling/1/105-20-Water-supply-tank/Coolant-filler-cap-lid/57502
  '9ce9e21f6f084db4bd9a3aea',
] as const;

export const retailerHostFingerprints = [
  // demon-tweeks.com
  '7bbf67554d6809f2c4aaffa2',
  // ecstuning.com
  '13490e338f93e16546fd1f72',
  // europaparts.com
  '1f1c51664a81193b59c80f47',
  // eurosporttuning.com
  '0a32222fe85d3ef69c1027ae',
  // fcpeuro.com
  '320bece6520cba1e0c00294f',
  // flat6motorsports.com
  '96541dd7a6f79cce9bd9a18b',
  // lnengineering.com
  'a8b74e23a50c00ee22d69788',
  // oemvwshop.com
  '78cf406dba88fe01d2621534',
  // paragon-products.com
  'd816efabeced9494a3014cda',
  // partsgeek.com
  'b6c9d443e05ef437cef78a38',
  // patrickmotorsports.com
  '9d2d8f55863e1d2ebf34171d',
  // pcarpartsguys.com
  '8ca726434e7a194eaf87849e',
  // radhausperformance.com
  '0115fe7a279b4f34e11ccfbb',
  // radiatorgrillstore.com
  'a3120bad996b95320f68d8e3',
  // restoration-design.com
  'fc41312001a68e25f30e0d08',
  // rmeuropean.com
  'da8cab53f0633b9dd89f93f3',
  // shop.porsche.com
  'a0e97bee2bf7c06a684fdb6b',
  // sierramadrecollection.com
  '95b43017c0f96b3be466b510',
  // sr1performance.com
  '7cf85342cbdfa0501c74eb21',
  // teile.com
  '213d4cc6b8155106615bd434',
] as const;
