// GENERATED by scripts/build-repair-first-verified-batch.mjs for Suzuki.
// Comments keep exact approvals human-reviewable; runtime stores compact fingerprints.

export const productUrlFingerprints = [
  // https://business.walmart.com/ip/Dorman-90802-H7-Ceramic-Socket-Pack-of-2/905979391
  '27745b8b838b5a7209204e64',
  // https://shop.advanceautoparts.com/p/pennzoil-platinum-5w-30-full-synthetic-motor-oil-5-quart-550046126/11499296-P
  'd0d6d2a121d1dc7d6c05ee27',
  // https://sparkautomotive.com/products/evergreen-sa-7308076616-timing-chain-kit-w-o-gear-oil-water-pump-fit-99-07-chevrolet-suzuki-h25a-h27a
  '209d9bd660d32265b9ce9b28',
  // https://www.autozone.com/p/sylvania-basic-cornering-light-bulb-h7/197158
  '567486b9698a7691055a96d5',
  // https://www.carparts.com/details/Suzuki/Grand_Vitara/Replacement/Timing_Chain_Kit/2009/KIT-101917-04.html
  '0c67859babef34837dbb37cd',
  // https://www.mlperformanceusa.com/products/exedy-sk04h406-stage1-clutch-set-swift-sport-zc33s-1-4t-17-on-6spd
  '21bcca26ea883f5352053e93',
  // https://www.trodo.com/condenser-air-conditioning-hart-611-254
  '65ff703dad5bdfe2eb7ad8a0',
] as const;

export const vendorUrlFingerprints = [
  // advance auto parts | https://shop.advanceautoparts.com/p/pennzoil-platinum-5w-30-full-synthetic-motor-oil-5-quart-550046126/11499296-P
  '41074fa4ac818165b5e72ccf',
  // autozone | https://www.autozone.com/p/sylvania-basic-cornering-light-bulb-h7/197158
  'ca15c4e342295a8d438cc363',
  // carparts.com | https://www.carparts.com/details/Suzuki/Grand_Vitara/Replacement/Timing_Chain_Kit/2009/KIT-101917-04.html
  '63b0a33b23ebff9c2ff88218',
  // ebay / rvt-powers | https://www.ebay.com/itm/315660227726?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '8fdebc7e5634d9af0343a7f4',
  // ebay / sims suzuki genuine parts | https://www.ebay.com/itm/182904109044?mkevt=1&mkcid=1&mkrid=711-53200-19255-0&campid=5339164204&customid=known-issue-parts&toolid=10001
  '3481a3ad46ef70bb6d423677',
  // ml performance us | https://www.mlperformanceusa.com/products/exedy-sk04h406-stage1-clutch-set-swift-sport-zc33s-1-4t-17-on-6spd
  '2312d015f83bad6a553b3d9d',
  // spark automotive | https://sparkautomotive.com/products/evergreen-sa-7308076616-timing-chain-kit-w-o-gear-oil-water-pump-fit-99-07-chevrolet-suzuki-h25a-h27a
  '687659b9ad2d8635603de460',
  // trodo | https://www.trodo.com/condenser-air-conditioning-hart-611-254
  '7e75ea8cfafbb8070b03d581',
  // walmart business | https://business.walmart.com/ip/Dorman-90802-H7-Ceramic-Socket-Pack-of-2/905979391
  '835891dd09a4f96cabe00ce2',
] as const;

export const retailerHostFingerprints = [
  // autozone.com
  '12fa1f440ebfbfd1c0ab1b19',
  // business.walmart.com
  '54e0b7d99e709c8b24851cb9',
  // carparts.com
  'cb39b9c3d06e48b637584a8e',
  // mlperformanceusa.com
  'c89be5d082d9a18be650ebd8',
  // shop.advanceautoparts.com
  '3d7f5ea36b6847e33e997fca',
  // sparkautomotive.com
  '9f1a1e95fa2c5d137eb3c94d',
  // trodo.com
  '7cfff290db0ca3ed5e1f70fd',
] as const;
