import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Au7o design system — tokens (CSS variables) + utility classes used by
// the redesigned hub + mobile shell. Imported AFTER globals.css so var()
// definitions cascade and utility classes override Tailwind defaults
// where they overlap. The body element is intentionally NOT touched —
// globals.css owns it so existing pages don't repaint.
import "@/styles/au7o-tokens.css";
import "@/styles/au7o-utilities.css";
// Twin stage + tech tree: the --ki-* palette and hotspot/tree animations the
// ported design needs. Additive only — defines what the app didn't already have.
import "@/styles/twin-stage.css";
import { AppProvider } from "@/contexts/AppContext";
import { OfflineIndicator } from "@/components/offline/OfflineIndicator";
import { GoogleAnalytics } from "@/components/analytics/GoogleAnalytics";
// Vercel Web Analytics — cookieless, counts EVERY visitor (no consent gate),
// so it captures the traffic GA4 misses now that analytics_storage defaults to
// denied. Numbers live in the Vercel dashboard (Project → Analytics).
import { Analytics } from "@vercel/analytics/next";
import { MicrosoftClarity } from "@/components/analytics/MicrosoftClarity";
import { SessionProvider } from "@/components/auth/SessionProvider";
import { AdSenseScript } from "@/components/ads/AdSenseScript";
import { TermlyConsentBootstrap } from "@/components/consent/TermlyConsentBootstrap";
import TermlyRouteReinit from "@/components/consent/TermlyRouteReinit";
import { OrganizationJsonLd, WebSiteJsonLd, SoftwareApplicationJsonLd } from "@/components/seo/JsonLd";
import { FloatingAuthButton } from "@/components/auth/FloatingAuthButton";
import { InstallPrompt } from "@/components/pwa/InstallPrompt";
import { ServiceWorkerRefresh } from "@/components/pwa/ServiceWorkerRefresh";
import { PhotoDebugOverlay } from "@/components/debug/PhotoDebugOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL('https://au7o.io'),
  // Google Search Console ownership — a permanent <meta google-site-verification>
  // that's ALWAYS in <head> (unlike GA/DNS verification, which can drift or be
  // consent-gated). Set GOOGLE_SITE_VERIFICATION in Vercel to the token from GSC
  // → Settings → Ownership verification → "HTML tag" (the content="..." value).
  verification: {
    google: process.env.GOOGLE_SITE_VERIFICATION,
  },
  title: {
    default: 'Au7o - AI-Powered Automotive Repair Guides',
    template: '%s | Au7o',
  },
  icons: {
    icon: '/favicon.ico',
    apple: '/icons/icon-192.png',
  },
  description: 'Expert DIY car repair guides powered by AI. Step-by-step instructions tailored to your exact vehicle. Works offline. Free to start.',
  keywords: ['car repair', 'DIY mechanic', 'auto repair guide', 'vehicle maintenance', 'automotive', 'repair tutorial', 'oil change', 'brake pads'],
  authors: [{ name: 'Au7o' }],
  creator: 'Au7o',
  publisher: 'Au7o',
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Au7o',
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://au7o.io',
    siteName: 'Au7o',
    title: 'Au7o - AI-Powered Automotive Repair Guides',
    description: 'Expert DIY car repair guides powered by AI. Step-by-step instructions tailored to your exact vehicle. Works offline.',
    // OG image is auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Au7o - AI-Powered Automotive Repair Guides',
    description: 'Expert DIY car repair guides powered by AI. Step-by-step instructions tailored to your exact vehicle.',
    // Twitter image is auto-generated by twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export const viewport: Viewport = {
  themeColor: "#3B82F6",
  // Without viewport-fit=cover, iOS reports env(safe-area-inset-*) as 0 and
  // every safe-area padding in the app (hub composer, bottom bars) is dead
  // code — in installed-PWA mode the controls sat in the home-indicator
  // gesture zone (2026-06-12 review finding).
  viewportFit: "cover",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Resource hints — preconnect to the ONE render-blocking third party
            (Termly's consent resource-blocker, which must load beforeInteractive
            for GCM compliance and can't be deferred) so its DNS+TCP+TLS is warm
            before it executes; dns-prefetch the now-deferred analytics/ads
            origins so they resolve faster when they load post-interactive. */}
        <link rel="preconnect" href="https://app.termly.io" />
        <link rel="dns-prefetch" href="https://app.termly.io" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://www.clarity.ms" />
        <link rel="dns-prefetch" href="https://pagead2.googlesyndication.com" />
        {/* Termly resource-blocker — MUST be the first script in <head>
            so Consent Mode v2 default signals arrive before any Google
            tag fires. Loads beforeInteractive (via Next's <Script>) so
            it executes before AdSense + GoogleAnalytics below. Previously
            this lived as a body-mounted client component with useEffect
            injection which made it land AFTER GA — Termly's GCM
            Validation Scan flagged that as "default consent signals
            sent too late." This placement passes the scan. */}
        <TermlyConsentBootstrap />
        {/* Advance Auto Parts / Impact affiliate ownership verification.
            Keep this in the document head so Impact can verify au7o.io. */}
        <script
          type="text/javascript"
          /* Same Termly problem as <AdSenseScript />: this is an inline
             wrapper that injects utt.impactcdn.com at runtime, so the URL
             never appears as a src attribute and no Domain Rule can match
             it. Termly stamped it data-termly-unknown-parent="1" and
             blocked it — the 2026-08-27 cookie scan found no Impact
             cookies at all. Declaring the category is what makes it
             governable rather than silently dead. */
          data-categories="advertising"
          dangerouslySetInnerHTML={{
            __html:
              "(function(i,m,p,a,c,t){c.ire_o=p;c[p]=c[p]||function(){(c[p].a=c[p].a||[]).push(arguments)};t=a.createElement(m);var z=a.getElementsByTagName(m)[0];t.async=1;t.src=i;z.parentNode.insertBefore(t,z)})('https://utt.impactcdn.com/P-A7655285-4eb7-438d-a105-b982cf1c4d4e1.js','script','impactStat',document,window);impactStat('transformLinks');impactStat('trackImpression');",
          }}
        />
        <link rel="apple-touch-icon" href="/icons/icon-192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        {/* AdSense site verification + Auto Ads loader. Per Google's
            instructions the script must live in <head> verbatim with the
            crossorigin="anonymous" attribute. */}
        <meta name="google-adsense-account" content="ca-pub-6245698513720418" />
        <AdSenseScript />
        <GoogleAnalytics />
        <MicrosoftClarity />
        <OrganizationJsonLd />
        <WebSiteJsonLd />
        <SoftwareApplicationJsonLd />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* SPA navigation: re-init Termly's banner on every route change
            so its scope tracks pathname + query updates. The initial
            script load is done via <TermlyConsentBootstrap /> in <head>. */}
        <TermlyRouteReinit />
        {/* Google Translate widget removed 2026-06-12 — native locale pages
            (/pt-br, /es, /de, /fr, /ko) replace machine translation, and the
            widget's iframe weighed on LCP for every visitor. */}
        <SessionProvider>
          {/* Floating sign-in pill — top-right. Inside SessionProvider so
              useSession() works. */}
          <FloatingAuthButton />
          <AppProvider>
            <OfflineIndicator position="top" showFeatures />
            {children}
            <InstallPrompt />
            <ServiceWorkerRefresh />
            {/* Debug overlay — renders null unless ?debug=1 or
                localStorage.au7o_debug=on. Zero impact on production users. */}
            <PhotoDebugOverlay />
          </AppProvider>
        </SessionProvider>
        <Analytics />
      </body>
    </html>
  );
}
