import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "@/contexts/AppContext";
import { OfflineIndicator } from "@/components/offline/OfflineIndicator";
import { GoogleAnalytics } from "@/components/analytics/GoogleAnalytics";
import { SessionProvider } from "@/components/auth/SessionProvider";
import { AdSenseScript } from "@/components/ads/AdSenseScript";
import TermlyCMP from "@/components/consent/TermlyCMP";
import { OrganizationJsonLd, WebSiteJsonLd, SoftwareApplicationJsonLd } from "@/components/seo/JsonLd";
import { GoogleTranslate } from "@/components/shared/GoogleTranslate";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  metadataBase: new URL('https://au7o.io'),
  title: {
    default: 'Au7o - AI-Powered Automotive Repair Guides',
    template: '%s | Au7o',
  },
  icons: {
    icon: '/favicon.ico',
    apple: '/icons/icon-192.png',
  },
  description: 'Expert DIY car repair guides powered by AI. Step-by-step instructions tailored to your exact vehicle. Works offline. Free to start.',
  keywords: ['car repair', 'DIY mechanic', 'auto repair guide', 'vehicle maintenance', 'automotive', 'repair tutorial', 'oil change', 'brake pads'],
  authors: [{ name: 'Au7o' }],
  creator: 'Au7o',
  publisher: 'Au7o',
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: 'Au7o',
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://au7o.io',
    siteName: 'Au7o',
    title: 'Au7o - AI-Powered Automotive Repair Guides',
    description: 'Expert DIY car repair guides powered by AI. Step-by-step instructions tailored to your exact vehicle. Works offline.',
    // OG image is auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Au7o - AI-Powered Automotive Repair Guides',
    description: 'Expert DIY car repair guides powered by AI. Step-by-step instructions tailored to your exact vehicle.',
    // Twitter image is auto-generated by twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};

export const viewport: Viewport = {
  themeColor: "#3B82F6",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="apple-touch-icon" href="/icons/icon-192.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <GoogleAnalytics />
        <OrganizationJsonLd />
        <WebSiteJsonLd />
        <SoftwareApplicationJsonLd />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TermlyCMP />
        <AdSenseScript />
        <GoogleTranslate />
        <SessionProvider>
          <AppProvider>
            <OfflineIndicator position="top" showFeatures />
            {children}
          </AppProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
