/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs'); const test = require('node:test'); const assert = require('node:assert/strict');
const { ALL_IDS, BLOCKER_IDS, IDS, OUTPUT, RETAIN_IDS, SNAPSHOT, buildPacket } = require('./build-mercedes-sprinter-adjudication');
const { validatePacket } = require('./validate-mercedes-sprinter-adjudication');
const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
function packet() { return buildPacket(snapshot); }
test('packet validates deterministically', () => assert.deepEqual(validatePacket(packet(), snapshot), []));
test('all thirteen frozen identities are covered once', () => assert.deepEqual(packet().rows.map((row) => row.id).sort(), ALL_IDS));
test('one identity retains and twelve remain held', () => { const value = packet(); assert.equal(value.rows.filter((row) => RETAIN_IDS.includes(row.id)).length, 1); assert.deepEqual(value.applicationGate.blockerRecordIds, BLOCKER_IDS); });
test('indexed identity and vehicle metadata remain immutable', () => { for (const row of packet().rows) for (const field of ['make', 'model', 'years', 'trims', 'engines', 'category', 'title', 'severity', 'status', 'lastReportedByOwners', 'relatedIssueIds']) assert.deepEqual(row.proposal[field], row.before[field], `${row.id}:${field}`); });
test('positive report counts become zero and existing zero counts stay zero', () => { const rows = packet().rows; assert.equal(rows.filter((row) => row.before.reportCount > 0).length, 5); assert.equal(rows.filter((row) => row.before.reportCount === 0).length, 8); for (const row of rows) { assert.equal(row.proposal.reportCount, 0); assert.doesNotMatch(`${row.proposal.description} ${row.proposal.solution}`, /0\+ owners|owners have reported/i); } });
test('packet introduces no commerce or recommendation', () => { for (const row of packet().rows) { assert.deepEqual(row.proposal.fixParts, []); assert.deepEqual(row.proposal.communityRecommendations, []); assert.match(row.proposal.solution, /do not buy/i); assert.match(row.commerceDecision, /no universal retail part/i); } });
test('unsafe bypass and universal regeneration instructions are removed', () => { const value = packet(); assert.match(value.rows.find((row) => row.id === IDS.swirl).proposal.solution, /Do not install a resistor bypass/); assert.match(value.rows.find((row) => row.id === IDS.dpf).proposal.solution, /Do not force a regeneration/); });
test('DEF identity remains diagnosis first', () => { const row = packet().rows.find((value) => value.id === IDS.def); assert.equal(row.action, 'retain_indexed_identity_accuracy_cleanup_proposal'); assert.match(row.proposal.description, /multiple DEF\/AdBlue and SCR fault paths/); assert.match(row.proposal.solution, /XENTRY guided tests/); });
test('oil cooler and injector evidence stay bounded', () => { const value = packet(); assert.match(value.rows.find((row) => row.id === IDS.oilCooler).identityConflict, /ends with 2017/); assert.match(value.rows.find((row) => row.id === IDS.injector).identityConflict, /2023-2025/); });
test('no-evidence paths remain explicit', () => { const value = packet(); for (const id of [IDS.swirl, IDS.balancer, IDS.turboActuator, IDS.glowPlug, IDS.resonator]) assert.match(value.rows.find((row) => row.id === id).evidence.primaryEvidence.join(' '), /zero exact|No exact/i); });
test('committed packet matches deterministic build', () => { if (fs.existsSync(OUTPUT)) assert.deepEqual(JSON.parse(fs.readFileSync(OUTPUT, 'utf8')), packet()); });
test('no PDF selected and dataset citation is direct', () => { const value = packet(); assert.deepEqual(value.pdfSources, {}); for (const row of value.rows) assert.equal(row.proposal.citations[0].url, 'https://www.nhtsa.gov/nhtsa-datasets-and-apis'); });
