/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs'); const test = require('node:test'); const assert = require('node:assert/strict');
const { OUTPUT, SNAPSHOT } = require('./build-lincoln-ls-adjudication'); const { hashValue } = require('./lincoln-adjudication-utils'); const { validatePacket } = require('./validate-lincoln-ls-adjudication');
const packet = JSON.parse(fs.readFileSync(OUTPUT, 'utf8')); const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8')); function clone(value) { return JSON.parse(JSON.stringify(value)); } function rehash(row) { row.proposalSha256 = hashValue(row.proposal); }
test('LS packet passes the complete one-page safety contract', () => assert.deepEqual(validatePacket(packet, snapshot), []));
test('validator rejects missing, duplicate, and unknown LS coverage', () => { const a = clone(packet); a.rows = []; assert.ok(validatePacket(a, snapshot).length); const b = clone(packet); b.rows[0].id = 'other'; assert.ok(validatePacket(b, snapshot).length); });
test('validator rejects identity, fitment, severity, relation and archive drift', () => { for (const [field, value] of [['title', 'Changed title'], ['years', [1900]], ['trims', ['UNSUPPORTED']], ['engines', ['UNSUPPORTED']], ['severity', 'critical'], ['relatedIssueIds', ['other']], ['status', 'archived']]) { const p = clone(packet); const row = p.rows[0]; row.proposal[field] = value; rehash(row); assert.ok(validatePacket(p, snapshot).some((error) => error.includes(field) || error.includes('severity') || error.includes('archived'))); } });
test('validator rejects a revived universal crossover diagnosis', () => { const p = clone(packet); const row = p.rows[0]; row.proposal.description = 'Every LS has a rear crossover failure.'; rehash(row); assert.ok(validatePacket(p, snapshot).some((error) => error.includes('crossover'))); });
test('validator rejects loss of the TSB fan scope and overheat safety', () => { const p = clone(packet); const row = p.rows[0]; row.proposal.solution = 'Replace the crossover on every model year.'; rehash(row); const errors = validatePacket(p, snapshot); assert.ok(errors.some((error) => error.includes('TSB') || error.includes('safety'))); });
test('validator rejects an all-years Gold coolant instruction', () => { const p = clone(packet); const row = p.rows[0]; row.proposal.solution = 'Use Motorcraft Premium Gold on every 2000-2006 LS. Do not buy parts; no universal retail part is recommended.'; rehash(row); assert.ok(validatePacket(p, snapshot).some((error) => error.includes('coolant'))); });
test('validator rejects blind parts, costs and search commerce', () => { const p = clone(packet); const row = p.rows[0]; row.proposal.solution += ' Replace all plastic fittings for $300-$600.'; row.proposal.citations.push({ type: 'manual', title: 'Search', url: 'https://example.com/search?q=kit' }); rehash(row); const errors = validatePacket(p, snapshot); assert.ok(errors.some((error) => error.includes('parts or cost'))); assert.ok(errors.some((error) => error.includes('search-style'))); });
test('validator rejects fake owner social proof', () => { const p = clone(packet); const row = p.rows[0]; row.proposal.reportCount = 99; row.proposal.description += ' 99+ owners have reported this.'; rehash(row); assert.ok(validatePacket(p, snapshot).some((error) => error.includes('social proof'))); });
