/* eslint-disable @typescript-eslint/no-require-imports */
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const { IDS } = require('./build-hyundai-elantra-adjudication');
const { validatePacket } = require('./validate-hyundai-elantra-adjudication');

const ROOT = path.resolve(__dirname, '..');
const packet = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', 'known-issue-hyundai-elantra-adjudication-2026-08-06.json'), 'utf8'));
const snapshot = JSON.parse(fs.readFileSync(path.join(ROOT, 'data', '_hyundai-deeplink-snapshot-2026-08-06.json'), 'utf8'));
const byId = new Map(packet.rows.map((row) => [row.id, row]));

test('Elantra packet passes the complete proposal-only safety contract', () => { assert.deepEqual(validatePacket(packet, snapshot, packet.source.snapshotSha256), []); });
test('all nineteen Elantra holds remain byte-for-byte frozen', () => { const holds = packet.rows.filter((row) => row.action === 'keep_published_pending_source'); assert.equal(holds.length, 19); for (const row of holds) { assert.equal(row.beforeSha256, row.proposalSha256, row.id); assert.deepEqual(row.changedFields, [], row.id); } });
test('all ten rewrites remain published, identity-stable and commerce-free', () => { const rewrites = packet.rows.filter((row) => row.action === 'rewrite_same_identity'); assert.equal(rewrites.length, 10); for (const row of rewrites) { assert.equal(row.proposal.status, 'published', row.id); assert.equal(row.proposal.title, row.before.title, row.id); assert.equal(row.proposal.category, row.before.category, row.id); assert.deepEqual(row.proposal.trims, [], row.id); assert.deepEqual(row.proposal.engines, [], row.id); assert.deepEqual(row.proposal.fixParts, [], row.id); assert.deepEqual(row.proposal.communityRecommendations, [], row.id); assert.equal(row.proposal.estimatedCostLow, null, row.id); assert.equal(row.proposal.estimatedCostHigh, null, row.id); } });
test('packet covers every frozen Elantra ID exactly once', () => { const expected = snapshot.records.filter((row) => row.model === 'Elantra').map((row) => row.id).sort(); const actual = packet.rows.map((row) => row.id).sort(); assert.deepEqual(actual, expected); assert.equal(new Set(actual).size, 29); });
test('the two ABS recalls remain separate exact identities without unsupported details', () => { const newer = byId.get(IDS.abs251); const older = byId.get(IDS.abs188); assert.equal(newer.proposal.title, newer.before.title); assert.match(newer.proposal.description, /brake fluid internally/); assert.doesNotMatch(JSON.stringify(newer.proposal), /warning light|malfunction-indicator|lower-amperage/i); assert.equal(older.proposal.title, older.before.title); assert.match(older.proposal.description, /remains energized/); assert.notDeepEqual(newer.proposal.years, older.proposal.years); });
test('EPS identity swap is rejected while the distinct MDPS coupling rewrite remains narrow', () => { const eps = byId.get(IDS.eps); const coupler = byId.get(IDS.mdps); assert.equal(eps.action, 'keep_published_pending_source'); assert.equal(eps.beforeSha256, eps.proposalSha256); assert.match(coupler.proposal.description, /does not affect steering control and is not a safety issue/); assert.doesNotMatch(coupler.proposal.description + coupler.proposal.solution, /loss of assist|C1260|C1604|C1656/i); });
test('Nu bearing page is not replaced by a piston-slap bulletin', () => { const row = byId.get(IDS.nuEngine); assert.equal(row.action, 'keep_published_pending_source'); assert.equal(row.beforeSha256, row.proposalSha256); });
test('pretensioner rewrite is limited to model years 2021-2022', () => { const row = byId.get(IDS.pretensioner); assert.deepEqual(row.proposal.years, [2021, 2022]); assert.doesNotMatch(row.proposal.description, /2023/); });
test('misleading 2001 slugs are frozen instead of receiving later campaigns', () => { for (const id of [IDS.brakeSwitch, IDS.coilSpring]) { const row = byId.get(id); assert.equal(row.action, 'keep_published_pending_source'); assert.equal(row.beforeSha256, row.proposalSha256); } });
test('P0128 and paint rewrites retain only exact Hyundai scope', () => { const p0128 = byId.get(IDS.p0128).proposal; assert.deepEqual(p0128.years, [2017]); assert.deepEqual(p0128.dtcCodes, ['P0128']); assert.match(p0128.description, /no drivability issues/i); const paint = byId.get(IDS.paint).proposal; assert.deepEqual(paint.years, [2015, 2016, 2017, 2018]); assert.match(paint.description, /W8 or WW8/); assert.doesNotMatch(paint.description + paint.solution, /Scratch Recovery|\$|1,500|3,000/i); });
test('anti-theft rewrite is gated by ignition equipment and VIN', () => { const theft = byId.get(IDS.theft).proposal; assert.deepEqual(theft.years, Array.from({ length: 12 }, (_, index) => 2011 + index)); assert.match(theft.description, /turn-key/); assert.match(theft.description, /push-button/); assert.match(theft.solution, /VIN/); assert.doesNotMatch(theft.description + theft.solution, /1,000%|USB connector|insurance coverage denied/i); });
