/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs'); const test = require('node:test'); const assert = require('node:assert/strict');
const { IDS, OUTPUT, SNAPSHOT } = require('./build-mazda-cx-7-adjudication'); const { diffFields, hashValue } = require('./mazda-adjudication-utils'); const { validatePacket } = require('./validate-mazda-cx-7-adjudication');
const packet = JSON.parse(fs.readFileSync(OUTPUT, 'utf8')); const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
function clone(value) { return JSON.parse(JSON.stringify(value)); } function rowFor(copy, id) { return copy.rows.find((row) => row.id === id); } function rehash(row) { row.proposalSha256 = hashValue(row.proposal); row.changedFields = diffFields(row.before, row.proposal); } function rejected(copy, pattern) { const errors = validatePacket(copy, snapshot); assert.ok(errors.some((error) => pattern.test(error)), errors.join('\n')); }
test('CX-7 packet passes its complete two-page contract', () => assert.deepEqual(validatePacket(packet, snapshot), []));
test('coverage gate rejects missing, duplicate and invented rows', () => { const a = clone(packet); a.rows.pop(); assert.ok(validatePacket(a, snapshot).length); const b = clone(packet); b.rows[0] = clone(b.rows[1]); assert.ok(validatePacket(b, snapshot).length); const c = clone(packet); c.rows.push(clone(c.rows[0])); c.rows.at(-1).id = 'invented'; assert.ok(validatePacket(c, snapshot).length); });
test('identity gate rejects metadata and report-count drift', () => { for (const [field, value] of [['title', 'Changed'], ['years', [1900]], ['trims', ['x']], ['engines', ['x']], ['category', 'other'], ['severity', 'critical'], ['status', 'archived'], ['relatedIssueIds', ['x']], ['reportCount', 1]]) { const copy = clone(packet); copy.rows[0].proposal[field] = value; rehash(copy.rows[0]); assert.ok(validatePacket(copy, snapshot).length); } });
test('social proof, hidden redirect, search URL and commerce are rejected', () => { const copy = clone(packet); const row = copy.rows[0]; row.proposal.solution += ' 250+ owners have reported this.'; row.proposal.canonicalId = 'x'; row.proposal.fixParts = [{ name: 'x' }]; row.proposal.citations.push({ title: 'search', type: 'article', url: 'https://example.com/search?q=x' }); rehash(row); const errors = validatePacket(copy, snapshot); assert.ok(errors.some((e) => /social proof/.test(e))); assert.ok(errors.some((e) => /unauthorized/.test(e))); assert.ok(errors.some((e) => /commerce-free/.test(e))); });
test('combined page cannot merge SSP86 and SSP87 or restore oil/parts folklore', () => { const copy = clone(packet); const row = rowFor(copy, IDS.combined); row.proposal.description = 'All 2007-2012 CX-7 vehicles have the same turbo and VVT defect.'; row.proposal.solution = 'Use 5W-20 every 5,000 miles and buy L3K9-13-70X. Do not buy yet.'; rehash(row); rejected(copy, /combined SSP86\/SSP87/); });
test('VVT page cannot restore solenoid theory, frozen DTCs or 2011-2012 official scope', () => { const copy = clone(packet); const row = rowFor(copy, IDS.vvt); row.proposal.description = 'SSP87 covers 2007-2012 and P0011 P0012 P0016.'; row.proposal.solution = 'A VVT solenoid restores the system. Do not buy yet.'; row.proposal.dtcCodes = ['P0011']; rehash(row); rejected(copy, /VVT SSP87|unsupported DTC/); });
test('all four PDF pages and blocked gate are required', () => { const a = clone(packet); a.pdfSources.ssp87.visualPages = [1]; rejected(a, /PDF evidence/); const b = clone(packet); b.applicationGate.status = 'ready'; rejected(b, /blocked proposal-only/); });
