/* eslint-disable @typescript-eslint/no-require-imports */
const assert = require('node:assert/strict'); const fs = require('node:fs'); const test = require('node:test'); const { IDS, OUTPUT, SNAPSHOT } = require('./build-mercedes-eqb-adjudication'); const { hashValue } = require('./known-issue-adjudication-utils'); const { validatePacket } = require('./validate-mercedes-eqb-adjudication'); const frozen = JSON.parse(fs.readFileSync(OUTPUT, 'utf8')); const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
function clone(value) { return JSON.parse(JSON.stringify(value)); } function row(packet, id) { return packet.rows.find((item) => item.id === id); } function rehash(item) { item.proposalSha256 = hashValue(item.proposal); item.changedFields = Object.keys(item.proposal).filter((key) => hashValue(item.before[key]) !== hashValue(item.proposal[key])); } function rejects(name, mutate, pattern) { test(name, () => { const packet = clone(frozen); mutate(packet); assert.match(validatePacket(packet, snapshot).join('\n'), pattern); }); }
test('frozen EQB packet passes', () => assert.deepEqual(validatePacket(clone(frozen), snapshot), []));
rejects('rejects title change', (packet) => { const item = row(packet, IDS.brakes); item.proposal.title += ' revised'; rehash(item); }, /deterministic|immutable title/);
rejects('rejects year change', (packet) => { const item = row(packet, IDS.range); item.proposal.years = [2022, 2023]; rehash(item); }, /deterministic|immutable years/);
rejects('rejects trim change', (packet) => { const item = row(packet, IDS.infotainment); item.proposal.trims = ['EQB 350 4MATIC']; rehash(item); }, /deterministic|immutable trims/);
rejects('rejects engine change', (packet) => { const item = row(packet, IDS.range); item.proposal.engines = []; rehash(item); }, /deterministic|immutable engines/);
rejects('rejects category change', (packet) => { const item = row(packet, IDS.brakes); item.proposal.category = 'electrical'; rehash(item); }, /deterministic|immutable category/);
rejects('rejects archive', (packet) => { const item = row(packet, IDS.range); item.proposal.status = 'archived'; rehash(item); }, /deterministic|immutable status|identity verdict/);
rejects('rejects social proof', (packet) => { const item = row(packet, IDS.range); item.proposal.description += ' 890+ owners have reported it.'; rehash(item); }, /deterministic|owner social proof/);
rejects('rejects commerce', (packet) => { const item = row(packet, IDS.infotainment); item.proposal.fixParts.push({ partNumber: 'A26/17' }); rehash(item); }, /deterministic|commerce-free/);
rejects('rejects search citation', (packet) => { const item = row(packet, IDS.range); item.proposal.citations[0].url = 'https://example.com/search?q=range'; rehash(item); }, /deterministic|citation/);
rejects('rejects retain action', (packet) => { const item = row(packet, IDS.brakes); item.action = 'retain_indexed_identity_and_accuracy_cleanup'; item.identityReviewRequired = false; }, /deterministic|identity verdict/);
rejects('rejects blocker removal', (packet) => { packet.applicationGate.blockerRecordIds.pop(); }, /deterministic|blocker/);
for (const [name, id, count] of [['brake', IDS.brakes, 510], ['infotainment', IDS.infotainment, 720], ['range', IDS.range, 890]]) rejects(`rejects fabricated ${name} count`, (packet) => { const item = row(packet, id); item.proposal.reportCount = count; rehash(item); }, /deterministic|fabricated report count/);
rejects('rejects pedal-defect transfer', (packet) => { const item = row(packet, IDS.brakes); item.proposal.description = '11029023 proves a dead-zone brake defect.'; rehash(item); }, /deterministic|brake normal-noise/);
rejects('rejects MBUX symptom transfer', (packet) => { const item = row(packet, IDS.infotainment); item.proposal.description = '10251122 proves all EQB screens crash.'; rehash(item); }, /deterministic|MBUX campaign/);
rejects('rejects range percentage transfer', (packet) => { const item = row(packet, IDS.range); item.proposal.description = 'The corpus proves a 30% range shortfall.'; rehash(item); }, /deterministic|range evidence/);
rejects('rejects 42 PSI transfer', (packet) => { const item = row(packet, IDS.range); item.proposal.solution = 'Inflate every EQB to 42 PSI.'; rehash(item); }, /deterministic|range evidence/);
rejects('rejects related-link mutation', (packet) => { const item = row(packet, IDS.infotainment); item.proposal.relatedIssueIds = []; rehash(item); }, /deterministic|immutable relatedIssueIds/);
rejects('rejects PDF injection', (packet) => { packet.pdfSources.fake = { pages: 1 }; }, /deterministic|source manifest/);
rejects('rejects human approval', (packet) => { const item = row(packet, IDS.range); item.proposal.humanApproved = true; rehash(item); }, /deterministic|commerce-free/);
