/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require('node:assert/strict');const fs=require('node:fs');const test=require('node:test');
const {CLEANUP_IDS,IDS,PDF_SOURCES,REWRITE_IDS}=require('./build-kia-stinger-adjudication');
const {EXPECTED_SUMMARY,PACKET,SNAPSHOT,validatePacket}=require('./validate-kia-stinger-adjudication');
const packet=JSON.parse(fs.readFileSync(PACKET,'utf8'));const snapshot=JSON.parse(fs.readFileSync(SNAPSHOT,'utf8'));const byId=new Map(packet.rows.map((row)=>[row.id,row]));
test('Stinger packet passes its blocked proposal-only safety contract',()=>{assert.deepEqual(validatePacket(packet,snapshot),[]);assert.deepEqual(packet.summary,EXPECTED_SUMMARY);assert.deepEqual(packet.applicationGate.blockerRecordIds,CLEANUP_IDS.slice().sort());});
test('four exact recall identities get bounded dealer-only rewrites',()=>{for(const id of REWRITE_IDS){const row=byId.get(id);assert.equal(row.action,'rewrite_same_identity');assert.match(row.commerceDecision,/^dealer-only-no-retail-part-/);assert.equal(row.proposal.citations.length,1);assert.deepEqual(row.proposal.dtcCodes,[]);assert.deepEqual(row.proposal.communityRecommendations,[]);assert.deepEqual(row.proposal.fixParts,[]);}});
test('the false DCT page explicitly identifies the 8AT and removes DCT prescriptions',()=>{const row=byId.get(IDS.transmission);assert.equal(row.action,'targeted_safety_cleanup_pending_source');assert.match(row.proposal.description,/8AT\), not the wet dual-clutch transmission/i);assert.match(row.proposal.solution,/Event 367/);assert.match(row.proposal.solution,/Event 373/);assert.doesNotMatch(row.proposal.solution,/DCT fluid every 30,000 miles/i);assert.deepEqual(row.proposal.dtcCodes,[]);});
test('the wrong-model ENG237 citation is retained only as an explicit exclusion boundary',()=>{const row=byId.get(IDS.oilPressure);assert.match(row.proposal.description,/ENG237 does not include the Stinger/i);assert.match(row.proposal.description,/Sorento, Cadenza and Sedona/i);assert.match(row.proposal.solution,/verify actual pressure/i);assert.deepEqual(row.proposal.dtcCodes,[]);assert.equal(row.proposal.citations[0].url,PDF_SOURCES.eng237WrongModel.url);});
test('roof and headliner bulletins are not stretched into all-year failure mechanisms',()=>{assert.match(byId.get(IDS.sunroof).proposal.description,/BOD309 addresses an inoperative sunroof/i);assert.match(byId.get(IDS.sunroof).proposal.description,/BOD317 addresses intermittent headliner noise/i);assert.match(byId.get(IDS.rattles).proposal.description,/certain 2022 Stinger/i);});
test('all links are primary direct sources and no search commerce survives',()=>{for(const row of packet.rows){for(const citation of row.proposal.citations)assert.match(citation.url,/^https:\/\/(?:api|static)\.nhtsa\.gov\//);assert.doesNotMatch(JSON.stringify(row.proposal),/amazon\.com\/s\?k=|ebay\.com\/sch|rockauto\.com\/en\/partsearch/i);assert.deepEqual(row.proposal.communityRecommendations,[]);assert.deepEqual(row.proposal.fixParts,[]);}});
test('all indexed Stinger identities, applicability fields and publication states are preserved',()=>{assert.equal(packet.rows.length,10);for(const row of packet.rows){for(const field of ['make','model','years','trims','engines','category','title','status'])assert.deepEqual(row.proposal[field],row.before[field]);assert.equal(row.proposal.status,'published');assert.equal(row.proposal.humanApproved,false);}});
