/* eslint-disable @typescript-eslint/no-require-imports */
const assert = require('node:assert/strict'); const fs = require('node:fs'); const test = require('node:test'); const { IDS, OUTPUT, SNAPSHOT } = require('./build-mercedes-eqc-adjudication'); const { hashValue } = require('./known-issue-adjudication-utils'); const { validatePacket } = require('./validate-mercedes-eqc-adjudication'); const frozen = JSON.parse(fs.readFileSync(OUTPUT, 'utf8')); const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
function clone(value) { return JSON.parse(JSON.stringify(value)); } function row(packet, id) { return packet.rows.find((item) => item.id === id); } function rehash(item) { item.proposalSha256 = hashValue(item.proposal); item.changedFields = Object.keys(item.proposal).filter((key) => hashValue(item.before[key]) !== hashValue(item.proposal[key])); } function rejects(name, mutate, pattern) { test(name, () => { const packet = clone(frozen); mutate(packet); assert.match(validatePacket(packet, snapshot).join('\n'), pattern); }); }
test('frozen EQC packet passes', () => assert.deepEqual(validatePacket(clone(frozen), snapshot), []));
rejects('rejects title change', (packet) => { const item = row(packet, IDS.steering); item.proposal.title += ' revised'; rehash(item); }, /deterministic|immutable title/);
rejects('rejects year change', (packet) => { const item = row(packet, IDS.coolant); item.proposal.years = [2020, 2021, 2022]; rehash(item); }, /deterministic|immutable years/);
rejects('rejects trim change', (packet) => { const item = row(packet, IDS.batteryHousing); item.proposal.trims = []; rehash(item); }, /deterministic|immutable trims/);
rejects('rejects engine change', (packet) => { const item = row(packet, IDS.crashSensor); item.proposal.engines = []; rehash(item); }, /deterministic|immutable engines/);
rejects('rejects category change', (packet) => { const item = row(packet, IDS.brakes); item.proposal.category = 'electrical'; rehash(item); }, /deterministic|immutable category/);
rejects('rejects archive', (packet) => { const item = row(packet, IDS.battery12v); item.proposal.status = 'archived'; rehash(item); }, /deterministic|immutable status|published zero-count/);
rejects('rejects social proof', (packet) => { const item = row(packet, IDS.coldRange); item.proposal.description += ' 300+ owners have reported it.'; rehash(item); }, /deterministic|owner social proof/);
rejects('rejects commerce', (packet) => { const item = row(packet, IDS.coolant); item.proposal.fixParts.push({ partNumber: 'drive-module' }); rehash(item); }, /deterministic|commerce-free/);
rejects('rejects search citation', (packet) => { const item = row(packet, IDS.steering); item.proposal.citations[0].url = 'https://example.com/search?q=steering'; rehash(item); }, /deterministic|citation/);
rejects('rejects battery retain converted to hold', (packet) => { const item = row(packet, IDS.batteryHousing); item.action = 'hold_indexed_identity_and_accuracy_cleanup_pending_identity_policy'; item.identityReviewRequired = true; }, /deterministic|retain verdict/);
rejects('rejects sensor retain converted to hold', (packet) => { const item = row(packet, IDS.crashSensor); item.action = 'hold_indexed_identity_and_accuracy_cleanup_pending_identity_policy'; item.identityReviewRequired = true; }, /deterministic|retain verdict/);
rejects('rejects coolant hold converted to retain', (packet) => { const item = row(packet, IDS.coolant); item.action = 'retain_indexed_identity_and_accuracy_cleanup'; item.identityReviewRequired = false; }, /deterministic|hold verdict/);
rejects('rejects blocker removal', (packet) => { packet.applicationGate.blockerRecordIds.pop(); }, /deterministic|blocker/);
rejects('rejects invented owner count', (packet) => { const item = row(packet, IDS.brakes); item.proposal.reportCount = 1; rehash(item); }, /deterministic|published zero-count/);
rejects('rejects coolant year transfer', (packet) => { const item = row(packet, IDS.coolant); item.proposal.description = 'China SAMR proves all 2019-2021 EQCs need a reducer seal.'; rehash(item); }, /deterministic|drive-module recall/);
rejects('rejects steering year transfer', (packet) => { const item = row(packet, IDS.steering); item.proposal.description = 'REC-000980 proves every 2019-2021 EQC is affected.'; rehash(item); }, /deterministic|steering recall/);
rejects('rejects battery identity loss', (packet) => { const item = row(packet, IDS.batteryHousing); item.proposal.description = 'Battery problem.'; rehash(item); }, /deterministic|battery-housing retain/);
rejects('rejects sensor identity loss', (packet) => { const item = row(packet, IDS.crashSensor); item.proposal.description = 'Airbag problem.'; rehash(item); }, /deterministic|crash-sensor retain/);
rejects('rejects pedal-defect transfer', (packet) => { const item = row(packet, IDS.brakes); item.proposal.description = '10186135 proves inconsistent brake blending.'; rehash(item); }, /deterministic|brake evidence/);
rejects('rejects heat-pump transfer', (packet) => { const item = row(packet, IDS.coldRange); item.proposal.description = 'The corpus proves heat-pump inefficiency.'; rehash(item); }, /deterministic|cold-range evidence/);
rejects('rejects related-link mutation', (packet) => { const item = row(packet, IDS.brakes); item.proposal.relatedIssueIds = ['unauthorized']; rehash(item); }, /deterministic|immutable relatedIssueIds/);
rejects('rejects PDF page omission', (packet) => { packet.pdfSources.romaniaCrashSensorRecall.visualPages = [1]; }, /deterministic|source manifest/);
rejects('rejects human approval', (packet) => { const item = row(packet, IDS.crashSensor); item.proposal.humanApproved = true; rehash(item); }, /deterministic|commerce-free/);
