/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs'); const test = require('node:test'); const assert = require('node:assert/strict');
const { IDS, OUTPUT, SNAPSHOT } = require('./build-mazda-cx-9-adjudication');
const { diffFields, hashValue } = require('./mazda-adjudication-utils'); const { validatePacket } = require('./validate-mazda-cx-9-adjudication');
const packet = JSON.parse(fs.readFileSync(OUTPUT, 'utf8')); const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
function clone(value) { return JSON.parse(JSON.stringify(value)); } function rowFor(copy, id) { return copy.rows.find((row) => row.id === id); }
function rehash(row) { row.proposalSha256 = hashValue(row.proposal); row.changedFields = diffFields(row.before, row.proposal); }
function rejected(copy, pattern) { const errors = validatePacket(copy, snapshot); assert.ok(errors.some((error) => pattern.test(error)), errors.join('\n')); }

test('CX-9 packet passes its complete eight-page contract', () => assert.deepEqual(validatePacket(packet, snapshot), []));
test('coverage gate rejects missing, duplicate and invented rows', () => { const a = clone(packet); a.rows.pop(); assert.ok(validatePacket(a, snapshot).length); const b = clone(packet); b.rows[0] = clone(b.rows[1]); assert.ok(validatePacket(b, snapshot).length); const c = clone(packet); c.rows.push(clone(c.rows[0])); c.rows.at(-1).id = 'invented'; assert.ok(validatePacket(c, snapshot).length); });
test('identity gate rejects metadata and report-count drift', () => { for (const [field, value] of [['title', 'Changed'], ['years', [1900]], ['trims', ['x']], ['engines', ['x']], ['category', 'other'], ['severity', 'critical'], ['status', 'archived'], ['relatedIssueIds', ['x']], ['reportCount', 1]]) { const copy = clone(packet); copy.rows[0].proposal[field] = value; rehash(copy.rows[0]); assert.ok(validatePacket(copy, snapshot).length); } });
test('social proof, hidden redirect, search URL and commerce are rejected', () => { const copy = clone(packet); const row = copy.rows[0]; row.proposal.solution += ' 900+ owners have reported this.'; row.proposal.canonicalId = 'x'; row.proposal.fixParts = [{ name: 'x' }]; row.proposal.citations.push({ title: 'search', type: 'article', url: 'https://example.com/search?q=x' }); rehash(row); const errors = validatePacket(copy, snapshot); assert.ok(errors.some((e) => /social proof/.test(e))); assert.ok(errors.some((e) => /unauthorized/.test(e))); assert.ok(errors.some((e) => /commerce-free/.test(e))); });
test('A/C page cannot turn a single complaint or newer TSB into first-generation proof', () => { const copy = clone(packet); const row = rowFor(copy, IDS.acEvaporator); row.proposal.description = 'All 2007-2015 vehicles have pinhole evaporator leaks and annual refrigerant loss; Mazda proved it in its 2016-2022 bulletin.'; row.proposal.solution = 'Replace the evaporator after dashboard removal (8-12 hours). Do not buy yet.'; rehash(row); rejected(copy, /A\/C complaint and generation/); });
test('liftgate page cannot restore strut-motor replacement or broaden the 2016 procedure', () => { const copy = clone(packet); const row = rowFor(copy, IDS.liftgate); row.proposal.description = 'Every 2016-2023 liftgate has worn strut motors.'; row.proposal.solution = 'Replace power liftgate strut motors. Do not buy yet.'; row.proposal.dtcCodes = []; rehash(row); rejected(copy, /liftgate low-voltage|exact liftgate DTC/); });
test('rear differential page cannot turn cracked mounts into coupling failure', () => { const copy = clone(packet); const row = rowFor(copy, IDS.rearDifferential); row.proposal.description = 'The electronically controlled coupling overheats and stores P1889.'; row.proposal.solution = 'Change fluid every 30,000 miles. Do not buy yet.'; rehash(row); rejected(copy, /rear differential mount\/coupling/); });
test('first-generation timing page cannot infer a universal defect from one complaint', () => { const copy = clone(packet); const row = rowFor(copy, IDS.timingV6); row.proposal.description = 'Every engine stretches its chain between 80,000 and 120,000 miles.'; row.proposal.solution = 'Install a complete kit. Do not buy yet.'; rehash(row); rejected(copy, /first-generation timing complaint/); });
test('second-generation timing page cannot treat installation guidance as failure proof', () => { const copy = clone(packet); const row = rowFor(copy, IDS.timingTurbo); row.proposal.description = 'Mazda proved timing-chain stretch and covers 2016-2025.'; row.proposal.solution = 'Use a 5,000-mile interval and software remedy. Do not buy yet.'; rehash(row); rejected(copy, /second-generation timing installation/); });
test('transfer page cannot restore wrong fluid, interval or whole-unit narrative', () => { const copy = clone(packet); const row = rowFor(copy, IDS.transferLeak); row.proposal.description = 'All 2007-2023 transfer cases leak and need Mazda FE-LS ATF.'; row.proposal.solution = 'Remove the transfer assembly and change fluid at a 30,000-mile preventive interval. Do not buy yet.'; rehash(row); rejected(copy, /transfer seal\/fluid/); });
test('CSP11 cannot be rewritten as a turbo coolant-line campaign', () => { const copy = clone(packet); const row = rowFor(copy, IDS.turboCoolant); row.proposal.description = 'The turbocharger supply and return hoses fail on 2016-2023 vehicles.'; row.proposal.solution = 'Mazda revised the hose material. Do not buy yet.'; rehash(row); rejected(copy, /CSP11 cylinder-head\/turbo-line/); });
test('water-pump reports cannot authorize crossover, timing-set or engine bundles', () => { const copy = clone(packet); const row = rowFor(copy, IDS.waterPump); row.proposal.description = 'Mazda determined a model-wide crossover and water-pump defect.'; row.proposal.solution = 'Replace everything as a complete job for $2,000. Do not buy yet.'; rehash(row); rejected(copy, /water-pump complaint and repair-bundle/); });
test('all 20 visual PDF pages and blocked gate are required', () => { const a = clone(packet); a.pdfSources.transferOilSeals.visualPages = [1, 2]; rejected(a, /PDF evidence/); const b = clone(packet); b.applicationGate.status = 'ready'; rejected(b, /blocked proposal-only/); });
