/* eslint-disable @typescript-eslint/no-require-imports */
const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path'); const test = require('node:test');
const { IDS, MISMATCH_SOURCES, REWRITE_CARDS, SOURCES, fullRecord, hashValue } = require('./build-honda-insight-adjudication'); const { validatePacket } = require('./validate-honda-insight-adjudication');
const ROOT = path.resolve(__dirname, '..'); const PACKET = path.join(ROOT, 'data', 'known-issue-honda-insight-adjudication-2026-08-06.json'); const SNAPSHOT = path.join(ROOT, 'data', '_honda-deeplink-snapshot-2026-08-05.json'); function fixture() { return { packet: JSON.parse(fs.readFileSync(PACKET, 'utf8')), snapshot: JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8')) }; }
test('valid Insight packet passes every invariant', () => { const { packet, snapshot } = fixture(); assert.deepEqual(validatePacket(packet, snapshot), []); });
test('all seven source-gap rows remain byte-for-byte frozen', () => { const { packet, snapshot } = fixture(); const sourceById = new Map(snapshot.records.filter((row) => row.model === 'Insight').map((row) => [row.id, row])); const keeps = packet.rows.filter((row) => row.action === 'keep_published_pending_source'); assert.equal(keeps.length, 7); for (const row of keeps) { const frozen = fullRecord(sourceById.get(row.id)); assert.deepEqual(row.before, frozen); assert.deepEqual(row.proposal, frozen); assert.equal(row.beforeSha256, hashValue(frozen)); assert.equal(row.proposalSha256, row.beforeSha256); assert.deepEqual(row.changedFields, []); } });
test('three recall rewrites use exact years and contain no commerce', () => { const { packet } = fixture(); const rewrites = packet.rows.filter((row) => row.action === 'rewrite_same_identity'); assert.equal(rewrites.length, 3); for (const row of rewrites) { assert.deepEqual(row.proposal.years, REWRITE_CARDS[row.id].years); assert.deepEqual(row.proposal.trims, []); assert.deepEqual(row.proposal.engines, []); assert.deepEqual(row.proposal.communityRecommendations, []); assert.deepEqual(row.proposal.fixParts, []); assert.equal(row.proposal.estimatedCostLow, null); assert.equal(row.proposal.estimatedCostHigh, null); } assert.deepEqual(packet.rows.find((row) => row.id === IDS.fuelPump).proposal.years, [2019, 2020, 2022]); assert.equal(packet.rows.find((row) => row.id === IDS.bcm).proposal.citations[0].url, SOURCES.bcm); });
test('false 21-079 and 15-086 citations are exposed without mutation', () => { const { packet } = fixture(); const battery = packet.rows.find((row) => row.id === IDS.battery12v); const cvt = packet.rows.find((row) => row.id === IDS.cvt); assert.equal(battery.evidence[0].url, MISMATCH_SOURCES.bulletin21079); assert.match(battery.evidence[0].observation, /Civic key-fob/i); assert.equal(cvt.evidence[0].url, MISMATCH_SOURCES.bulletin15086); assert.match(cvt.evidence[0].observation, /CR-V/i); });
test('validator rejects mutation, archive, invented applicability and commerce', () => { const first = fixture(); const keep = first.packet.rows.find((row) => row.id === IDS.imaBattery); keep.proposal.title = 'mutated'; keep.proposalSha256 = hashValue(keep.proposal); assert.ok(validatePacket(first.packet, first.snapshot).some((error) => error.includes('keep changed content'))); const second = fixture(); const rewrite = second.packet.rows.find((row) => row.id === IDS.dcDc); rewrite.proposal.status = 'archived'; rewrite.proposalSha256 = hashValue(rewrite.proposal); assert.ok(validatePacket(second.packet, second.snapshot).some((error) => error.includes('identity/status drift'))); const third = fixture(); const fuel = third.packet.rows.find((row) => row.id === IDS.fuelPump); fuel.proposal.trims = ['Touring']; fuel.proposalSha256 = hashValue(fuel.proposal); assert.ok(validatePacket(third.packet, third.snapshot).some((error) => error.includes('invented applicability'))); const fourth = fixture(); const bcm = fourth.packet.rows.find((row) => row.id === IDS.bcm); bcm.proposal.fixParts = [{ name: 'module' }]; bcm.proposalSha256 = hashValue(bcm.proposal); assert.ok(validatePacket(fourth.packet, fourth.snapshot).some((error) => error.includes('contains commerce'))); });
