/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require('node:assert/strict');const fs=require('node:fs');const test=require('node:test');
const {CLEANUP_IDS,IDS,PDF_SOURCES}=require('./build-kia-soul-adjudication');
const {EXPECTED_SUMMARY,PACKET,SNAPSHOT,validatePacket}=require('./validate-kia-soul-adjudication');
const packet=JSON.parse(fs.readFileSync(PACKET,'utf8'));const snapshot=JSON.parse(fs.readFileSync(SNAPSHOT,'utf8'));const byId=new Map(packet.rows.map((row)=>[row.id,row]));
test('Soul packet passes its blocked proposal-only safety contract',()=>{assert.deepEqual(validatePacket(packet,snapshot),[]);assert.deepEqual(packet.summary,EXPECTED_SUMMARY);assert.deepEqual(packet.applicationGate.blockerRecordIds,CLEANUP_IDS.slice().sort());});
test('the Optima-only anti-judder citation is rejected while exact TRA083 remains',()=>{const row=byId.get(IDS.dct);assert.equal(row.proposal.citations.length,1);assert.equal(row.proposal.citations[0].url,PDF_SOURCES.tra083.url);assert.doesNotMatch(JSON.stringify(row.proposal.citations),/10200552/);assert.match(row.proposal.description,/Optima-only/i);});
test('HECU, piston and MDPS boundaries remain explicit',()=>{assert.match(byId.get(IDS.hecu).proposal.description,/exact cause of the short remains unknown/i);assert.match(byId.get(IDS.piston).proposal.description,/does not make every 2022-2023 vehicle part of recall 21V259/i);assert.match(byId.get(IDS.mdps).proposal.description,/2012-2013 Soul vehicles/i);});
test('exact recall identities retain only primary direct sources and bounded DTCs',()=>{assert.deepEqual(byId.get(IDS.catalytic).proposal.dtcCodes,['P0420']);assert.deepEqual(byId.get(IDS.piston).proposal.dtcCodes,['P1327']);for(const id of [IDS.catalytic,IDS.mdps,IDS.piston,IDS.pinion])for(const citation of byId.get(id).proposal.citations)assert.match(citation.url,/^https:\/\/(?:api|static)\.nhtsa\.gov\//);});
test('unsupported EV and sunroof pages remove secondary sources and generic commerce',()=>{for(const id of [IDS.evMotor,IDS.sunroof]){const row=byId.get(id);assert.deepEqual(row.proposal.citations,[]);assert.deepEqual(row.proposal.communityRecommendations,[]);assert.deepEqual(row.proposal.fixParts,[]);assert.equal(row.action,'targeted_safety_cleanup_pending_source');}});
test('all indexed Soul identity fields and publication states remain preserved',()=>{for(const row of packet.rows){for(const field of ['make','model','years','trims','engines','category','title','status'])assert.deepEqual(row.proposal[field],row.before[field]);assert.equal(row.proposal.status,'published');assert.equal(row.proposal.humanApproved,false);}});
