/* eslint-disable @typescript-eslint/no-require-imports */
const assert = require('node:assert/strict'); const fs = require('node:fs'); const test = require('node:test');
const { CAMPAIGNS, HOLD_IDS, REWRITE_IDS } = require('./build-kia-forte-adjudication'); const { PACKET, SNAPSHOT, validatePacket } = require('./validate-kia-forte-adjudication');
const packet = JSON.parse(fs.readFileSync(PACKET, 'utf8')); const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));

test('Forte packet passes the proposal-only safety contract', () => { assert.deepEqual(validatePacket(packet, snapshot), []); assert.deepEqual(packet.summary, { rewrite_same_identity: 3, keep_published_pending_source: 7, total: 10 }); assert.equal(packet.applicationGate.status, 'blocked'); });
test('three exact official identities get bounded no-retail rewrites', () => { const byId = new Map(packet.rows.map((row) => [row.id, row])); for (const id of Object.values(REWRITE_IDS)) { const row = byId.get(id); assert.equal(row.action, 'rewrite_same_identity'); assert.ok(row.changedFields.length); assert.deepEqual(row.proposal.communityRecommendations, []); assert.deepEqual(row.proposal.fixParts, []); assert.match(row.commerceDecision, /^dealer-only-no-retail-part-/); assert.equal(row.proposal.title, row.before.title); assert.deepEqual(row.proposal.years, row.before.years); assert.equal(row.proposal.status, 'published'); } });
test('HECU correction removes the wrong recall while preserving boundary evidence', () => { const row = packet.rows.find((item) => item.id === REWRITE_IDS.hecu); assert.doesNotMatch(JSON.stringify(row.proposal), /21V331/i); assert.match(JSON.stringify(row.proposal.citations), /23V652/); assert.ok(row.evidence.some((item) => item.urls?.includes(CAMPAIGNS.wrongHecu))); });
test('seven scope-conflicted or false-citation rows stay frozen and block application', () => { const byId = new Map(packet.rows.map((row) => [row.id, row])); for (const id of Object.values(HOLD_IDS)) { const row = byId.get(id); assert.equal(row.action, 'keep_published_pending_source'); assert.deepEqual(row.proposal, row.before); assert.equal(row.proposalSha256, row.beforeSha256); assert.ok(packet.applicationGate.blockerRecordIds.includes(id)); } assert.match(byId.get(HOLD_IDS.lowBeam).reason, /SC149.*Sorento/i); assert.match(byId.get(HOLD_IDS.rodBearing).reason, /manufacturing debris.*no manufacturing or design cause was identified/i); });
test('all indexed Forte identities and publication states are preserved', () => { assert.equal(packet.rows.length, 10); for (const row of packet.rows) { assert.equal(row.proposal.title, row.before.title); assert.equal(row.proposal.category, row.before.category); assert.deepEqual(row.proposal.years, row.before.years); assert.equal(row.proposal.status, 'published'); } assert.ok(packet.observations.some((item) => item.code === 'all-forte-pages-preserved')); });
