/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs');
const test = require('node:test');
const assert = require('node:assert/strict');
const { clone } = require('./lexus-adjudication-utils');
const { IDS, SNAPSHOT, buildPacket } = require('./build-lexus-ls-adjudication');
const { validatePacket } = require('./validate-lexus-ls-adjudication');
const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
function row(packet, id) { return packet.rows.find((item) => item.id === id); }

test('LS packet passes the complete five-page safety contract', () => { assert.deepEqual(validatePacket(buildPacket(snapshot), snapshot), []); });
test('validator rejects indexed identity, engine and severity drift', () => { const packet = buildPacket(snapshot); row(packet, IDS.airSuspension).proposal.title = 'Changed'; row(packet, IDS.headlight).proposal.engines = ['Guess']; row(packet, IDS.infotainment).proposal.severity = 'critical'; const errors = validatePacket(packet, snapshot); assert.ok(errors.some((error) => /immutable title|proposal drift/.test(error))); assert.ok(errors.some((error) => /immutable engines/.test(error))); assert.ok(errors.some((error) => /severity/.test(error))); });
test('validator rejects archives and guessed commerce', () => { const packet = buildPacket(snapshot); row(packet, IDS.lamps).proposal.status = 'archived'; row(packet, IDS.airbag).proposal.fixParts = [{ oemPartNumber: 'GUESS' }]; const errors = validatePacket(packet, snapshot); assert.ok(errors.some((error) => /publication\/source\/severity|proposal drift/.test(error))); assert.ok(errors.some((error) => /derived-data\/commerce/.test(error))); });
test('validator rejects unsafe suspension, lighting, recall and infotainment prescriptions', () => { const packet = clone(buildPacket(snapshot)); row(packet, IDS.airSuspension).proposal.solution += ' Install the SM-LS460 coil conversion kit.'; row(packet, IDS.headlight).proposal.solution += ' Replace all four headlight level sensors.'; row(packet, IDS.lamps).proposal.solution += ' Buy and install a generic Bosch bulb.'; row(packet, IDS.airbag).proposal.solution += ' Replace the battery before checking the recall.'; row(packet, IDS.infotainment).proposal.solution += ' Retrofit and install the 2024 touchscreen head unit.'; const errors = validatePacket(packet, snapshot); for (const id of Object.values(IDS)) assert.ok(errors.some((error) => error === `${id}: unsupported parts prescription survived`)); });
test('validator rejects missing explicit no-commerce boundaries', () => { const packet = clone(buildPacket(snapshot)); for (const item of packet.rows) item.proposal.solution = item.proposal.solution.replace(/This is [^.]+; no universal retail part is asserted\./, 'Buy a generic replacement.'); const errors = validatePacket(packet, snapshot); for (const id of Object.values(IDS)) assert.ok(errors.some((error) => error === `${id}: explicit no-commerce marker missing`)); });
test('validator rejects campaign partition and direct-source drift', () => { const packet = buildPacket(snapshot); packet.mappedCampaigns = ['09E012000']; row(packet, IDS.airbag).proposal.citations[0].url = 'https://www.google.com/search?q=06V096'; const errors = validatePacket(packet, snapshot); assert.ok(errors.some((error) => /recall partition/.test(error))); assert.ok(errors.some((error) => /citation boundary|proposal drift/.test(error))); });
