/* eslint-disable @typescript-eslint/no-require-imports */
const assert=require('node:assert/strict');const fs=require('node:fs');const test=require('node:test');
const {CLEANUP_IDS,IDS,PDF_SOURCES,REWRITE_IDS}=require('./build-kia-sportage-adjudication');
const {EXPECTED_SUMMARY,PACKET,SNAPSHOT,validatePacket}=require('./validate-kia-sportage-adjudication');
const packet=JSON.parse(fs.readFileSync(PACKET,'utf8'));const snapshot=JSON.parse(fs.readFileSync(SNAPSHOT,'utf8'));const byId=new Map(packet.rows.map((row)=>[row.id,row]));
test('Sportage packet passes its blocked proposal-only safety contract',()=>{assert.deepEqual(validatePacket(packet,snapshot),[]);assert.deepEqual(packet.summary,EXPECTED_SUMMARY);assert.deepEqual(packet.applicationGate.blockerRecordIds,CLEANUP_IDS.slice().sort());});
test('the HECU identity uses both exact campaigns and no false DTC or retail remedy',()=>{const row=byId.get(IDS.hecu);assert.equal(row.action,'rewrite_same_identity');assert.deepEqual(REWRITE_IDS,[IDS.hecu]);assert.deepEqual(row.proposal.dtcCodes,[]);assert.equal(row.proposal.citations.length,2);assert.match(row.proposal.description,/23V652000/);assert.match(row.proposal.description,/22V051000/);assert.deepEqual(row.proposal.communityRecommendations,[]);});
test('conflated recall pages retain explicit year and mechanism boundaries',()=>{assert.match(byId.get(IDS.coolingFan).proposal.description,/2002 Sportage/);assert.match(byId.get(IDS.coolingFan).proposal.solution,/Do not assume a 2000 vehicle is covered/i);assert.match(byId.get(IDS.fuelTank).proposal.description,/two different year and mechanism groups/i);assert.match(byId.get(IDS.oilPump).proposal.description,/does not list the frozen 2024 Sportage year/i);});
test('invalid videos, false DTCs and imported ICCU claims are removed',()=>{for(const id of [IDS.coupling,IDS.turboLine]){assert.deepEqual(byId.get(id).proposal.dtcCodes,[]);assert.ok(byId.get(id).evidence.some((item)=>item.kind==='publisher-citation-unavailable'));}assert.deepEqual(byId.get(IDS.iccu).proposal.citations,[]);assert.match(byId.get(IDS.iccu).proposal.description,/no ICCU or Integrated Charging Control Unit defect package/i);});
test('official PDF rows retain only direct NHTSA sources and inspected hashes',()=>{for(const id of [IDS.transmission,IDS.coupling,IDS.oilConsumption,IDS.infotainment,IDS.airConditioning]){const row=byId.get(id);assert.ok(row.evidence.some((item)=>item.kind==='official-pdf-review'));for(const citation of row.proposal.citations)assert.match(citation.url,/^https:\/\/static\.nhtsa\.gov\//);}for(const source of Object.values(PDF_SOURCES)){assert.equal(source.visuallyInspectedPages.length,source.pages);assert.match(source.sha256,/^[a-f0-9]{64}$/);}});
test('all search commerce and relations are removed while every indexed identity stays published',()=>{for(const row of packet.rows){assert.deepEqual(row.proposal.communityRecommendations,[]);assert.deepEqual(row.proposal.fixParts,[]);assert.deepEqual(row.proposal.relatedIssueIds,[]);for(const field of ['make','model','years','trims','engines','category','title','status'])assert.deepEqual(row.proposal[field],row.before[field]);assert.equal(row.proposal.status,'published');assert.equal(row.proposal.humanApproved,false);}});
