/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs'); const test = require('node:test'); const assert = require('node:assert/strict'); const { clone } = require('./lexus-adjudication-utils'); const { IDS, SNAPSHOT, buildPacket } = require('./build-lexus-sc-adjudication'); const { validatePacket } = require('./validate-lexus-sc-adjudication'); const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8'));
test('SC packet passes the complete three-page safety contract', () => { assert.deepEqual(validatePacket(buildPacket(snapshot), snapshot), []); });
test('validator rejects indexed identity, fitment and severity drift', () => { const packet = buildPacket(snapshot); packet.rows[0].proposal.title = 'Changed'; packet.rows[0].proposal.trims = ['Guess']; packet.rows[0].proposal.severity = 'critical'; const errors = validatePacket(packet, snapshot); assert.ok(errors.some((error) => /proposal drift|immutable title/.test(error))); assert.ok(errors.some((error) => /immutable trims/.test(error))); assert.ok(errors.some((error) => /severity/.test(error))); });
test('validator rejects archives and guessed commerce', () => { const packet = buildPacket(snapshot); packet.rows[0].proposal.status = 'archived'; packet.rows[0].proposal.fixParts = [{ oemPartNumber: 'GUESS' }]; assert.ok(validatePacket(packet, snapshot).some((error) => /proposal drift|publication\/source\/severity|derived-data\/commerce/.test(error))); });
test('validator rejects the blanket A/C replacement claim', () => { const packet = clone(buildPacket(snapshot)); const row = packet.rows.find((item) => item.id === IDS.ac); row.proposal.solution += ' Flush the entire AC system and always replace the receiver/drier.'; assert.ok(validatePacket(packet, snapshot).some((error) => /unsupported positive claim|conditional remedy/.test(error))); });
test('validator rejects the false ZE7 coverage promise', () => { const packet = clone(buildPacket(snapshot)); const row = packet.rows.find((item) => item.id === IDS.dashboard); row.proposal.solution += ' The SC430 is covered under ZE7.'; assert.ok(validatePacket(packet, snapshot).some((error) => /unsupported positive claim/.test(error))); });
test('validator rejects the universal nine-year timing-kit prescription', () => { const packet = clone(buildPacket(snapshot)); const row = packet.rows.find((item) => item.id === IDS.timing); row.proposal.solution += ' Replace the complete kit every 90,000 miles or 9 years.'; assert.ok(validatePacket(packet, snapshot).some((error) => /unsupported positive claim/.test(error))); });
test('validator rejects loss of no-commerce markers and fake owner totals', () => { const packet = clone(buildPacket(snapshot)); packet.rows[0].proposal.solution = packet.rows[0].proposal.solution.replace('no universal compressor, clutch, bearing, drier, valve, condenser or retail part is asserted', 'buy this compressor'); packet.rows[1].proposal.description += ' 0+ owners have reported this issue.'; const errors = validatePacket(packet, snapshot); assert.ok(errors.some((error) => /no-commerce marker/.test(error))); assert.ok(errors.some((error) => /zero-owner social proof/.test(error))); });
