/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs'); const test = require('node:test'); const assert = require('node:assert/strict'); const { ALL_IDS, BLOCKER_IDS, IDS, OUTPUT, SNAPSHOT, buildPacket } = require('./build-mercedes-v-class-adjudication'); const { validatePacket } = require('./validate-mercedes-v-class-adjudication'); const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8')); function packet() { return buildPacket(snapshot); }
test('packet validates deterministically', () => assert.deepEqual(validatePacket(packet(), snapshot), []));
test('all eight frozen identities are covered once and held', () => { const value = packet(); assert.deepEqual(value.rows.map((row) => row.id).sort(), ALL_IDS); assert.deepEqual(value.applicationGate.blockerRecordIds, BLOCKER_IDS); assert.equal(value.rows.filter((row) => row.identityReviewRequired).length, 8); });
test('indexed identity and vehicle metadata remain immutable', () => { for (const row of packet().rows) for (const field of ['make', 'model', 'years', 'trims', 'engines', 'category', 'title', 'severity', 'status', 'lastReportedByOwners', 'relatedIssueIds']) assert.deepEqual(row.proposal[field], row.before[field], `${row.id}:${field}`); });
test('all report counts remain zero without social proof', () => { for (const row of packet().rows) { assert.equal(row.before.reportCount, 0); assert.equal(row.proposal.reportCount, 0); assert.doesNotMatch(`${row.proposal.description} ${row.proposal.solution}`, /0\+ owners|owners have reported/i); } });
test('packet introduces no commerce or recommendation', () => { for (const row of packet().rows) { assert.deepEqual(row.proposal.fixParts, []); assert.deepEqual(row.proposal.communityRecommendations, []); assert.match(row.proposal.solution, /do not buy/i); assert.match(row.commerceDecision, /no universal retail part/i); } });
test('Metris evidence is bounded from V-Class identity', () => { const value = packet(); assert.match(value.rows.find((row) => row.id === IDS.wheelBearing).identityConflict, /2017 Metris/); assert.match(value.rows.find((row) => row.id === IDS.adblue).identityConflict, /OM651 V-Class/); });
test('unsafe emissions and regeneration directions are removed', () => { const value = packet(); assert.match(value.rows.find((row) => row.id === IDS.adblue).proposal.solution, /Do not install an emissions delete/); assert.match(value.rows.find((row) => row.id === IDS.dpf).proposal.solution, /Do not force a regeneration/); });
test('wheel bearing recall remains exact and conditional', () => { const row = packet().rows.find((value) => value.id === IDS.wheelBearing); assert.match(row.proposal.description, /17V651000/); assert.match(row.proposal.description, /2017 Mercedes-Benz Metris/); assert.match(row.proposal.solution, /VIN coverage/); });
test('unsupported diesel identities remain explicit', () => { const value = packet(); for (const id of [IDS.injector, IDS.timingChain, IDS.coolantPump]) assert.match(value.rows.find((row) => row.id === id).evidence.primaryEvidence.join(' '), /zero exact|No exact/i); });
test('committed packet matches deterministic build', () => { if (fs.existsSync(OUTPUT)) assert.deepEqual(JSON.parse(fs.readFileSync(OUTPUT, 'utf8')), packet()); });
test('no PDF selected and dataset citation is direct', () => { const value = packet(); assert.deepEqual(value.pdfSources, {}); for (const row of value.rows) assert.equal(row.proposal.citations[0].url, 'https://www.nhtsa.gov/nhtsa-datasets-and-apis'); });
