/* eslint-disable @typescript-eslint/no-require-imports */
const fs = require('node:fs'); const test = require('node:test'); const assert = require('node:assert/strict');
const { OUTPUT, SNAPSHOT } = require('./build-lincoln-corsair-adjudication'); const { hashValue } = require('./lincoln-adjudication-utils'); const { validatePacket } = require('./validate-lincoln-corsair-adjudication');
const packet = JSON.parse(fs.readFileSync(OUTPUT, 'utf8')); const snapshot = JSON.parse(fs.readFileSync(SNAPSHOT, 'utf8')); function clone(value) { return JSON.parse(JSON.stringify(value)); } function rehash(row) { row.proposalSha256 = hashValue(row.proposal); }
test('Corsair packet passes the complete four-page safety contract', () => assert.deepEqual(validatePacket(packet, snapshot), []));
test('validator rejects missing, duplicate, and unknown pages', () => { const a = clone(packet); a.rows.pop(); assert.ok(validatePacket(a, snapshot).length); const b = clone(packet); b.rows[0] = clone(b.rows[1]); assert.ok(validatePacket(b, snapshot).length); });
test('validator rejects identity, fitment, severity, relation and archive drift', () => { for (const [field, value] of [['title', 'Changed title'], ['years', [1900]], ['engines', ['UNSUPPORTED']], ['severity', 'critical'], ['relatedIssueIds', ['other']], ['status', 'archived']]) { const p = clone(packet); const row = p.rows[0]; row.proposal[field] = value; rehash(row); assert.ok(validatePacket(p, snapshot).some((error) => error.includes(field) || error.includes('severity') || error.includes('archived'))); } });
test('validator rejects the invented EGR remedy date and 2.3L scope', () => { const p = clone(packet); const row = p.rows.find((item) => item.id.includes('egr-valve')); row.proposal.description = 'The 2.3-liter Corsair is covered.'; row.proposal.solution = 'Remedy expected September 2026 with loaner/mobile diagnosis.'; rehash(row); assert.ok(validatePacket(p, snapshot).some((error) => error.includes('EGR') || error.includes('commerce'))); });
test('validator rejects unsupported seat-belt warnings and whole-retractor replacement', () => { const p = clone(packet); const row = p.rows.find((item) => item.id.includes('seat-belt')); row.proposal.solution = 'Avoid placing children there; replace the entire retractor if it rattles or binds.'; rehash(row); assert.ok(validatePacket(p, snapshot).some((error) => error.includes('seat-belt') || error.includes('commerce'))); });
test('validator rejects loss of lamp population and dealer remedy', () => { const p = clone(packet); const row = p.rows.find((item) => item.id.includes('tail-light')); row.proposal.description = 'All Corsairs leak.'; row.proposal.solution = 'Buy two lamps.'; rehash(row); assert.ok(validatePacket(p, snapshot).some((error) => error.includes('lamp') || error.includes('commerce'))); });
test('validator rejects another editing instruction on the windshield page', () => { const p = clone(packet); const row = p.rows.find((item) => item.id.includes('windshield')); row.proposal.description = "Change 'Owner letters' date again."; rehash(row); assert.ok(validatePacket(p, snapshot).some((error) => error.includes('windshield'))); });
test('validator rejects fake owner social proof and search-style commerce', () => { const p = clone(packet); const row = p.rows[0]; row.proposal.reportCount = 99; row.proposal.solution += ' 99+ owners have reported this.'; row.proposal.citations.push({ type: 'manual', title: 'Search', url: 'https://example.com/search?q=part' }); rehash(row); const errors = validatePacket(p, snapshot); assert.ok(errors.some((error) => error.includes('social proof'))); assert.ok(errors.some((error) => error.includes('search-style'))); });
